{
 "title": "HW Servers Overview",
 "tags": [
  "ipmi",
  "ipmi-sensors",
  "ipmi-overview",
  "power",
  "folder-physical-servers"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "site",
    "label": "DC",
    "query": {
     "query": "label_values(node_ipmi_up,site)"
    }
   },
   {
    "name": "cloud",
    "label": "cloud",
    "query": {
     "query": "label_values(node_ipmi_up{site=~\"$site\"},os_region)"
    }
   },
   {
    "name": "rack",
    "label": "Rack",
    "query": {
     "query": "label_values(node_ipmi_up{site=~\"$site\", os_region=~\"$cloud\"},rack)"
    }
   },
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Servers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_ipmi_up{site=~\"$site\",rack=~\"$rack\",os_region=~\"$cloud\"} == 1) by (instance)) or on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Racks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_ipmi_dcmi_power_consumption_watts{site=~\"$site\",rack=~\"$rack\",os_region=~\"$cloud\"} > 5) by (rack))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Powered off",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_ipmi_chassis_power_state{site=~\"$site\",rack=~\"$rack\",os_region=~\"$cloud\"} == 0) by (instance)) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Powered on",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_ipmi_chassis_power_state{site=~\"$site\",rack=~\"$rack\",os_region=~\"$cloud\"}==1)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Reporting Power Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count(node_ipmi_dcmi_power_consumption_watts{site=~\"$site\",rack=~\"$rack\",os_region=~\"$cloud\"} > 5) by (instance))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power reading in Watts",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_ipmi_dcmi_power_consumption_watts{site=~\"$site\",rack=~\"$rack\",os_region=~\"$cloud\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Power State Warning",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_ipmi_power_state{site=~\"$site\",rack=~\"$rack\",os_region=~\"$cloud\"} == 1) by (instance)) or vector(0)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Power State Critical",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_ipmi_power_state{site=~\"$site\",rack=~\"$rack\",os_region=~\"$cloud\",os_region=~\"$cloud\"} == 2) by (instance)) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IPMI Agent Down",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_ipmi_up{site=~\"$site\",rack=~\"$rack\",os_region=~\"$cloud\"} == 0) by (instance)) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Not reporting Power Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_ipmi_up{site=~\"$site\",rack=~\"$rack\",os_region=~\"$cloud\"}) by (instance) unless (count(node_ipmi_dcmi_power_consumption_watts{site=~\"$site\",rack=~\"$rack\",os_region=~\"$cloud\"}) by (instance))) or on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power Consumption watts",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum(node_ipmi_power_watts{site=~\"$site\",rack=~\"$rack\",os_region=~\"$cloud\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Power Consumption by a rack",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum(node_ipmi_dcmi_power_consumption_watts{site=~\"$site\",rack=~\"$rack\",os_region=~\"$cloud\"}) by (rack,site)",
     "legendFormat": "{{site}}-{{rack}}"
    }
   ]
  },
  {
   "title": "IPMI Sensors State",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "node_ipmi_sensor_state{site=~\"$site\",rack=~\"$rack\",os_region=~\"$cloud\"} > 0"
    }
   ]
  },
  { "title": "Voltage State Sensors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Voltage Sate Sensors",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "node_ipmi_voltage_state{site=~\"$site\",rack=~\"$rack\",os_region=~\"$cloud\"} > 0 or vector(0)",
     "legendFormat": "{{instance}}-{{name}}"
    }
   ]
  },
  { "title": "Fans State Sensors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Fan Speed State Sensors",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "node_ipmi_fan_speed_state{site=~\"$site\",rack=~\"$rack\"} >0 or vector(0)",
     "legendFormat": "{{instance}}-{{name}}"
    }
   ]
  },
  { "title": "Temperature State Sensors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Temperature State Alerts",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "node_ipmi_temperature_state{site=\"$site\",rack=\"$rack\",os_region=~\"$cloud\"} > 0 or vector(0)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Server Export",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true,
   "panels": [
    {
     "title": "HW Servers List",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 49 },
     "targets": [
      {
       "expr": "node_ipmi_bmc_info{site=~\"$site\",rack=~\"$rack\",os_region=~\"$cloud\"} + on(instance) group_left(board_vendor,product_name,manufacturer_id,bios_date,bios_release,bios_vendor,chassis_vendor,bios_version,board_name) node_dmi_info{} + on(instance) group_left(pretty_name,name,id) node_os_info{} + on(instance) group_left(release,machine) node_uname_info{}"
      }
     ]
    }
   ]
  }
 ]
}