{
 "title": "Network Monitoring Between Regions",
 "description": "Network Monitoring including",
 "tags": [
  "VictoriaMetrics",
  "PingStation",
  "Network"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "station",
    "label": "Source",
    "query": {
     "query": "label_values(ping_loss_percent, host)"
    }
   },
   {
    "name": "name_icmp",
    "label": "Target ICMP",
    "query": {
     "query": "label_values(ping_loss_percent{host=~\"$station\"}, name)"
    }
   },
   {
    "name": "name_mtr",
    "label": "Target MTR",
    "query": {
     "query": "label_values(mtr_hops{host=~\"$station\"}, name)"
    }
   },
   {
    "name": "name_tcp",
    "label": "Target TCP",
    "query": {
     "query": "label_values(tcp_connection_status{host=~\"$station\"}, name)"
    }
   },
   {
    "name": "name_http",
    "label": "Target HTTP",
    "query": {
     "query": "label_values(http_get_status{host=~\"$station\"}, name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "ICMP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Standard Deviation Statistics (Jitter) $station > $name_icmp",
   "type": "timeseries",
   "description": "- SD: Squared deviation\n- USD: Standard deviation without correction\n- CSD: Standard deviation with correction (Bessel's)\n- RANGE: Max-Min value range",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "keep_last_value(ping_rtt_seconds{host=~\"$station\",name=~\"$name_icmp\", type=\"sd\" }[$__interval])",
     "legendFormat": "SD"
    },
    {
     "expr": "keep_last_value(ping_rtt_seconds{host=~\"$station\",name=~\"$name_icmp\", type=\"usd\" }[$__interval])",
     "legendFormat": "USD"
    },
    {
     "expr": "keep_last_value(ping_rtt_seconds{host=~\"$station\",name=~\"$name_icmp\", type=\"csd\" }[$__interval])",
     "legendFormat": "CSD"
    },
    {
     "expr": "keep_last_value(ping_rtt_seconds{host=~\"$station\",name=~\"$name_icmp\", type=\"range\" }[$__interval])",
     "legendFormat": "RANGE"
    }
   ]
  },
  {
   "title": "Response time / Packet loss $station -> $name_icmp",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "keep_last_value(min_over_time(ping_rtt_seconds{host=~\"$station\",name=~\"$name_icmp\", type=\"best\"}[$__interval]))",
     "legendFormat": "best"
    },
    {
     "expr": "keep_last_value(avg_over_time(ping_rtt_seconds{host=~\"$station\",name=~\"$name_icmp\", type=\"mean\"}[$__interval]))",
     "legendFormat": "mean"
    },
    {
     "expr": "keep_last_value(max_over_time(ping_rtt_seconds{host=~\"$station\",name=~\"$name_icmp\", type=\"worst\"}[$__interval]))",
     "legendFormat": "worst"
    },
    {
     "expr": "ping_loss_percent{host=~\"$station\",name=~\"$name_icmp\"}",
     "legendFormat": "loss"
    }
   ]
  },
  {
   "title": "Packet loss (All) from $station",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "ping_loss_percent{host=~\"$station\"} <= 100 > 0 or (0)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Packet loss per Location -> $name_icmp",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "ping_loss_percent{name=~\"$name_icmp\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Response time per Location",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(avg_over_time(ping_rtt_seconds{name=~\"$name_icmp\", type=\"mean\"}[$__interval])) by (host)",
     "legendFormat": "mean - {{host}}"
    }
   ]
  },
  {
   "title": "MTR",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Hops",
   "type": "stat",
   "description": "Number of network HOPS",
   "gridPos": { "h": 29, "w": 2, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mtr_hops{host=~\"$station\",name=~\"$name_mtr\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "MTR - Mean $station -> $name_mtr",
   "type": "timeseries",
   "description": "Mean Response time",
   "gridPos": { "h": 11, "w": 22, "x": 2, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sort(keep_last_value(avg_over_time(mtr_rtt_seconds{host=~\"$station\",name=~\"$name_mtr\", type=\"mean\"}[$__interval])))",
     "legendFormat": "{{ttl}} - {{path}}"
    }
   ]
  },
  {
   "title": "MTR - Loss $station -> $name_mtr",
   "type": "timeseries",
   "description": "Packet loss in percent",
   "gridPos": { "h": 10, "w": 22, "x": 2, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sort(keep_last_value(avg_over_time(mtr_rtt_seconds{host=~\"$station\",name=~\"$name_mtr\", type=\"loss\"}[$__interval])))",
     "legendFormat": "{{ttl}} - {{path}}"
    }
   ]
  },
  {
   "title": "Hops - Changes to $name_mtr",
   "type": "timeseries",
   "description": "Number of network HOPS Changes",
   "gridPos": { "h": 8, "w": 22, "x": 2, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "changes(mtr_hops{name=~\"$name_mtr\"}[$__interval])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "TCP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Status",
     "type": "stat",
     "gridPos": { "h": 10, "w": 2, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "tcp_connection_status{host=~\"$station\",name=~\"$name_tcp\"}",
       "legendFormat": "{{target}}:{{port}}"
      }
     ]
    },
    {
     "title": "Connection time $station -> $name_tcp",
     "type": "timeseries",
     "description": "Response time",
     "gridPos": { "h": 10, "w": 22, "x": 2, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg_over_time(tcp_connection_seconds{host=~\"$station\",name=~\"$name_tcp\"}[$__interval])",
       "legendFormat": "{{target}}:{{port}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "HTTP Get $station -> $name_http",
     "type": "timeseries",
     "description": "Download Drilldown",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(http_get_seconds{host=~\"$station\",name=~\"$name_http\"}[$__interval]) by (host,type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "HTTP Get - Time $station -> $name_http",
     "type": "timeseries",
     "description": "Total Download time",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 88 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(http_get_seconds{name=~\"$name_http\", type=\"Total\"}[$__interval]) by (host)",
       "legendFormat": "{{station}}"
      }
     ]
    },
    {
     "title": "HTTP Get - Speed $station -> $name_http",
     "type": "timeseries",
     "description": "Download Speed",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 88 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "max(http_get_content_bytes{name=\"$name_http\"}) by (host) / avg(http_get_seconds{type=\"Total\",name=\"$name_http\"}[$__interval]) by (host)",
       "legendFormat": "{{station}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Exporter Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Target Status by Type $station",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ping_up{host=~\"$station\"}",
       "legendFormat": "ICMP - {{host}}"
      },
      {
       "expr": "mtr_up{host=~\"$station\"}",
       "legendFormat": "MTR - {{host}}"
      },
      {
       "expr": "tcp_up{host=~\"$station\"}",
       "legendFormat": "TCP - {{host}}"
      },
      {
       "expr": "http_get_up{host=~\"$station\"}",
       "legendFormat": "HTTPGet - {{host}}"
      }
     ]
    },
    {
     "title": "Active Targets by Type $station",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "sum(ping_targets{}) by (host)", "legendFormat": "ICMP - {{host}}" },
      { "expr": "sum(mtr_targets{}) by (host)", "legendFormat": "MTR - {{host}}" },
      { "expr": "sum(tcp_targets{}) by (host)", "legendFormat": "TCP - {{host}}" },
      {
       "expr": "sum(http_get_targets{}) by (host)",
       "legendFormat": "HTTPGet - {{host}}"
      }
     ]
    },
    {
     "title": "go goroutines",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(go_goroutines{host=\"$station\"}) by (host)",
       "legendFormat": "{{station}}"
      }
     ]
    },
    {
     "title": "go process resident memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{host=\"$station\"}",
       "legendFormat": "{{host}}"
      }
     ]
    }
   ]
  }
 ]
}