{
 "title": "Ceph Cluster - Advanced",
 "description": "Ceph cluster overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(cluster_name)" } },
   {
    "name": "pool_name",
    "label": "Pool Name",
    "query": {
     "query": "label_values(ceph_pool_metadata,name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CLUSTER STATE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ceph health status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_health_status{cluster_name=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Available Capacity",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(ceph_cluster_total_bytes{cluster_name=~\"$cluster\"}-ceph_cluster_total_used_bytes{cluster_name=~\"$cluster\"})/ceph_cluster_total_bytes{cluster_name=~\"$cluster\"}",
     "legendFormat": "{{cluster_name}}"
    }
   ]
  },
  {
   "title": "Cluster Capacity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_cluster_total_bytes{cluster_name=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Write Throughput",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_op_w_in_bytes{cluster_name=~\"$cluster\"}[5m]))"
    }
   ]
  },
  {
   "title": "Read Throughput",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_op_r_out_bytes{cluster_name=~\"$cluster\"}[5m]))"
    }
   ]
  },
  {
   "title": "OSDs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "All",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "count(ceph_osd_metadata{cluster_name=~\"$cluster\"})",
     "legendFormat": "All",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "alias": "In",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(ceph_osd_in{cluster_name=~\"$cluster\"})",
     "legendFormat": "In",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "alias": "Out",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(ceph_osd_in{cluster_name=~\"$cluster\"} == bool 0)",
     "legendFormat": "Out",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 1
    },
    {
     "aggregation": "Last",
     "alias": "Up",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(ceph_osd_up{cluster_name=~\"$cluster\"})",
     "legendFormat": "Up",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "alias": "Down",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(ceph_osd_up{cluster_name=~\"$cluster\"} == bool 0)",
     "legendFormat": "Down",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 1
    }
   ]
  },
  {
   "title": "MGRs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "Active",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "count(ceph_mgr_status{cluster_name=~\"$cluster\"} == 1) or vector(0)",
     "legendFormat": "Active",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "alias": "Standby",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "count(ceph_mgr_status{cluster_name=~\"$cluster\"} == 0) or vector(0)",
     "legendFormat": "Standby",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Firing Alerts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "Active",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "count(ALERTS{cluster_name=~\"$cluster\",alertstate=\"firing\",alertname=~\"^Ceph.+\", severity=\"critical\"}) OR vector(0)",
     "legendFormat": "Critical",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "alias": "Standby",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "count(ALERTS{cluster_name=~\"$cluster\",alertstate=\"firing\",alertname=~\"^Ceph.+\", severity=\"warning\"}) OR vector(0)",
     "legendFormat": "Warning",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Used Capacity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_cluster_total_used_bytes{cluster_name=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Write IOPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_op_w{cluster_name=~\"$cluster\"}[1m]))"
    }
   ]
  },
  {
   "title": "Read IOPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_op_r{cluster_name=~\"$cluster\"}[1m]))"
    }
   ]
  },
  {
   "title": "Monitors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "In Quorum",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(ceph_mon_quorum_status{cluster_name=~\"$cluster\"})",
     "legendFormat": "In Quorum",
     "units": "none",
     "valueHandler": "Text Only"
    },
    {
     "aggregation": "Last",
     "alias": "Total",
     "crit": 1,
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "count(ceph_mon_quorum_status{cluster_name=~\"$cluster\"})",
     "legendFormat": "Total",
     "units": "none",
     "valueHandler": "Text Only",
     "warn": 2
    },
    {
     "aggregation": "Last",
     "alias": "MONs out of Quorum",
     "crit": 1.6,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Annotation",
     "displayValueWithAlias": "Never",
     "expr": "count(ceph_mon_quorum_status{cluster_name=~\"$cluster\"}) - sum(ceph_mon_quorum_status{cluster_name=~\"$cluster\"})",
     "legendFormat": "MONs out of Quorum",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 1.1
    }
   ]
  },
  { "title": "CLUSTER STATS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 } },
  {
   "title": "Capacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "ceph_cluster_total_bytes{cluster_name=~\"$cluster\"}",
     "legendFormat": "Total Capacity"
    },
    {
     "expr": "ceph_cluster_total_used_bytes{cluster_name=~\"$cluster\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Cluster Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_op_w_in_bytes{cluster_name=~\"$cluster\"}[5m]))",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(irate(ceph_osd_op_r_out_bytes{cluster_name=~\"$cluster\"}[5m]))",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_op_w{cluster_name=~\"$cluster\"}[1m]))",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(irate(ceph_osd_op_r{cluster_name=~\"$cluster\"}[1m]))",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Pool Used Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(ceph_pool_bytes_used{cluster_name=~\"$cluster\"}) *on (pool_id) group_left(name)(ceph_pool_metadata{cluster_name=~\"$cluster\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Pool Used RAW Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(ceph_pool_stored_raw{cluster_name=~\"$cluster\"}) *on (pool_id) group_left(name)(ceph_pool_metadata{cluster_name=~\"$cluster\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Pool Objects Quota",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(ceph_pool_quota_objects{cluster_name=~\"$cluster\"}) *on (pool_id) group_left(name)(ceph_pool_metadata{cluster_name=~\"$cluster\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Pool Quota Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(ceph_pool_quota_bytes{cluster_name=~\"$cluster\"}) *on (pool_id) group_left(name)(ceph_pool_metadata{cluster_name=~\"$cluster\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Objects Per Pool",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(ceph_pool_objects{cluster_name=~\"$cluster\"}) *on (pool_id) group_left(name)(ceph_pool_metadata{cluster_name=~\"$cluster\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "OBJECTS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "OSD Type Count",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(ceph_pool_objects{cluster_name=~\"$cluster\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "PGs State",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 6, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(ceph_pg_active{cluster_name=~\"$cluster\"})",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(ceph_pg_clean{cluster_name=~\"$cluster\"})",
     "legendFormat": "Clean"
    },
    {
     "expr": "sum(ceph_pg_peering{cluster_name=~\"$cluster\"})",
     "legendFormat": "Peering"
    },
    {
     "expr": "sum(ceph_pg_degraded{cluster_name=~\"$cluster\"})",
     "legendFormat": "Degraded"
    },
    {
     "expr": "sum(ceph_pg_stale{cluster_name=~\"$cluster\"})",
     "legendFormat": "Stale"
    },
    {
     "expr": "sum(ceph_unclean_pgs{cluster_name=~\"$cluster\"})",
     "legendFormat": "Unclean"
    },
    {
     "expr": "sum(ceph_pg_undersized{cluster_name=~\"$cluster\"})",
     "legendFormat": "Undersized"
    },
    {
     "expr": "sum(ceph_pg_incomplete{cluster_name=~\"$cluster\"})",
     "legendFormat": "Incomplete"
    },
    {
     "expr": "sum(ceph_pg_forced_backfill{cluster_name=~\"$cluster\"})",
     "legendFormat": "Forced Backfill"
    },
    {
     "expr": "sum(ceph_pg_forced_recovery{cluster_name=~\"$cluster\"})",
     "legendFormat": "Forced Recovery"
    },
    {
     "expr": "sum(ceph_pg_creating{cluster_name=~\"$cluster\"})",
     "legendFormat": "Creating"
    },
    {
     "expr": "sum(ceph_pg_wait_backfill{cluster_name=~\"$cluster\"})",
     "legendFormat": "Wait Backfill"
    },
    {
     "expr": "sum(ceph_pg_deep{cluster_name=~\"$cluster\"})",
     "legendFormat": "Deep"
    },
    {
     "expr": "sum(ceph_pg_scrubbing{cluster_name=~\"$cluster\"})",
     "legendFormat": "Scrubbing"
    },
    {
     "expr": "sum(ceph_pg_recovering{cluster_name=~\"$cluster\"})",
     "legendFormat": "Recovering"
    },
    {
     "expr": "sum(ceph_pg_repair{cluster_name=~\"$cluster\"})",
     "legendFormat": "Repair"
    },
    {
     "expr": "sum(ceph_pg_down{cluster_name=~\"$cluster\"})",
     "legendFormat": "Down"
    },
    {
     "expr": "sum(ceph_pg_peered{cluster_name=~\"$cluster\"})",
     "legendFormat": "Peered"
    },
    {
     "expr": "sum(ceph_pg_backfill{cluster_name=~\"$cluster\"})",
     "legendFormat": "Backfill"
    },
    {
     "expr": "sum(ceph_pg_remapped{cluster_name=~\"$cluster\"})",
     "legendFormat": "Remapped"
    },
    {
     "expr": "sum(ceph_pg_backfill_toofull{cluster_name=~\"$cluster\"})",
     "legendFormat": "Backfill Toofull"
    }
   ]
  },
  {
   "title": "Stuck PGs",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(ceph_pg_degraded{cluster_name=~\"$cluster\"})",
     "legendFormat": "Degraded"
    },
    {
     "expr": "sum(ceph_pg_stale{cluster_name=~\"$cluster\"})",
     "legendFormat": "Stale"
    },
    {
     "expr": "sum(ceph_pg_undersized{cluster_name=~\"$cluster\"})",
     "legendFormat": "Undersized"
    }
   ]
  },
  {
   "title": "Recovery Operations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_recovery_ops{cluster_name=~\"$cluster\"}[$interval]))",
     "legendFormat": "OPS"
    }
   ]
  },
  { "title": "LATENCY", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "OSD Apply Latency Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "ceph_osd_apply_latency_ms{cluster_name=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "OSD Commit Latency Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "ceph_osd_commit_latency_ms{cluster_name=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "OSD Read Op Latency Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "rate(ceph_osd_op_r_latency_sum{cluster_name=~\"$cluster\"}[5m]) / rate(ceph_osd_op_r_latency_count{cluster_name=~\"$cluster\"}[5m]) >= 0"
    }
   ]
  },
  {
   "title": "OSD Write Op Latency Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "rate(ceph_osd_op_w_latency_sum{cluster_name=~\"$cluster\"}[5m]) / rate(ceph_osd_op_w_latency_count{cluster_name=~\"$cluster\"}[5m]) >= 0"
    }
   ]
  },
  {
   "title": "Recovery Operations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(rate(ceph_osd_op_r_latency_sum{cluster_name=~\"$cluster\"}[5m]) / rate(ceph_osd_op_r_latency_count{cluster_name=~\"$cluster\"}[5m]) >= 0)",
     "legendFormat": "Read"
    },
    {
     "expr": "avg(rate(ceph_osd_op_w_latency_sum{cluster_name=~\"$cluster\"}[5m]) / rate(ceph_osd_op_w_latency_count{cluster_name=~\"$cluster\"}[5m]) >= 0)",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "AVG OSD Apply + Commit Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(ceph_osd_apply_latency_ms{cluster_name=~\"$cluster\"})",
     "legendFormat": "apply"
    },
    {
     "expr": "avg(ceph_osd_commit_latency_ms{cluster_name=~\"$cluster\"})",
     "legendFormat": "commit"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Ceph Versions",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "count by (ceph_version)(ceph_osd_metadata{cluster_name=~\"$cluster\"})",
     "legendFormat": "OSD Services"
    },
    {
     "expr": "count by (ceph_version)(ceph_mon_metadata{cluster_name=~\"$cluster\"})",
     "legendFormat": "Mon Services"
    },
    {
     "expr": "count by (ceph_version)(ceph_mds_metadata{cluster_name=~\"$cluster\"})",
     "legendFormat": "MDS Services"
    },
    {
     "expr": "count by (ceph_version)(ceph_rgw_metadata{cluster_name=~\"$cluster\"})",
     "legendFormat": "RGW Services"
    },
    {
     "expr": "count by (ceph_version)(ceph_mgr_metadata{cluster_name=~\"$cluster\"})",
     "legendFormat": "MGR Services"
    }
   ]
  }
 ]
}