{
 "title": "Ceph capacity dashboard",
 "description": "Ceph cluster overview",
 "tags": [ "folder-capacity" ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(cluster_name)" } },
   {
    "name": "pool_name",
    "label": "Pool Name",
    "query": {
     "query": "label_values(ceph_pool_metadata,name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "POOLS OVERVIEW", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "us-dfw-object-data-pool",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_pool_percent_used{cluster_name=\"us-dfw-object\",pool_id=\"29\"})",
     "legendFormat": "us-dfw-object-data-pool"
    }
   ]
  },
  {
   "title": "de-fra-object-data-pool",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_pool_percent_used{cluster_name=\"de-fra-object\",pool_id=\"26\"})",
     "legendFormat": "de-fra-object"
    }
   ]
  },
  {
   "title": "de-fra-nvme-block-data-pool",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_pool_percent_used{cluster_name=\"de-fra-nvme-block\",pool_id=\"2\"})",
     "legendFormat": "de-fra-nvme-block"
    }
   ]
  },
  {
   "title": "gb-lon-archive-data-pool",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_pool_percent_used{cluster_name=\"gb-lon-archive\",pool_id=\"19\"})",
     "legendFormat": "gb-lon-archive"
    }
   ]
  },
  {
   "title": "gb-lon-object-data-pool",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_pool_percent_used{cluster_name=\"gb-lon-object\",pool_id=\"21\"})",
     "legendFormat": "gb-lon-object"
    }
   ]
  },
  {
   "title": "gb-lon-nvme-block-data-pool",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_pool_percent_used{cluster_name=\"gb-lon-nvme-block\",pool_id=\"2\"})",
     "legendFormat": "gb-lon-nvme-block"
    }
   ]
  },
  { "title": "US-DFW DATA POOL USAGE STATS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "us-dfw-object-data-pool",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_pool_percent_used{cluster_name=\"us-dfw-object\",pool_id=\"29\"})",
     "legendFormat": "us-dfw-object-data-pool"
    }
   ]
  },
  {
   "title": "us-dfw-object-data-pool",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(ceph_pool_max_avail{cluster_name=\"us-dfw-object\", pool_id=\"29\"})+sum(ceph_pool_bytes_used{cluster_name=\"us-dfw-object\", pool_id=\"29\"})",
     "legendFormat": "Capacity TiB"
    },
    {
     "expr": "sum(ceph_pool_bytes_used{cluster_name=\"us-dfw-object\", pool_id=\"29\"})",
     "legendFormat": "Pool Usage TiB"
    }
   ]
  },
  {
   "title": "us-dfw-object-data-pool % used over time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "ceph_pool_percent_used{cluster_name=\"us-dfw-object\", pool_id=\"29\"}",
     "legendFormat": "us-dfw-object-data-pool"
    }
   ]
  },
  { "title": "DE-FRA DATA POOL USAGE STATS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "de-fra-object-data-pool",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_pool_percent_used{cluster_name=\"de-fra-object\",pool_id=\"26\"})",
     "legendFormat": "de-fra-object"
    }
   ]
  },
  {
   "title": "de-fra-object-data-pool",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(ceph_pool_max_avail{cluster_name=\"de-fra-object\", pool_id=\"26\"})+sum(ceph_pool_bytes_used{cluster_name=\"de-fra-object\", pool_id=\"26\"})",
     "legendFormat": "Capacity TiB"
    },
    {
     "expr": "sum(ceph_pool_bytes_used{cluster_name=\"de-fra-object\", pool_id=\"26\"})",
     "legendFormat": "Pool Usage TiB"
    }
   ]
  },
  {
   "title": "de-fra-object-data-pool % used over time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "ceph_pool_percent_used{cluster_name=\"de-fra-object\", pool_id=\"26\"}",
     "legendFormat": "de-fra-object-data-pool"
    }
   ]
  },
  {
   "title": "de-fra-nvme-block-data-pool",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_pool_percent_used{cluster_name=\"de-fra-nvme-block\",pool_id=\"2\"})",
     "legendFormat": "de-fra-nvme-block"
    }
   ]
  },
  {
   "title": "de-fra-nvme-block-data-pool ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(ceph_pool_max_avail{cluster_name=\"de-fra-nvme-block\", pool_id=\"2\"})+sum(ceph_pool_bytes_used{cluster_name=\"de-fra-nvme-block\", pool_id=\"2\"})",
     "legendFormat": "Capacity TiB"
    },
    {
     "expr": "sum(ceph_pool_bytes_used{cluster_name=\"de-fra-nvme-block\", pool_id=\"2\"})",
     "legendFormat": "Pool Usage TiB"
    }
   ]
  },
  {
   "title": "de-fra-nvme-block-data-pool % used over time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "ceph_pool_percent_used{cluster_name=\"de-fra-nvme-block\", pool_id=\"2\"}",
     "legendFormat": "de-fra-nvme-block-data-pool"
    }
   ]
  },
  { "title": "GB-LON DATA POOL USAGE STATS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "gb-lon-archive-data-pool",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_pool_percent_used{cluster_name=\"gb-lon-archive\",pool_id=\"19\"})",
     "legendFormat": "gb-lon-archive"
    }
   ]
  },
  {
   "title": "gb-lon-archive-pool",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(ceph_pool_max_avail{cluster_name=\"gb-lon-archive\", pool_id=\"19\"})+sum(ceph_pool_bytes_used{cluster_name=\"gb-lon-archive\", pool_id=\"19\"})",
     "legendFormat": "Capacity TiB"
    },
    {
     "expr": "sum(ceph_pool_bytes_used{cluster_name=\"gb-lon-archive\", pool_id=\"19\"})",
     "legendFormat": "Pool Usage TiB"
    }
   ]
  },
  {
   "title": "gb-lon-archive-data-pool % used over time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "ceph_pool_percent_used{cluster_name=\"gb-lon-archive\", pool_id=\"19\"}",
     "legendFormat": "gb-lon-archive-data-pool"
    }
   ]
  },
  {
   "title": "gb-lon-object-data-pool",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_pool_percent_used{cluster_name=\"gb-lon-object\",pool_id=\"21\"})",
     "legendFormat": "gb-lon-object"
    }
   ]
  },
  {
   "title": "gb-lon-object-pool",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(ceph_pool_max_avail{cluster_name=\"gb-lon-object\", pool_id=\"21\"})+sum(ceph_pool_bytes_used{cluster_name=\"gb-lon-object\", pool_id=\"21\"})",
     "legendFormat": "Capacity TiB"
    },
    {
     "expr": "sum(ceph_pool_bytes_used{cluster_name=\"gb-lon-object\", pool_id=\"21\"})",
     "legendFormat": "Pool Usage TiB"
    }
   ]
  },
  {
   "title": "gb-lon-object-data-pool % used over time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "ceph_pool_percent_used{cluster_name=\"gb-lon-object\", pool_id=\"21\"}",
     "legendFormat": "gb-lon-object-data-pool"
    }
   ]
  },
  {
   "title": "gb-lon-nvme-block-data-pool",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_pool_percent_used{cluster_name=\"gb-lon-nvme-block\",pool_id=\"2\"})",
     "legendFormat": "gb-lon-nvme-block"
    }
   ]
  },
  {
   "title": "gb-lon-nvme-block-data-pool",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(ceph_pool_max_avail{cluster_name=\"gb-lon-nvme-block\", pool_id=\"2\"})+sum(ceph_pool_bytes_used{cluster_name=\"gb-lon-nvme-block\", pool_id=\"2\"})",
     "legendFormat": "Capacity TiB"
    },
    {
     "expr": "sum(ceph_pool_bytes_used{cluster_name=\"gb-lon-nvme-block\", pool_id=\"2\"})",
     "legendFormat": "Pool Usage TiB"
    }
   ]
  },
  {
   "title": "gb-lon-nvme-block-data-pool % used over time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "ceph_pool_percent_used{cluster_name=\"gb-lon-nvme-block\", pool_id=\"2\"}",
     "legendFormat": "gb-lon-nvme-block-data-pool"
    }
   ]
  },
  { "title": "RAW CLUSTER CAPACITY STATS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "us-dfw-object-raw",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_cluster_total_used_raw_bytes{cluster_name=\"us-dfw-object\"})/sum(ceph_cluster_total_bytes{cluster_name=\"us-dfw-object\"})",
     "legendFormat": "us-dfw-object"
    }
   ]
  },
  {
   "title": "US-DFW-OBJECT-CONSUMED",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(ceph_pool_bytes_used{cluster_name=\"us-dfw-object\"})",
     "legendFormat": "RAW Consumed"
    },
    {
     "expr": "sum(ceph_osd_stat_bytes{cluster_name=\"us-dfw-object\"})  ",
     "legendFormat": "RAW Capacity"
    }
   ]
  },
  {
   "title": "de-fra-object-raw",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_cluster_total_used_raw_bytes{cluster_name=\"de-fra-object\"})/sum(ceph_cluster_total_bytes{cluster_name=\"de-fra-object\"})",
     "legendFormat": "de-fra-object"
    }
   ]
  },
  {
   "title": "DE-FRA-OBJECT-CONSUMED",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(ceph_pool_bytes_used{cluster_name=\"de-fra-object\"})",
     "legendFormat": "RAW Consumed"
    },
    {
     "expr": "sum(ceph_osd_stat_bytes{cluster_name=\"de-fra-object\"})  ",
     "legendFormat": "RAW Capacity"
    }
   ]
  },
  {
   "title": "de-fra-nvme-block-raw",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_cluster_total_used_raw_bytes{cluster_name=\"de-fra-nvme-block\"})/sum(ceph_cluster_total_bytes{cluster_name=\"de-fra-nvme-block\"})",
     "legendFormat": "de-fra-nvme-block"
    }
   ]
  },
  {
   "title": "DE-FRA-NVME-BLOCK",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(ceph_pool_bytes_used{cluster_name=\"de-fra-nvme-block\"})",
     "legendFormat": "RAW Consumed"
    },
    {
     "expr": "sum(ceph_osd_stat_bytes{cluster_name=\"de-fra-nvme-block\"})  ",
     "legendFormat": "RAW Capacity"
    }
   ]
  },
  {
   "title": "gb-lon-archive-raw",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_cluster_total_used_raw_bytes{cluster_name=\"gb-lon-archive\"})/sum(ceph_cluster_total_bytes{cluster_name=\"gb-lon-archive\"})",
     "legendFormat": "gb-lon-archive"
    }
   ]
  },
  {
   "title": "gb-lon-archive-raw",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(ceph_pool_bytes_used{cluster_name=\"gb-lon-archive\"})",
     "legendFormat": "RAW Consumed"
    },
    {
     "expr": "sum(ceph_osd_stat_bytes{cluster_name=\"gb-lon-archive\"})  ",
     "legendFormat": "RAW Capacity"
    }
   ]
  },
  {
   "title": "gb-lon-object-raw",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_cluster_total_used_raw_bytes{cluster_name=\"gb-lon-object\"})/sum(ceph_cluster_total_bytes{cluster_name=\"gb-lon-object\"})",
     "legendFormat": "gb-lon-object-raw"
    }
   ]
  },
  {
   "title": "gb-lon-object-raw",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(ceph_pool_bytes_used{cluster_name=\"gb-lon-object\"})",
     "legendFormat": "RAW Consumed"
    },
    {
     "expr": "sum(ceph_osd_stat_bytes{cluster_name=\"gb-lon-object\"})  ",
     "legendFormat": "RAW Capacity"
    }
   ]
  },
  {
   "title": "gb-lon-nvme-block-raw",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_cluster_total_used_raw_bytes{cluster_name=\"gb-lon-nvme-block\"})/sum(ceph_cluster_total_bytes{cluster_name=\"gb-lon-nvme-block\"})",
     "legendFormat": "gb-lon-nvme-block-raw"
    }
   ]
  },
  {
   "title": "gb-lon-nvme-block-raw",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(ceph_pool_bytes_used{cluster_name=\"gb-lon-nvme-block\"})",
     "legendFormat": "RAW Consumed"
    },
    {
     "expr": "sum(ceph_osd_stat_bytes{cluster_name=\"gb-lon-nvme-block\"})  ",
     "legendFormat": "RAW Capacity"
    }
   ]
  }
 ]
}