{
 "title": "OSD device details",
 "tags": [
  "ceph-mixin",
  "folder-ceph"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(cluster_name)" } },
   {
    "name": "osd",
    "label": "OSD",
    "query": {
     "query": "label_values(ceph_osd_metadata{cluster_name=\"$cluster\"},ceph_daemon)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "OSD Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$osd Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(ceph_osd_op_r_latency_sum{cluster_name=~\"$cluster\", ceph_daemon=~\"$osd\"}[$__rate_interval]) /\n  on (ceph_daemon) rate(ceph_osd_op_r_latency_count{cluster_name=~\"$cluster\", ceph_daemon=~\"$osd\"}[$__rate_interval])\n",
     "legendFormat": "read"
    },
    {
     "expr": "rate(ceph_osd_op_w_latency_sum{cluster_name=~\"$cluster\", ceph_daemon=~\"$osd\"}[$__rate_interval]) /\n  on (ceph_daemon) rate(ceph_osd_op_w_latency_count{cluster_name=~\"$cluster\", ceph_daemon=~\"$osd\"}[$__rate_interval])\n",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "$osd R/W IOPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(ceph_osd_op_r{cluster_name=~\"$cluster\", ceph_daemon=~\"$osd\"}[$__rate_interval])",
     "legendFormat": "Reads"
    },
    {
     "expr": "rate(ceph_osd_op_w{cluster_name=~\"$cluster\", ceph_daemon=~\"$osd\"}[$__rate_interval])",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "$osd R/W Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(ceph_osd_op_r_out_bytes{cluster_name=~\"$cluster\", ceph_daemon=~\"$osd\"}[$__rate_interval])",
     "legendFormat": "Read Bytes"
    },
    {
     "expr": "rate(ceph_osd_op_w_in_bytes{cluster_name=~\"$cluster\", ceph_daemon=~\"$osd\"}[$__rate_interval])",
     "legendFormat": "Write Bytes"
    }
   ]
  },
  {
   "title": "Physical Device Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Physical Device Latency for $osd",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(\n  label_replace(\n    rate(node_disk_read_time_seconds_total{}[$__rate_interval]) /\n      rate(node_disk_reads_completed_total{}[$__rate_interval]),\n    \"instance\", \"$1\", \"instance\", \"([^:.]*).*\"\n  ) and on (instance, device) label_replace(\n    label_replace(\n      ceph_disk_occupation_human{cluster_name=~\"$cluster\", ceph_daemon=~\"$osd\"},\n      \"device\", \"$1\", \"device\", \"/dev/(.*)\"\n    ), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\"\n  )\n)\n",
     "legendFormat": "{{instance}}/{{device}} Reads"
    },
    {
     "expr": "(\n  label_replace(\n    rate(node_disk_write_time_seconds_total{}[$__rate_interval]) /\n      rate(node_disk_writes_completed_total{}[$__rate_interval]),\n    \"instance\", \"$1\", \"instance\", \"([^:.]*).*\") and on (instance, device)\n    label_replace(\n      label_replace(\n        ceph_disk_occupation_human{cluster_name=~\"$cluster\", ceph_daemon=~\"$osd\"}, \"device\", \"$1\", \"device\", \"/dev/(.*)\"\n      ), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\"\n    )\n  )\n",
     "legendFormat": "{{instance}}/{{device}} Writes"
    }
   ]
  },
  {
   "title": "Physical Device R/W IOPS for $osd",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(\n  rate(node_disk_writes_completed_total{}[$__rate_interval]),\n  \"instance\", \"$1\", \"instance\", \"([^:.]*).*\"\n) and on (instance, device) label_replace(\n  label_replace(\n    ceph_disk_occupation_human{cluster_name=~\"$cluster\", ceph_daemon=~\"$osd\"},\n    \"device\", \"$1\", \"device\", \"/dev/(.*)\"\n  ), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\"\n)\n",
     "legendFormat": "{{device}} on {{instance}} Writes"
    },
    {
     "expr": "label_replace(\n  rate(node_disk_reads_completed_total{}[$__rate_interval]),\n  \"instance\", \"$1\", \"instance\", \"([^:.]*).*\"\n) and on (instance, device) label_replace(\n  label_replace(\n    ceph_disk_occupation_human{cluster_name=~\"$cluster\", ceph_daemon=~\"$osd\"},\n    \"device\", \"$1\", \"device\", \"/dev/(.*)\"\n  ), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\"\n)\n",
     "legendFormat": "{{device}} on {{instance}} Reads"
    }
   ]
  },
  {
   "title": "Physical Device R/W Bytes for $osd",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "label_replace(\n  rate(node_disk_read_bytes_total{}[$__rate_interval]), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\"\n) and on (instance, device) label_replace(\n  label_replace(\n    ceph_disk_occupation_human{cluster_name=~\"$cluster\", ceph_daemon=~\"$osd\"},\n    \"device\", \"$1\", \"device\", \"/dev/(.*)\"\n  ), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\"\n)\n",
     "legendFormat": "{{instance}} {{device}} Reads"
    },
    {
     "expr": "label_replace(\n  rate(node_disk_written_bytes_total{}[$__rate_interval]), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\"\n) and on (instance, device) label_replace(\n  label_replace(\n    ceph_disk_occupation_human{cluster_name=~\"$cluster\", ceph_daemon=~\"$osd\"},\n    \"device\", \"$1\", \"device\", \"/dev/(.*)\"\n  ), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\"\n)\n",
     "legendFormat": "{{instance}} {{device}} Writes"
    }
   ]
  },
  {
   "title": "Physical Device Util% for $osd",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "label_replace(\n  rate(node_disk_io_time_seconds_total{}[$__rate_interval]),\n  \"instance\", \"$1\", \"instance\", \"([^:.]*).*\"\n) and on (instance, device) label_replace(\n  label_replace(\n    ceph_disk_occupation_human{cluster_name=~\"$cluster\", ceph_daemon=~\"$osd\"}, \"device\", \"$1\", \"device\", \"/dev/(.*)\"\n  ), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\"\n)\n",
     "legendFormat": "{{device}} on {{instance}}"
    }
   ]
  }
 ]
}