{
 "title": "Ceph Pool Details",
 "tags": [
  "ceph-mixin",
  "folder-ceph"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(cluster_name)" } },
   {
    "name": "pool_name",
    "label": "Pool Name",
    "query": {
     "query": "label_values(ceph_pool_metadata{cluster_name=\"$cluster\"},name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Capacity used",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(ceph_pool_stored{cluster_name=~\"$cluster\"} / (ceph_pool_stored{cluster_name=~\"$cluster\"} + ceph_pool_max_avail{cluster_name=~\"$cluster\"})) * on(pool_id) group_left(instance, name) ceph_pool_metadata{cluster_name=~\"$cluster\", name=~\"$pool_name\"}\n"
    }
   ]
  },
  {
   "title": "Time till full",
   "type": "stat",
   "description": "Time till pool is full assuming the average fill rate of the last 24 hours",
   "gridPos": { "h": 7, "w": 5, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(ceph_pool_max_avail{cluster_name=~\"$cluster\"} / deriv(ceph_pool_stored{cluster_name=~\"$cluster\"}[6h])) * on(pool_id) group_left(instance, name) ceph_pool_metadata{cluster_name=~\"$cluster\", name=~\"$pool_name\"} > 0"
    }
   ]
  },
  {
   "title": "$pool_name Object Ingress/Egress",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ops", "label": "Objects out(-) / in(+) " }
   ],
   "targets": [
    {
     "expr": "deriv(ceph_pool_objects{cluster_name=~\"$cluster\"}[1m]) *\n  on(pool_id) group_left(instance, name) ceph_pool_metadata{cluster_name=~\"$cluster\", name=~\"$pool_name\"}\n",
     "legendFormat": "Objects per second"
    }
   ]
  },
  {
   "title": "$pool_name Client IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "iops", "label": "Read (-) / Write (+)" }
   ],
   "targets": [
    {
     "expr": "rate(ceph_pool_rd{cluster_name=~\"$cluster\"}[$__rate_interval]) *\n  on(pool_id) group_left(instance,name) ceph_pool_metadata{cluster_name=~\"$cluster\", name=~\"$pool_name\"}\n",
     "legendFormat": "reads"
    },
    {
     "expr": "rate(ceph_pool_wr{cluster_name=~\"$cluster\"}[$__rate_interval]) *\n  on(pool_id) group_left(instance, name) ceph_pool_metadata{cluster_name=~\"$cluster\", name=~\"$pool_name\"}\n",
     "legendFormat": "writes"
    }
   ]
  },
  {
   "title": "$pool_name Client Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "Bps", "label": "Read (-) / Write (+)" }
   ],
   "targets": [
    {
     "expr": "rate(ceph_pool_rd_bytes{cluster_name=~\"$cluster\"}[$__rate_interval]) +\n  on(pool_id) group_left(instance, name) ceph_pool_metadata{cluster_name=~\"$cluster\", name=~\"$pool_name\"}\n",
     "legendFormat": "reads"
    },
    {
     "expr": "rate(ceph_pool_wr_bytes{cluster_name=~\"$cluster\"}[$__rate_interval]) +\n  on(pool_id) group_left(instance,name) ceph_pool_metadata{cluster_name=~\"$cluster\", name=~\"$pool_name\"}\n",
     "legendFormat": "writes"
    }
   ]
  },
  {
   "title": "$pool_name Objects",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "Objects" }
   ],
   "targets": [
    {
     "expr": "ceph_pool_objects{cluster_name=~\"$cluster\"} *\n  on(pool_id) group_left(instance,name) ceph_pool_metadata{cluster_name=~\"$cluster\", name=~\"$pool_name\"}\n",
     "legendFormat": "Number of Objects"
    }
   ]
  }
 ]
}