{
 "title": "RGW Overview",
 "tags": [ "ceph-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(cluster_name)" } },
   {
    "name": "rgw_servers",
    "query": {
     "query": "label_values(ceph_rgw_metadata{cluster_name=\"$cluster\"},ceph_daemon)"
    }
   },
   {
    "name": "code",
    "label": "HTTP Code",
    "query": "label_values(haproxy_server_http_responses_total{job=~\"$job_haproxy\", instance=~\"$ingress_service\"}, code)"
   },
   {
    "name": "job_haproxy",
    "label": "job haproxy",
    "query": "label_values(haproxy_server_status, job)"
   },
   {
    "name": "ingress_service",
    "label": "Ingress Service",
    "query": "label_values(haproxy_server_status{job=~\"$job_haproxy\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "RGW Overview - All Gateways",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Average GET/PUT Latencies by RGW Instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "label_replace(\n  rate(ceph_rgw_get_initial_lat_sum{cluster_name=~\"$cluster\"}[$__rate_interval]) /\n    rate(ceph_rgw_get_initial_lat_count{cluster_name=~\"$cluster\"}[$__rate_interval]) *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{cluster_name=~\"$cluster\", ceph_daemon=~\"$rgw_servers\"},\n  \"rgw_host\", \"$1\", \"ceph_daemon\", \"rgw.(.*)\"\n)\n",
     "legendFormat": "GET {{rgw_host}}"
    },
    {
     "expr": "label_replace(\n  rate(ceph_rgw_put_initial_lat_sum{cluster_name=~\"$cluster\"}[$__rate_interval]) /\n    rate(ceph_rgw_put_initial_lat_count{cluster_name=~\"$cluster\"}[$__rate_interval]) *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{cluster_name=~\"$cluster\", ceph_daemon=~\"$rgw_servers\"},\n  \"rgw_host\", \"$1\", \"ceph_daemon\", \"rgw.(.*)\"\n)\n",
     "legendFormat": "PUT {{rgw_host}}"
    }
   ]
  },
  {
   "title": "Total Requests/sec by RGW Instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (rgw_host) (\n  label_replace(\n    rate(ceph_rgw_req{cluster_name=~\"$cluster\"}[$__rate_interval]) *\n      on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{cluster_name=~\"$cluster\", ceph_daemon=~\"$rgw_servers\"},\n    \"rgw_host\", \"$1\", \"ceph_daemon\", \"rgw.(.*)\"\n  )\n)\n",
     "legendFormat": "{{rgw_host}}"
    }
   ]
  },
  {
   "title": "GET Latencies by RGW Instance",
   "type": "timeseries",
   "description": "Latencies are shown stacked, without a yaxis to provide a visual indication of GET latency imbalance across RGW hosts",
   "gridPos": { "h": 7, "w": 6, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "label_replace(\n  rate(ceph_rgw_get_initial_lat_sum{cluster_name=~\"$cluster\"}[$__rate_interval]) /\n    rate(ceph_rgw_get_initial_lat_count{cluster_name=~\"$cluster\"}[$__rate_interval]) *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{cluster_name=~\"$cluster\", ceph_daemon=~\"$rgw_servers\"},\n  \"rgw_host\", \"$1\", \"ceph_daemon\", \"rgw.(.*)\"\n)\n",
     "legendFormat": "{{rgw_host}}"
    }
   ]
  },
  {
   "title": "Bandwidth Consumed by Type",
   "type": "timeseries",
   "description": "Total bytes transferred in/out of all radosgw instances within the cluster",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(ceph_rgw_get_b{cluster_name=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "GETs"
    },
    {
     "expr": "sum(rate(ceph_rgw_put_b{cluster_name=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "PUTs"
    }
   ]
  },
  {
   "title": "Bandwidth by RGW Instance",
   "type": "timeseries",
   "description": "Total bytes transferred in/out through get/put operations, by radosgw instance",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "label_replace(sum by (instance_id) (\n  rate(ceph_rgw_get_b{cluster_name=~\"$cluster\"}[$__rate_interval]) +\n    rate(ceph_rgw_put_b{cluster_name=~\"$cluster\"}[$__rate_interval])) *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{cluster_name=~\"$cluster\", ceph_daemon=~\"$rgw_servers\"},\n  \"rgw_host\", \"$1\", \"ceph_daemon\", \"rgw.(.*)\"\n)\n",
     "legendFormat": "{{rgw_host}}"
    }
   ]
  },
  {
   "title": "PUT Latencies by RGW Instance",
   "type": "timeseries",
   "description": "Latencies are shown stacked, without a yaxis to provide a visual indication of PUT latency imbalance across RGW hosts",
   "gridPos": { "h": 6, "w": 6, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "label_replace(\n  rate(ceph_rgw_put_initial_lat_sum{cluster_name=~\"$cluster\"}[$__rate_interval]) /\n    rate(ceph_rgw_put_initial_lat_count{cluster_name=~\"$cluster\"}[$__rate_interval]) *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{cluster_name=~\"$cluster\", ceph_daemon=~\"$rgw_servers\"},\n  \"rgw_host\", \"$1\", \"ceph_daemon\", \"rgw.(.*)\"\n)\n",
     "legendFormat": "{{rgw_host}}"
    }
   ]
  },
  {
   "title": "RGW Overview - HAProxy Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total responses by HTTP code",
   "type": "graph",
   "gridPos": { "h": 12, "w": 5, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(\n    haproxy_frontend_http_responses_total{code=~\"$code\", job=~\"$job_haproxy\", instance=~\"$ingress_service\", proxy=~\"frontend\"}[$__rate_interval]\n  )\n) by (code)\n",
     "legendFormat": "Frontend {{ code }}"
    },
    {
     "expr": "sum(\n  rate(\n    haproxy_backend_http_responses_total{code=~\"$code\", job=~\"$job_haproxy\", instance=~\"$ingress_service\", proxy=~\"backend\"}[$__rate_interval]\n  )\n) by (code)\n",
     "legendFormat": "Backend {{ code }}"
    }
   ]
  },
  {
   "title": "Total requests / responses",
   "type": "graph",
   "gridPos": { "h": 12, "w": 5, "x": 5, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(\n    haproxy_frontend_http_requests_total{proxy=~\"frontend\", job=~\"$job_haproxy\", instance=~\"$ingress_service\"}[$__rate_interval]\n  )\n) by (instance)\n",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(\n  rate(\n    haproxy_backend_response_errors_total{proxy=~\"backend\", job=~\"$job_haproxy\", instance=~\"$ingress_service\"}[$__rate_interval]\n  )\n) by (instance)\n",
     "legendFormat": "Response errors"
    },
    {
     "expr": "sum(\n  rate(\n    haproxy_frontend_request_errors_total{proxy=~\"frontend\", job=~\"$job_haproxy\", instance=~\"$ingress_service\"}[$__rate_interval]\n  )\n) by (instance)\n",
     "legendFormat": "Requests errors"
    },
    {
     "expr": "sum(\n  rate(\n    haproxy_backend_redispatch_warnings_total{proxy=~\"backend\", job=~\"$job_haproxy\", instance=~\"$ingress_service\"}[$__rate_interval]\n  )\n) by (instance)\n",
     "legendFormat": "Backend redispatch"
    },
    {
     "expr": "sum(\n  rate(\n    haproxy_backend_retry_warnings_total{proxy=~\"backend\", job=~\"$job_haproxy\", instance=~\"$ingress_service\"}[$__rate_interval]\n  )\n) by (instance)\n",
     "legendFormat": "Backend retry"
    },
    {
     "expr": "sum(\n  rate(\n    haproxy_frontend_requests_denied_total{proxy=~\"frontend\", job=~\"$job_haproxy\", instance=~\"$ingress_service\"}[$__rate_interval]\n  )\n) by (instance)\n",
     "legendFormat": "Request denied"
    },
    {
     "expr": "sum(\n  haproxy_backend_current_queue{proxy=~\"backend\", job=~\"$job_haproxy\", instance=~\"$ingress_service\"}\n) by (instance)\n",
     "legendFormat": "Backend Queued"
    }
   ]
  },
  {
   "title": "Total number of connections",
   "type": "graph",
   "gridPos": { "h": 12, "w": 5, "x": 10, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(\n    haproxy_frontend_connections_total{proxy=~\"frontend\", job=~\"$job_haproxy\", instance=~\"$ingress_service\"}[$__rate_interval]\n  )\n) by (instance)\n",
     "legendFormat": "Front"
    },
    {
     "expr": "sum(\n  rate(\n    haproxy_backend_connection_attempts_total{proxy=~\"backend\", job=~\"$job_haproxy\", instance=~\"$ingress_service\"}[$__rate_interval]\n  )\n) by (instance)\n",
     "legendFormat": "Back"
    },
    {
     "expr": "sum(\n  rate(\n    haproxy_backend_connection_errors_total{proxy=~\"backend\", job=~\"$job_haproxy\", instance=~\"$ingress_service\"}[$__rate_interval]\n  )\n) by (instance)\n",
     "legendFormat": "Back errors"
    }
   ]
  },
  {
   "title": "Current total of incoming / outgoing bytes",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 15, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(\n    haproxy_frontend_bytes_in_total{proxy=~\"frontend\", job=~\"$job_haproxy\", instance=~\"$ingress_service\"}[$__rate_interval]\n  ) * 8\n) by (instance)\n",
     "legendFormat": "IN Front"
    },
    {
     "expr": "sum(\n  rate(\n    haproxy_frontend_bytes_out_total{proxy=~\"frontend\", job=~\"$job_haproxy\", instance=~\"$ingress_service\"}[$__rate_interval]\n  ) * 8\n) by (instance)\n",
     "legendFormat": "OUT Front"
    },
    {
     "expr": "sum(\n  rate(\n    haproxy_backend_bytes_in_total{proxy=~\"backend\", job=~\"$job_haproxy\", instance=~\"$ingress_service\"}[$__rate_interval]\n  ) * 8\n) by (instance)\n",
     "legendFormat": "IN Back"
    },
    {
     "expr": "sum(\n  rate(\n    haproxy_backend_bytes_out_total{proxy=~\"backend\", job=~\"$job_haproxy\", instance=~\"$ingress_service\"}[$__rate_interval]\n  ) * 8\n) by (instance)\n",
     "legendFormat": "OUT Back"
    }
   ]
  }
 ]
}