{
 "title": "RGW Instance Detail",
 "tags": [
  "ceph-mixin",
  "overview"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(cluster_name)" } },
   {
    "name": "rgw_servers",
    "query": {
     "query": "label_values(ceph_rgw_metadata{cluster_name=\"$cluster\"},ceph_daemon)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "RGW Host Detail : $rgw_servers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$rgw_servers GET/PUT Latencies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (instance_id) (\n  rate(ceph_rgw_get_initial_lat_sum{cluster_name=~\"$cluster\"}[$__rate_interval]) /\n    rate(ceph_rgw_get_initial_lat_count{cluster_name=~\"$cluster\"}[$__rate_interval])\n) * on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{cluster_name=~\"$cluster\", ceph_daemon=~\"$rgw_servers\"}\n",
     "legendFormat": "GET {{ceph_daemon}}"
    },
    {
     "expr": "sum by (instance_id) (\n  rate(ceph_rgw_put_initial_lat_sum{cluster_name=~\"$cluster\"}[$__rate_interval]) /\n    rate(ceph_rgw_put_initial_lat_count{cluster_name=~\"$cluster\"}[$__rate_interval])\n) * on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{cluster_name=~\"$cluster\", ceph_daemon=~\"$rgw_servers\"}\n",
     "legendFormat": "PUT {{ceph_daemon}}"
    }
   ]
  },
  {
   "title": "Bandwidth by HTTP Operation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(ceph_rgw_get_b{cluster_name=~\"$cluster\"}[$__rate_interval]) *\n  on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{cluster_name=~\"$cluster\", ceph_daemon=~\"$rgw_servers\"}\n",
     "legendFormat": "GETs {{ceph_daemon}}"
    },
    {
     "expr": "rate(ceph_rgw_put_b{cluster_name=~\"$cluster\"}[$__rate_interval]) *\n  on (instance_id) group_left (ceph_daemon)\n  ceph_rgw_metadata{cluster_name=~\"$cluster\", ceph_daemon=~\"$rgw_servers\"}\n",
     "legendFormat": "PUTs {{ceph_daemon}}"
    }
   ]
  },
  {
   "title": "HTTP Request Breakdown",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(ceph_rgw_failed_req{cluster_name=~\"$cluster\"}[$__rate_interval]) *\n  on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{cluster_name=~\"$cluster\", ceph_daemon=~\"$rgw_servers\"}\n",
     "legendFormat": "Requests Failed {{ceph_daemon}}"
    },
    {
     "expr": "rate(ceph_rgw_get{cluster_name=~\"$cluster\"}[$__rate_interval]) *\n  on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{cluster_name=~\"$cluster\", ceph_daemon=~\"$rgw_servers\"}\n",
     "legendFormat": "GETs {{ceph_daemon}}"
    },
    {
     "expr": "rate(ceph_rgw_put{cluster_name=~\"$cluster\"}[$__rate_interval]) *\n  on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{cluster_name=~\"$cluster\", ceph_daemon=~\"$rgw_servers\"}\n",
     "legendFormat": "PUTs {{ceph_daemon}}"
    },
    {
     "expr": "(\n  rate(ceph_rgw_req{cluster_name=~\"$cluster\"}[$__rate_interval]) -\n    (\n      rate(ceph_rgw_get{cluster_name=~\"$cluster\"}[$__rate_interval]) +\n        rate(ceph_rgw_put{cluster_name=~\"$cluster\"}[$__rate_interval])\n    )\n) * on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{cluster_name=~\"$cluster\", ceph_daemon=~\"$rgw_servers\"}\n",
     "legendFormat": "Other {{ceph_daemon}}"
    }
   ]
  },
  {
   "title": "Workload Breakdown",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(ceph_rgw_failed_req{cluster_name=~\"$cluster\"}[$__rate_interval]) *\n  on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{cluster_name=~\"$cluster\", ceph_daemon=~\"$rgw_servers\"}\n",
     "legendFormat": "Failures {{ceph_daemon}}"
    },
    {
     "expr": "rate(ceph_rgw_get{cluster_name=~\"$cluster\"}[$__rate_interval]) *\n  on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{cluster_name=~\"$cluster\", ceph_daemon=~\"$rgw_servers\"}\n",
     "legendFormat": "GETs {{ceph_daemon}}"
    },
    {
     "expr": "rate(ceph_rgw_put{cluster_name=~\"$cluster\"}[$__rate_interval]) *\n  on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{cluster_name=~\"$cluster\", ceph_daemon=~\"$rgw_servers\"}\n",
     "legendFormat": "PUTs {{ceph_daemon}}"
    },
    {
     "expr": "(\n  rate(ceph_rgw_req{cluster_name=~\"$cluster\"}[$__rate_interval]) -\n    (\n      rate(ceph_rgw_get{cluster_name=~\"$cluster\"}[$__rate_interval]) +\n        rate(ceph_rgw_put{cluster_name=~\"$cluster\"}[$__rate_interval])\n    )\n) * on (instance_id) group_left (ceph_daemon)\n  ceph_rgw_metadata{cluster_name=~\"$cluster\", ceph_daemon=~\"$rgw_servers\"}\n",
     "legendFormat": "Other (DELETE,LIST) {{ceph_daemon}}"
    }
   ]
  }
 ]
}