{
 "title": "RBD Details",
 "description": "Detailed Performance of RBD Images (IOPS/Throughput/Latency)",
 "tags": [ "ceph-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(ceph_rbd_read_ops,cluster_name)"
    }
   },
   {
    "name": "pool",
    "query": "label_values(ceph_rbd_read_ops{cluster_name=\"$cluster\"},pool)"
   },
   {
    "name": "image",
    "query": {
     "query": "label_values(ceph_rbd_read_ops{cluster_name=\"$cluster\",pool=\"$pool\"},image)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "IOPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "rate(ceph_rbd_write_ops{pool=\"$pool\", image=\"$image\", cluster_name=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{pool}} Write"
    },
    {
     "expr": "rate(ceph_rbd_read_ops{pool=\"$pool\", image=\"$image\", cluster_name=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{pool}} Read"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(ceph_rbd_write_bytes{pool=\"$pool\", image=\"$image\", cluster_name=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{pool}} Write"
    },
    {
     "expr": "rate(ceph_rbd_read_bytes{pool=\"$pool\", image=\"$image\", cluster_name=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{pool}} Read"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(ceph_rbd_write_latency_sum{pool=\"$pool\", image=\"$image\", cluster_name=\"$cluster\"}[$__rate_interval]) /\n  rate(ceph_rbd_write_latency_count{pool=\"$pool\", image=\"$image\", cluster_name=\"$cluster\"}[$__rate_interval])\n",
     "legendFormat": "{{pool}} Write"
    },
    {
     "expr": "rate(ceph_rbd_read_latency_sum{pool=\"$pool\", image=\"$image\", cluster_name=\"$cluster\"}[$__rate_interval]) /\n  rate(ceph_rbd_read_latency_count{pool=\"$pool\", image=\"$image\", cluster_name=\"$cluster\"}[$__rate_interval])\n",
     "legendFormat": "{{pool}} Read"
    }
   ]
  }
 ]
}