{
 "title": "RBD Overview",
 "tags": [
  "ceph-mixin",
  "overview",
  "folder-ceph"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(ceph_rbd_read_ops,cluster_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Highest IOPS",
   "type": "table",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10,\n  (\n    sort((\n      rate(ceph_rbd_write_ops{cluster_name=~\"$cluster\"}[$__rate_interval]) +\n        on (image, pool, namespace) rate(ceph_rbd_read_ops{cluster_name=~\"$cluster\"}[$__rate_interval])\n    ))\n  )\n)\n"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(sum(rate(ceph_rbd_write_ops{cluster_name=~\"$cluster\"}[$__rate_interval])))",
     "legendFormat": "Writes"
    },
    {
     "expr": "round(sum(rate(ceph_rbd_read_ops{cluster_name=~\"$cluster\"}[$__rate_interval])))",
     "legendFormat": "Reads"
    }
   ]
  },
  {
   "title": "Highest Throughput",
   "type": "table",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10,\n  sort(\n    sum(\n      rate(ceph_rbd_read_bytes{cluster_name=~\"$cluster\"}[$__rate_interval]) +\n        rate(ceph_rbd_write_bytes{cluster_name=~\"$cluster\"}[$__rate_interval])\n    ) by (pool, image, namespace)\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "round(sum(rate(ceph_rbd_write_bytes{cluster_name=~\"$cluster\"}[$__rate_interval])))",
     "legendFormat": "Write"
    },
    {
     "expr": "round(sum(rate(ceph_rbd_read_bytes{cluster_name=~\"$cluster\"}[$__rate_interval])))",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Highest Latency",
   "type": "table",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10,\n  sum(\n    rate(ceph_rbd_write_latency_sum{cluster_name=~\"$cluster\"}[$__rate_interval]) /\n      clamp_min(rate(ceph_rbd_write_latency_count{cluster_name=~\"$cluster\"}[$__rate_interval]), 1) +\n      rate(ceph_rbd_read_latency_sum{cluster_name=~\"$cluster\"}[$__rate_interval]) /\n      clamp_min(rate(ceph_rbd_read_latency_count{cluster_name=~\"$cluster\"}[$__rate_interval]), 1)\n  ) by (pool, image, namespace)\n)\n"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "round(\n  sum(rate(ceph_rbd_write_latency_sum{cluster_name=~\"$cluster\"}[$__rate_interval])) /\n    sum(rate(ceph_rbd_write_latency_count{cluster_name=~\"$cluster\"}[$__rate_interval]))\n)\n",
     "legendFormat": "Write"
    },
    {
     "expr": "round(\n  sum(rate(ceph_rbd_read_latency_sum{cluster_name=~\"$cluster\"}[$__rate_interval])) /\n    sum(rate(ceph_rbd_read_latency_count{cluster_name=~\"$cluster\"}[$__rate_interval]))\n)\n",
     "legendFormat": "Read"
    }
   ]
  }
 ]
}