{
 "title": "S3/Object Usage Tenant Overview",
 "description": "Object/S3 usage per tenant",
 "tags": [
  "ceph",
  "overview",
  "s3",
  "ceph-s3",
  "folder-tenant"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(rgw_total_buckets,cluster_name)"
    }
   },
   {
    "name": "tenant",
    "query": {
     "query": "label_values(rgw_bucket_used_b{cluster_name=~\"$cluster\"},tenant)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Bucket Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Bucket Quota Enabled?",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rgw_bucket_quota_enabled{cluster_name=\"$cluster\",tenant=\"$tenant\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "User Quota Enabled?",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rgw_user_quota_is_enabled{cluster_name=\"$cluster\",tenant=\"$tenant\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Object Quota",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rgw_user_bucket_quota_max_objects{cluster_name=\"$cluster\",tenant=\"$tenant\"})",
     "legendFormat": "Object Quota"
    },
    {
     "expr": "sum(rgw_bucket_num_objects{cluster_name=\"$cluster\",tenant=\"$tenant\"})",
     "legendFormat": "Object Usage"
    }
   ]
  },
  {
   "title": "Bucket Quota",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "rgw_user_bucket_quota_max_size_kb{cluster_name=\"$cluster\",tenant=\"$tenant\"}",
     "legendFormat": "User Bucket Quota"
    },
    {
     "expr": "sum(rgw_bucket_used_b{cluster_name=\"$cluster\",tenant=\"$tenant\"})",
     "legendFormat": "Bucket Usage"
    }
   ]
  },
  {
   "title": "Total Buckets",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rgw_bucket_used_b{cluster_name=~\"$cluster\",tenant=\"$tenant\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bucket Shard Percentage",
   "type": "table",
   "description": "The default value for rgw_max_objs_per_shard is 100k objects per shard. \nThis displays the % of shard utilized.",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rgw_bucket_shard_percentage{cluster_name=~\"$cluster\", tenant=\"$tenant\"}"
    }
   ]
  },
  {
   "title": "Total Buckets Size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rgw_bucket_used_b{cluster_name=~\"$cluster\",tenant=\"$tenant\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Buckets by Size Top 20",
   "type": "barchart",
   "description": "Hover for details",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "topk(20, rgw_bucket_used_b{cluster_name=~\"$cluster\",tenant=\"$tenant\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Buckets Growth",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "rgw_bucket_used_b{cluster_name=~\"$cluster\",tenant=\"$tenant\"} > 1",
     "legendFormat": "{{bucket}} - {{cluster_name}}"
    }
   ]
  },
  {
   "title": "Top Object Count Growth",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rgw_bucket_num_objects{cluster_name=~\"$cluster\",tenant=\"$tenant\"} > 1",
     "legendFormat": "{{bucket}} - {{cluster_name}}"
    }
   ]
  },
  { "title": "DataExport", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Bucket Breakdown",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "rgw_bucket_used_b{cluster_name=~\"$cluster\",tenant=\"$tenant\"} > 1"
    }
   ]
  },
  {
   "title": "Object Breakdown",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rgw_bucket_num_objects{cluster_name=~\"$cluster\",tenant=\"$tenant\"}"
    }
   ]
  }
 ]
}