{
 "title": "RGW Bucket Overview",
 "tags": [
  "ceph",
  "overview",
  "s3",
  "ceph-s3",
  "folder-ceph"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(rgw_total_buckets,cluster_name)"
    }
   },
   { "name": "bucket", "query": { "query": "label_values(bucket)" } }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "![App Platorm](https://ceph.io/assets/svgs/logo-ceph-grey.svg)\n# RGW Bucket Overview\n\nOverview of top consumers\n"
   }
  },
  {
   "title": "Total Buckets",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rgw_total_buckets{cluster_name=~\"$cluster\"}",
     "legendFormat": "{{cluster_name}}"
    }
   ]
  },
  {
   "title": "Bucket Objects - TOP 10",
   "type": "table",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, rgw_bucket_num_objects{cluster_name=~\"$cluster\",bucket=~\"$bucket\"})"
    }
   ]
  },
  {
   "title": "Bucket Shard Percentage - TOP 20",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(20, rgw_bucket_shard_percentage{cluster_name=~\"$cluster\",bucket=~\"$bucket\"})"
    }
   ]
  },
  {
   "title": "Buckets Growth > 10G - TOP 10",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "topk(10, sort(rgw_bucket_used_b{cluster_name=~\"$cluster\",bucket=~\"$bucket\"} > 10000000))",
     "legendFormat": "{{bucket}}-{{tenant}}"
    }
   ]
  },
  {
   "title": "Buckets by Size - TOP 10",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, rgw_bucket_used_b{cluster_name=~\"$cluster\",bucket=~\"$bucket\"})"
    }
   ]
  },
  {
   "title": "Top Object Count Growth > 500k - TOP 10",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, rgw_bucket_num_objects{cluster_name=~\"$cluster\",bucket=~\"$bucket\"} > 500000)",
     "legendFormat": "{{bucket}}-{{tenant}}"
    }
   ]
  }
 ]
}