{
 "title": "Cumulus Stats",
 "tags": [
  "network",
  "cumulus",
  "folder-network"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "site",
    "label": "Site",
    "query": {
     "query": "label_values(nvswitch_interface_info,site)"
    }
   },
   {
    "name": "instance",
    "label": "Device",
    "query": {
     "query": "label_values(nvswitch_interface_info{site=\"$site\"},instance)"
    }
   },
   {
    "name": "interface",
    "label": "Interface",
    "query": {
     "query": "label_values(nvswitch_interface_info{instance=\"$instance\"},interface)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Switch Details",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "node_uname_info{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Fabric ports UP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(nvswitch_interface_oper_state{instance=\"$instance\", interface=~\"swp(49|50|51|52)\"} == 1)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Fabric ports DOWN",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(nvswitch_interface_oper_state{instance=\"$instance\", interface=~\"swp(49|50|51|52)\"} == 2)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Customer ports UP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(nvswitch_interface_oper_state{instance=\"$instance\", interface=~\"swp([1-9]|[1-4][0-9]|48)\"} == 1)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Customer ports DOWN",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(nvswitch_interface_oper_state{instance=\"$instance\", interface=~\"swp([1-9]|[1-4][0-9]|48)\"} == 2)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "PSU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nvswitch_platform_environment_psu_state{instance=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "ARP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "ARP Entries",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_arp_entries{instance=\"$instance\"}",
       "legendFormat": "{{ device }} - ARP entries"
      }
     ]
    }
   ]
  },
  {
   "title": "Hardware",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Switch Memory Free",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "node_memory_MemFree_bytes{instance=\"$instance\"}",
       "legendFormat": "Memory Free"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg(sum by (cpu) (irate(node_cpu_seconds_total{instance=\"$instance\",mode!='idle'}[1m])))",
       "legendFormat": "CPU (Average)"
      },
      {
       "expr": "sum by (cpu) (irate(node_cpu_seconds_total{instance=\"$instance\",mode!='idle'}[1m]))",
       "legendFormat": "CPU {{cpu}}"
      }
     ]
    },
    {
     "title": "Temperature",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "nvswitch_platform_environment_temp_current{instance=\"$instance\"}",
       "legendFormat": "{{description}}"
      }
     ]
    },
    {
     "title": "Fan Speed",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "rotrpm" } },
     "targets": [
      {
       "expr": "nvswitch_platform_environment_fan_cur_speed{instance=\"$instance\"}",
       "legendFormat": "{{description}}"
      }
     ]
    },
    {
     "title": "PSU Voltage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "expr": "nvswitch_platform_environment_psu_voltage{instance=\"$instance\"}",
       "legendFormat": "{{description}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Ports - $interface",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "repeat": "interface",
   "collapsed": true,
   "panels": [
    {
     "title": "Oper Status",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "nvswitch_interface_oper_state{instance=\"$instance\", interface=\"$interface\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Port Transitions",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 5, "x": 3, "y": 8 },
     "targets": [
      {
       "expr": "sum by (instance, interface) (\n  increase(nvswitch_interface_carrier_changes_total{instance=\"$instance\", interface=\"$interface\"}[$__rate_interval]) > 0\n) * on(instance, interface) group_left(ifalias) nvswitch_interface_info",
       "legendFormat": "{{instance}} - {{interface}} - {{ifalias}}"
      }
     ]
    },
    {
     "title": "Interface bit/s",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "nvswitch_interface_in_bits_rate{instance=\"$instance\", interface=\"$interface\"}",
       "legendFormat": "In"
      },
      {
       "expr": "nvswitch_interface_out_bits_rate{instance=\"$instance\", interface=\"$interface\"}",
       "legendFormat": "Out"
      }
     ]
    },
    {
     "title": "Interface % Util",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "nvswitch_interface_in_link_util_percentage{instance=\"$instance\", interface=\"$interface\"}",
       "legendFormat": "In"
      },
      {
       "expr": "nvswitch_interface_out_link_util_percentage{instance=\"$instance\", interface=\"$interface\"}",
       "legendFormat": "Out"
      }
     ]
    },
    {
     "title": "Port Speed",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "nvswitch_interface_oper_aggregate_speed{interface=\"$interface\", instance=\"$instance\"}",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Interface RX Dropped",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(node_network_receive_drop_total{instance=\"$instance\", device=~\"$interface\"}[1m])",
       "legendFormat": "{{ device }} RX Drop"
      }
     ]
    },
    {
     "title": "Interface TX Dropped",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(node_network_transmit_drop_total{instance=\"$instance\", device=~\"$interface\"}[1m])",
       "legendFormat": "{{ device }} RX Drop"
      }
     ]
    },
    {
     "title": "Interface RX Errors",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(node_network_receive_errs_total{instance=\"$instance\", device=~\"$interface\"}[1m])",
       "legendFormat": "{{ device }} RX Drop"
      }
     ]
    },
    {
     "title": "Interface TX Errors",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(node_network_transmit_errs_total{instance=\"$instance\", device=~\"$interface\"}[1m])",
       "legendFormat": "{{ device }} RX Drop"
      }
     ]
    }
   ]
  }
 ]
}