{
 "title": "Cumulus - Flapping ports",
 "tags": [
  "network",
  "cumulus",
  "folder-network"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "site",
    "label": "site",
    "query": {
     "query": "label_values(nvswitch_interface_carrier_changes_total,site)"
    }
   },
   {
    "name": "rack",
    "label": "rack",
    "query": {
     "query": "label_values(nvswitch_interface_carrier_changes_total{site=\"$site\"},rack)"
    }
   },
   {
    "name": "switch",
    "label": "switch",
    "query": {
     "query": "label_values(nvswitch_interface_carrier_changes_total{site=\"$site\",rack=~\"$rack\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Port Transitions - Interval Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (instance, interface) (\n  increase(nvswitch_interface_carrier_changes_total{site=\"$site\", rack=~\"$rack\", instance=~\"$switch\"}[$__rate_interval]) > 0\n) * on(instance, interface) group_left(ifalias) nvswitch_interface_info",
     "legendFormat": "{{instance}} - {{interface}} - {{ifalias}}"
    }
   ]
  },
  {
   "title": "Port Transitions - Per 15 minutes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (instance, interface) (\n  increase(nvswitch_interface_carrier_changes_total{site=\"$site\", rack=~\"$rack\", instance=~\"$switch\"}[15m]) > 0\n) * on(instance, interface) group_left(ifalias) nvswitch_interface_info",
     "legendFormat": "{{instance}} - {{interface}} - {{ifalias}}"
    }
   ]
  },
  {
   "title": "Port Transitions - Per 60 minutes",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by (instance, interface) (\n  increase(nvswitch_interface_carrier_changes_total{site=\"$site\", rack=~\"$rack\", instance=~\"$switch\"}[60m]) > 0\n) * on(instance, interface) group_left(ifalias) nvswitch_interface_info",
     "legendFormat": "{{instance}} - {{interface}} - {{ifalias}}"
    }
   ]
  }
 ]
}