{
 "title": "dnsdist dashboard",
 "description": "Prometheus Powerdns exporter metrics.",
 "tags": [
  "prometheus",
  "dnsdist"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(dnsdist_uptime, instance)"
   },
   {
    "name": "address",
    "label": "address",
    "query": "label_values(dnsdist_server_drops,address)"
   },
   {
    "name": "Site1DNSHost",
    "query": "label_values(node_uname_info, nodename)"
   },
   {
    "name": "Site1ActiveDNS",
    "query": "label_values(node_uname_info, job)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dnsdist_uptime{instance=~\"$instance\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{os_region}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "UDP queries last 5m",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(dnsdist_frontend_queries{instance=~\"$instance\",proto=\"UDP\"}[5m])*300",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {}
   ]
  },
  {
   "title": "Active downstreams",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(dnsdist_pool_active_servers{instance=~\"$instance\", job=\"dnsdist\", pool=~\".*\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "VIP CPU Load (5m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load5{job=~\"(?i:(${Site1ActiveDNS:pipe}).*)\"}) /  count(count(node_cpu_seconds_total{job=~\"(?i:(${Site1ActiveDNS:pipe}).*)\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "# of queries not answered",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(rate(dnsdist_server_drops{address=~\"$address\"}[5m]) * 100) ",
     "legendFormat": "{{ address }}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "dnsdist_server_latency{address=~\"$address\"}",
     "legendFormat": "{{ address }}"
    }
   ]
  },
  {
   "title": "Send Errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "dnsdist_downstream_send_errors{instance=~\"$instance\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Timeouts last 5m",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "round(rate(dnsdist_downstream_timeouts{instance=~\"$instance\"}[5m])*300)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TCP queries last 5m",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(dnsdist_frontend_queries{instance=~\"$instance\",proto=\"TCP\"}[5m])*300",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "VIP Used FS",
   "type": "gauge",
   "description": "Active VIP Used Root FS",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"$instance\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=~\"$instance\",mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "VIP Used RAM",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=~\"$instance\"} * 100) / node_memory_MemTotal_bytes{instance=~\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of responses received from backends",
   "type": "timeseries",
   "description": "Number of responses received from backends",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(dnsdist_responses{instance=~\"$instance\"}[5m])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Number of queries answered",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (rate(dnsdist_latency0_1{instance=~\"$instance\"}[5m]))",
     "legendFormat": "0-1 ms"
    },
    {
     "expr": "sum (rate(dnsdist_latency1_10{instance=~\"$instance\"}[5m]))",
     "legendFormat": "1-10 ms"
    },
    {
     "expr": "sum (rate(dnsdist_latency10_100{instance=~\"$instance\"}[5m]))",
     "legendFormat": "10-100 ms"
    },
    {
     "expr": "sum (rate(dnsdist_latency100_1000{instance=~\"$instance\"}[5m]))",
     "legendFormat": "100-1000 ms"
    },
    {
     "expr": "sum (rate(dnsdist_latency_slow{instance=~\"$instance\"}[5m]))",
     "legendFormat": "slow"
    }
   ]
  },
  {
   "title": "Cache hits 5m",
   "type": "timeseries",
   "description": "Number of times an answer was retrieved from cache",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(dnsdist_cache_hits{instance=~\"$instance\"}[5m])*60",
     "legendFormat": "Cache hits"
    }
   ]
  },
  {
   "title": "Cache misses",
   "type": "timeseries",
   "description": "Number of times an answer not found in the cache",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(dnsdist_cache_misses{instance=~\"$instance\"}[5m])*60",
     "legendFormat": "Cache misses"
    }
   ]
  },
  {
   "title": "response latency of the last 1K packets",
   "type": "timeseries",
   "description": "response latency of the last 1K packets",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "dnsdist_latency_avg1000{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Memory Usage $instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(dnsdist_real_memory_usage{instance=~\"$instance\"}[5m]))",
     "legendFormat": "{$instance}"
    }
   ]
  },
  {
   "title": "CPU msec $instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(dnsdist_cpu_sys_msec{instance=~\"$instance\"}[5m]))",
     "legendFormat": "System mode"
    },
    {
     "expr": "sum(rate(dnsdist_cpu_user_msec{instance=~\"$instance\"}[5m]))",
     "legendFormat": "User mode"
    }
   ]
  },
  {
   "title": "Filesystem space available",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{instance=~\"$instance\",device!~'rootfs'}",
     "legendFormat": "{{job}} {{mountpoint}} - Available"
    }
   ]
  },
  {
   "title": "Used memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((label_replace(node_memory_MemAvailable_bytes{instance=~\"$instance\"}, \"instance\", \"$1\", \"instance\", \"^([^.]+).*\") * 100) / label_replace(node_memory_MemTotal_bytes{instance=~\"$instance\"}, \"instance\", \"$1\", \"instance\", \"^([^.]+).*\"))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU System load 5m",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(node_load5{instance=~\"$instance\"}, \"instance\", \"$1\", \"instance\", \"^([^.]+).*\") / count(label_replace(node_cpu_seconds_total{instance=~\"$instance\",mode=\"system\"},\"instance\", \"$1\", \"instance\", \"^([^.]+).*\")) WITHOUT (cpu, mode)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Outgoing Network Traffic",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "label_replace(rate(node_network_transmit_bytes_total{instance=~\"$instance\",device!=\"lo\"}[5m]), \"instance\", \"$1\", \"instance\", \"^([^.]+).*\")",
     "legendFormat": "{{ instance  }} Tx"
    }
   ]
  },
  {
   "title": "Incoming Network Traffic",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "label_replace(rate(node_network_receive_bytes_total{instance=~\"$instance\",device!=\"lo\"}[5m]), \"instance\", \"$1\", \"instance\", \"^([^.]+).*\")",
     "legendFormat": "{{ instance  }} Rx"
    }
   ]
  }
 ]
}