{
 "title": "HPE Storage Volume Details",
 "description": "Provides a drill-down overview of a volume.",
 "tags": [ "HPE Storage Volume Details" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "array", "label": "Array", "query": { "query": "label_values(array)" } },
   { "name": "pool", "label": "Pool", "query": "default" },
   {
    "name": "volume_name",
    "label": "volume_name",
    "query": {
     "query": "label_values(hpe_volume_size_bytes{array=\"$array\"},volume_name)"
    }
   },
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Volume Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Volume Capacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "hpe_volume_size_bytes{array=\"$array\", volume_name=~\"$volume_name\",storagepool=\"$pool\"}",
     "legendFormat": "Size"
    },
    {
     "expr": "hpe_volume_used_bytes{array=\"$array\", volume_name=~\"$volume_name\",storagepool=\"$pool\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "hpe_volume_snapshot_used_bytes{array=\"$array\", volume_name=~\"$volume_name\",storagepool=\"$pool\"}",
     "legendFormat": "Snapshot Used"
    }
   ]
  },
  {
   "title": "Max Read Throughput (5m avg)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "hpe_volume_read_bytes_per_second_avg5m{array=\"$array\", volume_name=~\"$volume_name\",storagepool=\"$pool\"}",
     "legendFormat": "Max Read Throughput"
    }
   ]
  },
  {
   "title": "Max Write Throughput (5m avg)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "hpe_volume_write_bytes_per_second_avg5m{array=\"$array\",volume_name=~\"$volume_name\",storagepool=\"$pool\"}",
     "legendFormat": "Max Write Throughput"
    }
   ]
  },
  {
   "title": "Volume Read Performance (5m avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hpe_volume_reads_per_second_avg5m{array=\"$array\",volume_name=~\"$volume_name\",storagepool=\"$pool\"}",
     "legendFormat": "IOPS"
    },
    {
     "expr": "hpe_volume_seconds_per_read_avg5m{array=\"$array\", volume_name=~\"$volume_name\",storagepool=\"$pool\"}",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Volume Write Performance (5m avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg_over_time(avg(hpe_volume_writes_per_second_avg5m{array=~\"$array\",volume_name=\"$volume_name\",storagepool=\"$pool\"})[$__range])",
     "legendFormat": "IOPS"
    },
    {
     "expr": "hpe_volume_seconds_per_write_avg5m{array=~\"$array\",volume_name=\"$volume_name\",storagepool=\"$pool\"}",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Volume Latency Heatmap (5m avg)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "hpe_volume_seconds_per_write_avg5m{array=~\"$array\", volume_name=~\"$volume_name\",storagepool=\"$pool\"}",
     "legendFormat": "Write"
    },
    {
     "expr": "hpe_volume_seconds_per_read_avg5m{array=~\"$array\", volume_name=~\"$volume_name\",storagepool=\"$pool\"}",
     "legendFormat": "Read"
    }
   ]
  }
 ]
}