{
 "title": "HPE Storage Array - Overview",
 "description": "HPE Storage arrays overview",
 "tags": [ "HPE Storage Volume Details" ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "region",
    "label": "Region",
    "query": {
     "query": "label_values(hpe_storagepool_available_bytes,os_region)"
    }
   },
   {
    "name": "array",
    "label": "Array",
    "query": {
     "query": "label_values(hpe_storagepool_available_bytes{os_region=~\"$region\"},array)"
    }
   },
   { "name": "TopItems", "label": "Top Items", "query": "1,2,3,4,5,6,7,8,10,15,25" },
   { "name": "pool", "label": "Pool", "query": "default" },
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Sum of Space Utilization by $array array(s)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(hpe_storagepool_volume_used_bytes{array=~\"$array\"}) - sum(hpe_storagepool_data_reduction_bytes{array=~\"$array\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(hpe_storagepool_capacity_bytes{array=~\"$array\"})",
     "legendFormat": "Capacity"
    },
    {
     "expr": "sum(hpe_storagepool_unused_reserve_bytes{array=~\"$array\"})",
     "legendFormat": "Unused Reserved"
    },
    {
     "expr": "sum(hpe_storagepool_snapshot_used_bytes{array=~\"$array\"})",
     "legendFormat": "Snapshot"
    },
    {
     "expr": "sum(hpe_storagepool_data_reduction_bytes{array=~\"$array\"})",
     "legendFormat": "Reduction"
    }
   ]
  },
  {
   "title": "Firmware version info",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 9, "y": 0 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "os/nimble" },
     "host": { "filter": "$array" },
     "item": { "filter": "/Firmware version/" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "os/nimble" },
     "host": { "filter": "$array" },
     "item": { "filter": "/Nimble model/" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Volume Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(hpe_volume_size_bytes{array=~\"$array\"})"
    }
   ]
  },
  {
   "title": "Volumes IOPS (total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(hpe_volume_reads_per_second_avg5m{array=~\"$array\"})",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(hpe_volume_writes_per_second_avg5m{array=~\"$array\"})",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Avg. Read Latency (5min avg)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(hpe_volume_seconds_per_read_avg5m{array=~\"$array\"})"
    }
   ]
  },
  {
   "title": "Avg. Write Latency (5min avg)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(hpe_volume_seconds_per_write_avg5m{array=~\"$array\"})"
    }
   ]
  },
  {
   "title": "Array Latency Heat Map (5min avg)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "hpe_volume_seconds_per_write_avg5m{array=~\"$array\"}"
    },
    {
     "expr": "hpe_volume_seconds_per_read_avg5m{array=\"$array\"}"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Top $TopItems Read Throughput (5m avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "avg(hpe_volume_read_bytes_per_second_avg5m{array=~\"$array\",storagepool=\"$pool\"}[$__range]) by (array,volume_name) + topk($TopItems, avg(avg_over_time(hpe_volume_read_bytes_per_second_avg5m{array=~\"$array\",storagepool=\"$pool\"}[$__range] @ end())) by (array,volume_name)) != 0",
     "legendFormat": "{{volume_name}}"
    }
   ]
  },
  {
   "title": "Top $TopItems Write Throughput (5m avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk($TopItems, avg(avg_over_time(hpe_volume_write_bytes_per_second_avg5m{array=~\"$array\", storagepool=\"$pool\"}[$__range] @ end())) by (array,volume_name))",
     "legendFormat": "{{volume_name}}"
    }
   ]
  },
  {
   "title": "Top $TopItems Volume Read IOPs Performance (5m avg)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "topk($TopItems, avg(avg_over_time(hpe_volume_reads_per_second_avg5m\n{array=~\"$array\",storagepool=\"$pool\"}[$__range] @ end())) by (array,volume_name)) != 0",
     "legendFormat": "{{volume_name}}"
    }
   ]
  },
  {
   "title": "Top $TopItems Volume IOPs Write Performance (5m avg)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk($TopItems, avg(avg_over_time(hpe_volume_writes_per_second_avg5m{array=~\"$array\",storagepool=\"$pool\"}[$__range] @ end())) by (array,volume_name))",
     "legendFormat": "{{volume_name}}"
    }
   ]
  },
  {
   "title": "Top $TopItems Volume Read Latency (5m avg)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk($TopItems, avg(avg_over_time(hpe_volume_seconds_per_read_avg5m\n{array=~\"$array\",storagepool=\"$pool\"} [$__range] @ end())) by (array,volume_name))\n",
     "legendFormat": "{{volume_name}}"
    }
   ]
  },
  {
   "title": "Top $TopItems Volume Write Latency (5m avg)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk($TopItems, avg(avg_over_time(hpe_volume_seconds_per_write_avg5m{array=~\"$array\",storagepool=\"$pool\"}[$__range] @ end())) by (array,volume_name))",
     "legendFormat": "{{volume_name}}"
    }
   ]
  },
  { "title": "Capacity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Pool Capacities (total)",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(hpe_storagepool_volume_used_bytes{array=~\"$array\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(hpe_storagepool_capacity_bytes{array=~\"$array\"})",
     "legendFormat": "Capacity"
    },
    {
     "expr": "sum(hpe_storagepool_unused_reserve_bytes{array=~\"$array\"})",
     "legendFormat": "Unused Reserved"
    },
    {
     "expr": "sum(hpe_storagepool_snapshot_used_bytes{array=~\"$array\"})",
     "legendFormat": "Snapshot"
    },
    {
     "expr": "sum(hpe_storagepool_data_reduction_bytes{array=~\"$array\"})",
     "legendFormat": "Reduction"
    }
   ]
  },
  {
   "title": "Top $TopItems by Volume Capacity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk($TopItems, avg(hpe_volume_size_bytes{array=~\"$array\",storagepool=\"$pool\"}) by (array,volume_name))",
     "legendFormat": "{{volume_name}}"
    }
   ]
  },
  {
   "title": "Top $TopItems by Volume Used",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk($TopItems, avg(hpe_volume_used_bytes{array=~\"$array\",storagepool=\"$pool\"}) by (array,volume_name))",
     "legendFormat": "{{volume_name}}"
    }
   ]
  },
  {
   "title": "Top $TopItems by Volume by Snapshot Used",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 23, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk($TopItems, avg(avg_over_time(hpe_volume_snapshot_used_bytes{array=~\"$array\",storagepool=\"$pool\"}[$__range] @ end())) by (array,volume_name))",
     "legendFormat": "{{volume_name}}"
    }
   ]
  }
 ]
}