{
 "title": "Nimble Capacity Dashboard",
 "description": "HPE Storage arrays overview",
 "tags": [ "HPE Storage Volume Details" ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "region",
    "label": "Region",
    "query": {
     "query": "label_values(hpe_storagepool_available_bytes,os_region)"
    }
   },
   {
    "name": "array",
    "label": "Array",
    "query": {
     "query": "label_values(hpe_storagepool_available_bytes{os_region=~\"$region\"},array)"
    }
   },
   { "name": "TopItems", "label": "Top Items", "query": "1,2,3,4,5,6,7,8,10,15,25" },
   { "name": "pool", "label": "Pool", "query": "default" },
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Capacity Dashboard", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 }, "options": { "content": "# HPE Nimble Storage Array\n\n" } },
  {
   "title": "Total Capacity - All Regions",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(hpe_storagepool_capacity_bytes{os_region=\"us-dfw\"}) + sum(hpe_storagepool_capacity_bytes{os_region=\"gb-lon\"}) + sum(hpe_storagepool_capacity_bytes{os_region=\"de-fra\"})",
     "legendFormat": "Total Capacity"
    },
    {
     "expr": "sum(sum(hpe_storagepool_volume_used_bytes{os_region=\"gb-lon\"}) - sum(hpe_storagepool_data_reduction_bytes{os_region=\"gb-lon\"}) + sum(hpe_storagepool_snapshot_used_bytes{os_region=\"gb-lon\"}))\n+\nsum(sum(hpe_storagepool_volume_used_bytes{os_region=\"de-fra\"}) - sum(hpe_storagepool_data_reduction_bytes{os_region=\"de-fra\"}) + sum(hpe_storagepool_snapshot_used_bytes{os_region=\"de-fra\"}))\n+\nsum(sum(hpe_storagepool_volume_used_bytes{os_region=\"us-dfw\"}) - sum(hpe_storagepool_data_reduction_bytes{os_region=\"us-dfw\"}) + sum(hpe_storagepool_snapshot_used_bytes{os_region=\"us-dfw\"}))",
     "legendFormat": "Total Used"
    },
    {
     "expr": "(sum(hpe_storagepool_volume_used_bytes{array=\"us4-sn-001\"}) - sum(hpe_storagepool_data_reduction_bytes{array=\"us4-sn-001\"}) + sum(hpe_storagepool_snapshot_used_bytes{array=\"us4-sn-001\"})) +\n(sum(hpe_storagepool_volume_used_bytes{array=\"us4-sn-002\"}) - sum(hpe_storagepool_data_reduction_bytes{array=\"us4-sn-002\"}) + sum(hpe_storagepool_snapshot_used_bytes{array=\"us4-sn-002\"})) +\n(sum(hpe_storagepool_volume_used_bytes{array=\"us4-sn-003\"}) - sum(hpe_storagepool_data_reduction_bytes{array=\"us4-sn-003\"}) + sum(hpe_storagepool_snapshot_used_bytes{array=\"us4-sn-003\"}))",
     "legendFormat": "US-DFW Usage"
    },
    {
     "expr": "(sum(hpe_storagepool_volume_used_bytes{array=\"gb4-sn-005\"}) - sum(hpe_storagepool_data_reduction_bytes{array=\"gb4-sn-005\"}) + sum(hpe_storagepool_snapshot_used_bytes{array=\"gb4-sn-005\"})) +\n(sum(hpe_storagepool_volume_used_bytes{array=\"gb4-sn-006\"}) - sum(hpe_storagepool_data_reduction_bytes{array=\"gb4-sn-006\"}) + sum(hpe_storagepool_snapshot_used_bytes{array=\"gb4-sn-006\"})) +\n(sum(hpe_storagepool_volume_used_bytes{array=\"gb4-sn-007\"}) - sum(hpe_storagepool_data_reduction_bytes{array=\"gb4-sn-007\"}) + sum(hpe_storagepool_snapshot_used_bytes{array=\"gb4-sn-007\"}))",
     "legendFormat": "GB-LON Usage"
    },
    {
     "expr": "(sum(hpe_storagepool_volume_used_bytes{array=\"de1-sn-001\"}) - sum(hpe_storagepool_data_reduction_bytes{array=\"de1-sn-001\"}) + sum(hpe_storagepool_snapshot_used_bytes{array=\"de1-sn-001\"})) +\n(sum(hpe_storagepool_volume_used_bytes{array=\"de1-sn-002\"}) - sum(hpe_storagepool_data_reduction_bytes{array=\"de1-sn-002\"}) + sum(hpe_storagepool_snapshot_used_bytes{array=\"de1-sn-002\"})) +\n(sum(hpe_storagepool_volume_used_bytes{array=\"de1-sn-003\"}) - sum(hpe_storagepool_data_reduction_bytes{array=\"de1-sn-003\"}) + sum(hpe_storagepool_snapshot_used_bytes{array=\"de1-sn-003\"}))",
     "legendFormat": "DE-FRA Usage"
    }
   ]
  },
  {
   "title": "Volume Count over time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 3 },
   "targets": [
    {
     "expr": "count(hpe_volume_size_bytes{array=~\"us4-sn-001\"}) + count(hpe_volume_size_bytes{array=~\"us4-sn-002\"}) + count(hpe_volume_size_bytes{array=~\"us4-sn-003\"})",
     "legendFormat": "us-dfw"
    },
    {
     "expr": "count(hpe_volume_size_bytes{array=~\"de1-sn-001\"}) + count(hpe_volume_size_bytes{array=~\"de1-sn-002\"}) + count(hpe_volume_size_bytes{array=~\"de1-sn-003\"})",
     "legendFormat": "de-fra"
    },
    {
     "expr": "count(hpe_volume_size_bytes{array=~\"gb4-sn-005\"}) + count(hpe_volume_size_bytes{array=~\"gb4-sn-006\"}) + count(hpe_volume_size_bytes{array=~\"gb4-sn-007\"})",
     "legendFormat": "gb-lon"
    }
   ]
  },
  {
   "title": "All Regions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 11, "x": 13, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A + $B + $C", "type": "math" }
   ]
  },
  { "title": "GB-LON", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Usage Total gb-lon",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "(sum(hpe_storagepool_volume_used_bytes{array=\"gb4-sn-005\"}) - sum(hpe_storagepool_data_reduction_bytes{array=\"gb4-sn-005\"}) + sum(hpe_storagepool_snapshot_used_bytes{array=\"gb4-sn-005\"})) +\n(sum(hpe_storagepool_volume_used_bytes{array=\"gb4-sn-006\"}) - sum(hpe_storagepool_data_reduction_bytes{array=\"gb4-sn-006\"}) + sum(hpe_storagepool_snapshot_used_bytes{array=\"gb4-sn-006\"})) +\n(sum(hpe_storagepool_volume_used_bytes{array=\"gb4-sn-007\"}) - sum(hpe_storagepool_data_reduction_bytes{array=\"gb4-sn-007\"}) + sum(hpe_storagepool_snapshot_used_bytes{array=\"gb4-sn-007\"}))",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Usage - Cluster Breakdown - gb-lon",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(hpe_storagepool_volume_used_bytes{array=\"gb4-sn-005\"}) - sum(hpe_storagepool_data_reduction_bytes{array=\"gb4-sn-005\"}) + sum(hpe_storagepool_snapshot_used_bytes{array=\"gb4-sn-005\"})",
     "legendFormat": "gb4-sn-005"
    },
    {
     "expr": "sum(hpe_storagepool_volume_used_bytes{array=\"gb4-sn-006\"}) - sum(hpe_storagepool_data_reduction_bytes{array=\"gb4-sn-006\"}) + sum(hpe_storagepool_snapshot_used_bytes{array=\"gb4-sn-006\"})",
     "legendFormat": "gb4-sn-006"
    },
    {
     "expr": "sum(hpe_storagepool_volume_used_bytes{array=\"gb4-sn-007\"}) - sum(hpe_storagepool_data_reduction_bytes{array=\"gb4-sn-007\"}) + sum(hpe_storagepool_snapshot_used_bytes{array=\"gb4-sn-007\"})",
     "legendFormat": "gb4-sn-007"
    }
   ]
  },
  {
   "title": "Pool Capacity gb-lon",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hpe_storagepool_capacity_bytes{os_region=\"gb-lon\"})",
     "legendFormat": "Capacity"
    },
    {
     "expr": "(sum(hpe_storagepool_volume_used_bytes{array=\"gb4-sn-005\"}) - sum(hpe_storagepool_data_reduction_bytes{array=\"gb4-sn-005\"}) + sum(hpe_storagepool_snapshot_used_bytes{array=\"gb4-sn-005\"})) +\n(sum(hpe_storagepool_volume_used_bytes{array=\"gb4-sn-006\"}) - sum(hpe_storagepool_data_reduction_bytes{array=\"gb4-sn-006\"}) + sum(hpe_storagepool_snapshot_used_bytes{array=\"gb4-sn-006\"})) +\n(sum(hpe_storagepool_volume_used_bytes{array=\"gb4-sn-007\"}) - sum(hpe_storagepool_data_reduction_bytes{array=\"gb4-sn-007\"}) + sum(hpe_storagepool_snapshot_used_bytes{array=\"gb4-sn-007\"}))",
     "legendFormat": "Used"
    },
    { "expression": "($A*100)/$B", "type": "math" }
   ]
  },
  {
   "title": "Array Capacity gb4-sn-005",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hpe_storagepool_capacity_bytes{array=\"gb4-sn-005\"})",
     "legendFormat": "Capacity"
    },
    {
     "expr": "sum(hpe_storagepool_volume_used_bytes{array=\"gb4-sn-005\"}) - sum(hpe_storagepool_data_reduction_bytes{array=\"gb4-sn-005\"}) + sum(hpe_storagepool_snapshot_used_bytes{array=\"gb4-sn-005\"})",
     "legendFormat": "Used"
    },
    { "expression": "($A*100)/$B", "type": "math" },
    {
     "expr": "sum(hpe_storagepool_unused_reserve_bytes{array=\"gb4-sn-005\"})",
     "legendFormat": "Unused Reserved"
    },
    {
     "expr": "sum(hpe_storagepool_snapshot_used_bytes{array=\"gb4-sn-005\"})",
     "legendFormat": "Snapshot"
    },
    {
     "expr": "sum(hpe_storagepool_data_reduction_bytes{array=\"gb4-sn-005\"})",
     "legendFormat": "Reduction"
    }
   ]
  },
  {
   "title": "Array Capacity gb4-sn-006",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hpe_storagepool_capacity_bytes{array=\"gb4-sn-006\"})",
     "legendFormat": "Capacity"
    },
    {
     "expr": "sum(hpe_storagepool_volume_used_bytes{array=\"gb4-sn-006\"}) - sum(hpe_storagepool_data_reduction_bytes{array=\"gb4-sn-006\"}) + sum(hpe_storagepool_snapshot_used_bytes{array=\"gb4-sn-006\"})",
     "legendFormat": "Used"
    },
    { "expression": "($A*100)/$B", "type": "math" },
    {
     "expr": "sum(hpe_storagepool_unused_reserve_bytes{array=\"gb4-sn-006\"})",
     "legendFormat": "Unused Reserved"
    },
    {
     "expr": "sum(hpe_storagepool_snapshot_used_bytes{array=\"gb4-sn-006\"})",
     "legendFormat": "Snapshot"
    },
    {
     "expr": "sum(hpe_storagepool_data_reduction_bytes{array=\"gb4-sn-006\"})",
     "legendFormat": "Reduction"
    }
   ]
  },
  {
   "title": "Array Capacity gb4-sn-007",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hpe_storagepool_capacity_bytes{array=\"gb4-sn-007\"})",
     "legendFormat": "Capacity"
    },
    {
     "expr": "sum(hpe_storagepool_volume_used_bytes{array=\"gb4-sn-007\"}) - sum(hpe_storagepool_data_reduction_bytes{array=\"gb4-sn-007\"}) + sum(hpe_storagepool_snapshot_used_bytes{array=\"gb4-sn-007\"})",
     "legendFormat": "Used"
    },
    { "expression": "($A*100)/$B", "type": "math" },
    {
     "expr": "sum(hpe_storagepool_unused_reserve_bytes{array=\"gb4-sn-007\"})",
     "legendFormat": "Unused Reserved"
    },
    {
     "expr": "sum(hpe_storagepool_snapshot_used_bytes{array=\"gb4-sn-007\"})",
     "legendFormat": "Snapshot"
    },
    {
     "expr": "sum(hpe_storagepool_data_reduction_bytes{array=\"gb4-sn-007\"})",
     "legendFormat": "Reduction"
    }
   ]
  },
  {
   "title": "Total Volume Count gb-lon",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(hpe_volume_size_bytes{array=~\"gb4-sn-005\"}) + count(hpe_volume_size_bytes{array=~\"gb4-sn-006\"}) + count(hpe_volume_size_bytes{array=~\"gb4-sn-007\"})",
     "legendFormat": "Total Volumes"
    }
   ]
  },
  {
   "title": "Volume Count gb4-sn-005",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(hpe_volume_size_bytes{array=~\"gb4-sn-005\"})",
     "legendFormat": "Total Volumes"
    }
   ]
  },
  {
   "title": "Volume Count gb4-sn-006",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(hpe_volume_size_bytes{array=~\"gb4-sn-006\"})",
     "legendFormat": "Total Volumes"
    }
   ]
  },
  {
   "title": "Volume Count gb4-sn-007",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(hpe_volume_size_bytes{array=~\"gb4-sn-007\"})",
     "legendFormat": "Total Volumes"
    }
   ]
  },
  {
   "title": "US-DFW",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Usage Total us-dfw",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 11, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "(sum(hpe_storagepool_volume_used_bytes{array=\"us4-sn-001\"}) - sum(hpe_storagepool_data_reduction_bytes{array=\"us4-sn-001\"}) + sum(hpe_storagepool_snapshot_used_bytes{array=\"us4-sn-001\"})) +\n(sum(hpe_storagepool_volume_used_bytes{array=\"us4-sn-002\"}) - sum(hpe_storagepool_data_reduction_bytes{array=\"us4-sn-002\"}) + sum(hpe_storagepool_snapshot_used_bytes{array=\"us4-sn-002\"})) +\n(sum(hpe_storagepool_volume_used_bytes{array=\"us4-sn-003\"}) - sum(hpe_storagepool_data_reduction_bytes{array=\"us4-sn-003\"}) + sum(hpe_storagepool_snapshot_used_bytes{array=\"us4-sn-003\"}))",
       "legendFormat": "Usage"
      }
     ]
    },
    {
     "title": "Usage - Cluster Breakdown - us-dfw",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 13, "x": 11, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(hpe_storagepool_volume_used_bytes{array=\"us4-sn-001\"}) - sum(hpe_storagepool_data_reduction_bytes{array=\"us4-sn-001\"}) + sum(hpe_storagepool_snapshot_used_bytes{array=\"us4-sn-001\"})",
       "legendFormat": "us4-sn-001"
      },
      {
       "expr": "sum(hpe_storagepool_volume_used_bytes{array=\"us4-sn-002\"}) - sum(hpe_storagepool_data_reduction_bytes{array=\"us4-sn-002\"}) + sum(hpe_storagepool_snapshot_used_bytes{array=\"us4-sn-002\"})",
       "legendFormat": "us4-sn-002"
      },
      {
       "expr": "sum(hpe_storagepool_volume_used_bytes{array=\"us4-sn-003\"}) - sum(hpe_storagepool_data_reduction_bytes{array=\"us4-sn-003\"}) + sum(hpe_storagepool_snapshot_used_bytes{array=\"us4-sn-003\"})",
       "legendFormat": "us4-sn-003"
      }
     ]
    },
    {
     "title": "Pool Capacity us-dfw",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(hpe_storagepool_capacity_bytes{os_region=\"us-dfw\"})",
       "legendFormat": "Capacity"
      },
      {
       "expr": "(sum(hpe_storagepool_volume_used_bytes{array=\"us4-sn-001\"}) - sum(hpe_storagepool_data_reduction_bytes{array=\"us4-sn-001\"}) + sum(hpe_storagepool_snapshot_used_bytes{array=\"us4-sn-001\"})) +\n(sum(hpe_storagepool_volume_used_bytes{array=\"us4-sn-002\"}) - sum(hpe_storagepool_data_reduction_bytes{array=\"us4-sn-002\"}) + sum(hpe_storagepool_snapshot_used_bytes{array=\"us4-sn-002\"})) +\n(sum(hpe_storagepool_volume_used_bytes{array=\"us4-sn-003\"}) - sum(hpe_storagepool_data_reduction_bytes{array=\"us4-sn-003\"}) + sum(hpe_storagepool_snapshot_used_bytes{array=\"us4-sn-003\"}))",
       "legendFormat": "Used"
      },
      { "expression": "($A*100)/$B", "type": "math" }
     ]
    },
    {
     "title": "Array Capacity us4-sn-001",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(hpe_storagepool_capacity_bytes{array=\"us4-sn-001\"})",
       "legendFormat": "Capacity"
      },
      {
       "expr": "sum(hpe_storagepool_volume_used_bytes{array=\"us4-sn-001\"}) - sum(hpe_storagepool_data_reduction_bytes{array=\"us4-sn-001\"}) + sum(hpe_storagepool_snapshot_used_bytes{array=\"us4-sn-001\"})",
       "legendFormat": "Used"
      },
      { "expression": "($A*100)/$B", "type": "math" },
      {
       "expr": "sum(hpe_storagepool_unused_reserve_bytes{array=\"us4-sn-001\"})",
       "legendFormat": "Unused Reserved"
      },
      {
       "expr": "sum(hpe_storagepool_snapshot_used_bytes{array=\"us4-sn-001\"})",
       "legendFormat": "Snapshot"
      },
      {
       "expr": "sum(hpe_storagepool_data_reduction_bytes{array=\"us4-sn-001\"})",
       "legendFormat": "Reduction"
      }
     ]
    },
    {
     "title": "Array Capacity us4-sn-002",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(hpe_storagepool_capacity_bytes{array=\"us4-sn-002\"})",
       "legendFormat": "Capacity"
      },
      {
       "expr": "sum(hpe_storagepool_volume_used_bytes{array=\"us4-sn-002\"}) - sum(hpe_storagepool_data_reduction_bytes{array=\"us4-sn-002\"}) + sum(hpe_storagepool_snapshot_used_bytes{array=\"us4-sn-002\"})",
       "legendFormat": "Used"
      },
      { "expression": "($A*100)/$B", "type": "math" },
      {
       "expr": "sum(hpe_storagepool_unused_reserve_bytes{array=\"us4-sn-002\"})",
       "legendFormat": "Unused Reserved"
      },
      {
       "expr": "sum(hpe_storagepool_snapshot_used_bytes{array=\"us4-sn-002\"})",
       "legendFormat": "Snapshot"
      },
      {
       "expr": "sum(hpe_storagepool_data_reduction_bytes{array=\"us4-sn-002\"})",
       "legendFormat": "Reduction"
      }
     ]
    },
    {
     "title": "Array Capacity us4-sn-003",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(hpe_storagepool_capacity_bytes{array=\"us4-sn-003\"})",
       "legendFormat": "Capacity"
      },
      {
       "expr": "sum(hpe_storagepool_volume_used_bytes{array=\"us4-sn-003\"}) - sum(hpe_storagepool_data_reduction_bytes{array=\"us4-sn-003\"}) + sum(hpe_storagepool_snapshot_used_bytes{array=\"us4-sn-003\"})",
       "legendFormat": "Used"
      },
      { "expression": "($A*100)/$B", "type": "math" },
      {
       "expr": "sum(hpe_storagepool_unused_reserve_bytes{array=\"us4-sn-003\"})",
       "legendFormat": "Unused Reserved"
      },
      {
       "expr": "sum(hpe_storagepool_snapshot_used_bytes{array=\"us4-sn-003\"})",
       "legendFormat": "Snapshot"
      },
      {
       "expr": "sum(hpe_storagepool_data_reduction_bytes{array=\"us4-sn-003\"})",
       "legendFormat": "Reduction"
      }
     ]
    },
    {
     "title": "Total Volume Count us-dfw",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(hpe_volume_size_bytes{array=~\"us4-sn-001\"}) + count(hpe_volume_size_bytes{array=~\"us4-sn-002\"}) + count(hpe_volume_size_bytes{array=~\"us4-sn-003\"})",
       "legendFormat": "Total Volumes"
      }
     ]
    },
    {
     "title": "Volume Count us4-sn-001",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(hpe_volume_size_bytes{array=~\"us4-sn-001\"})",
       "legendFormat": "Total Volumes"
      }
     ]
    },
    {
     "title": "Volume Count us4-sn-002",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(hpe_volume_size_bytes{array=~\"us4-sn-002\"})",
       "legendFormat": "Total Volumes"
      }
     ]
    },
    {
     "title": "Volume Count us4-sn-002",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(hpe_volume_size_bytes{array=~\"us4-sn-002\"})",
       "legendFormat": "Total Volumes"
      }
     ]
    }
   ]
  },
  {
   "title": "DE-FRA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Usage Total de-fra",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 11, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "(sum(hpe_storagepool_volume_used_bytes{array=\"de1-sn-001\"}) - sum(hpe_storagepool_data_reduction_bytes{array=\"de1-sn-001\"}) + sum(hpe_storagepool_snapshot_used_bytes{array=\"de1-sn-001\"})) +\n\n(sum(hpe_storagepool_volume_used_bytes{array=\"de1-sn-002\"}) - sum(hpe_storagepool_data_reduction_bytes{array=\"de1-sn-002\"}) + sum(hpe_storagepool_snapshot_used_bytes{array=\"de1-sn-002\"})) +\n\n(sum(hpe_storagepool_volume_used_bytes{array=\"de1-sn-003\"}) - sum(hpe_storagepool_data_reduction_bytes{array=\"de1-sn-003\"}) + sum(hpe_storagepool_snapshot_used_bytes{array=\"de1-sn-003\"}))",
       "legendFormat": "Usage"
      }
     ]
    },
    {
     "title": "Usage - Cluster Breakdown - de-fra",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 13, "x": 11, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(hpe_storagepool_volume_used_bytes{array=\"de1-sn-001\"}) - sum(hpe_storagepool_data_reduction_bytes{array=\"de1-sn-001\"}) + sum(hpe_storagepool_snapshot_used_bytes{array=\"de1-sn-001\"})",
       "legendFormat": "de1-sn-001"
      },
      {
       "expr": "sum(hpe_storagepool_volume_used_bytes{array=\"de1-sn-002\"}) - sum(hpe_storagepool_data_reduction_bytes{array=\"de1-sn-002\"}) + sum(hpe_storagepool_snapshot_used_bytes{array=\"de1-sn-002\"})",
       "legendFormat": "de1-sn-002"
      },
      {
       "expr": "sum(hpe_storagepool_volume_used_bytes{array=\"de1-sn-003\"}) - sum(hpe_storagepool_data_reduction_bytes{array=\"de1-sn-003\"}) + sum(hpe_storagepool_snapshot_used_bytes{array=\"de1-sn-003\"})",
       "legendFormat": "de1-sn-003"
      }
     ]
    },
    {
     "title": "Pool Capacity de-fra",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(hpe_storagepool_capacity_bytes{os_region=\"de-fra\"})",
       "legendFormat": "Capacity"
      },
      {
       "expr": "(sum(hpe_storagepool_volume_used_bytes{array=\"de1-sn-001\"}) - sum(hpe_storagepool_data_reduction_bytes{array=\"de1-sn-001\"}) + sum(hpe_storagepool_snapshot_used_bytes{array=\"de1-sn-001\"})) +\n(sum(hpe_storagepool_volume_used_bytes{array=\"de1-sn-002\"}) - sum(hpe_storagepool_data_reduction_bytes{array=\"de1-sn-002\"}) + sum(hpe_storagepool_snapshot_used_bytes{array=\"de1-sn-002\"})) +\n(sum(hpe_storagepool_volume_used_bytes{array=\"de1-sn-003\"}) - sum(hpe_storagepool_data_reduction_bytes{array=\"de1-sn-003\"}) + sum(hpe_storagepool_snapshot_used_bytes{array=\"de1-sn-003\"}))",
       "legendFormat": "Used"
      },
      { "expression": "($A*100)/$B", "type": "math" }
     ]
    },
    {
     "title": "Array Capacity de1-sn-001",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(hpe_storagepool_capacity_bytes{array=\"de1-sn-001\"})",
       "legendFormat": "Capacity"
      },
      {
       "expr": "sum(hpe_storagepool_volume_used_bytes{array=\"de1-sn-001\"}) - sum(hpe_storagepool_data_reduction_bytes{array=\"de1-sn-001\"}) + sum(hpe_storagepool_snapshot_used_bytes{array=\"de1-sn-001\"})",
       "legendFormat": "Used"
      },
      { "expression": "($A*100)/$B", "type": "math" },
      {
       "expr": "sum(hpe_storagepool_unused_reserve_bytes{array=\"de1-sn-001\"})",
       "legendFormat": "Unused Reserved"
      },
      {
       "expr": "sum(hpe_storagepool_snapshot_used_bytes{array=\"de1-sn-001\"})",
       "legendFormat": "Snapshot"
      },
      {
       "expr": "sum(hpe_storagepool_data_reduction_bytes{array=\"de1-sn-001\"})",
       "legendFormat": "Reduction"
      }
     ]
    },
    {
     "title": "Array Capacity de1-sn-002",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(hpe_storagepool_capacity_bytes{array=\"de1-sn-002\"})",
       "legendFormat": "Capacity"
      },
      {
       "expr": "sum(hpe_storagepool_volume_used_bytes{array=\"de1-sn-002\"}) - sum(hpe_storagepool_data_reduction_bytes{array=\"de1-sn-002\"}) + sum(hpe_storagepool_snapshot_used_bytes{array=\"de1-sn-002\"})",
       "legendFormat": "Used"
      },
      { "expression": "($A*100)/$B", "type": "math" },
      {
       "expr": "sum(hpe_storagepool_unused_reserve_bytes{array=\"de1-sn-002\"})",
       "legendFormat": "Unused Reserved"
      },
      {
       "expr": "sum(hpe_storagepool_snapshot_used_bytes{array=\"de1-sn-002\"})",
       "legendFormat": "Snapshot"
      },
      {
       "expr": "sum(hpe_storagepool_data_reduction_bytes{array=\"de1-sn-002\"})",
       "legendFormat": "Reduction"
      }
     ]
    },
    {
     "title": "Array Capacity de1-sn-003",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(hpe_storagepool_capacity_bytes{array=\"de1-sn-003\"})",
       "legendFormat": "Capacity"
      },
      {
       "expr": "sum(hpe_storagepool_volume_used_bytes{array=\"de1-sn-003\"}) - sum(hpe_storagepool_data_reduction_bytes{array=\"de1-sn-003\"}) + sum(hpe_storagepool_snapshot_used_bytes{array=\"de1-sn-003\"})",
       "legendFormat": "Used"
      },
      { "expression": "($A*100)/$B", "type": "math" },
      {
       "expr": "sum(hpe_storagepool_unused_reserve_bytes{array=\"de1-sn-003\"})",
       "legendFormat": "Unused Reserved"
      },
      {
       "expr": "sum(hpe_storagepool_snapshot_used_bytes{array=\"de1-sn-003\"})",
       "legendFormat": "Snapshot"
      },
      {
       "expr": "sum(hpe_storagepool_data_reduction_bytes{array=\"de1-sn-003\"})",
       "legendFormat": "Reduction"
      }
     ]
    },
    {
     "title": "Total Volume Count DE-FRA",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(hpe_volume_size_bytes{array=~\"de1-sn-001\"}) + count(hpe_volume_size_bytes{array=~\"de1-sn-002\"}) + count(hpe_volume_size_bytes{array=~\"de1-sn-003\"})",
       "legendFormat": "Total Volumes"
      }
     ]
    },
    {
     "title": "Volume Count de1-sn-001",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(hpe_volume_size_bytes{array=~\"de1-sn-001\"})",
       "legendFormat": "Total Volumes"
      }
     ]
    },
    {
     "title": "Volume Count de1-sn-002",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(hpe_volume_size_bytes{array=~\"de1-sn-002\"})",
       "legendFormat": "Total Volumes"
      }
     ]
    },
    {
     "title": "Volume Count de1-sn-003",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(hpe_volume_size_bytes{array=~\"de1-sn-003\"})",
       "legendFormat": "Total Volumes"
      }
     ]
    }
   ]
  }
 ]
}