{
 "title": "Pure Capacity Dashboard",
 "tags": [ "folder-capacity" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   { "name": "env", "label": "Env", "query": { "query": "query_result(purefa_info)" } },
   {
    "name": "instance",
    "label": "FlashArray",
    "query": {
     "query": "query_result(purefa_info{instance=~\".+\"})"
    }
   },
   { "name": "TopItems", "label": "Top Items", "query": "1,2,3,4,5,6,7,8,10,15,25,50" },
   { "name": "site", "query": { "query": "label_values(purefa_info,site)" } }
  ]
 },
 "panels": [
  { "title": "Capacity Dashboard", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 }, "options": { "content": "# **PURE** STORAGE" } },
  {
   "title": "Total Capacity - All Regions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(purefa_array_space_bytes{space=\"capacity\",site=~\"$site\"}) by (site) +\nsum(purefa_array_space_bytes{space=\"capacity\",site=~\"$site\"}) by (site)",
     "legendFormat": "Total Capacity - {{site}}"
    },
    {
     "expr": "sum(purefa_array_space_bytes{space=\"total_provisioned\", site=~\"$site\"}) by (site)",
     "legendFormat": "Total Used - {{site}}"
    }
   ]
  },
  {
   "title": "Volume Count over time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(purefa_host_connections_info{site=~\"$site\"}) by (site)",
     "legendFormat": "{{site}}"
    }
   ]
  },
  {
   "title": "All Regions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(purefa_host_connections_info{site=~\"$site\"}) by (site)",
     "legendFormat": "{{site}}"
    }
   ]
  },
  {
   "title": "FlashArray System Detail",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(purefa_info{instance=~\"$instance\",env=~\"$env\", site=~\"$site\"}) by (instance,version,class,site)",
     "legendFormat": "Version"
    },
    {
     "expr": "sum(purefa_alerts_open{instance=~\"$instance\",env=~\"$env\",site=~\"$site\"}) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(purefa_array_space_data_reduction_ratio{instance=~\"$instance\",env=~\"$env\",site=~\"$site\"}) by (instance)",
     "legendFormat": "Data Reduction"
    },
    {
     "expr": "sum(purefa_array_space_bytes{instance=~\"$instance\",env=~\"$env\",space=\"capacity\",site=~\"$site\"}) by (instance) /1024/1024/1024/1024",
     "legendFormat": "Capacity"
    },
    {
     "expr": "sum(purefa_array_space_bytes{instance=~\"$instance\",env=~\"$env\",space=\"empty\",site=~\"$site\"}) by (instance) /1024/1024/1024/1024",
     "legendFormat": "Free Capacity (TB)"
    },
    {
     "expr": "sum(purefa_array_space_utilization{instance=~\"$instance\",env=~\"$env\",site=~\"$site\"}) by (instance)",
     "legendFormat": "Utilization %"
    }
   ]
  },
  {
   "title": "Pure Capacity $site",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "repeat": "site",
   "collapsed": true,
   "panels": [
    {
     "title": "Total Capacity - Tier1",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(purefa_array_space_bytes{space=\"capacity\", class=\"tier1\", site=~\"$site\"}) by(instance)",
       "legendFormat": "Total - {{instance}}"
      },
      {
       "expr": "sum(purefa_array_space_bytes{space=\"total_physical\",site=~\"$site\", class=\"tier1\"}) by(instance)",
       "legendFormat": "Usage - {{instance}}"
      }
     ]
    },
    {
     "title": "Total Capacity - $site - Tier2",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(purefa_array_space_bytes{space=\"capacity\",site=~\"$site\", class=\"tier2\"}) by(instance)",
       "legendFormat": "Total - {{instance}}"
      },
      {
       "expr": "sum(purefa_array_space_bytes{space=\"total_physical\", site=~\"$site\", class=\"tier2\"})  by(instance)",
       "legendFormat": "Usage - {{instance}}"
      }
     ]
    },
    {
     "title": "Capacity $site Tier1",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 9, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(purefa_array_space_bytes{space=\"capacity\", site=~\"$site\", class=\"tier1\"})",
       "legendFormat": "Capacity"
      },
      {
       "expr": "sum(purefa_array_space_bytes{space=\"total_provisioned\", site=~\"$site\", class=\"tier1\"})",
       "legendFormat": "Provisioned"
      },
      {
       "expr": "sum(purefa_array_space_bytes{space=\"total_physical\",site=~\"$site\", class=\"tier1\"})",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "Average Data Reduction Tier1",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 9, "y": 40 },
     "fieldConfig": { "defaults": { "unit": ":1" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg(purefa_array_space_data_reduction_ratio{instance=~\"^$instance\",site=~\"$site\", class=\"tier1\"})"
      }
     ]
    },
    {
     "title": "Capacity $site Tier2",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 9, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(purefa_array_space_bytes{space=\"capacity\", site=~\"$site\", class=\"tier2\"})",
       "legendFormat": "Capacity"
      },
      {
       "expr": "sum(purefa_array_space_bytes{space=\"total_provisioned\", site=~\"$site\", class=\"tier2\"})",
       "legendFormat": "Provisioned"
      },
      {
       "expr": "sum(purefa_array_space_bytes{space=\"total_physical\",site=~\"$site\", class=\"tier2\"})",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "Average Data Reduction tier2",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 21, "y": 40 },
     "fieldConfig": { "defaults": { "unit": ":1" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg(purefa_array_space_data_reduction_ratio{instance=~\"^$instance\",site=~\"$site\", class=\"tier2\"})"
      }
     ]
    },
    {
     "title": "Percentage used Tier1",
     "type": "bargauge",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(purefa_array_space_utilization{site=~\"$site\", class=\"tier1\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Percentage used Tier2",
     "type": "bargauge",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(purefa_array_space_utilization{site=~\"$site\", class=\"tier2\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "DE1-OS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Capacity DE1",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 10, "x": 0, "y": 358 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(purefa_array_space_bytes{space=\"capacity\", instance=\"de1-sn-pure-001\"}) + sum(purefa_array_space_bytes{space=\"capacity\", instance=\"de1-sn-pure-002\"})",
       "legendFormat": "Capacity"
      },
      {
       "expr": "sum(purefa_array_space_bytes{space=\"total_provisioned\", instance=\"de1-sn-pure-001\"}) + sum(purefa_array_space_bytes{space=\"total_provisioned\", instance=\"de1-sn-pure-002\"})",
       "legendFormat": "Provisioned"
      },
      {
       "expr": "sum(purefa_array_space_bytes{space=\"total_physical\",instance=\"de1-sn-pure-001\"}) + sum(purefa_array_space_bytes{space=\"total_physical\",instance=\"de1-sn-pure-002\"})",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "Capacity de1-sn-pure-001",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 7, "x": 10, "y": 358 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "purefa_array_space_bytes{instance=\"de1-sn-pure-001\",space=\"capacity\"}",
       "legendFormat": "Capacity"
      },
      {
       "expr": "purefa_array_space_bytes{space=\"total_provisioned\", instance=\"de1-sn-pure-001\"}",
       "legendFormat": "Provisioned"
      },
      {
       "expr": "purefa_array_space_bytes{space=\"total_physical\",instance=\"de1-sn-pure-001\"}",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "Capacity de1-sn-pure-002",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 7, "x": 17, "y": 358 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "purefa_array_space_bytes{instance=\"de1-sn-pure-002\",space=\"capacity\"}",
       "legendFormat": "Capacity"
      },
      {
       "expr": "purefa_array_space_bytes{space=\"total_provisioned\", instance=\"de1-sn-pure-002\"}",
       "legendFormat": "Provisioned"
      },
      {
       "expr": "purefa_array_space_bytes{space=\"total_physical\",instance=\"de1-sn-pure-002\"}",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "Percentage used DE1",
     "type": "bargauge",
     "gridPos": { "h": 2, "w": 10, "x": 0, "y": 365 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expression": "($A+$B)/2", "type": "math" }
     ]
    },
    {
     "title": "Percentage used de1-sn-pure-001",
     "type": "bargauge",
     "gridPos": { "h": 2, "w": 7, "x": 10, "y": 365 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(purefa_array_space_utilization{env=\"os-de1\",instance=\"de1-sn-pure-001\"}) by (instance))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Percentage used de1-sn-pure-002",
     "type": "bargauge",
     "gridPos": { "h": 2, "w": 7, "x": 17, "y": 365 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(purefa_array_space_utilization{env=\"os-de1\",instance=\"de1-sn-pure-002\"}) by (instance))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "LON2-OS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Capacity GB4",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 10, "x": 0, "y": 368 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(purefa_array_space_bytes{space=\"capacity\", instance=\"gb4-sn-pure-001\"}) + sum(purefa_array_space_bytes{space=\"capacity\", instance=\"gb4-sn-pure-002\"})",
       "legendFormat": "Capacity"
      },
      {
       "expr": "sum(purefa_array_space_bytes{space=\"total_provisioned\", instance=\"gb4-sn-pure-001\"}) + sum(purefa_array_space_bytes{space=\"total_provisioned\", instance=\"gb4-sn-pure-002\"})",
       "legendFormat": "Provisioned"
      },
      {
       "expr": "sum(purefa_array_space_bytes{space=\"total_physical\",instance=\"gb4-sn-pure-001\"}) + sum(purefa_array_space_bytes{space=\"total_physical\",instance=\"gb4-sn-pure-002\"})",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "Capacity gb4-sn-pure-001",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 7, "x": 10, "y": 368 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "purefa_array_space_bytes{instance=\"gb4-sn-pure-001\",space=\"capacity\"}",
       "legendFormat": "Capacity"
      },
      {
       "expr": "purefa_array_space_bytes{space=\"total_provisioned\", instance=\"gb4-sn-pure-001\"}",
       "legendFormat": "Provisioned"
      },
      {
       "expr": "sum(purefa_array_space_bytes{space=\"total_physical\",instance=\"gb4-sn-pure-001\"}) ",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "Capacity gb4-sn-pure-002",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 7, "x": 17, "y": 368 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "purefa_array_space_bytes{instance=\"gb4-sn-pure-002\",space=\"capacity\"}",
       "legendFormat": "Capacity"
      },
      {
       "expr": "purefa_array_space_bytes{space=\"total_provisioned\", instance=\"gb4-sn-pure-002\"}",
       "legendFormat": "Provisioned"
      },
      {
       "expr": "sum(purefa_array_space_bytes{space=\"total_physical\",instance=\"gb4-sn-pure-002\"})",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "Percentage used GB4",
     "type": "bargauge",
     "gridPos": { "h": 2, "w": 10, "x": 0, "y": 374 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expression": "($A+$B)/2", "type": "math" }
     ]
    },
    {
     "title": "Percentage used gb4-sn-pure-001",
     "type": "bargauge",
     "gridPos": { "h": 2, "w": 7, "x": 10, "y": 374 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(purefa_array_space_utilization{env=\"os-gb4\",instance=\"gb4-sn-pure-001\"}) by (instance))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Percentage used gb4-sn-pure-002",
     "type": "bargauge",
     "gridPos": { "h": 2, "w": 7, "x": 17, "y": 374 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(purefa_array_space_utilization{env=\"os-gb4\",instance=\"gb4-sn-pure-002\"}) by (instance))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}