{
 "title": "Pure Storage FlashArray PCI - Overview",
 "tags": [ "folder-storage" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "dc", "label": "DC", "query": { "query": "label_values(purefa_info, dc)" } },
   {
    "name": "array",
    "label": "FlashArray",
    "query": {
     "query": "label_values(purefa_info,array_name)"
    }
   },
   { "name": "TopItems", "label": "Top Items", "query": "1,2,3,4,5,6,7,8,10,15,25,50" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": {
    "content": "<img src=\"https://www.purestorage.com/content/dam/pure/logos/pure_storage/primary/pure-logo.png\" width=\"100%\">"
   }
  },
  {
   "title": "FlashArray System Detail",
   "type": "table",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(purefa_info{array=~\"$array\",dc=~\"$dc\"}) by (array,os,version,site,class)",
     "legendFormat": "Version"
    },
    {
     "expr": "sum(purefa_alerts_open{array=~\"$array\",dc=~\"$dc\"}) by (array)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(purefa_array_space_data_reduction_ratio{array=~\"$array\",dc=~\"$dc\"}) by (array)",
     "legendFormat": "Data Reduction"
    },
    {
     "expr": "sum(purefa_array_space_bytes{array=~\"$array\",dc=~\"$dc\",space=\"capacity\"}) by (array) /1024/1024/1024/1024",
     "legendFormat": "Capacity"
    },
    {
     "expr": "sum(purefa_array_space_bytes{array=~\"$array\",dc=~\"$dc\",space=\"empty\"}) by (array) /1024/1024/1024/1024",
     "legendFormat": "Free Capacity (TB)"
    },
    {
     "expr": "sum(purefa_array_space_utilization{array=~\"$array\",dc=~\"$dc\"}) by (array)",
     "legendFormat": "Utilization %"
    }
   ]
  },
  {
   "title": "Average Total Bandwidth for $array array(s) bytes SI",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(purefa_array_performance_bandwidth_bytes{array=~\"^$array\",dc=~\"^$dc\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dectbytes" } },
   "targets": [
    {
     "expr": "sum by (space) (\n  purefa_array_space_bytes{\n    array=~\"$array\",\n    dc=~\"$dc\",\n    space=~\"system|shared|snapshots|unique|empty\"\n  }\n) / 1024^4",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Data Reduction Ratio for $array array(s)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": ":1" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(purefa_array_space_data_reduction_ratio{array=~\"^$array\",dc=~\"^$dc\"})"
    }
   ]
  },
  {
   "title": "Top $TopItems Volumes for Read IOPs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 13 },
   "targets": [
    {
     "expr": "avg(purefa_volume_performance_throughput_iops{dc=~\"$dc\", array=~\"$array\", dimension=\"reads_per_sec\"}) by (array,dimension,name)\nand\ntopk($TopItems, avg(rate(purefa_volume_performance_throughput_iops{dc=~\"$dc\", array=~\"$array\", dimension=\"reads_per_sec\"}[$__range] @ end() )) by (array,dimension,name))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Top $TopItems Volumes for Write IOPs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 13 },
   "targets": [
    {
     "expr": "avg(purefa_volume_performance_throughput_iops{dc=~\"$dc\", array=~\"$array\", dimension=\"writes_per_sec\"}) by (array,dimension,name)\nand\ntopk($TopItems, avg(rate(purefa_volume_performance_throughput_iops{dc=~\"$dc\", array=~\"$array\", dimension=\"writes_per_sec\"}[$__range] @ end() )) by (array,dimension,name))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Average Array Utilization for $array array(s)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(purefa_array_space_utilization{array=~\"^$array\",dc=~\"^$dc\"})"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(purefa_alerts_open{array=~\"$array\", dc=~\"$dc\", severity=\"info\"}) by (array) OR on() sum(purefa_alerts_open{array=~\"$array\", dc=~\"$dc\"}*0) by (array)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(purefa_alerts_open{array=~\"$array\", dc=~\"$dc\", severity=\"warning\"}) by (array) OR on() sum(purefa_alerts_open{array=~\"$array\", dc=~\"$dc\"}*0) by (array)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(purefa_alerts_open{array=~\"$array\", dc=~\"$dc\", severity=\"critical\"}) by (array) OR on() sum(purefa_alerts_open{array=~\"$array\", dc=~\"$dc\"}*0) by (array)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(purefa_alerts_open{array=~\"$array\", dc=~\"$dc\", severity=\".*\"}) by (array) OR on() sum(purefa_alerts_open{array=~\"$array\", dc=~\"$dc\"}) by (array)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write Bandwidth by $array array(s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(purefa_array_performance_bandwidth_bytes{dc=~\"^$dc\", array=~\"^$array\", dimension=\"write_bytes_per_sec\"} [$__interval])) by (array)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read Bandwidth by $array array(s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(purefa_array_performance_bandwidth_bytes{dc=~\"^$dc\", array=~\"^$array\", dimension=\"read_bytes_per_sec\"} [$__interval])) by (array)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sum of Space Utilization by $array array(s)",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (purefa_array_space_bytes{array=~\"^$array\",dc=~\"^$dc\",space=~\"system|replication|shared|snapshots|unique|empty\"}) by(space)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Top $TopItems Latent Volumes by $array array(s) & IO type",
   "type": "timeseries",
   "description": "This query is very expensive on Prometheus and the browser. For large environments it may be advisable to reduce scope by using the filter and narrower time frame, use a tabular view or create a recording rule.\n\nhttps://prometheus.io/docs/prometheus/latest/querying/basics/#avoiding-slow-queries-and-overloads",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg(purefa_volume_performance_latency_usec{dc=~\"$dc\", array=~\"$array\"}) by (array,dimension,name)\nand\ntopk($TopItems, avg(rate(purefa_volume_performance_latency_usec{dc=~\"$dc\", array=~\"$array\"}[$__range] @ end() )) by (array,dimension,name))",
     "legendFormat": "{{array}} - {{dimension}} - {{name}}"
    }
   ]
  },
  {
   "title": "Array QDepth by $array array(s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg(purefa_array_performance_queue_depth_ops{array=~\"^$array\",dc=~\"^$dc\"}) by (array)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average IOPS by IO Type and $array array(s)",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(purefa_array_performance_throughput_iops{array=~\"^$array\",dc=~\"^$dc\"}[$__range])) by (dimension)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Top $TopItems Read Throughput by $array array(s) & Hosts ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "avg(purefa_host_performance_throughput_iops{dc=~\"$dc\", array=~\"$array\", dimension=\"reads_per_sec\"}) by (array,host)\nand\ntopk($TopItems, avg(rate(purefa_host_performance_throughput_iops{dc=~\"$dc\", array=~\"$array\", dimension=\"reads_per_sec\"}[$__range] @ end() )) by (array,host))",
     "legendFormat": "{{array}}  - {{host}}"
    }
   ]
  },
  {
   "title": "Average Top $TopItems Write Throughput by $array array(s) & Hosts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "avg(purefa_host_performance_throughput_iops{dc=~\"$dc\", array=~\"$array\", dimension=\"writes_per_sec\"}) by (array,host)\nand\ntopk($TopItems, avg(rate(purefa_host_performance_throughput_iops{dc=~\"$dc\", array=~\"$array\", dimension=\"writes_per_sec\"}[$__range] @ end() )) by (array,host))",
     "legendFormat": "{{array}} - {{host}}"
    }
   ]
  },
  {
   "title": "Average Total Latency for $array array(s)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(purefa_array_performance_latency_usec{array=~\"^$array\",dc=~\"^$dc\",dimension=\"usec_per_read_op\"}[$__interval]))",
     "legendFormat": "usec_per_read_op"
    },
    {
     "expr": "sum(avg_over_time(purefa_array_performance_latency_usec{array=~\"^$array\",dc=~\"^$dc\",dimension=\"usec_per_write_op\"}[$__interval]))",
     "legendFormat": "usec_per_write_op"
    },
    {
     "expr": "sum(avg_over_time(purefa_array_performance_latency_usec{array=~\"^$array\",dc=~\"^$dc\",dimension=\"usec_per_mirrored_write_op\"}[$__interval]))",
     "legendFormat": "usec_per_mirrored_write_op"
    },
    {
     "expr": "sum(avg_over_time(purefa_array_performance_latency_usec{array=~\"^$array\",dc=~\"^$dc\",dimension=\"usec_per_other_op\"}[$__interval]))",
     "legendFormat": "usec_per_other_op"
    }
   ]
  },
  {
   "title": "Average Total IOPS for $array array(s)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(purefa_array_performance_throughput_iops{array=~\"^$array\",dc=~\"^$dc\",dimension=\"reads_per_sec\"}[$__interval]))",
     "legendFormat": "reads_per_sec"
    },
    {
     "expr": "sum(avg_over_time(purefa_array_performance_throughput_iops{array=~\"^$array\",dc=~\"^$dc\",dimension=\"writes_per_sec\"}[$__interval]))",
     "legendFormat": "writes_per_sec"
    },
    {
     "expr": "sum(avg_over_time(purefa_array_performance_throughput_iops{array=~\"^$array\",dc=~\"^$dc\",dimension=\"mirrored_writes_per_sec\"}[$__interval]))",
     "legendFormat": "mirrored_per_sec"
    },
    {
     "expr": "sum(avg_over_time(purefa_array_performance_throughput_iops{array=~\"^$array\",dc=~\"^$dc\",dimension=\"others_per_sec\"}[$__interval]))",
     "legendFormat": "others_per_sec"
    }
   ]
  },
  {
   "title": "Average Total Bandwidth for $array array(s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(purefa_array_performance_bandwidth_bytes{array=~\"^$array\",dc=~\"^$dc\",dimension=\"read_bytes_per_sec\"}[$__interval]))",
     "legendFormat": "reads_per_sec"
    },
    {
     "expr": "sum(avg_over_time(purefa_array_performance_bandwidth_bytes{array=~\"^$array\",dc=~\"^$dc\",dimension=\"write_bytes_per_sec\"}[$__interval]))",
     "legendFormat": "writes_per_sec"
    },
    {
     "expr": "sum(avg_over_time(purefa_array_performance_bandwidth_bytes{array=~\"^$array\",dc=~\"^$dc\",dimension=\"mirrored_write_bytes_per_sec\"}[$__interval]))",
     "legendFormat": "mirrored_per_sec"
    }
   ]
  }
 ]
}