{
 "title": "Pure Storage FlashArray - Overview",
 "tags": [ "folder-storage" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   { "name": "env", "label": "Env", "query": { "query": "query_result(purefa_info)" } },
   {
    "name": "instance",
    "label": "FlashArray",
    "query": {
     "query": "label_values(purefa_info{env=~\"$env\"},instance)"
    }
   },
   { "name": "TopItems", "label": "Top Items", "query": "1,2,3,4,5,6,7,8,10,15,25,50" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": {
    "content": "<img src=\"https://www.purestorage.com/content/dam/pure/logos/pure_storage/primary/pure-logo.png\" width=\"100%\">"
   }
  },
  {
   "title": "FlashArray System Detail",
   "type": "table",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(purefa_info{instance=~\"$instance\",env=~\"$env\"}) by (instance,os,version,site,class)",
     "legendFormat": "Version"
    },
    {
     "expr": "sum(purefa_alerts_open{instance=~\"$instance\",env=~\"$env\"}) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(purefa_array_space_data_reduction_ratio{instance=~\"$instance\",env=~\"$env\"}) by (instance)",
     "legendFormat": "Data Reduction"
    },
    {
     "expr": "sum(purefa_array_space_bytes{instance=~\"$instance\",env=~\"$env\",space=\"capacity\"}) by (instance) /1024/1024/1024/1024",
     "legendFormat": "Capacity"
    },
    {
     "expr": "sum(purefa_array_space_bytes{instance=~\"$instance\",env=~\"$env\",space=\"empty\"}) by (instance) /1024/1024/1024/1024",
     "legendFormat": "Free Capacity (TB)"
    },
    {
     "expr": "sum(purefa_array_space_utilization{instance=~\"$instance\",env=~\"$env\"}) by (instance)",
     "legendFormat": "Utilization %"
    }
   ]
  },
  {
   "title": "Average Total Bandwidth for $instance array(s) bytes SI",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(purefa_array_performance_bandwidth_bytes{instance=~\"^$instance\",env=~\"^$env\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Errors/s for $instance array(s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(purefa_network_interface_performance_errors{instance=~\"^$instance\",env=~\"^$env\"}[3m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average Data Reduction Ratio for $instance array(s)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": ":1" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(purefa_array_space_data_reduction_ratio{instance=~\"^$instance\",env=~\"^$env\"})"
    }
   ]
  },
  {
   "title": "Top $TopItems Volumes for Read IOPs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 13 },
   "targets": [
    {
     "expr": "avg(purefa_volume_performance_throughput_iops{env=~\"$env\", instance=~\"$instance\", dimension=\"reads_per_sec\"}) by (instance,dimension,name)\nand\ntopk($TopItems, avg(rate(purefa_volume_performance_throughput_iops{env=~\"$env\", instance=~\"$instance\", dimension=\"reads_per_sec\"}[$__range] @ end() )) by (instance,dimension,name))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Top $TopItems Volumes for Write IOPs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 13 },
   "targets": [
    {
     "expr": "avg(purefa_volume_performance_throughput_iops{env=~\"$env\", instance=~\"$instance\", dimension=\"writes_per_sec\"}) by (instance,dimension,name)\nand\ntopk($TopItems, avg(rate(purefa_volume_performance_throughput_iops{env=~\"$env\", instance=~\"$instance\", dimension=\"writes_per_sec\"}[$__range] @ end() )) by (instance,dimension,name))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Average Array Utilization for $instance array(s)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(purefa_array_space_utilization{instance=~\"^$instance\",env=~\"^$env\"})"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(purefa_alerts_open{instance=~\"$instance\", env=~\"$env\", severity=\"info\"}) by (instance) OR on() sum(purefa_alerts_open{instance=~\"$instance\", env=~\"$env\"}*0) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(purefa_alerts_open{instance=~\"$instance\", env=~\"$env\", severity=\"warning\"}) by (instance) OR on() sum(purefa_alerts_open{instance=~\"$instance\", env=~\"$env\"}*0) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(purefa_alerts_open{instance=~\"$instance\", env=~\"$env\", severity=\"critical\"}) by (instance) OR on() sum(purefa_alerts_open{instance=~\"$instance\", env=~\"$env\"}*0) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(purefa_alerts_open{instance=~\"$instance\", env=~\"$env\", severity=\".*\"}) by (instance) OR on() sum(purefa_alerts_open{instance=~\"$instance\", env=~\"$env\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write Bandwidth by $instance array(s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(purefa_array_performance_bandwidth_bytes{env=~\"^$env\", instance=~\"^$instance\", dimension=\"write_bytes_per_sec\"} [$__interval])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read Bandwidth by $instance array(s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(purefa_array_performance_bandwidth_bytes{env=~\"^$env\", instance=~\"^$instance\", dimension=\"read_bytes_per_sec\"} [$__interval])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sum of Space Utilization by $instance array(s)",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (purefa_array_space_bytes{instance=~\"^$instance\",env=~\"^$env\",space=~\"system|replication|shared|snapshots|unique|empty\"}) by(space)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Top $TopItems Latent Volumes by $instance array(s) & IO type",
   "type": "timeseries",
   "description": "This query is very expensive on Prometheus and the browser. For large environments it may be advisable to reduce scope by using the filter and narrower time frame, use a tabular view or create a recording rule.\n\nhttps://prometheus.io/docs/prometheus/latest/querying/basics/#avoiding-slow-queries-and-overloads",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg(purefa_volume_performance_latency_usec{env=~\"$env\", instance=~\"$instance\"}) by (instance,dimension,name)\nand\ntopk($TopItems, avg(rate(purefa_volume_performance_latency_usec{env=~\"$env\", instance=~\"$instance\"}[$__range] @ end() )) by (instance,dimension,name))",
     "legendFormat": "{{instance}} - {{dimension}} - {{name}}"
    }
   ]
  },
  {
   "title": "Array QDepth by $instance array(s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg(purefa_array_performance_queue_depth_ops{instance=~\"^$instance\",env=~\"^$env\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average IOPS by IO Type and $instance array(s)",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(purefa_array_performance_throughput_iops{instance=~\"^$instance\",env=~\"^$env\"}[$__range])) by (dimension)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Top $TopItems Read Throughput by $instance array(s) & Hosts ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "avg(purefa_host_performance_throughput_iops{env=~\"$env\", instance=~\"$instance\", dimension=\"reads_per_sec\"}) by (instance,host)\nand\ntopk($TopItems, avg(rate(purefa_host_performance_throughput_iops{env=~\"$env\", instance=~\"$instance\", dimension=\"reads_per_sec\"}[$__range] @ end() )) by (instance,host))",
     "legendFormat": "{{instance}}  - {{host}}"
    }
   ]
  },
  {
   "title": "Average Top $TopItems Write Throughput by $instance array(s) & Hosts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "avg(purefa_host_performance_throughput_iops{env=~\"$env\", instance=~\"$instance\", dimension=\"writes_per_sec\"}) by (instance,host)\nand\ntopk($TopItems, avg(rate(purefa_host_performance_throughput_iops{env=~\"$env\", instance=~\"$instance\", dimension=\"writes_per_sec\"}[$__range] @ end() )) by (instance,host))",
     "legendFormat": "{{instance}} - {{host}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 24, "w": 6, "x": 0, "y": 43 },
   "options": {
    "content": "## Metrics\n\nAll metrics are prefixed with purefa_\nBelow are the metrics names available\n```\n* alerts_open\n* array_performance_average_bytes\n* array_performance_bandwidth_bytes\n* array_performance_latency_usec\n* array_performance_queue_depth_ops\n* array_performance_throughput_iops\n* array_space_bytes\n* array_space_data_reduction_ratio\n* array_space_utilization\n* directory_performance_average_bytes\n* directory_performance_bandwidth_bytes\n* directory_performance_latency_usec\n* directory_performance_throughput_iops\n* directory_space_bytes\n* directory_space_data_reduction_ratio\n* host_connections_info\n* host_performance_average_bytes\n* host_performance_bandwidth_bytes\n* host_performance_latency_usec\n* host_performance_throughput_iops\n* host_space_bytes\n* host_space_data_reduction_ratio\n* host_space_size_bytes\n* hw_component_status\n* hw_component_temperature_celsius\n* hw_component_voltage_volt\n* info\n* pod_performance_average_bytes\n* pod_performance_bandwidth_bytes\n* pod_performance_latency_usec\n* pod_performance_throughput_iops\n* pod_space_bytes\n* pod_space_data_reduction_ratio\n* volume_performance_average_bytes\n* volume_performance_bandwidth_bytes\n* volume_performance_latency_usec\n* volume_performance_throughput_iops\n* volume_space_bytes\n* volume_space_data_reduction_ratio\n```"
   }
  },
  {
   "title": "Average Total Latency for $instance array(s)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(purefa_array_performance_latency_usec{instance=~\"^$instance\",env=~\"^$env\",dimension=\"usec_per_read_op\"}[$__interval]))",
     "legendFormat": "usec_per_read_op"
    },
    {
     "expr": "sum(avg_over_time(purefa_array_performance_latency_usec{instance=~\"^$instance\",env=~\"^$env\",dimension=\"usec_per_write_op\"}[$__interval]))",
     "legendFormat": "usec_per_write_op"
    },
    {
     "expr": "sum(avg_over_time(purefa_array_performance_latency_usec{instance=~\"^$instance\",env=~\"^$env\",dimension=\"usec_per_mirrored_write_op\"}[$__interval]))",
     "legendFormat": "usec_per_mirrored_write_op"
    },
    {
     "expr": "sum(avg_over_time(purefa_array_performance_latency_usec{instance=~\"^$instance\",env=~\"^$env\",dimension=\"usec_per_other_op\"}[$__interval]))",
     "legendFormat": "usec_per_other_op"
    }
   ]
  },
  {
   "title": "Average Total IOPS for $instance array(s)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(purefa_array_performance_throughput_iops{instance=~\"^$instance\",env=~\"^$env\",dimension=\"reads_per_sec\"}[$__interval]))",
     "legendFormat": "reads_per_sec"
    },
    {
     "expr": "sum(avg_over_time(purefa_array_performance_throughput_iops{instance=~\"^$instance\",env=~\"^$env\",dimension=\"writes_per_sec\"}[$__interval]))",
     "legendFormat": "writes_per_sec"
    },
    {
     "expr": "sum(avg_over_time(purefa_array_performance_throughput_iops{instance=~\"^$instance\",env=~\"^$env\",dimension=\"mirrored_writes_per_sec\"}[$__interval]))",
     "legendFormat": "mirrored_per_sec"
    },
    {
     "expr": "sum(avg_over_time(purefa_array_performance_throughput_iops{instance=~\"^$instance\",env=~\"^$env\",dimension=\"others_per_sec\"}[$__interval]))",
     "legendFormat": "others_per_sec"
    }
   ]
  },
  {
   "title": "Average Total Bandwidth for $instance array(s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(purefa_array_performance_bandwidth_bytes{instance=~\"^$instance\",env=~\"^$env\",dimension=\"read_bytes_per_sec\"}[$__interval]))",
     "legendFormat": "reads_per_sec"
    },
    {
     "expr": "sum(avg_over_time(purefa_array_performance_bandwidth_bytes{instance=~\"^$instance\",env=~\"^$env\",dimension=\"write_bytes_per_sec\"}[$__interval]))",
     "legendFormat": "writes_per_sec"
    },
    {
     "expr": "sum(avg_over_time(purefa_array_performance_bandwidth_bytes{instance=~\"^$instance\",env=~\"^$env\",dimension=\"mirrored_write_bytes_per_sec\"}[$__interval]))",
     "legendFormat": "mirrored_per_sec"
    }
   ]
  }
 ]
}