{
 "title": "Pure Storage FlashBlade - Overview",
 "description": "Get real-time visibility into your FlashBlade environment with a powerful, high-level dashboard built for speed, scale, and clarity. Instantly surface performance, capacity, and top talkers—so you can troubleshoot smarter and act faster.",
 "tags": [
  "pure",
  "storage",
  "pure storage",
  "flashblade",
  "fb",
  "prometheus",
  "openmetrics",
  "folder-storage"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DashboardVersion", "query": "1.0.8" },
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "env", "label": "Env", "query": { "query": "label_values(purefb_info,env)" } },
   {
    "name": "instance",
    "label": "FlashBlade",
    "query": {
     "query": "label_values(purefb_info,instance)"
    }
   },
   { "name": "TopItems", "label": "Top Items", "query": "1,2,3,4,5,6,8,10,15,20,25,50" },
   {
    "name": "protocol",
    "label": "Protocol",
    "query": {
     "query": "query_result(purefb_array_performance_latency_usec)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "FlashBlade Array System Detail",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(purefb_info{instance=~\"$instance\",env=~\"$env\"}) by (instance, os, version)",
     "legendFormat": "{{os}} {{version}}"
    },
    {
     "expr": "min(purefb_hardware_health{instance=~\"$instance\",env=~\"$env\"}) by (instance)",
     "legendFormat": "Hardware Health"
    },
    {
     "expr": "sum(purefb_alerts_open{instance=~\"$instance\",env=~\"$env\"}) by (instance)",
     "legendFormat": "Number of Alerts"
    },
    {
     "expr": "avg(purefb_array_space_data_reduction_ratio{instance=~\"$instance\",env=~\"$env\",type=\"array\"}) by (instance)",
     "legendFormat": "Ratio"
    },
    {
     "expr": "sum(purefb_array_space_bytes{instance=~\"$instance\",env=~\"$env\",type=\"array\",space=\"capacity\"}) by (instance) /1024/1024/1024/1024",
     "legendFormat": "Array Capacity (TB)"
    },
    {
     "expr": "sum(purefb_array_space_bytes{instance=~\"$instance\",env=~\"$env\",type=\"array\",space=\"empty\"}) by (instance) /1024/1024/1024/1024",
     "legendFormat": "Array Free Space"
    },
    {
     "expr": "purefb_array_space_utilization{env=~\"$env\", instance=~\"$instance\"}",
     "legendFormat": "Utililzation"
    }
   ]
  },
  {
   "title": "FlashBlade Array Alerts",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(purefb_alerts_open{instance=~\"$instance\", env=~\"$env\", severity=\"critical\"}) by (instance) OR on() sum(purefb_alerts_open{instance=~\"$instance\"}*0) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(purefb_alerts_open{instance=~\"$instance\",severity=\"warning\",env=~\"$env\"}) by (instance) OR on() sum(purefb_alerts_open{instance=~\"$instance\"}*0) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(purefb_alerts_open{instance=~\"$instance\",severity=\"info\",env=~\"$env\"}) by (instance) OR on() sum(purefb_alerts_open{instance=~\"$instance\"}*0) by (instance)\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(purefb_alerts_open{instance=~\"$instance\",severity=\".*\",env=~\"$env\"}) by (instance) OR on() sum(purefb_alerts_open{instance=~\"$instance\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Capacity per File System",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance, env, name) (\n  purefb_file_systems_space_bytes{space=\"virtual\", instance=~\"$instance\", env=~\"$env\"}\n)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sum Array Space Utilization by Type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(purefb_array_space_bytes{instance=~\"$instance\",env=~\"$env\",space=~\"total_physical\",type!=\"array\"}) by (type)",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum(purefb_array_space_bytes{instance=~\"$instance\",env=~\"$env\",space=~\"snapshots\"}) by (space)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(purefb_array_space_bytes{instance=~\"$instance\",env=~\"$env\",space=~\"empty\"}) by (space)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Over Time IOPS by IO Type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(purefb_array_performance_throughput_iops{instance=~\"$instance\",env=~\"$env\"}[$__range])) by (dimension)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Over Time IOPS by All Protocols",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(purefb_array_performance_throughput_iops{env=~\"$env\", instance=~\"$instance\",protocol!=\"all\"}[$__range])) by (protocol)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read Throughput by $protocol protocol(s)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "purefb_array_performance_bandwidth_bytes{env=~\"$env\", instance=~\"$instance\", dimension=\"read_bytes_per_sec\", protocol=~\"$protocol\", job=~\".+array.+\"}\nand\ntopk($TopItems, rate(purefb_array_performance_bandwidth_bytes{env=~\"$env\", instance=~\"$instance\", dimension=\"read_bytes_per_sec\", protocol=~\"$protocol\", job=~\".+array.+\"}[$__range] @ end() ))",
     "legendFormat": "{{instance}} - {{protocol}}"
    }
   ]
  },
  {
   "title": "Write Throughput by $protocol protocol(s)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "purefb_array_performance_bandwidth_bytes{env=~\"$env\", instance=~\"$instance\", dimension=\"write_bytes_per_sec\", protocol=~\"$protocol\", job=~\".+array.+\"}\nand\ntopk($TopItems, rate(purefb_array_performance_bandwidth_bytes{env=~\"$env\", instance=~\"$instance\", dimension=\"write_bytes_per_sec\", protocol=~\"$protocol\", job=~\".+array.+\"}[$__range] @ end() ))",
     "legendFormat": "{{instance}} - {{protocol}}"
    }
   ]
  },
  { "title": "Filesystems", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Top $TopItems Avg Filesystem Throughput by IO Type",
   "type": "timeseries",
   "description": "#### Requirements\n`/metrics/filesystems` endpoint required for this panel.\n\n#### Panel Overview\nThis graph displays the top `$TopItems` values, based on their average across the selected time range.\n\nIt combines two Prometheus queries:\n- The first shows the average values over time for all matching entities.\n- The second uses `topk()` with `avg_over_time(... @ end())` to select the top N values, based on total usage across the full range.\n- Only entities present in both queries are shown, meaning the graph displays only the top-N performers.\n\n---\n\n#### Why It’s Set Up This Way\nPrometheus doesn’t support filtering a time series dynamically by top N across time, so this setup is a workaround.\n\nUsing `@ end()` ensures the `topk()` query selects exactly N entities based on a single, consistent snapshot taken at the end of the selected time range.  \nThis avoids the issue where the top N can vary over time and result in more than N lines being shown on the graph.\n\nWe also use `avg_over_time`, not `rate()`, because the metric is pre-aggregated — it's not a counter. Using `rate()` would give incorrect results.\n\n---\n\n#### Tips for Best Use\n- This panel works best for focused time windows, ideally 20 minutes to 3 hours.  \n  Longer ranges (e.g. days) smooth out the signal and may hide short-lived spikes.\n- Use it to quickly spot heavy resource consumers over time, then drill into specific panels or metrics.\n- If graph lines look broken or inconsistent, try zooming in or shifting the time range slightly before \"now\" to avoid scrape alignment issues.\n- Combine with filters (e.g., instance or protocol) to reduce clutter and highlight key trends.\n- For troubleshooting or spot checks, reduce the time range to 15–30 minutes for clearer insight.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(purefb_file_systems_performance_bandwidth_bytes{env=~\"$env\", instance=~\"$instance\"}) by (name,instance, dimension)\nand\ntopk($TopItems, avg(avg_over_time(purefb_file_systems_performance_bandwidth_bytes{env=~\"$env\", instance=~\"$instance\"}[$__range] @ end() )) by (name,instance, dimension))",
     "legendFormat": "{{instance}} - {{dimension}} - {{name}}"
    }
   ]
  },
  {
   "title": "Top $TopItems Avg File System Latency by IO Type",
   "type": "timeseries",
   "description": "#### Requirements\n`/metrics/filesystems` endpoint required for this panel.\n\n#### Panel Overview\nThis graph displays the top `$TopItems` values, based on their average across the selected time range.\n\nIt combines two Prometheus queries:\n- The first shows the average values over time for all matching entities.\n- The second uses `topk()` with `avg_over_time(... @ end())` to select the top N values, based on total usage across the full range.\n- Only entities present in both queries are shown, meaning the graph displays only the top-N performers.\n\n---\n\n#### Why It’s Set Up This Way\nPrometheus doesn’t support filtering a time series dynamically by top N across time, so this setup is a workaround.\n\nUsing `@ end()` ensures the `topk()` query selects exactly N entities based on a single, consistent snapshot taken at the end of the selected time range.  \nThis avoids the issue where the top N can vary over time and result in more than N lines being shown on the graph.\n\nWe also use `avg_over_time`, not `rate()`, because the metric is pre-aggregated — it's not a counter. Using `rate()` would give incorrect results.\n\n---\n\n#### Tips for Best Use\n- This panel works best for focused time windows, ideally 20 minutes to 3 hours.  \n  Longer ranges (e.g. days) smooth out the signal and may hide short-lived spikes.\n- Use it to quickly spot heavy resource consumers over time, then drill into specific panels or metrics.\n- If graph lines look broken or inconsistent, try zooming in or shifting the time range slightly before \"now\" to avoid scrape alignment issues.\n- Combine with filters (e.g., instance or protocol) to reduce clutter and highlight key trends.\n- For troubleshooting or spot checks, reduce the time range to 15–30 minutes for clearer insight.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg(purefb_file_systems_performance_latency_usec{env=~\"$env\", instance=~\"$instance\"}) by (name,dimension,instance)\nand\ntopk($TopItems, avg(avg_over_time(purefb_file_systems_performance_latency_usec{env=~\"$env\", instance=~\"$instance\"}[$__range] @ end() )) by (name,dimension,instance))",
     "legendFormat": "{{instance}} - {{dimension}} - {{name}}"
    }
   ]
  },
  {
   "title": "Objectstore",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopItems Avg Bucket Throughput by IO Type & $instance arrays(s)",
     "type": "timeseries",
     "description": "#### Requirements\n`/metrics/objectstore` endpoint required for this panel.\n\n#### Panel Overview\nThis graph displays the top `$TopItems` values, based on their average across the selected time range.\n\nIt combines two Prometheus queries:\n- The first shows the average values over time for all matching entities.\n- The second uses `topk()` with `avg_over_time(... @ end())` to select the top N values, based on total usage across the full range.\n- Only entities present in both queries are shown, meaning the graph displays only the top-N performers.\n\n---\n\n#### Why It’s Set Up This Way\nPrometheus doesn’t support filtering a time series dynamically by top N across time, so this setup is a workaround.\n\nUsing `@ end()` ensures the `topk()` query selects exactly N entities based on a single, consistent snapshot taken at the end of the selected time range.  \nThis avoids the issue where the top N can vary over time and result in more than N lines being shown on the graph.\n\nWe also use `avg_over_time`, not `rate()`, because the metric is pre-aggregated — it's not a counter. Using `rate()` would give incorrect results.\n\n---\n\n#### Tips for Best Use\n- This panel works best for focused time windows, ideally 20 minutes to 3 hours.  \n  Longer ranges (e.g. days) smooth out the signal and may hide short-lived spikes.\n- Use it to quickly spot heavy resource consumers over time, then drill into specific panels or metrics.\n- If graph lines look broken or inconsistent, try zooming in or shifting the time range slightly before \"now\" to avoid scrape alignment issues.\n- Combine with filters (e.g., instance or protocol) to reduce clutter and highlight key trends.\n- For troubleshooting or spot checks, reduce the time range to 15–30 minutes for clearer insight.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "avg(purefb_buckets_performance_bandwidth_bytes{env=~\"$env\", instance=~\"$instance\"}) by (name,instance,dimension)\nand\ntopk($TopItems, avg(avg_over_time(purefb_buckets_performance_bandwidth_bytes{env=~\"$env\", instance=~\"$instance\"}[$__range] @end () )) by (name,instance,dimension))",
       "legendFormat": "{{instance}} - {{dimension}} - {{name}}"
      }
     ]
    },
    {
     "title": "Top $TopItems Avg Bucket Latency by IO Type & $instance arrays(s)",
     "type": "timeseries",
     "description": "#### Requirements\n`/metrics/objectstore` endpoint required for this panel.\n\n#### Panel Overview\nThis graph displays the top `$TopItems` values, based on their average across the selected time range.\n\nIt combines two Prometheus queries:\n- The first shows the average values over time for all matching entities.\n- The second uses `topk()` with `avg_over_time(... @ end())` to select the top N values, based on total usage across the full range.\n- Only entities present in both queries are shown, meaning the graph displays only the top-N performers.\n\n---\n\n#### Why It’s Set Up This Way\nPrometheus doesn’t support filtering a time series dynamically by top N across time, so this setup is a workaround.\n\nUsing `@ end()` ensures the `topk()` query selects exactly N entities based on a single, consistent snapshot taken at the end of the selected time range.  \nThis avoids the issue where the top N can vary over time and result in more than N lines being shown on the graph.\n\nWe also use `avg_over_time`, not `rate()`, because the metric is pre-aggregated — it's not a counter. Using `rate()` would give incorrect results.\n\n---\n\n#### Tips for Best Use\n- This panel works best for focused time windows, ideally 20 minutes to 3 hours.  \n  Longer ranges (e.g. days) smooth out the signal and may hide short-lived spikes.\n- Use it to quickly spot heavy resource consumers over time, then drill into specific panels or metrics.\n- If graph lines look broken or inconsistent, try zooming in or shifting the time range slightly before \"now\" to avoid scrape alignment issues.\n- Combine with filters (e.g., instance or protocol) to reduce clutter and highlight key trends.\n- For troubleshooting or spot checks, reduce the time range to 15–30 minutes for clearer insight.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "avg(purefb_buckets_performance_latency_usec{env=~\"$env\", instance=~\"$instance\"}) by (name,dimension,instance)\nand\ntopk($TopItems, avg(avg_over_time(purefb_buckets_performance_latency_usec{env=~\"$env\", instance=~\"$instance\"}[$__range] @end () )) by (name,dimension,instance))",
       "legendFormat": "{{instance}} - {{dimension}} - {{name}}"
      }
     ]
    }
   ]
  },
  { "title": "Array Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Avg Latency by $instance array(s) & $protocol protocol(s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg(purefb_array_performance_latency_usec{instance=~\"^$instance\",env=~\"^$env\",dimension=\"usec_per_read_op\"})",
     "legendFormat": "usec_per_read_op"
    },
    {
     "expr": "avg(purefb_array_performance_latency_usec{instance=~\"^$instance\",env=~\"^$env\",dimension=\"usec_per_write_op\"})",
     "legendFormat": "usec_per_write_op"
    },
    {
     "expr": "avg(purefb_array_performance_latency_usec{instance=~\"^$instance\",env=~\"^$env\",dimension=\"usec_per_other_op\"})",
     "legendFormat": "usec_per_other_op"
    }
   ]
  },
  {
   "title": "Avg IOPS by $instance array(s) & $protocol protocol(s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "avg(purefb_array_performance_throughput_iops{instance=~\"^$instance\",env=~\"^$env\",dimension=\"reads_per_sec\"})",
     "legendFormat": "reads_per_sec"
    },
    {
     "expr": "avg(purefb_array_performance_throughput_iops{instance=~\"^$instance\",env=~\"^$env\",dimension=\"writes_per_sec\"})",
     "legendFormat": "writes_per_sec"
    },
    {
     "expr": "avg(purefb_array_performance_throughput_iops{instance=~\"^$instance\",env=~\"^$env\",dimension=\"others_per_sec\"})",
     "legendFormat": "other_per_sec"
    }
   ]
  },
  {
   "title": "Avg Bandwidth by $instance array(s) & $protocol protocol(s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "avg(purefb_array_performance_bandwidth_bytes{instance=~\"^$instance\",env=~\"^$env\", dimension=\"read_bytes_per_sec\", protocol=~\"$protocol\"})",
     "legendFormat": "read_bytes_per_sec"
    },
    {
     "expr": "avg(purefb_array_performance_bandwidth_bytes{instance=~\"^$instance\",env=~\"^$env\", dimension=\"write_bytes_per_sec\", protocol=~\"$protocol\"})",
     "legendFormat": "write_bytes_per_sec"
    },
    {
     "expr": "avg(purefb_array_performance_bandwidth_bytes{instance=~\"^$instance\",env=~\"^$env\", dimension=\"other_bytes_per_sec\", protocol=~\"$protocol\"})",
     "legendFormat": "other_bytes_per_sec"
    }
   ]
  },
  { "title": "Array Capacity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Capacity Utilization by Type & $instance array(s)",
   "type": "timeseries",
   "description": "Recommended for single array only.\n\nPanel will display \"No Data\" until there is at least 12 hours of data in the data source as this panel displays the last 90 days at 12 hour intervals.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(purefb_array_space_bytes{instance=~\"^$instance\",env=~\"^$env\",type=\"array\",space=~\"total_physical|capacity\"}) by (space)\n#\"using sum() to show total of all arrays\"",
     "legendFormat": "{{space}}"
    },
    {
     "expr": "avg(purefb_array_space_data_reduction_ratio{instance=~\"^$instance\",env=~\"^$env\",type=\"array\"}) ",
     "legendFormat": "Array DRR"
    }
   ]
  }
 ]
}