{
 "title": "Tenant VM  Storage Dashboard",
 "description": "Provides a drill-down overview of a volume.",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(openstack_identity_up,os_region)"
    }
   },
   {
    "name": "region",
    "label": "Region",
    "query": {
     "query": "label_values(purefa_info,os_region)"
    }
   },
   {
    "name": "project",
    "label": "project",
    "query": {
     "query": "label_values({job=\"libvirt_exporter\", os_region=\"$region\", __name__=~\"libvirt_domain_info_meta|libvirt_domain_openstack_info\"},project_name)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "query_result(openstack_nova_server_status{os_region=\"$region\", tenant_id=\"$tenant_id\"})"
    }
   },
   {
    "name": "array",
    "label": "Array",
    "query": {
     "query": "label_values(purefa_info{os_region=~\"$region\"},instance)"
    }
   },
   {
    "name": "volume",
    "label": "volume",
    "query": {
     "query": "label_values(openstack_cinder_volume_gb{os_region=\"$region\", server_id=\"$instance\"},id)"
    }
   },
   { "name": "pool", "label": "Pool", "query": "default" },
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "tenant_id",
    "label": "tenant_id",
    "query": {
     "query": "label_values(openstack_cinder_limits_volume_max_gb{os_region=\"$region\", tenant=\"$project\"},tenant_id)"
    }
   },
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "volume_name",
    "label": "volume_name",
    "query": {
     "query": "label_values(openstack_cinder_volume_gb{os_region=\"$region\", id=\"$volume\"},name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Volume Stats: $volume_name ($volume)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Volume Capacity",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "purefa_volume_space_bytes{name=\"volume-$volume-cinder\",space=\"total_provisioned\"}",
     "legendFormat": "Size"
    },
    {
     "expr": "purefa_volume_space_bytes{name=\"volume-$volume-cinder\",space=\"total_physical\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "purefa_volume_space_bytes{name=\"volume-$volume-cinder\",space=\"snapshots\"}",
     "legendFormat": "Snapshot Used"
    }
   ]
  },
  {
   "title": "Max Read IOPS",
   "type": "stat",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max_over_time(purefa_volume_performance_throughput_iops{name=\"volume-$volume-cinder\",dimension=\"reads_per_sec\"}[$__range])",
     "legendFormat": "Max Read IOPS"
    }
   ]
  },
  {
   "title": "Max Write IOPS",
   "type": "stat",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max_over_time(purefa_volume_performance_throughput_iops{name=\"volume-$volume-cinder\",dimension=\"writes_per_sec\"}[$__range])",
     "legendFormat": "Max Write IOPS"
    }
   ]
  },
  {
   "title": "Volume Read IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "purefa_volume_performance_throughput_iops{name=\"volume-$volume-cinder\",dimension=\"reads_per_sec\"}",
     "legendFormat": "Read IOPS"
    }
   ]
  },
  {
   "title": "Volume Write IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "purefa_volume_performance_throughput_iops{name=\"volume-$volume-cinder\",dimension=\"writes_per_sec\"}",
     "legendFormat": "Write IOPS"
    }
   ]
  },
  {
   "title": "Volume Read Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "purefa_volume_performance_latency_usec{name=\"volume-$volume-cinder\",dimension=\"usec_per_read_op\"} / 1000",
     "legendFormat": "Read latency"
    }
   ]
  },
  {
   "title": "Volume Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "purefa_volume_performance_latency_usec{name=\"volume-$volume-cinder\",dimension=\"usec_per_write_op\"} / 1000",
     "legendFormat": "Write latency"
    }
   ]
  },
  {
   "title": "Volume Read bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "purefa_volume_performance_bandwidth_bytes{name=\"volume-$volume-cinder\",dimension=\"read_bytes_per_sec\"}",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Volume Write bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "purefa_volume_performance_bandwidth_bytes{name=\"volume-$volume-cinder\",dimension=\"write_bytes_per_sec\"}",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Average Read Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "purefa_volume_performance_average_bytes{name=\"volume-$volume-cinder\",dimension=\"bytes_per_read\"}",
     "legendFormat": "Read size"
    }
   ]
  },
  {
   "title": "Average Write Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "purefa_volume_performance_average_bytes{name=\"volume-$volume-cinder\",dimension=\"bytes_per_write\"}",
     "legendFormat": "Write size"
    }
   ]
  },
  {
   "title": "Volume Latency Heatmap (5m avg)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "purefa_volume_performance_latency_usec{name=\"volume-$volume-cinder\",dimension=\"usec_per_write_op\"}",
     "legendFormat": "Write"
    },
    {
     "expr": "purefa_volume_performance_latency_usec{name=\"volume-$volume-cinder\",dimension=\"usec_per_read_op\"}",
     "legendFormat": "Read"
    }
   ]
  }
 ]
}