{
 "title": "VMware Cluster Licensing",
 "description": "Shows licence core usage per cluster vs expectation",
 "tags": [
  "vmware",
  "folder-vmware"
 ],
 "time": { "from": "now-7d", "to": "now-10m" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "DC",
    "label": "DC Name",
    "query": {
     "query": "label_values(vmware_host_hardware_info,dc_name)"
    }
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(vmware_host_hardware_info{dc_name=~\"$DC\"},vmware_cluster_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Cluster Licensable CPU Count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(\r\n  vmware_host_num_cpu{vmware_cluster_name=~\"$cluster\",dc_name=~\"$DC\"}\r\n  )\r\n  -\r\n  sum(vmware_host_num_cpu{vmware_cluster_name=~\"$cluster\",dc_name=~\"$DC\"}\r\n  * on(instance, host_name) group_left()\r\n  (vmware_host_maintenance_mode == 1) or vector(0)\r\n)\r\n",
     "legendFormat": "Physical CPU Count"
    }
   ]
  },
  {
   "title": "License Cost Per Year",
   "type": "stat",
   "description": "Price of Licenses per year, list price",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(\r\n  vmware_host_num_cpu{vmware_cluster_name=~\"$cluster\",dc_name=~\"$DC\"}\r\n  )\r\n  -\r\n  sum(vmware_host_num_cpu{vmware_cluster_name=~\"$cluster\"}\r\n  * on(instance, host_name) group_left()\r\n  (vmware_host_maintenance_mode == 1) or vector(0)\r\n))\r\n*350\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "License Cost Change (over Time period)",
   "type": "stat",
   "description": "Price of Licenses per year, list price",
   "gridPos": { "h": 5, "w": 5, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "(sum(\r\n  vmware_host_num_cpu{vmware_cluster_name=~\"$cluster\",dc_name=~\"$DC\"}\r\n  )\r\n  -\r\n  sum(vmware_host_num_cpu{vmware_cluster_name=~\"$cluster\"}\r\n  * on(instance, host_name) group_left()\r\n  (vmware_host_maintenance_mode == 1) or vector(0)\r\n))\r\n*350\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Host In Maintenance",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(vmware_host_maintenance_mode{vmware_cluster_name=~\"$cluster\",dc_name=~\"$DC\"}==1) OR vector(0)"
    }
   ]
  },
  {
   "title": "Host Number",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(vmware_host_connection_state{vmware_cluster_name=~\"$cluster\",dc_name=~\"$DC\"})"
    }
   ]
  },
  { "title": "$cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 }, "repeat": "cluster" },
  {
   "title": "Cluster Licensable CPU Count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(\r\n  vmware_host_num_cpu{vmware_cluster_name=\"$cluster\",dc_name=~\"$DC\"}\r\n  )\r\n  -\r\n  sum(vmware_host_num_cpu{vmware_cluster_name=\"$cluster\",dc_name=~\"$DC\"}\r\n  * on(instance, host_name) group_left()\r\n  (vmware_host_maintenance_mode == 1) or vector(0)\r\n)\r\n",
     "legendFormat": "Physical CPU Count"
    }
   ]
  },
  {
   "title": "License Cost Per Year",
   "type": "stat",
   "description": "Price of Licenses per year, list price",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(\r\n  vmware_host_num_cpu{vmware_cluster_name=\"$cluster\",dc_name=~\"$DC\"}\r\n  )\r\n  -\r\n  sum(vmware_host_num_cpu{vmware_cluster_name=\"$cluster\",dc_name=~\"$DC\"}\r\n  * on(instance, host_name) group_left()\r\n  (vmware_host_maintenance_mode == 1) or vector(0)\r\n))\r\n*350\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "License Cost Change",
   "type": "stat",
   "description": "Price of Licenses per year, list price",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "(sum(\r\n  vmware_host_num_cpu{vmware_cluster_name=\"$cluster\",dc_name=~\"$DC\"}\r\n  )\r\n  -\r\n  sum(vmware_host_num_cpu{vmware_cluster_name=\"$cluster\",dc_name=~\"$DC\"}\r\n  * on(instance, host_name) group_left()\r\n  (vmware_host_maintenance_mode == 1) or vector(0)\r\n))\r\n*350\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Host Number",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(vmware_host_connection_state{vmware_cluster_name=~\"$cluster\",dc_name=~\"$DC\"})"
    }
   ]
  },
  {
   "title": "Host In Maintenance",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(vmware_host_maintenance_mode{vmware_cluster_name=~\"$cluster\",dc_name=~\"$DC\"}==1) OR vector(0)"
    }
   ]
  },
  {
   "title": "Cluster CPU usage %",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(vmware_host_cpu_usagemhz_average{vmware_cluster_name=~\"$cluster\",dc_name=~\"$DC\"}) * 100 / sum(vmware_host_cpu_max{vmware_cluster_name=~\"$cluster\",dc_name=~\"$DC\"})",
     "legendFormat": "{{ $cluster }}"
    }
   ]
  },
  {
   "title": "Cluster Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum((vmware_host_memory_usage{vmware_cluster_name=~\"$cluster\",dc_name=~\"$DC\"}) * 100) / sum(vmware_host_memory_max{vmware_cluster_name=~\"$cluster\",dc_name=~\"$DC\"})",
     "legendFormat": "{{ $cluster }}"
    }
   ]
  }
 ]
}