{
 "title": "VMware Cluster",
 "description": "Overview of all VMware vCenter Clusters",
 "tags": [ "folder-vmware" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "DC",
    "label": "DC Name",
    "query": {
     "query": "label_values(vmware_host_hardware_info,dc_name)"
    }
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(vmware_host_hardware_info{dc_name=~\"$DC\"},vmware_cluster_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "vCenter SSL ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "SSL Expiry",
   "type": "table",
   "gridPos": { "h": 14, "w": 23, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "floor(\n  (\n    label_replace(\n      ( max_over_time(probe_ssl_earliest_cert_expiry{job=\"blackbox_vcenter_ssl\"}[36h])\n        or\n        max_over_time(probe_ssl_last_chain_expiry_timestamp_seconds{job=\"blackbox_vcenter_ssl\"}[36h])\n      ),\n      \"vcenter\", \"$1\", \"instance\", \"https?://([^:/]+)\"\n    ) - time()\n  ) / 86400\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Cpu Core Capacity",
   "type": "stat",
   "description": "CPU core capacity, enabled hosts only",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  vmware_host_num_cpu{vmware_cluster_name=~\"$cluster\"} \n  unless \n  on(host_name) vmware_host_maintenance_mode{vmware_cluster_name=~\"$cluster\"} == 1\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cpu Capacity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  vmware_host_cpu_max{vmware_cluster_name=~\"$cluster\"}\n  unless on(host_name) (vmware_host_maintenance_mode == 1)\n) * 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Capacity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  vmware_host_memory_max{vmware_cluster_name=~\"$cluster\"}\n  unless on(host_name) (vmware_host_maintenance_mode == 1)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Host Number",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(vmware_host_connection_state{vmware_cluster_name=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Host In Maintenance",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(vmware_host_maintenance_mode{vmware_cluster_name=~\"$cluster\"}==1) OR vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VMs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(vmware_vm_power_state{vmware_cluster_name=~\"$cluster\"}==1) OR vector(0)",
     "legendFormat": "UP"
    },
    {
     "expr": "count(\n  vmware_vm_power_state{\n    vmware_cluster_name=~\"$cluster\",\n    vm_name!~\"^ubuntu.*\"\n  } == 0\n) OR vector(0)",
     "legendFormat": "DOWN"
    }
   ]
  },
  {
   "title": "Cluster CPU usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (vmware_cluster_name)(\n  vmware_host_cpu_usagemhz_average{vmware_cluster_name=~\"$cluster\"}\n  unless on (host_name) (vmware_host_maintenance_mode == 1)\n) * 100\n/\nsum by (vmware_cluster_name)(\n  vmware_host_cpu_max{vmware_cluster_name=~\"$cluster\"}\n  unless on (host_name) (vmware_host_maintenance_mode == 1)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max VM Cpu Ready on Cluster",
   "type": "gauge",
   "description": "The time your VM is waiting in line to use the CPU on the host.",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(vmware_vm_cpu_ready_summation{vmware_cluster_name=~\"$cluster\"})/ 200",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max VM Cpu Co-Stop on Cluster",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(vmware_vm_cpu_costop_summation{vmware_cluster_name=~\"$cluster\"})/200",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Host CPU usage %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n  sum by (host_name) (vmware_host_cpu_usagemhz_average{vmware_cluster_name=~\"$cluster\"})\n/\n  sum by (host_name) (vmware_host_cpu_max{vmware_cluster_name=~\"$cluster\"})\n) * 100",
     "legendFormat": "{{ $cluster }}"
    }
   ]
  },
  {
   "title": "Cluster Memory usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  vmware_host_memory_usage{vmware_cluster_name=~\"$cluster\"}\n  unless on (host_name) (vmware_host_maintenance_mode == 1)\n) * 100\n/\nsum(\n  vmware_host_memory_max{vmware_cluster_name=~\"$cluster\"}\n  unless on (host_name) (vmware_host_maintenance_mode == 1)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max VM Ballooning",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(vmware_vm_mem_vmmemctl_average{vmware_cluster_name=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Provisioned Memory in cluster",
   "type": "gauge",
   "description": "Percentage of total provisioned memory for Powered on VM's",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\nsum by (dc_name, vmware_cluster_name) (\n  (vmware_vm_memory_max or vmware_vm_memory_size_mb)\n  * on (vm_name) group_left () (vmware_vm_power_state == 1)\n  * on (host_name) group_left (dc_name, vmware_cluster_name)\n    vmware_host_hardware_info{dc_name=~\"$DC\", vmware_cluster_name=~\"$cluster\"}\n)\n/ sum by (dc_name, vmware_cluster_name) (\n  (\n    (vmware_host_memory_max or vmware_host_memory_total or vmware_host_memory_capacity)\n    unless on (host_name) (vmware_host_maintenance_mode == 1)\n  )\n  * on (host_name) group_left (dc_name, vmware_cluster_name)\n    vmware_host_hardware_info{dc_name=~\"$DC\", vmware_cluster_name=~\"$cluster\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Provisioned CPU in cluster",
   "type": "gauge",
   "description": "Percentage of total provisioned memory for Powered on VM's",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\nsum by (dc_name, vmware_cluster_name) (\n  (vmware_vm_num_cpu or vmware_vm_cpu_count or vmware_vm_vcpu or vmware_vm_vcpu_count)\n  * on (vm_name) group_left () (vmware_vm_power_state == 1)\n  * on (host_name) group_left (dc_name, vmware_cluster_name)\n    vmware_host_hardware_info{dc_name=~\"$DC\", vmware_cluster_name=~\"$cluster\"}\n)\n/ sum by (dc_name, vmware_cluster_name) (\n  (\n    vmware_host_num_cpu\n    unless on (host_name) (vmware_host_maintenance_mode == 1)\n  )\n  * on (host_name) group_left (dc_name, vmware_cluster_name)\n    vmware_host_hardware_info{dc_name=~\"$DC\", vmware_cluster_name=~\"$cluster\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster RAM Usage %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n  sum by (host_name) (vmware_host_memory_usage{vmware_cluster_name=~\"$cluster\"})\n/\n  sum by (host_name) (vmware_host_memory_max{vmware_cluster_name=~\"$cluster\"})\n) * 100",
     "legendFormat": "{{ $cluster }}"
    }
   ]
  },
  { "title": "Hypervisors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Cluster Usage",
   "type": "table",
   "gridPos": { "h": 27, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "sum by (host_name,vmware_cluster_name,dc_name) (vmware_host_cpu_max{vmware_cluster_name=~\"$cluster\"})*1000000",
     "legendFormat": "VCPU Max Hz"
    },
    {
     "expr": "sum by (host_name,vmware_cluster_name,dc_name) (vmware_host_cpu_usage{vmware_cluster_name=~\"$cluster\"})*1000000",
     "legendFormat": "VPCU USAGE Hz"
    },
    {
     "expr": "sum by (host_name,vmware_cluster_name,dc_name) (vmware_host_memory_max{vmware_cluster_name=~\"$cluster\"})",
     "legendFormat": "Memory Max"
    },
    {
     "expr": "sum by (host_name,vmware_cluster_name,dc_name,host) (label_replace(vmware_host_memory_usage{vmware_cluster_name=~\"$cluster\"},\"host\",\"$1\",\"host_name\",\"([^.]+)(.+)\"))",
     "legendFormat": "__auto"
    },
    {
     "expr": "(\n  sum by (host_name, vmware_cluster_name, dc_name)(vmware_host_maintenance_mode{vmware_cluster_name=~\"$cluster\"})\n  +\n  on (host_name) group_left(hardware_cpu_model, hardware_model)\n  0 * vmware_host_hardware_info{vmware_cluster_name=~\"$cluster\"}\n)\n+\non (host_name) group_left(build, version)\n0 * vmware_host_product_info{vmware_cluster_name=~\"$cluster\"}",
     "legendFormat": "Status"
    },
    {
     "expr": "count by (host_name,vmware_cluster_name,dc_name) (vmware_vm_power_state{vmware_cluster_name=~\"$cluster\"}==1)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (host_name,vmware_cluster_name,dc_name) (vmware_host_num_cpu{vmware_cluster_name=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum((vmware_host_memory_usage{vmware_cluster_name=~\"$cluster\"}) * 100) / sum(vmware_host_memory_max{vmware_cluster_name=~\"$cluster\"})",
     "legendFormat": "{{ $cluster }}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 },
   "collapsed": true,
   "panels": [
    {
     "title": "Max VM Cpu Ready on Cluster",
     "type": "timeseries",
     "description": "The time your VM is waiting in line to use the CPU on the host.",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 126 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(avg(vmware_vm_cpu_ready_summation{vmware_cluster_name=~\"$cluster\"}/200) by(vmware_cluster_name,vm_name) + topk(20,avg(vmware_vm_cpu_ready_summation{vmware_cluster_name=~\"$cluster\"}/200) by(vmware_cluster_name,vm_name) @ end()))/2",
       "legendFormat": "{{ vmware_cluster_name }} - {{ vm_name }}"
      }
     ]
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Top  Disk Read And Write VMs",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "avg(vmware_vm_disk_read_average{vmware_cluster_name=~\"$cluster\"}) by(vmware_cluster_name,vm_name) + topk(10,avg(vmware_vm_disk_read_average{vmware_cluster_name=~\"$cluster\"}) by(vmware_cluster_name,vm_name) )@ end()/2",
     "legendFormat": "{{ vmware_cluster_name }} - {{ vm_name }} Read"
    },
    {
     "expr": "avg(vmware_vm_disk_write_average{vmware_cluster_name=~\"$cluster\"}) by(vmware_cluster_name,vm_name) + topk(10,avg(vmware_vm_disk_write_average{vmware_cluster_name=~\"$cluster\"}) by(vmware_cluster_name,vm_name) )@ end()/2",
     "legendFormat": "{{ vmware_cluster_name }} - {{ vm_name }} Write"
    },
    {
     "expr": "avg(vmware_vm_disk_maxTotalLatency_latest{vmware_cluster_name=~\"$cluster\"}) by(vmware_cluster_name,vm_name) + topk(10,avg(vmware_vm_disk_maxTotalLatency_latest{vmware_cluster_name=~\"$cluster\"}) by(vmware_cluster_name,vm_name) )@ end()/2",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Disk Read And Write",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "sum(vmware_vm_disk_read_average{vmware_cluster_name=~\"$cluster\"})",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(vmware_vm_disk_write_average{vmware_cluster_name=~\"$cluster\"})",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "VM Disk Latency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "avg(vmware_vm_disk_maxTotalLatency_latest{vmware_cluster_name=~\"$cluster\"}) by(vmware_cluster_name,vm_name) + topk(10,avg(vmware_vm_disk_maxTotalLatency_latest{vmware_cluster_name=~\"$cluster\"}) by(vmware_cluster_name,vm_name) )@ end()/2",
     "legendFormat": "{{ vmware_cluster_name }} - {{ vm_name }}"
    }
   ]
  },
  {
   "title": " Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 111 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster Network Usage",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 422 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "targets": [
      {
       "expr": "sum(vmware_vm_net_received_average{vmware_cluster_name=~\"$cluster\"})",
       "legendFormat": " RX"
      },
      {
       "expr": "sum(vmware_vm_net_transmitted_average{vmware_cluster_name=~\"$cluster\"})",
       "legendFormat": "TX"
      }
     ]
    },
    {
     "title": "Cluster Network Broadcast RX/TX",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 541 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "targets": [
      {
       "expr": "sum(vmware_vm_net_broadcastRx_summation{vmware_cluster_name=~\"$cluster\"})",
       "legendFormat": "RX"
      },
      {
       "expr": "sum(vmware_vm_net_broadcastTx_summation{vmware_cluster_name=~\"$cluster\"})",
       "legendFormat": "TX"
      }
     ]
    },
    {
     "title": "Host Network Multicast RX",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 556 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "targets": [
      {
       "expr": "sum(vmware_vm_net_multicastRx_summation{vmware_cluster_name=~\"$cluster\"})",
       "legendFormat": "RX"
      },
      {
       "expr": "sum(vmware_vm_net_multicastTx_summation{vmware_cluster_name=~\"$cluster\"})",
       "legendFormat": "TX"
      }
     ]
    }
   ]
  }
 ]
}