{
 "title": "VMware2Openstack",
 "tags": [ "folder-openstack" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(openstack_identity_groups,os_region)"
    }
   },
   {
    "name": "project",
    "query": {
     "query": "label_values(openstack_identity_project_info{os_region=~\"$cluster\"},name)"
    }
   },
   {
    "name": "site",
    "query": {
     "query": "label_values(openstack_identity_project_info{os_region=~\"$cluster\"},name)"
    }
   },
   {
    "name": "tenant_id",
    "query": {
     "query": "label_values(openstack_cinder_limits_volume_max_gb{tenant=\"$project\", os_region=\"$cluster\"},tenant_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Project qouta",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "VM",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "openstack_nova_limits_instances_max{tenant_id=\"$tenant_id\",os_region=\"$cluster\"}",
       "legendFormat": "Quota"
      },
      {
       "expr": "openstack_nova_limits_instances_used{tenant_id=\"$tenant_id\",os_region=\"$cluster\"}",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 6, "x": 5, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "openstack_nova_limits_vcpus_max{tenant_id=\"$tenant_id\",os_region=\"$cluster\"}",
       "legendFormat": "Quota"
      },
      {
       "expr": "openstack_nova_limits_vcpus_used{tenant_id=\"$tenant_id\",os_region=\"$cluster\"}",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "RAM",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 6, "x": 11, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "openstack_nova_limits_memory_max{tenant_id=\"$tenant_id\",os_region=\"$cluster\"}",
       "legendFormat": "Quota"
      },
      {
       "expr": "openstack_nova_limits_memory_used{tenant_id=\"$tenant_id\",os_region=\"$cluster\"}",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "Volume",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "openstack_cinder_limits_volume_max_gb{tenant_id=\"$tenant_id\",os_region=\"$cluster\"}",
       "legendFormat": "Quota"
      },
      {
       "expr": "openstack_cinder_limits_volume_used_gb{tenant_id=\"$tenant_id\",os_region=\"$cluster\"}",
       "legendFormat": "Used"
      }
     ]
    }
   ]
  },
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Annual saving VMware Equivalent Infrastructure License Cost",
   "type": "stat",
   "description": "Estimated cost of running current OpenStack workloads on VMware infrastructure. This metric calculates what the organization would pay for VMware licenses.",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_placement_resource_total{os_region=~\"$cluster\", resourcetype=\"VCPU\"})/2 * 350",
     "legendFormat": "VM license cost change"
    }
   ]
  },
  {
   "title": "VMware License Cost Change (over Time period)",
   "type": "stat",
   "description": "Price of Licenses change a year, list price",
   "gridPos": { "h": 6, "w": 7, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "(sum(\r\n  vmware_host_num_cpu{dc_name=~\"(?i).*${site}.*\"}\r\n  )\r\n  -\r\n  sum(vmware_host_num_cpu{dc_name=~\"(?i).*${site}.*\"}\r\n  * on(instance, host_name) group_left()\r\n  (vmware_host_maintenance_mode{dc_name=~\"(?i).*${site}.*\"} == 1) \r\n)) * 350",
     "legendFormat": "VM license cost change"
    }
   ]
  },
  {
   "title": "vCPU allocation ratio",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 11, "y": 2 },
   "fieldConfig": { "defaults": { "unit": ":1" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$C/$D", "type": "math" }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "description": "Openstack cluster RAM allocation",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(openstack_placement_resource_usage{resourcetype=\"MEMORY_MB\",os_region=~\"$cluster\"}) * 100)/\n(sum(openstack_placement_resource_total{resourcetype=\"MEMORY_MB\",os_region=~\"$cluster\"} * on(hostname) \n  (openstack_nova_agent_state{os_region=~\"$cluster\",service=\"nova-compute\"} == 1 and \n   openstack_nova_agent_state{adminState=\"enabled\",os_region=~\"$cluster\",service=\"nova-compute\"} == 1)) - \nsum(openstack_placement_resource_reserved{os_region=~\"$cluster\",resourcetype=\"MEMORY_MB\"} * on(hostname) \n  (openstack_nova_agent_state{os_region=~\"$cluster\",service=\"nova-compute\"} == 1 and \n   openstack_nova_agent_state{adminState=\"enabled\",os_region=~\"$cluster\",service=\"nova-compute\"} == 1)) - \n2*max(openstack_placement_resource_total{os_region=~\"$cluster\",resourcetype=\"MEMORY_MB\"} * on(hostname) \n  (openstack_nova_agent_state{os_region=~\"$cluster\",service=\"nova-compute\"} == 1 and \n   openstack_nova_agent_state{adminState=\"enabled\",os_region=~\"$cluster\",service=\"nova-compute\"} == 1)))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "RAM +  VMs in queue",
   "type": "stat",
   "description": "RAM Info including capacity of VMs that are in a queue. Cluster compute failure domain is 1\n\nRequired = Usage + Migration queue",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_placement_resource_total{resourcetype=\"MEMORY_MB\",os_region=~\"$cluster\"}) - \nsum(openstack_placement_resource_reserved{os_region=~\"$cluster\",resourcetype=\"MEMORY_MB\"}) - \n(sum(openstack_placement_resource_total{resourcetype=\"MEMORY_MB\",os_region=~\"$cluster\"} * on(hostname)  \n  (openstack_nova_agent_state{adminState=\"disabled\",os_region=\"$cluster\", service=\"nova-compute\"} == 1)) or vector(0))- 1*max(openstack_placement_resource_total{os_region=~\"$cluster\",resourcetype=\"MEMORY_MB\"})\n\n",
     "legendFormat": "Total"
    },
    {
     "expr": "(sum(vmware2openstack_vm_memory{site=~\"$site\"} and (0 < vmware2openstack_migration_status{site=~\"$site\"} <= 12)) + sum(openstack_placement_resource_usage{resourcetype=\"MEMORY_MB\",os_region=~\"$cluster\"})) or vector(0)",
     "legendFormat": "Required"
    }
   ]
  },
  {
   "title": "Annual savings(Internal vCPU Cost Model)",
   "type": "stat",
   "description": "Annual savings based on internal VPCU price",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((sum(vmware2openstack_vm_cpu{site=\"$site\"} and vmware2openstack_migration_status{site=\"$site\"} == 14) * 0.012644) - (sum(vmware2openstack_vm_cpu{site=\"$site\"} and vmware2openstack_migration_status{site=\"$site\"} == 14) *0.003700)) * 730 * 12 or on() vector(0)",
     "legendFormat": "Savings a year"
    }
   ]
  },
  {
   "title": "VM Migrated Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count(vmware2openstack_migration_status{site=~\"$site\"} == 13 or vmware2openstack_migration_status{site=~\"$site\"} == 14)) or vector(0)",
     "legendFormat": "Total VMs"
    }
   ]
  },
  {
   "title": "VM In progress",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 11, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(vmware2openstack_migration_status{site=\"$site\"} >= 7 and vmware2openstack_migration_status{site=\"$site\"} < 13 and vmware2openstack_migration_status{site=\"$site\"} != 8 and vmware2openstack_migration_status{site=\"$site\"} != 11) or vector(0)",
     "legendFormat": "In progress"
    }
   ]
  },
  {
   "title": "RAM  Migrated",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(vmware2openstack_vm_memory{site=\"${site}\"} and vmware2openstack_migration_status{site=\"${site}\"} >= 13)",
     "legendFormat": "RAM TOTAL"
    }
   ]
  },
  {
   "title": "VM Migration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "count(vmware2openstack_migration_status{site=\"$site\"} == 13 or vmware2openstack_migration_status{site=\"$site\"} == 14)",
     "legendFormat": "Total VMs"
    }
   ]
  },
  {
   "title": "VCPU Migrated",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 11, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(vmware2openstack_vm_cpu{site=\"${site}\"} and vmware2openstack_migration_status{site=\"${site}\"} >= 13)",
     "legendFormat": "VCPU Total"
    }
   ]
  },
  {
   "title": "Storage Migrated",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(vmware2openstack_vm_storage{site=\"${site}\"} and vmware2openstack_migration_status{site=\"${site}\"} >= 7)",
     "legendFormat": "Storage Total"
    }
   ]
  },
  {
   "title": "Migration in progress/completed",
   "type": "table",
   "gridPos": { "h": 29, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "((vmware2openstack_migration_status{site=~\"$site\"} and vmware2openstack_migrated_at{site=~\"$site\"} > ${__from:date:seconds}) * on (vm_name) group_left (os,service,team) vmware2openstack_vm_metadata{site=~\"$site\"}) <= 14",
     "legendFormat": "__auto"
    },
    {
     "expr": "vmware2openstack_vm_disks{site=~\"$site\"} and vmware2openstack_migrated_at{site=~\"$site\"} > ${__from:date:seconds}",
     "legendFormat": "__auto"
    },
    {
     "expr": "vmware2openstack_vm_storage{site=~\"$site\"} and vmware2openstack_migrated_at{site=~\"$site\"} > ${__from:date:seconds}",
     "legendFormat": "__auto"
    },
    {
     "expr": "vmware2openstack_vm_memory{site=~\"$site\"} and vmware2openstack_migrated_at{site=\"$site\"} > ${__from:date:seconds}",
     "legendFormat": "__auto"
    },
    {
     "expr": "vmware2openstack_downtime_seconds{site=~\"$site\"} and vmware2openstack_migrated_at{site=~\"$site\"} > ${__from:date:seconds}",
     "legendFormat": "__auto"
    },
    {
     "expr": "vmware2openstack_stopped_at{site=~\"$site\"} and vmware2openstack_migrated_at{site=~\"$site\"} > ${__from:date:seconds}",
     "legendFormat": "__auto"
    },
    {
     "expr": "vmware2openstack_cutover_at{site=~\"$site\"} and vmware2openstack_migrated_at{site=~\"$site\"} > ${__from:date:seconds}",
     "legendFormat": "__auto"
    },
    {
     "expr": "vmware2openstack_vm_prepare_at{site=\"$site\"} and vmware2openstack_prepare_at{site=\"$site\"} > ${__from:date:seconds}",
     "legendFormat": "__auto"
    },
    {
     "expr": "vmware2openstack_migrated_at{site=~\"$site\"} and vmware2openstack_migrated_at{site=~\"$site\"} > ${__from:date:seconds}",
     "legendFormat": "__auto"
    },
    {
     "expr": "vmware2openstack_vm_cpu{site=~\"$site\"}and vmware2openstack_prepare_at{site=~\"$site\"} > ${__from:date:seconds}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Openstack Capacity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory $cluster Openstack",
     "type": "piechart",
     "gridPos": { "h": 11, "w": 6, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(openstack_placement_resource_total{resourcetype=\"MEMORY_MB\",os_region=~\"$cluster\"}) - sum(openstack_placement_resource_reserved{os_region=~\"$cluster\",resourcetype=\"MEMORY_MB\"})",
       "legendFormat": "RAM Total"
      },
      {
       "expr": "sum(openstack_placement_resource_total{resourcetype=\"MEMORY_MB\",os_region=~\"$cluster\"}) - sum(openstack_placement_resource_usage{resourcetype=\"MEMORY_MB\",os_region=~\"$cluster\"}) - max(openstack_placement_resource_total{os_region=~\"$cluster\",resourcetype=\"MEMORY_MB\"})",
       "legendFormat": "RAM Available"
      },
      {
       "expr": "sum(openstack_placement_resource_usage{resourcetype=\"MEMORY_MB\",os_region=~\"$cluster\"})",
       "legendFormat": "RAM Used"
      }
     ]
    },
    {
     "title": "RAM",
     "type": "timeseries",
     "gridPos": { "h": 22, "w": 18, "x": 6, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "sum(openstack_placement_resource_total{resourcetype=\"MEMORY_MB\",os_region=~\"$cluster\"}) - sum(openstack_placement_resource_reserved{os_region=~\"gb4-retail\",resourcetype=\"MEMORY_MB\"}) - 2*max(openstack_placement_resource_total{os_region=~\"$cluster\",resourcetype=\"MEMORY_MB\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(openstack_placement_resource_usage{resourcetype=\"MEMORY_MB\",os_region=~\"$cluster\"})",
       "legendFormat": "Allocated"
      },
      {
       "expr": "sum(vmware2openstack_vm_memory{site=\"$site\"} and (0 < vmware2openstack_migration_status{site=\"$site\"} <= 12)) + sum(openstack_placement_resource_usage{resourcetype=\"MEMORY_MB\",os_region=~\"$cluster\"})",
       "legendFormat": "Required"
      },
      {
       "expr": "(sum(node_memory_MemTotal_bytes{os_region=~\"$cluster\",instance=~\".*-compute.*\"}) - sum(node_memory_MemFree_bytes{os_region=~\"$cluster\",instance=~\".*-compute.*\"}) - (sum(node_memory_Cached_bytes{os_region=~\"$cluster\",instance=~\".*-compute.*\"}) + sum(node_memory_Buffers_bytes{os_region=~\"$cluster\",instance=~\".*-compute.*\"})))/1024/1024",
       "legendFormat": "Usage"
      }
     ]
    },
    {
     "title": "Openstack RAM usage (libvirt)",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\n  libvirt_domain_info_maximum_memory_bytes{job=~\"libvirt_exporter\"} * on(domain) group_left(flavor,instance_name,project_name,user_name) \n  (\n    libvirt_domain_info_meta{job=~\"libvirt_exporter\",os_region=~\"$cluster\",project_name=\"$project\"} or\n    libvirt_domain_openstack_info{job=~\"libvirt_exporter\",os_region=~\"$cluster\",project_name=\"$project\"}\n  )\n) - sum(\n  libvirt_domain_memory_stats_unused_bytes{job=~\"libvirt_exporter\"} * on(domain) group_left(flavor,instance_name,project_name,user_name) \n  (\n    libvirt_domain_info_meta{job=~\"libvirt_exporter\",os_region=\"$cluster\",project_name=\"$project\"} or\n    libvirt_domain_openstack_info{job=~\"libvirt_exporter\",os_region=\"$cluster\",project_name=\"$project\"}\n  )\n) + (2.5*sum(openstack_placement_resource_reserved{os_region=~\"$cluster\",resourcetype=\"MEMORY_MB\"})*1024*1024)",
       "legendFormat": "Libvirt usage"
      }
     ]
    },
    {
     "title": "RAM(node exporter)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(node_memory_MemTotal_bytes{os_region=~\"$cluster\",instance=~\".*-compute.*\"}) - (1*max(openstack_placement_resource_total{os_region=~\"$cluster\",resourcetype=\"MEMORY_MB\"})*1024*1024)",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(node_memory_MemTotal_bytes{os_region=~\"$cluster\",instance=~\".*-compute.*\"}) - sum(node_memory_MemFree_bytes{os_region=~\"$cluster\",instance=~\".*-compute.*\"}) - (sum(node_memory_Cached_bytes{os_region=~\"$cluster\",instance=~\".*-compute.*\"}) + sum(node_memory_Buffers_bytes{os_region=~\"$cluster\",instance=~\".*-compute.*\"}))",
       "legendFormat": "Used"
      }
     ]
    }
   ]
  },
  {
   "title": "List of all VMs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(vmware2openstack_migration_status{site=\"$site\"} >= 13 and vmware2openstack_migration_status{site=\"$site\"} != 15)",
       "legendFormat": "Migrated"
      },
      {
       "expr": "count(vmware2openstack_migration_status{site=\"$site\"} >= 7 and vmware2openstack_migration_status{site=\"$site\"} < 13 and vmware2openstack_migration_status{site=\"$site\"} != 8) or vector(0)",
       "legendFormat": "Migration"
      },
      {
       "expr": "count(vmware2openstack_migration_status{site=\"$site\"} <= 6) or vector(0)",
       "legendFormat": "Queue"
      },
      {
       "expr": "count(vmware2openstack_migration_status{site=\"$site\"} == 8) + count(vmware2openstack_migration_status{site=~\"$site\"} == 11) or vector(0)",
       "legendFormat": "Sync Failed"
      },
      {
       "expr": "count(vmware2openstack_migration_status{site=\"$site\"} == 1) or vector(0)",
       "legendFormat": "Prepare"
      }
     ]
    },
    {
     "title": "Pre-migration readiness and failed",
     "type": "table",
     "gridPos": { "h": 24, "w": 24, "x": 0, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "((0 < vmware2openstack_migration_status{site=\"$site\"} <= 8) or (vmware2openstack_migration_status{site=\"$site\"} == 11)) * on (vm_name) group_left (os,service,team) vmware2openstack_vm_metadata{site=\"$site\"}",
       "legendFormat": "__auto"
      },
      { "expr": "vmware2openstack_vm_disks", "legendFormat": "__auto" },
      { "expr": "vmware2openstack_vm_storage", "legendFormat": "__auto" },
      { "expr": "vmware2openstack_vm_memory", "legendFormat": "__auto" },
      {
       "expr": "vmware2openstack_downtime_seconds",
       "legendFormat": "__auto"
      },
      {
       "expr": "vmware2openstack_vm_precheck_at",
       "legendFormat": "__auto"
      },
      { "expr": "vmware2openstack_stopped_at", "legendFormat": "__auto" },
      { "expr": "vmware2openstack_cutover_at", "legendFormat": "__auto" },
      { "expr": "vmware2openstack_vm_prepare_at", "legendFormat": "__auto" },
      { "expr": "vmware2openstack_migrated_at", "legendFormat": "__auto" },
      { "expr": "vmware2openstack_vm_cpu", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "All VMs ",
     "type": "table",
     "description": "List of Migrated and Ready for migration VMs",
     "gridPos": { "h": 30, "w": 24, "x": 0, "y": 107 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "vmware2openstack_migration_status{site=\"$site\"} * on (vm_name) group_left (os,service,team) vmware2openstack_vm_metadata{site=\"$site\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "vmware2openstack_vm_disks{site=\"$site\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "vmware2openstack_vm_storage{site=\"$site\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "vmware2openstack_vm_memory{site=\"$site\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "vmware2openstack_downtime_seconds{site=\"$site\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "vmware2openstack_vm_precheck_at{site=\"$site\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "vmware2openstack_stopped_at{site=\"$site\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "vmware2openstack_cutover_at{site=\"$site\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "vmware2openstack_vm_prepare_at{site=\"$site\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "vmware2openstack_migrated_at{site=\"$site\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "vmware2openstack_vm_cpu{site=\"$site\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Cost savings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "Annual Cost savings based on internal VPCU price",
     "type": "timeseries",
     "description": "Annual Cost savings",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 294 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "expr": "((sum(vmware2openstack_vm_cpu{site=\"$site\"} and vmware2openstack_migration_status{site=\"$site\"} >= 13) * 0.012634) - (sum(vmware2openstack_vm_cpu{site=\"$site\"} and vmware2openstack_migration_status{site=\"$site\"} >= 13) *0.004654)) * 730 or on() vector(0)",
       "legendFormat": "Savings a month"
      },
      {
       "expr": "((sum(vmware2openstack_vm_cpu{site=\"$site\"} and vmware2openstack_migration_status{site=\"$site\"} >= 13) * 0.012634) - (sum(vmware2openstack_vm_cpu{site=\"$site\"} and vmware2openstack_migration_status{site=\"$site\"} >= 13) *0.004654)) * 730 * 12 or on() vector(0)",
       "legendFormat": "Savings a year"
      }
     ]
    },
    {
     "title": "Cost savings a month internal VCPU price",
     "type": "timeseries",
     "description": "Cost savings a month based on VPCU price",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 306 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "expr": "((sum(vmware2openstack_vm_cpu{site=\"$site\"} and vmware2openstack_migration_status{site=\"$site\"} == 14) * 0.012634) - (sum(vmware2openstack_vm_cpu{site=\"$site\"} and vmware2openstack_migration_status{site=\"$site\"} == 14) *0.004654)) * 730",
       "legendFormat": "Savings a month"
      }
     ]
    }
   ]
  }
 ]
}