{
 "title": "Vmware Virtual Machine Top 10",
 "tags": [ "folder-vmware" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "DC",
    "label": "DC Name",
    "query": {
     "query": "label_values(vmware_host_hardware_info,dc_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Top 10 Virtual Machine Write's",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "topk(\n  10,\n  sum by (vm_name) (\n    max_over_time(\n      vmware_vm_disk_write_average{dc_name=~\"${DC:regex}\"}[$__range]\n    )\n  )\n)",
     "legendFormat": "Total Writes {{vm_name}}"
    }
   ]
  },
  {
   "title": "Top 10 Virtual Machine Read's",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "topk(\n  10,\n  sum by (vm_name) (\n    max_over_time(vmware_vm_disk_read_average{dc_name=~\"${DC:regex}\"}[$__range])\n  )\n)",
     "legendFormat": "Read Usage {{vm_name}}"
    }
   ]
  },
  {
   "title": "Top 10 Virtual Machine CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(\n  10,\n  clamp_max(\n    (\n      avg by (vm_name) (\n        avg_over_time(vmware_vm_cpu_usagemhz_average{dc_name=~\"${DC:regex}\"}[$__range])\n      )\n      /\n      max by (vm_name) (\n        vmware_vm_max_cpu_usage{dc_name=~\"${DC:regex}\"}\n      )\n    ) * 100,\n    100\n  )\n)",
     "legendFormat": "CPU usage {{vm_name}}"
    }
   ]
  },
  {
   "title": "Top 10 Virtual Machine Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(\n  10,\n  clamp_max(\n    (\n      avg by (vm_name) (\n        avg_over_time(\n          vmware_vm_mem_usage_average{dc_name=~\"${DC:regex}\"}[$__range]\n        )\n      ) * 100\n    )\n    /\n    max by (vm_name) (\n      vmware_vm_memory_max{dc_name=~\"${DC:regex}\"}\n    ),\n    100\n  )\n)",
     "legendFormat": "Memory usage {{vm_name}}"
    }
   ]
  }
 ]
}