{
 "title": "VMware ESXi Information",
 "description": "VMware ESXi single instance graphs.",
 "tags": [
  "vmware",
  "esxi"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "esxhost",
    "label": "esxhost",
    "query": "label_values(vmware_host_boot_timestamp_seconds,host_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(vmware_host_product_info{host_name=~\"$esxhost\"})",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "Build",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(vmware_host_product_info{host_name=~\"$esxhost\"})",
     "legendFormat": "{{ build }}"
    }
   ]
  },
  {
   "title": "Model",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(vmware_host_hardware_info{host_name=~\"$esxhost\"}) ",
     "legendFormat": "{{ hardware_model }}"
    }
   ]
  },
  {
   "title": "Cpu Model",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(vmware_host_hardware_info{host_name=~\"$esxhost\"}) ",
     "legendFormat": "{{ hardware_cpu_model }}"
    }
   ]
  },
  {
   "title": "ESXi host uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-vmware_host_boot_timestamp_seconds{host_name=~\"$esxhost\"} "
    }
   ]
  },
  {
   "title": "Cpu Number",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(vmware_host_num_cpu{host_name=~\"$esxhost\"})"
    }
   ]
  },
  {
   "title": "Memory Capaciy",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(vmware_host_memory_max{host_name=~\"$esxhost\"})"
    }
   ]
  },
  {
   "title": "Host CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(vmware_host_cpu_usagemhz_average{host_name=~\"$esxhost\"}) * 100 / (vmware_host_cpu_max{host_name=~\"$esxhost\"})"
    }
   ]
  },
  {
   "title": "Current Cpu Ready",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_host_cpu_ready_summation{host_name=~\"$esxhost\"}/200",
     "legendFormat": "Cpu Ready"
    }
   ]
  },
  {
   "title": "Current Cpu Co-Stop",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_host_cpu_costop_summation{host_name=~\"$esxhost\"}/200"
    }
   ]
  },
  {
   "title": "Host Memory usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(vmware_host_memory_usage{host_name=~\"$esxhost\"}) * 100 / (vmware_host_memory_max{host_name=~\"$esxhost\"})"
    }
   ]
  },
  {
   "title": "Virtual Machines",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "vmware_vm_power_state{host_name=~\"$esxhost\"}",
     "legendFormat": "auto"
    }
   ]
  },
  {
   "title": "Maintenance Mode Status",
   "type": "stat",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_host_maintenance_mode{host_name=~\"$esxhost\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Host CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(vmware_host_cpu_usagemhz_average{host_name=~\"$esxhost\"}) * 100 / (vmware_host_cpu_max{host_name=~\"$esxhost\"})",
     "legendFormat": "CPU Usage {{host_name}}"
    },
    {
     "expr": "(vmware_host_cpu_demand_average{host_name=~\"$esxhost\"}) * 100 / (vmware_host_cpu_max{host_name=~\"$esxhost\"})",
     "legendFormat": "CPU Demand {{host_name}}"
    }
   ]
  },
  {
   "title": "Host Cpu Contention",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "vmware_host_cpu_ready_summation{host_name=~\"$esxhost\"}/200",
     "legendFormat": "Cpu Ready {{host_name}}"
    },
    {
     "expr": "vmware_host_cpu_costop_summation{host_name=~\"$esxhost\"}/200",
     "legendFormat": "Cpu Co-Stop {{host_name}}"
    },
    {
     "expr": "vmware_host_cpu_swapwait_summation{host_name=~\"$esxhost\"}/200",
     "legendFormat": "Cpu Swap Wait {{host_name}}"
    }
   ]
  },
  {
   "title": "Host Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(vmware_host_memory_usage{host_name=~\"$esxhost\"} \n / vmware_host_memory_max{host_name=~\"$esxhost\"}) * 100",
     "legendFormat": "Memory Active {{host_name}}"
    }
   ]
  },
  {
   "title": "Host Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "vmware_host_mem_vmmemctl_average{host_name=~\"$esxhost\"}",
     "legendFormat": "Memory Balloon {{host_name}}"
    },
    {
     "expr": "vmware_host_mem_latency_average{host_name=~\"$esxhost\"}",
     "legendFormat": "Memory Latency {{host_name}}"
    },
    {
     "expr": "vmware_host_mem_swapinRate_average{host_name=~\"$esxhost\"}",
     "legendFormat": "Memory SwapInRate {{host_name}}"
    },
    {
     "expr": "vmware_host_mem_swapoutRate_average{host_name=~\"$esxhost\"}",
     "legendFormat": "Memory SwapOutRate {{host_name}}"
    }
   ]
  },
  {
   "title": "Host Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "vmware_host_net_usage_average{host_name=~\"$esxhost\"}",
     "legendFormat": "Total Usage {{host_name}}"
    },
    {
     "expr": "vmware_host_net_bytesRX_average{host_name=~\"$esxhost\"}",
     "legendFormat": "Usage RX {{host_name}}"
    },
    {
     "expr": "vmware_host_net_bytesTX_average{host_name=~\"$esxhost\"}",
     "legendFormat": "Usage TX {{host_name}}"
    },
    {
     "expr": "sum(vmware_vm_net_broadcastRx_summation{host_name=~\"$esxhost\"})",
     "legendFormat": "Broadcast RX {{host_name}}"
    },
    {
     "expr": "sum(vmware_vm_net_broadcastTx_summation{host_name=~\"$esxhost\"})",
     "legendFormat": "Broadcast TX {{host_name}}"
    },
    {
     "expr": "sum(vmware_vm_net_multicastRx_summation{host_name=~\"$esxhost\"})",
     "legendFormat": "Multicast RX {{host_name}}"
    },
    {
     "expr": "sum(vmware_vm_net_multicastTx_summation{host_name=~\"$esxhost\"})",
     "legendFormat": "Multicast TX {{host_name}}"
    }
   ]
  },
  {
   "title": "Host Network Contention",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "vmware_host_net_errorRX_summation{host_name=~\"$esxhost\"} OR vector(0)",
     "legendFormat": "Error RX {{host_name}}"
    },
    {
     "expr": "vmware_host_net_errorTX_summation{host_name=~\"$esxhost\"} OR vector(0) ",
     "legendFormat": "Error TX {{host_name}}"
    },
    {
     "expr": "vmware_host_net_droppedTX_summation{host_name=~\"$esxhost\"} OR vector(0)",
     "legendFormat": "Dropped TX {{host_name}}"
    },
    {
     "expr": "vmware_host_net_droppedRX_summation{host_name=~\"$esxhost\"} OR vector(0)",
     "legendFormat": "Dropped RX {{host_name}}"
    }
   ]
  },
  {
   "title": "Disk R/W Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "vmware_host_disk_read_average{host_name=~\"$esxhost\"}+vmware_host_disk_write_average{host_name=~\"$esxhost\"}",
     "legendFormat": "Disk Read and Write {{host_name}}"
    },
    {
     "expr": "vmware_host_disk_read_average{host_name=~\"$esxhost\"}",
     "legendFormat": "Disk Read {{host_name}}"
    },
    {
     "expr": "vmware_host_disk_write_average{host_name=~\"$esxhost\"}",
     "legendFormat": "Disk Write {{host_name}}"
    }
   ]
  }
 ]
}