{
 "title": "VMware Virtual Machines",
 "description": "VMware Virtual Machines information",
 "tags": [
  "vmware",
  "folder-vmware"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "vm", "label": "vm", "query": "label_values(vm_name)" }
  ]
 },
 "panels": [
  { "title": "Virtual Machine Snapshot info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Virtual Machine Snapshots",
   "type": "table",
   "gridPos": { "h": 18, "w": 22, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max by (vm_name, dc_name) (time() - vmware_vm_snapshot_timestamp_seconds)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Host",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(vmware_vm_boot_timestamp_seconds{vm_name=~\"$vm\"}) ",
     "legendFormat": "{{ host_name }}"
    }
   ]
  },
  {
   "title": "VM Type",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_template{vm_name=~\"$vm\"}"
    }
   ]
  },
  {
   "title": "VM State",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_power_state{vm_name=~\"$vm\"}==1"
    }
   ]
  },
  {
   "title": "Tools Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(vmware_vm_guest_tools_running_status{vm_name=~\"$vm\"})",
     "legendFormat": "{{ tools_status }}"
    }
   ]
  },
  {
   "title": "Tools Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(vmware_vm_guest_tools_version{vm_name=~\"$vm\"})",
     "legendFormat": "{{ tools_version}}"
    }
   ]
  },
  {
   "title": "Cpu Number",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(vmware_vm_num_cpu{vm_name=~\"$vm\"}) "
    }
   ]
  },
  {
   "title": "VM CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_cpu_usagemhz_average{vm_name=~\"$vm\"}/vmware_vm_max_cpu_usage{vm_name=~\"$vm\"}*100"
    }
   ]
  },
  {
   "title": "VM Cpu Ready",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(vmware_vm_cpu_ready_summation{vm_name=~\"$vm\"})/200"
    }
   ]
  },
  {
   "title": "VM Cpu Co-Stop",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_cpu_costop_summation{vm_name=~\"$vm\"}/200"
    }
   ]
  },
  {
   "title": "Memory Capacity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(vmware_vm_memory_max{vm_name=~\"$vm\"})  "
    }
   ]
  },
  {
   "title": "VM Memory usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(vmware_vm_mem_usage_average{vm_name=~\"$vm\"}) * 100 / (vmware_vm_memory_max{vm_name=~\"$vm\"})"
    }
   ]
  },
  {
   "title": "VM Ballooning",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_mem_vmmemctl_average{vm_name=~\"$vm\"}"
    }
   ]
  },
  {
   "title": "VM Swapped",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_mem_swapped_average{vm_name=~\"$vm\"}"
    }
   ]
  },
  {
   "title": "VM CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "vmware_vm_cpu_usagemhz_average{vm_name=~\"$vm\"}/vmware_vm_max_cpu_usage{vm_name=~\"$vm\"}*100",
     "legendFormat": "Cpu Usage {{vm_name}}"
    },
    {
     "expr": "vmware_vm_cpu_demand_average{vm_name=~\"$vm\"}/vmware_vm_max_cpu_usage{vm_name=~\"$vm\"}*100",
     "legendFormat": "Cpu Demand {{vm_name}}"
    }
   ]
  },
  {
   "title": "VM CPU Contention",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(vmware_vm_cpu_ready_summation{vm_name=~\"$vm\"})/200",
     "legendFormat": "Cpu Ready {{vm_name}}"
    },
    {
     "expr": "vmware_vm_cpu_costop_summation{vm_name=~\"$vm\"}/200",
     "legendFormat": "Co-Stop {{vm_name}}"
    }
   ]
  },
  {
   "title": "VM Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(vmware_vm_mem_usage_average{vm_name=~\"$vm\"}) * 100 / (vmware_vm_memory_max{vm_name=~\"$vm\"})",
     "legendFormat": "Memory Usage {{vm_name}}"
    }
   ]
  },
  {
   "title": "VM Memory Contention",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "vmware_vm_mem_vmmemctl_average{vm_name=~\"$vm\"}",
     "legendFormat": "Ballooning {{vm_name}}"
    },
    {
     "expr": "vmware_vm_mem_swapped_average{vm_name=~\"$vm\"}",
     "legendFormat": "Swap {{vm_name}}"
    }
   ]
  },
  {
   "title": "VM Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "vmware_vm_net_received_average{vm_name=~\"$vm\"}+vmware_vm_net_transmitted_average{vm_name=~\"$vm\"}",
     "legendFormat": "Total Usage {{vm_name}}"
    },
    {
     "expr": "vmware_vm_net_received_average{vm_name=~\"$vm\"}",
     "legendFormat": "Read Usage {{vm_name}}"
    },
    {
     "expr": "vmware_vm_net_transmitted_average{vm_name=~\"$vm\"}",
     "legendFormat": "Transmit Usage {{vm_name}}"
    },
    {
     "expr": "vmware_vm_net_broadcastTx_summation{vm_name=~\"$vm\"}",
     "legendFormat": "Broadcast TX {{vm_name}}"
    },
    {
     "expr": "vmware_vm_net_broadcastRx_summation{vm_name=~\"$vm\"}",
     "legendFormat": "Broadcast RX {{vm_name}}"
    },
    {
     "expr": "vmware_vm_net_multicastTx_summation{vm_name=~\"$vm\"}",
     "legendFormat": "Multicast TX {{vm_name}}"
    },
    {
     "expr": "vmware_vm_net_multicastRx_summation{vm_name=~\"$vm\"}",
     "legendFormat": "Multicast RX {{vm_name}}"
    }
   ]
  },
  {
   "title": "VM Network Packet Dropped",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "vmware_vm_net_droppedTx_summation{vm_name=~\"$vm\"}",
     "legendFormat": "Packet Dropped TX {{vm_name}}"
    },
    {
     "expr": "vmware_vm_net_droppedRx_summation{vm_name=~\"$vm\"}",
     "legendFormat": "Packet Dropped RX {{vm_name}}"
    }
   ]
  },
  {
   "title": "VM Disk Read And Write",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "vmware_vm_disk_read_average{vm_name=~\"$vm\"}+vmware_vm_disk_write_average{vm_name=~\"$vm\"}",
     "legendFormat": "Total Usage {{vm_name}}"
    },
    {
     "expr": "vmware_vm_disk_read_average{vm_name=~\"$vm\"}",
     "legendFormat": "Read Usage {{vm_name}}"
    },
    {
     "expr": "vmware_vm_disk_write_average{vm_name=~\"$vm\"}",
     "legendFormat": "Write Usage {{vm_name}}"
    }
   ]
  },
  {
   "title": "VM Disk Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "vmware_vm_disk_maxTotalLatency_latest{vm_name=~\"$vm\"}",
     "legendFormat": "Disk Latency {{vm_name}}"
    }
   ]
  }
 ]
}