{
 "title": "Ceph Log View",
 "tags": [ "folder-opensearch" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" },
   { "name": "cluster", "label": "Cluster", "query": "grafana-opensearch-datasource" }
  ]
 },
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Logs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "CEPH.* AND  warn|WARN|error|ERROR",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "API Resp",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "ERROR",
     "bucketAggs": [
      { "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "error|ERROR AND Logger: CEPH.*",
     "timeField": "@timestamp"
    },
    {
     "alias": "WARN",
     "bucketAggs": [
      { "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "WARN|warn AND Logger: CEPH.*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Log Levels",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 9, "y": 1 },
   "targets": [
    {
     "alias": "DEBUG",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "DBG AND Logger: CEPH.*",
     "timeField": "@timestamp"
    },
    {
     "alias": "INFO",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "info|INFO AND Logger: CEPH.*",
     "timeField": "@timestamp"
    },
    {
     "alias": "WARN",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "warn|WARN AND Logger: CEPH.*",
     "timeField": "@timestamp"
    },
    {
     "alias": "ERROR",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "error|ERROR AND Logger: CEPH.*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Service",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Logger.keyword",
       "id": "1",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger: CEPH.*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Hosts",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Hostname.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Hostname: *ceph* AND  warn|WARN|error|ERROR",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Ceph RGW ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Logs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger: CEPH.GW AND warn|WARN|error|ERROR",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "API Resp",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "ERROR",
     "bucketAggs": [
      { "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "error|ERROR AND Logger: CEPH.GW",
     "timeField": "@timestamp"
    },
    {
     "alias": "WARN",
     "bucketAggs": [
      { "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": " warn|WARN AND Logger: CEPH.GW",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Log Levels",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 9, "y": 7 },
   "targets": [
    {
     "alias": "DEBUG",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "DBG AND Logger: CEPH.GW",
     "timeField": "@timestamp"
    },
    {
     "alias": "INFO",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "info|INFO AND Logger: CEPH.GW",
     "timeField": "@timestamp"
    },
    {
     "alias": "WARN",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "warn|WARN AND Logger: CEPH.OSD",
     "timeField": "@timestamp"
    },
    {
     "alias": "ERROR",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "error|ERROR AND Logger: CEPH.OSD",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Program",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Programname.keyword",
       "id": "1",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger: CEPH.GW",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Hosts",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 7 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Hostname.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Hostname: *ceph* and Logger: CEPH.GW AND  warn|WARN|error|ERROR",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Log Levels",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "alias": "ERROR",
     "bucketAggs": [
      { "field": "@timestamp", "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "error|ERROR|warn|WARN AND Logger: CEPH.GW",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Ceph Manager ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Logs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger: CEPH.MGR AND warn|WARN|error|ERROR",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "API Resp",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "ERROR",
     "bucketAggs": [
      { "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "error|ERROR AND Logger: CEPH.MGR",
     "timeField": "@timestamp"
    },
    {
     "alias": "WARN",
     "bucketAggs": [
      { "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": " warn|WARN AND Logger: CEPH.MGR",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Log Levels",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 9, "y": 18 },
   "targets": [
    {
     "alias": "DEBUG",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "DBG AND Logger: CEPH.MGR",
     "timeField": "@timestamp"
    },
    {
     "alias": "INFO",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "info|INFO AND Logger: CEPH.OSD",
     "timeField": "@timestamp"
    },
    {
     "alias": "WARN",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "warn|WARN AND Logger: CEPH.OSD",
     "timeField": "@timestamp"
    },
    {
     "alias": "ERROR",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "error|ERROR AND Logger: CEPH.OSD",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Program",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Programname.keyword",
       "id": "1",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger: CEPH.MGR",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Hosts",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 18 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Hostname.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Hostname: *ceph* and Logger: CEPH.MGR AND  warn|WARN|error|ERROR",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Log Levels",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "alias": "ERROR",
     "bucketAggs": [
      { "field": "@timestamp", "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "error|ERROR|warn|WARN AND Logger: CEPH.MGR",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Ceph VOL ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Logs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger: CEPH.VOL AND warn|WARN|error|ERROR",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "API Resp",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "ERROR",
     "bucketAggs": [
      { "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "error|ERROR AND Logger: CEPH.VOL",
     "timeField": "@timestamp"
    },
    {
     "alias": "WARN",
     "bucketAggs": [
      { "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": " warn|WARN AND Logger: CEPH.VOL",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Log Levels",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 9, "y": 29 },
   "targets": [
    {
     "alias": "DEBUG",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "DBG AND Logger: CEPH.VOL",
     "timeField": "@timestamp"
    },
    {
     "alias": "INFO",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "info|INFO AND Logger: CEPH.VOL",
     "timeField": "@timestamp"
    },
    {
     "alias": "WARN",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "warn|WARN AND Logger: CEPH.OSD",
     "timeField": "@timestamp"
    },
    {
     "alias": "ERROR",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "error|ERROR AND Logger: CEPH.OSD",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Program",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Programname.keyword",
       "id": "1",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger: CEPH.VOL",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Hosts",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 29 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Hostname.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Hostname: *ceph* and Logger: CEPH.VOL AND  warn|WARN|error|ERROR",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Log Levels",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "alias": "ERROR",
     "bucketAggs": [
      { "field": "@timestamp", "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "error|ERROR|warn|WARN AND Logger: CEPH.VOL",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Ceph Monitors ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Logs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger: CEPH.MON AND warn|WARN|error|ERROR",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "API Resp",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "ERROR",
     "bucketAggs": [
      { "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "error|ERROR AND Logger: CEPH.MON",
     "timeField": "@timestamp"
    },
    {
     "alias": "WARN",
     "bucketAggs": [
      { "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": " warn|WARN AND Logger: CEPH.MON",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Log Levels",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 9, "y": 40 },
   "targets": [
    {
     "alias": "DEBUG",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "DBG AND Logger: CEPH.MON",
     "timeField": "@timestamp"
    },
    {
     "alias": "INFO",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "info|INFO AND Logger: CEPH.OSD",
     "timeField": "@timestamp"
    },
    {
     "alias": "WARN",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "warn|WARN AND Logger: CEPH.OSD",
     "timeField": "@timestamp"
    },
    {
     "alias": "ERROR",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "error|ERROR AND Logger: CEPH.OSD",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Program",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Programname.keyword",
       "id": "1",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger: CEPH.MON",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Hosts",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 40 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Hostname.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Hostname: *ceph* and Logger: CEPH.MON AND  warn|WARN|error|ERROR",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Log Levels",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "alias": "ERROR",
     "bucketAggs": [
      { "field": "@timestamp", "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "error|ERROR|warn|WARN AND Logger: CEPH.MON",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Ceph OSD", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Logs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger: CEPH.OSD AND warn|WARN|error|ERROR",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "API Resp",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "ERROR",
     "bucketAggs": [
      { "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "error|ERROR AND Logger: CEPH.OSD",
     "timeField": "@timestamp"
    },
    {
     "alias": "WARN",
     "bucketAggs": [
      { "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": " warn|WARN AND Logger: CEPH.OSD",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Log Levels",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 9, "y": 51 },
   "targets": [
    {
     "alias": "DEBUG",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "DBG AND Logger: CEPH.OSD",
     "timeField": "@timestamp"
    },
    {
     "alias": "INFO",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "info|INFO AND Logger: CEPH.OSD",
     "timeField": "@timestamp"
    },
    {
     "alias": "WARN",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "warn|WARN AND Logger: CEPH.OSD",
     "timeField": "@timestamp"
    },
    {
     "alias": "ERROR",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "error|ERROR AND Logger: CEPH.OSD",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Program",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Programname.keyword",
       "id": "1",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger: CEPH.OSD",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Hosts",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 51 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Hostname.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Hostname: *ceph* and Logger: CEPH.OSD AND  warn|WARN|error|ERROR",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Log Levels",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "alias": "ERROR",
     "bucketAggs": [
      { "field": "@timestamp", "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "error|ERROR|warn|WARN AND Logger: CEPH.OSD",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}