{
 "title": "Openstack VMs Overview Admin",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(os_region)" } },
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "interval", "label": "Interval", "query": "1m,2m,5m,15m,30m,1h,2h,1d" },
   {
    "name": "compute",
    "label": "Compute",
    "query": {
     "query": "label_values(libvirt_up{os_region=~\"$cluster\"},compute)"
    }
   },
   {
    "name": "virtual_machine",
    "label": "VM",
    "query": {
     "query": "label_values(libvirt_domain_info_meta{job=\"libvirt_exporter\", os_region=~\"$cluster\", compute=~\"$compute\"},domain)"
    }
   },
   { "name": "TopItems", "label": "Top Items", "query": "5,8,10,15,20,25" },
   {
    "name": "AZ",
    "label": "AZ",
    "query": {
     "query": "label_values(openstack_nova_agent_state{os_region=\"$cluster\"},zone)"
    }
   },
   {
    "name": "iops_limit",
    "label": "I/O Limit",
    "query": {
     "query": "label_values(openstack_cinder_volume_gb,volume_type)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cpu Core Capacity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_placement_resource_total{os_region=~\"$cluster\", resourcetype=\"VCPU\"})/2",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cpu Capacity Hz ",
   "type": "stat",
   "description": "This would include max clock speed not base line",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_cpu_scaling_frequency_hertz{os_region=~\"$cluster\",instance=~\".+nova.+|.+compute.+\"})/2",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Capacity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_placement_resource_total{resourcetype=\"MEMORY_MB\",os_region=~\"$cluster\"}) - sum(openstack_placement_resource_reserved{os_region=~\"$cluster\",resourcetype=\"MEMORY_MB\"}) - 2 * max(openstack_placement_resource_total{os_region=~\"$cluster\",resourcetype=\"MEMORY_MB\"})"
    }
   ]
  },
  {
   "title": "IOPS R/W on VMs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(rate(libvirt_domain_block_stats_read_requests_total{domain=~\"$virtual_machine\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Read IOPS"
    },
    {
     "expr": "sum(rate(libvirt_domain_block_stats_write_requests_total{domain=~\"$virtual_machine\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Write IOPS"
    }
   ]
  },
  {
   "title": "Throughput R/W on VMs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(libvirt_domain_block_stats_read_bytes_total{domain=~\"$virtual_machine\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Read Bytes"
    },
    {
     "expr": "sum(rate(libvirt_domain_block_stats_write_bytes_total{domain=~\"$virtual_machine\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Write Bytes"
    }
   ]
  },
  {
   "title": "Total vCPU Allocated",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(libvirt_domain_info_virtual_cpus{domain=~\"$virtual_machine\",compute=~\"$compute\", job=~\"libvirt_exporter\",os_region=~\"$cluster\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Total VMs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(libvirt_domain_info_state{domain=~\"$virtual_machine\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"}) or on() vector(0)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Shut Off VMs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(libvirt_domain_info_state{domain=~\"$virtual_machine\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"} == 5) or on() vector(0)",
     "legendFormat": "Shut Off"
    }
   ]
  },
  {
   "title": "RX/TX Packets Per Sec on VMs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 11, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(libvirt_domain_interface_stats_receive_packets_total{domain=~\"$virtual_machine\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "RX Packets"
    },
    {
     "expr": "sum(rate(libvirt_domain_interface_stats_transmit_packets_total{domain=~\"$virtual_machine\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "TX Packets"
    }
   ]
  },
  {
   "title": "RX/TX Throughput on VMs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(libvirt_domain_interface_stats_receive_bytes_total{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"}[$__rate_interval]))*8",
     "legendFormat": "RX Bytes"
    },
    {
     "expr": "sum(rate(libvirt_domain_interface_stats_transmit_bytes_total{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"}[$__rate_interval]))*8",
     "legendFormat": "TX Bytes"
    }
   ]
  },
  {
   "title": "Cluster CPU usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{instance=~\".*nova.*|.*compute.*\",os_region=~\"$cluster\",mode=\"idle\"}[2m])) * 100) + 3",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Suspend VMs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(libvirt_domain_info_state{domain=~\"$virtual_machine\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"} == 3) or on() vector(0)",
     "legendFormat": "Suspend"
    },
    {
     "expr": "count(libvirt_domain_info_state{domain=~\"$virtual_machine\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"} == 0) or on() vector(0)",
     "legendFormat": "Unknown state"
    },
    {
     "expr": "count(libvirt_domain_info_state{domain=~\"$virtual_machine\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"} == 6) or on() vector(0)",
     "legendFormat": "Crashed"
    }
   ]
  },
  {
   "title": "RX/TX Packets Drop on VMs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 11, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(libvirt_domain_interface_stats_receive_drops_total{domain=~\"$virtual_machine\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "RX Packets"
    },
    {
     "expr": "sum(rate(libvirt_domain_interface_stats_transmit_drops_total{domain=~\"$virtual_machine\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "TX Packets"
    }
   ]
  },
  {
   "title": "RX/TX Packets Error on VMs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(libvirt_domain_interface_stats_receive_errors_total{domain=~\"$virtual_machine\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "RX Packets"
    },
    {
     "expr": "sum(rate(libvirt_domain_interface_stats_transmit_errors_total{domain=~\"$virtual_machine\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "TX Packets"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes{os_region=~\"$cluster\",instance=~\"$compute\"}) - sum(node_memory_MemFree_bytes{os_region=~\"$cluster\",instance=~\"$compute\"}) - (sum(node_memory_Cached_bytes{os_region=~\"$cluster\",instance=~\"$compute\"}) + sum(node_memory_Buffers_bytes{os_region=~\"$cluster\",instance=~\"$compute\"})))",
     "legendFormat": "Memory Used"
    },
    {
     "expr": "sum(libvirt_domain_info_maximum_memory_bytes{domain=~\"$virtual_machine\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"})",
     "legendFormat": "Memory Allocated"
    }
   ]
  },
  {
   "title": "IOPS R/W on VMs",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(rate(libvirt_domain_block_stats_read_requests_total{domain=~\"$virtual_machine\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(rate(libvirt_domain_block_stats_write_requests_total{domain=~\"$virtual_machine\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Price per year running on VMware",
   "type": "stat",
   "description": "Price a year with commit and without commit",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_placement_resource_total{os_region=~\"$cluster\", resourcetype=\"VCPU\"})/2 * 350",
     "legendFormat": "Without commit"
    },
    {
     "expr": "sum(openstack_placement_resource_total{os_region=~\"$cluster\", resourcetype=\"VCPU\"})/2 * 338",
     "legendFormat": "With commit"
    }
   ]
  },
  {
   "title": "Cluster CPU usage % - $cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - 100 * (avg(irate(node_cpu_seconds_total{instance=~\".*nova.*|.*compute.*\",os_region=~\"$cluster\",mode=\"idle\"}[1m]))) + 5",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Memory usage % - $cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "($B/$A)", "type": "math" }
   ]
  },
  {
   "title": "Hypervisors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Computes ",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(openstack_nova_agent_state{adminState=\"enabled\",os_region=~\"$cluster\",service=\"nova-compute\"}) or vector(0)",
       "legendFormat": "Enabled"
      },
      {
       "expr": "count(openstack_nova_agent_state{adminState=\"disabled\",os_region=~\"$cluster\",service=\"nova-compute\"}) or vector(0)",
       "legendFormat": "Disabled"
      },
      { "expression": "$A + $B", "type": "math" }
     ]
    },
    {
     "title": "Compute Stats",
     "type": "table",
     "gridPos": { "h": 30, "w": 24, "x": 0, "y": 779 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "openstack_nova_memory_available_bytes{os_region=\"$cluster\",availability_zone=~\"$AZ\"}",
       "legendFormat": "Memory available"
      },
      {
       "expr": "openstack_nova_running_vms{os_region=\"$cluster\",availability_zone=~\"$AZ\"}",
       "legendFormat": "Instance"
      },
      {
       "expr": "openstack_placement_resource_total{os_region=\"$cluster\", resourcetype=\"VCPU\"} +\non (hostname) group_left(availability_zone) 0 * \n(openstack_nova_running_vms{os_region=\"$cluster\"} )\n",
       "legendFormat": "VCPU"
      },
      {
       "expr": "openstack_placement_resource_total{os_region=\"$cluster\",resourcetype=\"VCPU\"}*openstack_placement_resource_allocation_ratio{os_region=\"$cluster\",resourcetype=\"VCPU\"}",
       "legendFormat": "VCPU total"
      },
      {
       "expr": "openstack_placement_resource_usage{os_region=\"$cluster\",resourcetype=\"VCPU\"} +\non (hostname) group_left(availability_zone) 0 * \n(openstack_nova_running_vms{os_region=\"$cluster\"} )",
       "legendFormat": "VCPU Used"
      },
      {
       "expr": "openstack_placement_resource_total{os_region=\"$cluster\",resourcetype=\"DISK_GB\"} +\non (hostname) group_left(availability_zone) 0 * \n(openstack_nova_running_vms{os_region=\"$cluster\"} )",
       "legendFormat": "DISK_GB"
      },
      {
       "expr": "openstack_placement_resource_usage{os_region=\"$cluster\",resourcetype=\"DISK_GB\"}",
       "legendFormat": "DISK_GB Used"
      },
      {
       "expr": "openstack_placement_resource_total{os_region=\"$cluster\",resourcetype=\"MEMORY_MB\"}*1024*1024 +\non (hostname) group_left(availability_zone) 0 * \n(openstack_nova_running_vms{os_region=\"$cluster\"} )",
       "legendFormat": "RAM"
      },
      {
       "expr": "openstack_placement_resource_total{os_region=\"$cluster\",resourcetype=\"MEMORY_MB\"}*openstack_placement_resource_allocation_ratio{os_region=\"$cluster\",resourcetype=\"MEMORY_MB\"}*1024*1024",
       "legendFormat": "RAM Total"
      },
      {
       "expr": "(openstack_placement_resource_usage{os_region=\"$cluster\",resourcetype=\"MEMORY_MB\"}+openstack_placement_resource_reserved{os_region=\"$cluster\",resourcetype=\"MEMORY_MB\"}) * 1024 * 1024",
       "legendFormat": "RAM_ALLOCATED"
      },
      {
       "expr": "(label_replace(node_memory_MemTotal_bytes{instance=~\".*nova.*|.*compute.*\",os_region=\"$cluster\"},\"hostname\",\"$1\",\"instance\",\"(.+)\") - label_replace(node_memory_MemFree_bytes{instance=~\".*nova.*|.*compute.*\",os_region=\"$cluster\"},\"hostname\",\"$1\",\"instance\",\"(.+)\") - label_replace(node_memory_Cached_bytes{instance=~\".*nova.*|.*compute.*\",os_region=\"$cluster\"},\"hostname\",\"$1\",\"instance\",\"(.+)\") + label_replace(node_memory_Buffers_bytes{instance=~\".*nova.*|.*compute.*\",os_region=\"$cluster\"},\"hostname\",\"$1\",\"instance\",\"(.+)\") + on (hostname) group_left(availability_zone) 0 * (openstack_nova_running_vms{os_region=\"$cluster\"} )) * 1.03",
       "legendFormat": "RAM Usage"
      },
      {
       "expr": "round((label_replace(node_time_seconds{instance=~\".*nova.*|.*compute.*\",os_region=\"$cluster\"},\"hostname\",\"$1\",\"instance\",\"(.+)\") - label_replace(node_boot_time_seconds{instance=~\".*nova.*|.*compute.*\",os_region=\"$cluster\"},\"hostname\",\"$1\",\"instance\",\"(.+)\"))/86400) + on (hostname) group_left(availability_zone) 0 * (openstack_nova_running_vms{os_region=\"$cluster\"} )",
       "legendFormat": "Uptime"
      },
      {
       "expr": "(sum by (hostname) (label_replace(irate(node_cpu_seconds_total{mode!=\"idle\",instance=~\".*nova.*|.*compute.*\",os_region=\"$cluster\"}[3m]), \"hostname\", \"$1\", \"instance\", \"(.*)\")))\n / on(hostname) group_left sum by (hostname)(((sum by (hostname) (label_replace(irate(node_cpu_seconds_total{instance=~\".*nova.*|.*compute.*\",os_region=\"$cluster\"}[3m]), \"hostname\", \"$1\", \"instance\", \"(.*)\"))))) * 100 + on (hostname) group_left(availability_zone) 0 * (openstack_nova_running_vms{os_region=\"$cluster\"} )",
       "legendFormat": "CPU consumption"
      },
      {
       "expr": "openstack_nova_agent_state{os_region=\"$cluster\",service=\"nova-compute\"}",
       "legendFormat": "adminState"
      },
      {
       "expr": "label_replace(up{job=\"node\",os_region=\"$cluster\",instance=~\".*nova.*|.*compute.*\"},\"hostname\",\"$1\",\"instance\",\"(.+)\")",
       "legendFormat": "hostState"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopItems HVs by CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 18, "w": 24, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "topk($TopItems, 100 - 100 * (max by (instance) (irate(node_cpu_seconds_total{instance=~\".*nova.*|.*compute.*\", os_region=~\"$cluster\", mode=\"idle\"}[3m]))))",
       "legendFormat": "CPU usage {{instance}}"
      }
     ]
    },
    {
     "title": "Top $TopItems VMs by vCPU Steal Time",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 521 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (domain,compute,instance_name) (rate(libvirt_domain_vcpu_delay_seconds_total{job=~\"libvirt_exporter\",compute=~\"$compute\",os_region=~\"$cluster\"}[$__rate_interval]) * on(domain,compute) group_left(instance_name,project_name) libvirt_domain_openstack_info{job=~\"libvirt_exporter\",compute=~\"$compute\",os_region=~\"$cluster\"}) * 100 + topk($TopItems, avg_over_time((avg by (domain,compute,instance_name) (rate(libvirt_domain_vcpu_delay_seconds_total{job=~\"libvirt_exporter\",compute=~\"$compute\",os_region=~\"$cluster\"}[$__rate_interval]) * on(domain,compute) group_left(instance_name,project_name) libvirt_domain_openstack_info{job=~\"libvirt_exporter\",compute=~\"$compute\",os_region=~\"$cluster\"}) * 100)[$__range:] @ end())) * 0",
       "legendFormat": "{{instance_name}} - {{domain}} - {{compute}}"
      }
     ]
    },
    {
     "title": "Top $TopItems VMS by vCPU Usage",
     "type": "timeseries",
     "description": "100% = 1 Thread",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 534 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(rate(libvirt_domain_info_cpu_time_seconds_total{job=~\"libvirt_exporter\",os_region=~\"$cluster\"}[$__rate_interval])) by (domain,compute)\n+ \ntopk($TopItems,avg_over_time(sum(rate(libvirt_domain_info_cpu_time_seconds_total{job=~\"libvirt_exporter\",os_region=~\"$cluster\"}[$__rate_interval])) by (domain, compute)@ end()))",
       "legendFormat": "{{domain}} - {{compute}}"
      }
     ]
    },
    {
     "title": "Top $TopItems vCPU Total",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 543 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk($TopItems, libvirt_domain_info_virtual_cpus{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",compute=~\"$compute\",os_region=~\"$cluster\"})",
       "legendFormat": "{{domain}} - {{compute}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Volumes Close to ${iops_limit} write iOPS Limit",
     "type": "barchart",
     "gridPos": { "h": 19, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "(label_replace(\n    purefa_volume_performance_throughput_iops{\n      os_region=~\"$cluster\",\n      dimension=\"writes_per_sec\"\n    },\n    \"id\", \"$1\", \"name\", \"volume-(.*)-cinder\"\n  )\n  + on(id) group_left(volume_type, volume_name)\n  (\n    0 * (label_replace(\n      openstack_cinder_volume_gb{\n        os_region=~\"$cluster\",\n        volume_type=~\".*-${iops_limit}$\"\n      },\n      \"volume_name\", \"$1\", \"name\", \"(.*)\"\n      )\n    )\n  )\n) > (${iops_limit} * 0.85)",
       "legendFormat": "write-{{ id }} {{ volume_type }} {{ volume_name }}"
      }
     ]
    },
    {
     "title": "Volumes Close to $iops_limit Read iOPS Limit",
     "type": "barchart",
     "gridPos": { "h": 19, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "(label_replace(\n    purefa_volume_performance_throughput_iops{\n      os_region=~\"$cluster\",\n      dimension=\"reads_per_sec\"\n    },\n    \"id\", \"$1\", \"name\", \"volume-(.*)-cinder\"\n  )\n  + on(id) group_left(volume_type, volume_name)\n  (\n    0 * (label_replace(\n      openstack_cinder_volume_gb{\n        os_region=~\"$cluster\",\n        volume_type=~\".*-${iops_limit}$\"\n      },\n      \"volume_name\", \"$1\", \"name\", \"(.*)\"\n      )\n    )\n  )\n) > (${iops_limit} * 0.90)",
       "legendFormat": "read-{{ id }} {{ volume_type }} {{ volume_name }}"
      }
     ]
    },
    {
     "title": "Top $TopItems Volumes for Write IOPs Pure",
     "type": "timeseries",
     "gridPos": { "h": 17, "w": 12, "x": 0, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "label_replace(\n  avg(purefa_volume_performance_throughput_iops{os_region=~\"$cluster\", dimension=\"writes_per_sec\", name=~\"volume-.*\"}) by (instance,name),\n  \"id\", \"$1\", \"name\", \"volume-(.*)-cinder\"\n)\n* on(id) group_left(volume_name, size, status, tenant_id, volume_type)\n# Then, rename the name label to volume_name in the Cinder data\n(label_replace(\n  label_replace(\n    openstack_cinder_volume_gb{os_region=~\"$cluster\"},\n    \"volume_name\", \"$1\", \"name\", \"(.*)\"\n  ),\n  \"name\", \"volume-$1-cinder\", \"id\", \"(.*)\"\n) * 0 + 1)\nand\ntopk($TopItems, \n  label_replace(\n    avg(rate(purefa_volume_performance_throughput_iops{os_region=~\"$cluster\", dimension=\"writes_per_sec\", name=~\"volume-.*\"}[$__range] @ end() )) by (instance,name),\n    \"id\", \"$1\", \"name\", \"volume-(.*)-cinder\"\n  )\n  * on(id) group_left(volume_name, size, status, tenant_id, volume_type)\n  (label_replace(\n    label_replace(\n      openstack_cinder_volume_gb{os_region=~\"$cluster\"},\n      \"volume_name\", \"$1\", \"name\", \"(.*)\"\n    ),\n    \"name\", \"volume-$1-cinder\", \"id\", \"(.*)\"\n  ) * 0 + 1)\n)\n",
       "legendFormat": "{{id}} {{instance}} {{volume_name}} {{volume_type}}"
      }
     ]
    },
    {
     "title": "Top $TopItems Volumes for Read IOPs Pure",
     "type": "timeseries",
     "gridPos": { "h": 17, "w": 12, "x": 12, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "# First, extract the ID from the Pure volume name and add it as a label\nlabel_replace(\n  avg(purefa_volume_performance_throughput_iops{os_region=~\"$cluster\", dimension=\"reads_per_sec\", name=~\"volume-.*\"}) by (instance,name),\n  \"id\", \"$1\", \"name\", \"volume-(.*)-cinder\"\n)\n* on(id) group_left(volume_name, size, status, tenant_id, volume_type)\n# Then, rename the name label to volume_name in the Cinder data\n(label_replace(\n  label_replace(\n    openstack_cinder_volume_gb{os_region=~\"$cluster\"},\n    \"volume_name\", \"$1\", \"name\", \"(.*)\"\n  ),\n  \"name\", \"volume-$1-cinder\", \"id\", \"(.*)\"\n) * 0 + 1)\nand\ntopk($TopItems, \n  label_replace(\n    avg(rate(purefa_volume_performance_throughput_iops{os_region=~\"$cluster\", dimension=\"reads_per_sec\", name=~\"volume-.*\"}[$__range] @ end() )) by (instance,name),\n    \"id\", \"$1\", \"name\", \"volume-(.*)-cinder\"\n  )\n  * on(id) group_left(volume_name, size, status, tenant_id, volume_type)\n  (label_replace(\n    label_replace(\n      openstack_cinder_volume_gb{os_region=~\"$cluster\"},\n      \"volume_name\", \"$1\", \"name\", \"(.*)\"\n    ),\n    \"name\", \"volume-$1-cinder\", \"id\", \"(.*)\"\n  ) * 0 + 1)\n)",
       "legendFormat": "{{id}} {{instance}} {{volume_name}} {{volume_type}}"
      }
     ]
    },
    {
     "title": "Cluster Disk Read And Write",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 114 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(libvirt_domain_block_stats_read_bytes_total{compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "read_bytes"
      },
      {
       "expr": "sum(rate(libvirt_domain_block_stats_write_bytes_total{compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "write_bytes"
      }
     ]
    },
    {
     "title": "Top $TopItems Throughput Read",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 123 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(rate(libvirt_domain_block_stats_read_bytes_total{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",compute=~\"$compute\",os_region=~\"$cluster\"}[$__rate_interval])) by (domain, target_device,compute)\n+ \ntopk($TopItems,avg(rate(libvirt_domain_block_stats_read_bytes_total{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",compute=~\"$compute\",os_region=~\"$cluster\"}[$__rate_interval])) by (domain, target_device,compute)@ end())*0",
       "legendFormat": "{{domain}} - {{target_device}} - {{compute}}"
      }
     ]
    },
    {
     "title": "Top $TopItems Throughput Write",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 123 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(libvirt_domain_block_stats_write_bytes_total\n{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",compute=~\"$compute\",os_region=~\"$cluster\"}[$__rate_interval])) by (domain,target_device,compute)\n+ \ntopk($TopItems,avg_over_time(avg(rate(libvirt_domain_block_stats_write_bytes_total\n{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",compute=~\"$compute\",os_region=~\"$cluster\"}[$__rate_interval])) by (domain,target_device,compute)@ end()))\n",
       "legendFormat": "{{domain}} - {{target_device}} - {{ compute }}"
      }
     ]
    },
    {
     "title": "Top $TopItems IOPS Read",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 131 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "avg(rate(libvirt_domain_block_stats_read_requests_total{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",compute=~\"$compute\",os_region=~\"$cluster\"}[$__rate_interval])) by (domain, target_device,compute)\n+ \ntopk($TopItems,avg(rate(libvirt_domain_block_stats_read_requests_total{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",compute=~\"$compute\",os_region=~\"$cluster\"}[$__rate_interval])) by (domain,target_device,compute)@ end())",
       "legendFormat": "{{domain}} - {{target_device}} - {{ compute }}"
      }
     ]
    },
    {
     "title": "Top $TopItems IOPS Write",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 131 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "avg(rate(libvirt_domain_block_stats_write_requests_total{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",compute=~\"$compute\",os_region=~\"$cluster\"}[$__rate_interval])) by (domain, target_device,compute)\n+\ntopk($TopItems,(avg(rate(libvirt_domain_block_stats_write_requests_total{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",compute=~\"$compute\",os_region=~\"$cluster\"}[$__rate_interval])) by (domain, target_device, compute)@ end()))\n\n",
       "legendFormat": "{{domain}} - {{target_device}} - {{ compute }}"
      }
     ]
    },
    {
     "title": "Top $TopItems Read time",
     "type": "timeseries",
     "description": "Total time (ns) spent on reads on a block device, in ns, that is, 1/1,000,000,000 of a second, or 10−9 seconds.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 139 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(rate(libvirt_domain_block_stats_read_time_seconds_total{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",compute=~\"$compute\",os_region=~\"$cluster\"}[$__rate_interval])) by (domain, target_device,compute)\n+ \ntopk($TopItems,avg_over_time(sum(rate(libvirt_domain_block_stats_read_time_seconds_total{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",compute=~\"$compute\",os_region=~\"$cluster\"}[$__rate_interval])) by (domain, target_device,compute)@ end()))*0\n\n",
       "legendFormat": "{{domain}} - {{target_device}} - {{compute}}"
      }
     ]
    },
    {
     "title": "Write time",
     "type": "timeseries",
     "description": "Total time (ns) spent on writes on a block device, in ns, that is, 1/1,000,000,000 of a second, or 10−9 seconds.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 139 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(rate(libvirt_domain_block_stats_write_time_seconds_total\n{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",compute=~\"$compute\",os_region=~\"$cluster\"}[$__rate_interval])) by (domain, target_device,compute)\n+ \ntopk($TopItems,avg_over_time(sum(rate(libvirt_domain_block_stats_write_time_seconds_total\n{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",compute=~\"$compute\",os_region=~\"$cluster\"}[$__rate_interval])) by (domain, target_device,compute)@ end()))*0\n",
       "legendFormat": "{{domain}} - {{target_device}} - {{compute}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory on VMs",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1262 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(5, libvirt_domain_info_maximum_memory_bytes{domain=~\"$virtual_machine\", job=~\"libvirt_exporter\",os_region=~\"$cluster\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "topk(5, libvirt_domain_memory_stats_unused_bytes{domain=~\"$virtual_machine\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"})",
       "legendFormat": "Available"
      },
      {
       "expr": "topk(5, libvirt_domain_info_maximum_memory_bytes{domain=~\"$virtual_machine\", compute=~\"$compute\", job=~\"libvirt_exporter\",os_region=~\"$cluster\"} - libvirt_domain_memory_stats_unused_bytes{domain=~\"$virtual_machine\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"})",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1272 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk($TopItems,libvirt_domain_info_maximum_memory_bytes{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",os_region=~\"$cluster\", compute=~\"$compute\"})",
       "legendFormat": "{{domain}}"
      }
     ]
    },
    {
     "title": "Top $TopItems Resident Set Size",
     "type": "timeseries",
     "description": "Resident Set Size of the process running the domain, in bytes.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1272 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk($TopItems, libvirt_domain_memory_stats_rss_bytes{domain=~\"$virtual_machine\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"})",
       "legendFormat": "{{domain}}"
      }
     ]
    },
    {
     "title": "Used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1280 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(20, libvirt_domain_info_maximum_memory_bytes{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",compute=~\"$compute\",os_region=~\"$cluster\"} - libvirt_domain_memory_stats_unused_bytes{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",compute=~\"$compute\",os_region=~\"$cluster\"})",
       "legendFormat": "{{domain}}"
      }
     ]
    },
    {
     "title": "Top $TopItems Available",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1280 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk($TopItems, libvirt_domain_memory_stats_unused_bytes{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"})",
       "legendFormat": "{{domain}}"
      }
     ]
    },
    {
     "title": "Swap Read",
     "type": "timeseries",
     "description": "The total amount of data read from swap space",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1288 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "libvirt_domain_memory_stats_swap_in_bytes{compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"}",
       "legendFormat": "{{domain}}"
      }
     ]
    },
    {
     "title": "Swap Written",
     "type": "timeseries",
     "description": "The total amount of memory written out to swap space",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1288 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "libvirt_domain_memory_stats_swap_out_bytes{compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"}",
       "legendFormat": "{{domain}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "RX/TX VMs Network",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1214 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "sum(rate(libvirt_domain_interface_stats_receive_bytes_total{compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"}[$__rate_interval])) * 8",
       "legendFormat": "receive"
      },
      {
       "expr": "sum(rate(libvirt_domain_interface_stats_transmit_bytes_total{compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"}[$__rate_interval])) * 8",
       "legendFormat": "transmit"
      }
     ]
    },
    {
     "title": "Top $TopItems RX Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1223 },
     "fieldConfig": { "defaults": { "unit": "decbits" } },
     "targets": [
      {
       "expr": "sum(rate(libvirt_domain_interface_stats_receive_bytes_total{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",compute=~\"$compute\",os_region=~\"$cluster\"}[$__rate_interval])*8) by (domain,target_device,compute)\n+ \ntopk($TopItems,avg_over_time(sum(rate(libvirt_domain_interface_stats_receive_bytes_total{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",compute=~\"$compute\",os_region=~\"$cluster\"}[$__rate_interval])*8) by (domain,target_device,compute) @ end()))*0",
       "legendFormat": "{{domain}} - {{target_device}} - {{ compute }}"
      }
     ]
    },
    {
     "title": "Top $TopItems TX Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1223 },
     "fieldConfig": { "defaults": { "unit": "decbits" } },
     "targets": [
      {
       "expr": "sum(rate(libvirt_domain_interface_stats_transmit_bytes_total\n{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",compute=~\"$compute\",os_region=~\"$cluster\"}[$__rate_interval])*8) by (domain,target_device,compute)\n+ \ntopk($TopItems,avg_over_time(sum(rate(libvirt_domain_interface_stats_transmit_bytes_total\n{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",compute=~\"$compute\",os_region=~\"$cluster\"}[$__rate_interval])*8) by (domain,target_device,compute) @ end()))*0",
       "legendFormat": "{{domain}} - {{target_device}}"
      }
     ]
    },
    {
     "title": "Top $TopItems RX Packets",
     "type": "timeseries",
     "description": "Number of packets received on a network interface.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1239 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(libvirt_domain_interface_stats_receive_packets_total\n{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",compute=~\"$compute\",os_region=~\"$cluster\"}[$__rate_interval])) by (domain,target_device,compute)\n+ \ntopk($TopItems,avg_over_time(sum(rate(libvirt_domain_interface_stats_receive_packets_total\n{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",compute=~\"$compute\",os_region=~\"$cluster\"}[$__rate_interval])) by (domain, target_device,compute)@ end()))*0\n",
       "legendFormat": "{{domain}} - {{target_device}}"
      }
     ]
    },
    {
     "title": "TX Packets",
     "type": "timeseries",
     "description": "Number of packets transmitted on a network interface.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1239 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(libvirt_domain_interface_stats_transmit_packets_total{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",compute=~\"$compute\",os_region=~\"$cluster\"}[$__rate_interval])) by (domain,target_device,compute)\n+ \ntopk($TopItems,avg_over_time(sum(rate(libvirt_domain_interface_stats_transmit_packets_total\n{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",compute=~\"$compute\",os_region=~\"$cluster\"}[$__rate_interval])) by (domain, target_device,compute)@ end()))*0",
       "legendFormat": "{{domain}}-{{target_device}}-{{compute}}"
      }
     ]
    },
    {
     "title": "Top $TopItems RX/TX Packets Drop",
     "type": "timeseries",
     "description": "Number of packet receive/transmit drops on a network interface.",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1247 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(libvirt_domain_interface_stats_receive_drops_total\n{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",compute=~\"$compute\",os_region=~\"$cluster\"}[$__rate_interval])) by (domain,target_device,compute)\n+ \ntopk($TopItems,avg_over_time(sum(rate(libvirt_domain_interface_stats_receive_drops_total\n{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",compute=~\"$compute\",os_region=~\"$cluster\"}[$__rate_interval])) by (domain, target_device,compute) @end()))*0\n",
       "legendFormat": "{{domain}} - {{target_device}} - rx - {{compute}}"
      },
      {
       "expr": "sum(rate(libvirt_domain_interface_stats_transmit_drops_total\n\n{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",compute=~\"$compute\",os_region=~\"$cluster\"}[$__rate_interval])) by (domain,target_device,compute)\n+ \ntopk(10,avg_over_time(sum(rate(libvirt_domain_interface_stats_transmit_drops_total\n{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",compute=~\"$compute\",os_region=~\"$cluster\"}[$__rate_interval])) by (domain, target_device,compute)@ end()))*0\n",
       "legendFormat": "{{domain}} - {{target_device}} - tx - {{compute}}"
      }
     ]
    },
    {
     "title": "RX/TX Packets Error",
     "type": "timeseries",
     "description": "Number of packet receive/trasmit errors on a network interface.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1259 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "topk(10, rate(libvirt_domain_interface_stats_receive_errors_total{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",compute=~\"$compute\",os_region=~\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "{{domain}} - {{target_device}} - rx"
      },
      {
       "expr": "topk($TopItems,rate(libvirt_domain_interface_stats_transmit_errors_total{domain=~\"$virtual_machine\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "{{domain}} - {{target_device}} - tx"
      }
     ]
    }
   ]
  },
  {
   "title": "Data Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "VMs Stats",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "libvirt_domain_info_virtual_cpus{domain=~\"$virtual_machine\",compute=~\"$compute\", job=~\"libvirt_exporter\",os_region=~\"$cluster\"} * on(domain,compute) group_left(flavor_name,instance_name,project_id,project_name,user_name) libvirt_domain_openstack_info{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",compute=~\"$compute\",os_region=~\"$cluster\"}",
       "legendFormat": "vCPU Total"
      },
      {
       "expr": "(avg by (domain) (irate(libvirt_domain_info_cpu_time_seconds_total{domain=~\"$virtual_machine\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"}[$__rate_interval])) * 100)",
       "legendFormat": "vCPU Used"
      },
      {
       "expr": "libvirt_domain_info_maximum_memory_bytes{domain=~\"$virtual_machine\",compute=~\"$compute\", job=~\"libvirt_exporter\",os_region=~\"$cluster\"}",
       "legendFormat": "Memory Total"
      },
      {
       "expr": "(libvirt_domain_info_maximum_memory_bytes{domain=~\"$virtual_machine\",compute=~\"$compute\", job=~\"libvirt_exporter\",os_region=~\"$cluster\"} - libvirt_domain_memory_stats_unused_bytes{domain=~\"$virtual_machine\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"})/ 1e9",
       "legendFormat": "Memory Used"
      },
      {
       "expr": "sum(label_replace(openstack_cinder_volume_gb{os_region=~\"$cluster\"}, \"domain\", \"$1\", \"server_id\", \"(.*)\")) by (domain)  * on(domain) group_left libvirt_domain_openstack_info{domain=~\"$virtual_machine\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"} ",
       "legendFormat": "Disk Total"
      }
     ]
    }
   ]
  }
 ]
}