{
 "title": "Opensearch Dashboard",
 "tags": [ "folder-opensearch" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" },
   { "name": "cluster", "label": "Cluster", "query": "grafana-opensearch-datasource" }
  ]
 },
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Logs",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "OS API",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "log_level.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "OS Logs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 7, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "OS service perfs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 13, "y": 1 },
   "targets": [
    {
     "alias": "Nova",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger : openstack.nova",
     "timeField": "@timestamp"
    },
    {
     "alias": "Neutron",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger : openstack.neutron",
     "timeField": "@timestamp"
    },
    {
     "alias": "Cinder",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger : openstack.cinder",
     "timeField": "@timestamp"
    },
    {
     "alias": "Keystone",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger : openstack.keystone",
     "timeField": "@timestamp"
    },
    {
     "alias": "Ceilometer",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger : openstack.ceilometer",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "API Resp",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 1 },
   "targets": [
    {
     "alias": "INFO",
     "bucketAggs": [
      { "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "log_level : INFO OR log_level : info",
     "timeField": "@timestamp"
    },
    {
     "alias": "ERROR",
     "bucketAggs": [
      { "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "log_level : error",
     "timeField": "@timestamp"
    },
    {
     "alias": "DEBUG",
     "bucketAggs": [
      { "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "log_level : DEBUG OR log_level : debug",
     "timeField": "@timestamp"
    },
    {
     "alias": "WARN",
     "bucketAggs": [
      { "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "log_level : WARN OR log_level : warn",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Hosts",
   "type": "table",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 6 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Hostname.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "OS API Request Table",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 3, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "programname.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "OS Services",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 8, "y": 6 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Logger.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Tenants",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 14, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "tenant_id.keyword",
       "id": "1",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Project",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "user_domain.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Keystone", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Keystone Logs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 13 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger:openstack.keystone",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Log Levels",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 13 },
   "targets": [
    {
     "alias": "DEBUG",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "log_level : DEBUG AND Logger:openstack.keystone",
     "timeField": "@timestamp"
    },
    {
     "alias": "INFO",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(log_level : info OR log_level : INFO) AND Logger:openstack.keystone",
     "timeField": "@timestamp"
    },
    {
     "alias": "WARN",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(log_level : warn OR log_level : WARN) AND Logger:openstack.keystone",
     "timeField": "@timestamp"
    },
    {
     "alias": "ERROR",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "log_level : error AND Logger:openstack.keystone",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "API Resp",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 13 },
   "targets": [
    {
     "alias": "400",
     "bucketAggs": [
      { "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "http_status : 400 AND Logger:keystone",
     "timeField": "@timestamp"
    },
    {
     "alias": "404",
     "bucketAggs": [
      { "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "http_status : 404 AND Logger:keystone",
     "timeField": "@timestamp"
    },
    {
     "alias": "409",
     "bucketAggs": [
      { "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(http_status : 409 OR http_status : 401)  AND Logger:keystone",
     "timeField": "@timestamp"
    },
    {
     "alias": "504",
     "bucketAggs": [
      { "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "http_status : 504 AND Logger:keystone",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Hosts",
   "type": "table",
   "gridPos": { "h": 5, "w": 3, "x": 17, "y": 13 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Hostname.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger:openstack.keystone",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Programname",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "programname.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger:openstack.keystone",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Nova ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Nova Logs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 19 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger:openstack.nova",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Log Levels",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 19 },
   "targets": [
    {
     "alias": "DEBUG",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "log_level : DEBUG AND Logger:openstack.nova",
     "timeField": "@timestamp"
    },
    {
     "alias": "INFO",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(log_level : info OR log_level : INFO) AND Logger:openstack.nova",
     "timeField": "@timestamp"
    },
    {
     "alias": "WARN",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(log_level : warn OR log_level : WARN) AND Logger:openstack.nova",
     "timeField": "@timestamp"
    },
    {
     "alias": "ERROR",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "log_level : error  AND Logger:openstack.nova",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "API Resp",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 19 },
   "targets": [
    {
     "alias": "400",
     "bucketAggs": [
      { "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "http_status : 400 AND Logger:nova",
     "timeField": "@timestamp"
    },
    {
     "alias": "404",
     "bucketAggs": [
      { "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "http_status : 404 AND Logger:nova",
     "timeField": "@timestamp"
    },
    {
     "alias": "409",
     "bucketAggs": [
      { "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(http_status : 401 OR http_status : 409)  AND Logger:nova",
     "timeField": "@timestamp"
    },
    {
     "alias": "504",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "http_status : 504 AND Logger:keystone",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Hosts",
   "type": "table",
   "gridPos": { "h": 5, "w": 3, "x": 17, "y": 19 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Hostname.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger:openstack.nova",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Programname",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "programname.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger:openstack.nova",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Neutron", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Neutron Logs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 25 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger:openstack.neutron",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Log Levels",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 25 },
   "targets": [
    {
     "alias": "DEBUG",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "log_level : DEBUG AND Logger:openstack.neutron",
     "timeField": "@timestamp"
    },
    {
     "alias": "INFO",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(log_level : info OR log_level : INFO) AND Logger:openstack.neutron",
     "timeField": "@timestamp"
    },
    {
     "alias": "WARN",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(log_level : warn OR log_level : WARN) AND Logger:openstack.neutron",
     "timeField": "@timestamp"
    },
    {
     "alias": "ERROR",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "log_level : error  AND Logger:openstack.neutron",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "API Resp",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 25 },
   "targets": [
    {
     "alias": "400",
     "bucketAggs": [
      { "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "http_status : 400 AND Logger:neutron",
     "timeField": "@timestamp"
    },
    {
     "alias": "404",
     "bucketAggs": [
      { "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "http_status : 404 AND Logger:neutron",
     "timeField": "@timestamp"
    },
    {
     "alias": "409",
     "bucketAggs": [
      { "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(http_status : 401 OR http_status : 409)  AND Logger:neutron",
     "timeField": "@timestamp"
    },
    {
     "alias": "504",
     "bucketAggs": [
      { "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "http_status : 504  AND Logger:neutron",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Hosts",
   "type": "table",
   "gridPos": { "h": 5, "w": 3, "x": 17, "y": 25 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Hostname.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger:openstack.neutron",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Programname",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "programname.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger:openstack.neutron",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Placement", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Placement Logs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 31 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger:openstack.placement",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Log Levels",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 31 },
   "targets": [
    {
     "alias": "DEBUG",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "log_level : DEBUG AND Logger:openstack.placement",
     "timeField": "@timestamp"
    },
    {
     "alias": "INFO",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(log_level : info OR log_level : INFO) AND Logger:openstack.placement",
     "timeField": "@timestamp"
    },
    {
     "alias": "WARN",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(log_level : warn OR log_level : WARN) AND Logger:openstack.placement",
     "timeField": "@timestamp"
    },
    {
     "alias": "ERROR",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "log_level : error  AND Logger:openstack.placement",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "API Resp",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 31 },
   "targets": [
    {
     "alias": "400",
     "bucketAggs": [
      { "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "http_status : 400 AND Logger:placement",
     "timeField": "@timestamp"
    },
    {
     "alias": "404",
     "bucketAggs": [
      { "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "http_status : 404 AND Logger:placement",
     "timeField": "@timestamp"
    },
    {
     "alias": "409",
     "bucketAggs": [
      { "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(http_status : 401 OR http_status : 409)  AND Logger:placement",
     "timeField": "@timestamp"
    },
    {
     "alias": "504",
     "bucketAggs": [
      { "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "http_status : 504  AND Logger:placement",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Hosts",
   "type": "table",
   "gridPos": { "h": 5, "w": 3, "x": 17, "y": 31 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Hostname.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger:openstack.placement",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Programname",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "programname.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger:openstack.placement",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Octavia", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Octavia Logs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 37 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger:openstack.octavia",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Log Levels",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 37 },
   "targets": [
    {
     "alias": "DEBUG",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "log_level : DEBUG AND Logger:openstack.octavia",
     "timeField": "@timestamp"
    },
    {
     "alias": "INFO",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(log_level : info OR log_level : INFO) AND Logger:openstack.octavia",
     "timeField": "@timestamp"
    },
    {
     "alias": "WARN",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(log_level : warn OR log_level : WARN) AND Logger:openstack.octavia",
     "timeField": "@timestamp"
    },
    {
     "alias": "ERROR",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "log_level : error  AND Logger:openstack.octavia",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "API Resp",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 37 },
   "targets": [
    {
     "alias": "400",
     "bucketAggs": [
      { "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "http_status : 400 AND Logger:octavia",
     "timeField": "@timestamp"
    },
    {
     "alias": "404",
     "bucketAggs": [
      { "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "http_status : 404 AND Logger:octavia",
     "timeField": "@timestamp"
    },
    {
     "alias": "409",
     "bucketAggs": [
      { "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(http_status : 401 OR http_status : 409)  AND Logger:octavia",
     "timeField": "@timestamp"
    },
    {
     "alias": "504",
     "bucketAggs": [
      { "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "http_status : 504 AND Logger:octavia",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Hosts",
   "type": "table",
   "gridPos": { "h": 5, "w": 3, "x": 17, "y": 37 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Hostname.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger:openstack.octavia",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Programname",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "programname.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger:openstack.octavia",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Cinder", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Cinder Logs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 43 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger:openstack.cinder",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Log Levels",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 43 },
   "targets": [
    {
     "alias": "DEBUG",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "log_level : DEBUG AND Logger:openstack.cinder",
     "timeField": "@timestamp"
    },
    {
     "alias": "INFO",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(log_level : info OR log_level : INFO) AND Logger:openstack.cinder",
     "timeField": "@timestamp"
    },
    {
     "alias": "WARN",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(log_level : warn OR log_level : WARN) AND Logger:openstack.cinder",
     "timeField": "@timestamp"
    },
    {
     "alias": "ERROR",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "log_level : error  AND Logger:openstack.cinder",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "API Resp",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 43 },
   "targets": [
    {
     "alias": "400",
     "bucketAggs": [
      { "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "http_status : 400 AND Logger:cinder",
     "timeField": "@timestamp"
    },
    {
     "alias": "404",
     "bucketAggs": [
      { "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "http_status : 404 AND Logger:cinder",
     "timeField": "@timestamp"
    },
    {
     "alias": "409",
     "bucketAggs": [
      { "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(http_status : 401 OR http_status : 409)  AND Logger:cinder",
     "timeField": "@timestamp"
    },
    {
     "alias": "504",
     "bucketAggs": [
      { "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "http_status : 504  AND Logger:cinder",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Hosts",
   "type": "table",
   "gridPos": { "h": 5, "w": 3, "x": 17, "y": 43 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Hostname.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger:openstack.cinder",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Programname",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "programname.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger:openstack.cinder",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}