{
 "title": "Openstack Capacity Dashboard",
 "tags": [ "folder-capacity" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1d",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(openstack_identity_up,os_region)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,2m,5m,15m,30m,1h,2h,1d" },
   {
    "name": "project",
    "label": "project",
    "query": {
     "query": "label_values(libvirt_domain_info_meta{job=\"libvirt_exporter\", os_region=\"$cluster\"},project_name)"
    }
   },
   {
    "name": "compute",
    "label": "Compute",
    "query": {
     "query": "label_values(libvirt_up{os_region=\"$cluster\"},compute)"
    }
   },
   {
    "name": "compute_st_gb_lon",
    "label": "Compute_st",
    "query": {
     "query": "label_values(libvirt_up{os_region=\"gb-lon\"},compute)"
    }
   },
   {
    "name": "instance_name",
    "label": "Instance",
    "query": {
     "query": "label_values(libvirt_domain_info_meta{job=\"libvirt_exporter\", project_name=\"${project}\", os_region=\"$cluster\"},instance_name)"
    }
   },
   {
    "name": "tenant_id",
    "label": "Tenant",
    "query": {
     "query": "label_values(openstack_cinder_limits_volume_max_gb{os_region=\"$cluster\", tenant=~\"$project\"},tenant_id)"
    }
   },
   {
    "name": "availability_zone_all",
    "label": "AZ",
    "query": {
     "query": "label_values(openstack_nova_agent_state{os_region=\"$cluster\"},zone)"
    }
   },
   {
    "name": "availability_zone_1",
    "label": "AZ",
    "query": {
     "query": "label_values(openstack_nova_agent_state{os_region=\"$cluster\"},zone)"
    }
   },
   {
    "name": "availability_zone_2",
    "label": "AZ",
    "query": {
     "query": "label_values(openstack_nova_agent_state{os_region=\"$cluster\"},zone)"
    }
   },
   {
    "name": "availability_zone_3",
    "label": "AZ",
    "query": {
     "query": "label_values(openstack_nova_agent_state{os_region=\"$cluster\"},zone)"
    }
   },
   {
    "name": "availability_zone_st_gb_lon",
    "label": "AZ",
    "query": {
     "query": "label_values(openstack_nova_agent_state{os_region=\"gb-lon\"},zone)"
    }
   },
   {
    "name": "az1_hosts",
    "label": "AZ1 Hosts",
    "query": {
     "query": "label_values(openstack_nova_agent_state{zone=\"$availability_zone_1\"},hostname)"
    }
   },
   {
    "name": "az2_hosts",
    "label": "AZ2 Hosts",
    "query": {
     "query": "label_values(openstack_nova_agent_state{zone=\"$availability_zone_2\"},hostname)"
    }
   },
   {
    "name": "az3_hosts",
    "label": "AZ3 Hosts",
    "query": {
     "query": "label_values(openstack_nova_agent_state{zone=\"$availability_zone_3\"},hostname)"
    }
   },
   {
    "name": "st_hosts",
    "label": "AZ3 Hosts",
    "query": {
     "query": "label_values(openstack_nova_agent_state{zone=\"$availability_zone_3\"},hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "GB-LON ST Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Computes GB-LON ST",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(openstack_nova_agent_state{adminState=\"enabled\",hostname=~\"$st_hosts\",zone=\"gb-lon-3\"}) or vector(0)",
       "legendFormat": "Enabled"
      },
      {
       "expr": "sum(openstack_nova_agent_state{adminState=\"disabled\",hostname=~\"$st_hosts\",zone=\"gb-lon-3\"}) or vector(0)",
       "legendFormat": "Disabled"
      },
      { "expression": "$A + $B", "type": "math" }
     ]
    },
    { "title": "vCPU - ST Cluster", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
    {
     "title": "VCPU GB-LON ST",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(openstack_placement_resource_usage{resourcetype=\"VCPU\",os_region=~\"gb-lon\",hostname=~\"$st_hosts\",})",
       "legendFormat": " Used"
      },
      {
       "expr": "sum(openstack_placement_resource_total{resourcetype=\"VCPU\",os_region=~\"gb-lon\",hostname=~\"$st_hosts\"})",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "VCPU Usage Over Time - GB-LON ST",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 15, "x": 4, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(openstack_placement_resource_usage{resourcetype=\"VCPU\",os_region=~\"gb-lon\",hostname=~\"$st_hosts\"})",
       "legendFormat": "vCPU core used"
      },
      {
       "expr": "sum(openstack_placement_resource_total{resourcetype=\"VCPU\",os_region=~\"gb-lon\",hostname=~\"$st_hosts\"})",
       "legendFormat": "vCPU core total"
      }
     ]
    },
    {
     "title": "VCPU Over Commit Ratio - GB-LON ST",
     "type": "stat",
     "gridPos": { "h": 8, "w": 5, "x": 19, "y": 6 },
     "fieldConfig": { "defaults": { "unit": ":1" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expression": "$B/$F", "type": "math" }
     ]
    },
    {
     "title": "VCPU Usage per aggreggate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 19, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(aggregates,os_region)(openstack_nova_vcpus_used{os_region=\"gb-lon\",hostname=~\"$st_hosts\"})",
       "legendFormat": "{{aggregates}}"
      }
     ]
    },
    {
     "title": "vCPU (Broadwell) allocation ratio",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 19, "y": 14 },
     "fieldConfig": { "defaults": { "unit": ":1" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expression": "$C/$D", "type": "math" }
     ]
    },
    {
     "title": "vCPU (Haswell) allocation ratio",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 19, "y": 17 },
     "fieldConfig": { "defaults": { "unit": ":1" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expression": "$C/$D", "type": "math" }
     ]
    },
    {
     "title": "vCPU (Skylake) allocation ratio",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 19, "y": 20 },
     "fieldConfig": { "defaults": { "unit": ":1" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expression": "$C/$D", "type": "math" }
     ]
    },
    { "title": "Memory - ST Cluster", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
    {
     "title": "Memory Usage Over Time GB-LON ST",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 16, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "sum(openstack_placement_resource_total{resourcetype=\"MEMORY_MB\",os_region=~\"gb-lon\",hostname=~\"$st_hosts\"}) \n- sum(openstack_placement_resource_reserved{os_region=~\"$cluster\",resourcetype=\"MEMORY_MB\",hostname=~\"$st_hosts\"}) \n- 3*(max(openstack_placement_resource_total{os_region=~\"$cluster\",resourcetype=\"MEMORY_MB\",hostname=~\"$st_hosts\"}))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(openstack_placement_resource_usage{resourcetype=\"MEMORY_MB\",os_region=~\"gb-lon\",hostname=~\"$st_hosts\"})",
       "legendFormat": "Used"
      },
      {
       "expr": "(sum(openstack_placement_resource_total{resourcetype=\"MEMORY_MB\",os_region=~\"gb-lon\",hostname=~\"$st_hosts\"}) \n- 3*(max(openstack_placement_resource_total{os_region=~\"$cluster\",resourcetype=\"MEMORY_MB\",hostname=~\"$st_hosts\"}))) \n- sum(openstack_placement_resource_usage{resourcetype=\"MEMORY_MB\",os_region=~\"gb-lon\",hostname=~\"$st_hosts\"}) \n- sum(openstack_placement_resource_reserved{os_region=~\"$cluster\",resourcetype=\"MEMORY_MB\",hostname=~\"$st_hosts\"})",
       "legendFormat": "Free"
      }
     ]
    },
    {
     "title": "Actual Usage/Free GB-LON ST",
     "type": "stat",
     "gridPos": { "h": 9, "w": 4, "x": 16, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "sum(libvirt_domain_info_maximum_memory_bytes{job=~\"libvirt_exporter\"} * on(domain) group_left(flavor,instance_name,project_name,user_name) libvirt_domain_info_meta{job=~\"libvirt_exporter\",os_region=\"gb-lon\",project_name=\"st-retail-dev-test\"}) - sum(libvirt_domain_memory_stats_unused_bytes{job=~\"libvirt_exporter\"} * on(domain) group_left(flavor,instance_name,project_name,user_name) libvirt_domain_info_meta{job=~\"libvirt_exporter\",os_region=\"gb-lon\",project_name=\"st-retail-dev-test\"}) + (2.5*sum(openstack_placement_resource_reserved{os_region=~\"gb-lon\",resourcetype=\"MEMORY_MB\",hostname=~\"$st_hosts\"})*1024*1024)",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(node_memory_MemFree_bytes{os_region=\"gb-lon\",instance=~\"$st_hosts\"}) - (2*max(openstack_placement_resource_total{os_region=\"gb-lon\",resourcetype=\"MEMORY_MB\"})*1024*1024)",
       "legendFormat": "Free"
      }
     ]
    },
    {
     "title": "Memory Usage GB-LON ST",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 4, "x": 20, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(openstack_placement_resource_total{resourcetype=\"MEMORY_MB\",os_region=~\"gb-lon\",hostname=~\"$st_hosts\"}) - sum(openstack_placement_resource_usage{resourcetype=\"MEMORY_MB\",os_region=~\"gb-lon\",hostname=~\"$st_hosts\"}) - sum(openstack_placement_resource_reserved{os_region=~\"$cluster\",resourcetype=\"MEMORY_MB\",hostname=~\"$st_hosts\"}) - 1.5*(max(openstack_placement_resource_total{os_region=~\"$cluster\",resourcetype=\"MEMORY_MB\",hostname=~\"$st_hosts\"}))",
       "legendFormat": "Available"
      },
      {
       "expr": "sum(openstack_placement_resource_usage{resourcetype=\"MEMORY_MB\",os_region=~\"gb-lon\",hostname=~\"$st_hosts\"})",
       "legendFormat": " Used"
      }
     ]
    },
    {
     "title": "Memory by aggregate (Broadwell)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(openstack_nova_memory_used_bytes{os_region=\"gb-lon\",aggregates=\"compute_st-dev-broadwell\"})",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(openstack_nova_memory_available_bytes{os_region=\"gb-lon\",aggregates=\"compute_st-dev-broadwell\"} + on(hostname) group_left(hostname,resourcetype) (0* openstack_placement_resource_total{os_region=\"gb-lon\",resourcetype=\"MEMORY_MB\"})) - max((openstack_placement_resource_total{os_region=\"gb-lon\",resourcetype=\"MEMORY_MB\"} + on (hostname) group_left(hostname,aggregates) (0 * openstack_nova_memory_available_bytes{aggregates=\"compute_st-dev-broadwell\"})) * 1024 * 1024)",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Memory by aggregate (Haswell)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by(aggregates,os_region) (openstack_nova_memory_used_bytes{os_region=\"gb-lon\",aggregates=\"compute_st-dev-haswell\"})",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(openstack_nova_memory_available_bytes{os_region=\"gb-lon\",aggregates=\"compute_st-dev-haswell\"} + on(hostname) group_left(hostname,resourcetype) (0* openstack_placement_resource_total{os_region=\"gb-lon\",resourcetype=\"MEMORY_MB\"})) - max((openstack_placement_resource_total{os_region=\"gb-lon\",resourcetype=\"MEMORY_MB\"} + on (hostname) group_left(hostname,aggregates) (0 * openstack_nova_memory_available_bytes{aggregates=\"compute_st-dev-haswell\"})) * 1024 * 1024)",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Memory by aggregate (Skylake)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by(aggregates,os_region) (openstack_nova_memory_used_bytes{os_region=\"gb-lon\",aggregates=\"compute_st-dev-skylake\"})",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(openstack_nova_memory_available_bytes{os_region=\"gb-lon\",aggregates=\"compute_st-dev-skylake\"} + on(hostname) group_left(hostname,resourcetype) (0* openstack_placement_resource_total{os_region=\"gb-lon\",resourcetype=\"MEMORY_MB\"})) - max((openstack_placement_resource_total{os_region=\"gb-lon\",resourcetype=\"MEMORY_MB\"} + on (hostname) group_left(hostname,aggregates) (0 * openstack_nova_memory_available_bytes{aggregates=\"compute_st-dev-skylake\"})) * 1024 * 1024)",
       "legendFormat": "Total"
      }
     ]
    }
   ]
  },
  { "title": "Cluster overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Total Computes $cluster",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_nova_agent_state{adminState=\"enabled\",os_region=~\"$cluster\",service=\"nova-compute\"}) - (sum(openstack_nova_agent_state{adminState=\"enabled\",hostname=~\"$st_hosts\"}) or vector(0)) or vector(0)",
     "legendFormat": "Enabled"
    },
    {
     "expr": "sum(openstack_nova_agent_state{adminState=\"disabled\",os_region=~\"$cluster\",service=\"nova-compute\"}) - (sum(openstack_nova_agent_state{adminState=\"disabled\",hostname=~\"$st_hosts\"}) or vector(0)) or vector(0)",
     "legendFormat": "Disabled"
    },
    { "expression": "$A + $B", "type": "math" }
   ]
  },
  {
   "title": "VCPU $cluster",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_placement_resource_usage{resourcetype=\"VCPU\",os_region=~\"$cluster\"}) - (sum(openstack_placement_resource_usage{resourcetype=\"VCPU\",os_region=~\"$cluster\",hostname=~\"$st_hosts\"}) or vector(0))",
     "legendFormat": "vCPU Used"
    },
    {
     "expr": "sum(openstack_placement_resource_total{os_region=~\"$cluster\",resourcetype=\"VCPU\"})\n- 3*(max(openstack_placement_resource_total{os_region=~\"$cluster\",resourcetype=\"VCPU\"}))\n- sum(openstack_placement_resource_reserved{os_region=~\"$cluster\",resourcetype=\"VCPU\"})\n- (sum(openstack_placement_resource_total{resourcetype=\"VCPU\",hostname=~\"$disabled_hosts\"}) or vector(0))\n- (sum(openstack_placement_resource_total{resourcetype=\"VCPU\",hostname=~\"$st_hosts\"}) or vector(0))",
     "legendFormat": "vCPU Total"
    }
   ]
  },
  {
   "title": "Cluster CPU usage % - $cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - 100 * (avg(irate(node_cpu_seconds_total{instance=~\".*nova.*|.*compute.*\",os_region=\"$cluster\",mode=\"idle\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VCPU  - $cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(openstack_placement_resource_usage{resourcetype=\"VCPU\",os_region=~\"$cluster\"}) - (sum(openstack_placement_resource_usage{resourcetype=\"VCPU\",os_region=~\"$cluster\",hostname=~\"$st_hosts\"}) or vector(0))",
     "legendFormat": "vCPU core used"
    },
    {
     "expr": "sum(openstack_placement_resource_total{os_region=~\"$cluster\",resourcetype=\"VCPU\"})\n- 3*(max(openstack_placement_resource_total{os_region=~\"$cluster\",resourcetype=\"VCPU\"}))\n- sum(openstack_placement_resource_reserved{os_region=~\"$cluster\",resourcetype=\"VCPU\"})\n- (sum(openstack_placement_resource_total{resourcetype=\"VCPU\",hostname=~\"$disabled_hosts\"}) or vector(0))\n- (sum(openstack_placement_resource_total{resourcetype=\"VCPU\",os_region=~\"$cluster\",hostname=~\"$st_hosts\"}) or vector(0))",
     "legendFormat": "vCPU core total"
    }
   ]
  },
  {
   "title": "VCPU Usage ratio",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": ":1" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$B/$F", "type": "math" }
   ]
  },
  {
   "title": "Memory $cluster",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_placement_resource_usage{resourcetype=\"MEMORY_MB\",os_region=~\"$cluster\"})- (sum(openstack_placement_resource_total{resourcetype=\"MEMORY_MB\",os_region=~\"$cluster\",hostname=~\"$st_hosts\"}) or vector(0))",
     "legendFormat": "RAM Used"
    },
    { "expression": "$A-$C", "type": "math" }
   ]
  },
  {
   "title": "Cluster Memory usage % - $cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "($B/$A)", "type": "math" }
   ]
  },
  {
   "title": "Memory $cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(openstack_placement_resource_total{os_region=~\"$cluster\",resourcetype=\"MEMORY_MB\"})\n- 3*(max(openstack_placement_resource_total{os_region=~\"$cluster\",resourcetype=\"MEMORY_MB\"}))\n- sum(openstack_placement_resource_reserved{os_region=~\"$cluster\",resourcetype=\"MEMORY_MB\"})\n- (sum(openstack_placement_resource_total{resourcetype=\"MEMORY_MB\",hostname=~\"$disabled_hosts\"}) or vector(0))\n- (sum(openstack_placement_resource_total{resourcetype=\"MEMORY_MB\",os_region=~\"$cluster\",hostname=~\"$compute_st_gb_lon\"}) or vector(0))",
     "legendFormat": "Memory Total"
    },
    {
     "expr": "sum(openstack_placement_resource_usage{resourcetype=\"MEMORY_MB\",os_region=~\"$cluster\"}) + sum(openstack_placement_resource_reserved{os_region=~\"$cluster\",resourcetype=\"MEMORY_MB\"})- (sum(openstack_placement_resource_total{resourcetype=\"MEMORY_MB\",os_region=\"$cluster\",hostname=~\"$compute_st_gb_lon\"}) or vector(0))",
     "legendFormat": "Memory Used"
    },
    { "expression": "$A-$C", "type": "math" }
   ]
  },
  {
   "title": "AZ overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "AZ1 Computes $cluster",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(openstack_nova_agent_state{adminState=\"enabled\",os_region=~\"$cluster\",zone=\"$availability_zone_1\"}) or vector(0)",
       "legendFormat": "Enabled"
      },
      {
       "expr": "sum(openstack_nova_agent_state{adminState=\"disabled\",os_region=~\"$cluster\",zone=\"$availability_zone_1\"}) or vector(0)",
       "legendFormat": "Disabled"
      },
      { "expression": "$A + $B", "type": "math" }
     ]
    },
    {
     "title": "AZ2 Computes $cluster",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(openstack_nova_agent_state{adminState=\"enabled\",os_region=~\"$cluster\",zone=\"$availability_zone_2\"}) or vector(0)",
       "legendFormat": "Enabled"
      },
      {
       "expr": "sum(openstack_nova_agent_state{adminState=\"disabled\",os_region=~\"$cluster\",zone=\"$availability_zone_2\"}) or vector(0)",
       "legendFormat": "Disabled"
      },
      { "expression": "$A + $B", "type": "math" }
     ]
    },
    {
     "title": "AZ3 Computes $cluster",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(openstack_nova_agent_state{adminState=\"enabled\",os_region=~\"$cluster\",zone=\"$availability_zone_3\"}) - sum(openstack_nova_agent_state{adminState=\"enabled\",hostname=~\"$st_hosts\",zone=\"gb-lon-3\"}) or vector(0)",
       "legendFormat": "Enabled"
      },
      {
       "expr": "sum(openstack_nova_agent_state{adminState=\"disabled\",os_region=~\"$cluster\",zone=\"$availability_zone_3\"}) - sum(openstack_nova_agent_state{adminState=\"disabled\",hostname=~\"$st_hosts\",zone=\"gb-lon-3\"}) or vector(0)",
       "legendFormat": "Disabled"
      },
      { "expression": "$A + $B", "type": "math" }
     ]
    },
    {
     "title": "AZ1 Memory Usage $cluster",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(openstack_placement_resource_total{resourcetype=\"MEMORY_MB\",os_region=~\"$cluster\",hostname=~\"$az1_hosts\"})",
       "legendFormat": "Memory Total"
      },
      {
       "expr": "sum(openstack_placement_resource_total{resourcetype=\"MEMORY_MB\",os_region=~\"$cluster\",hostname=~\"$az1_hosts\"}) - sum(openstack_placement_resource_usage{resourcetype=\"MEMORY_MB\",os_region=~\"$cluster\",hostname=~\"$az1_hosts\"})",
       "legendFormat": "Memory Available"
      },
      {
       "expr": "sum(openstack_placement_resource_usage{resourcetype=\"MEMORY_MB\",os_region=~\"$cluster\",hostname=~\"$az1_hosts\"})",
       "legendFormat": "Memory Used"
      }
     ]
    },
    {
     "title": "AZ2 Memory Usage $cluster",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(openstack_placement_resource_total{resourcetype=\"MEMORY_MB\",os_region=~\"$cluster\",hostname=~\"$az2_hosts\"})",
       "legendFormat": "Memory Total"
      },
      {
       "expr": "sum(openstack_placement_resource_total{resourcetype=\"MEMORY_MB\",os_region=~\"$cluster\",hostname=~\"$az2_hosts\"}) - sum(openstack_placement_resource_usage{resourcetype=\"MEMORY_MB\",os_region=~\"$cluster\",hostname=~\"$az2_hosts\"})",
       "legendFormat": "Memory Available"
      },
      {
       "expr": "sum(openstack_placement_resource_usage{resourcetype=\"MEMORY_MB\",os_region=~\"$cluster\",hostname=~\"$az2_hosts\"})",
       "legendFormat": "Memory Used"
      }
     ]
    },
    {
     "title": "AZ3 Memory Usage $cluster",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(openstack_placement_resource_total{resourcetype=\"MEMORY_MB\",os_region=~\"$cluster\",hostname=~\"$az3_hosts\"}) - (sum(openstack_placement_resource_total{resourcetype=\"MEMORY_MB\",os_region=~\"gb-lon\",hostname=~\"$st_hosts\"}) or vector(0))",
       "legendFormat": "Memory Total"
      },
      {
       "expr": "(sum(openstack_placement_resource_total{resourcetype=\"MEMORY_MB\",os_region=~\"$cluster\",hostname=~\"$az3_hosts\"}) - sum(openstack_placement_resource_usage{resourcetype=\"MEMORY_MB\",os_region=~\"$cluster\",hostname=~\"$az3_hosts\"})) - (sum(openstack_placement_resource_total{resourcetype=\"MEMORY_MB\",os_region=~\"gb-lon\",hostname=~\"$st_hosts\"}) - sum(openstack_placement_resource_usage{resourcetype=\"MEMORY_MB\",os_region=~\"gb-lon\",hostname=~\"$st_hosts\"}) or vector(0))",
       "legendFormat": "Memory Available"
      },
      {
       "expr": "sum(openstack_placement_resource_usage{resourcetype=\"MEMORY_MB\",os_region=~\"$cluster\",hostname=~\"$az3_hosts\"}) - (sum(openstack_placement_resource_usage{resourcetype=\"MEMORY_MB\",os_region=~\"gb-lon\",hostname=~\"$st_hosts\"}) or vector(0))",
       "legendFormat": "Memory Used"
      }
     ]
    },
    {
     "title": "AZ1 VCPU usage $cluster",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 39 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(openstack_placement_resource_usage{resourcetype=\"VCPU\",os_region=~\"$cluster\",hostname=~\"$az1_hosts\"})",
       "legendFormat": "vCPU Used"
      },
      {
       "expr": "sum(openstack_placement_resource_total{resourcetype=\"VCPU\",os_region=~\"$cluster\",hostname=~\"$az1_hosts\"})",
       "legendFormat": "vCPU Total"
      }
     ]
    },
    {
     "title": "AZ2 VCPU usage $cluster",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 39 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(openstack_placement_resource_usage{resourcetype=\"VCPU\",os_region=~\"$cluster\",hostname=~\"$az2_hosts\"})",
       "legendFormat": "vCPU Used"
      },
      {
       "expr": "sum(openstack_placement_resource_total{resourcetype=\"VCPU\",os_region=~\"$cluster\",hostname=~\"$az2_hosts\"})",
       "legendFormat": "vCPU Total"
      }
     ]
    },
    {
     "title": "AZ3 VCPU usage $cluster",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 39 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(openstack_placement_resource_usage{resourcetype=\"VCPU\",os_region=~\"$cluster\",hostname=~\"$az3_hosts\"}) - (sum(openstack_placement_resource_usage{resourcetype=\"VCPU\",os_region=~\"gb-lon\",hostname=~\"$st_hosts\"}) or vector(0))",
       "legendFormat": "vCPU Used"
      },
      {
       "expr": "sum(openstack_placement_resource_total{resourcetype=\"VCPU\",os_region=~\"$cluster\",hostname=~\"$az3_hosts\"}) - (sum(openstack_placement_resource_total{resourcetype=\"VCPU\",os_region=~\"gb-lon\",hostname=~\"$st_hosts\"}) or vector(0))",
       "legendFormat": "vCPU Total"
      }
     ]
    },
    {
     "title": "Disabled Hosts $cluster",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "openstack_nova_agent_state{os_region=~\"$cluster\",service=\"nova-compute\",adminState=\"disabled\"}"
      }
     ]
    }
   ]
  }
 ]
}