{
 "title": "Openstack Logs View",
 "tags": [ "folder-opensearch" ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" },
   { "name": "cluster", "label": "Cluster", "query": "grafana-opensearch-datasource" }
  ]
 },
 "panels": [
  {
   "title": "Faults",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "log_level:warn|error|WARN|ERROR AND Logger:openstack.nova|openstack.neutron|openstack.keystone|openstack.cinder|openstack.glance",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Log Levels",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "WARN",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "log_level : warn|WARN AND Logger:openstack.nova|openstack.neutron|openstack.keystone|openstack.cinder|openstack.glance",
     "timeField": "@timestamp"
    },
    {
     "alias": "ERROR",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "log_level : error|ERROR AND Logger:openstack.nova|openstack.neutron|openstack.keystone|openstack.cinder|openstack.glance",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "API Resp",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 0 },
   "targets": [
    {
     "alias": "400",
     "bucketAggs": [
      { "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "http_status : 400 AND Logger:openstack.nova|openstack.neutron|openstack.keystone|openstack.cinder|openstack.glance",
     "timeField": "@timestamp"
    },
    {
     "alias": "404",
     "bucketAggs": [
      { "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "http_status : 404 AND Logger:openstack.nova|openstack.neutron|openstack.keystone|openstack.cinder|openstack.glance",
     "timeField": "@timestamp"
    },
    {
     "alias": "409",
     "bucketAggs": [
      { "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(http_status : 401 OR http_status : 409) AND Logger:openstack.nova|openstack.neutron|openstack.keystone|openstack.cinder|openstack.glance",
     "timeField": "@timestamp"
    },
    {
     "alias": "504",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "http_status : 504 AND Logger:openstack.nova|openstack.neutron|openstack.keystone|openstack.cinder|openstack.glance",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Hosts",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 13, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Hostname.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": " log_level:warn|error|WARN|ERROR AND Logger:openstack.nova|openstack.neutron|openstack.keystone|openstack.cinder|openstack.glance",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Programname",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "programname.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": " log_level:warn|error|WARN|ERROR AND Logger:openstack.nova|openstack.neutron|openstack.keystone|openstack.cinder|openstack.glance",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Nova ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Faults",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger:openstack.nova AND log_level:warn|error",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Log Levels",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "WARN",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(log_level : warn|WARN) AND Logger:openstack.nova",
     "timeField": "@timestamp"
    },
    {
     "alias": "ERROR",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "log_level : error|ERROR  AND Logger:openstack.nova",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "API Resp",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 6 },
   "targets": [
    {
     "alias": "400",
     "bucketAggs": [
      { "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "http_status : 400 AND Logger:nova",
     "timeField": "@timestamp"
    },
    {
     "alias": "404",
     "bucketAggs": [
      { "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "http_status : 404 AND Logger:nova",
     "timeField": "@timestamp"
    },
    {
     "alias": "409",
     "bucketAggs": [
      { "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(http_status : 401 OR http_status : 409)  AND Logger:nova",
     "timeField": "@timestamp"
    },
    {
     "alias": "504",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "http_status : 504 AND Logger:nova",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Hosts",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 13, "y": 6 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Hostname.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger:openstack.nova AND log_level:warn|error",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Programname",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "programname.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger:openstack.nova",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Log Levels",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "alias": "ERROR",
     "bucketAggs": [
      { "field": "@timestamp", "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "log_level:warn|error|WARN|ERROR AND Logger:openstack.nova",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Nova Logs",
   "type": "logs",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "repeat": "Filters",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "Logger:openstack.nova AND log_level:warn|error",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Neutron", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Faults",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger:openstack.neutron AND log_level:warn|error",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Log Levels",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "WARN",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(log_level : warn OR log_level : WARN) AND Logger:openstack.neutron",
     "timeField": "@timestamp"
    },
    {
     "alias": "ERROR",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "log_level : error  AND Logger:openstack.neutron",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "API Resp",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 19 },
   "targets": [
    {
     "alias": "400",
     "bucketAggs": [
      { "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "http_status : 400 AND Logger:nova",
     "timeField": "@timestamp"
    },
    {
     "alias": "404",
     "bucketAggs": [
      { "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "http_status : 404 AND Logger:nova",
     "timeField": "@timestamp"
    },
    {
     "alias": "409",
     "bucketAggs": [
      { "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(http_status : 401 OR http_status : 409)  AND Logger:nova",
     "timeField": "@timestamp"
    },
    {
     "alias": "504",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "http_status : 504 AND Logger:keystone",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Hosts",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 13, "y": 19 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Hostname.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger:openstack.neutron AND log_level:warn|error",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Programname",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "programname.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger:openstack.neutron AND log_level:warn|error",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Log Levels",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "alias": "ERROR",
     "bucketAggs": [
      { "field": "@timestamp", "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "log_level:warn|error|WARN|ERROR AND Logger:openstack.neutron",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Nova Logs",
   "type": "logs",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "repeat": "Filters",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "Logger:openstack.neutron AND log_level:warn|error",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Keystone", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Faults",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger:openstack.keystone AND log_level:warn|error|WARN|ERROR",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Log Levels",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "WARN",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(log_level : warn|WARN) AND Logger:openstack.keystone",
     "timeField": "@timestamp"
    },
    {
     "alias": "ERROR",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "log_level : error|ERROR  AND Logger:openstack.keystone",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "API Resp",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 32 },
   "targets": [
    {
     "alias": "400",
     "bucketAggs": [
      { "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "http_status : 400 AND Logger:keystone",
     "timeField": "@timestamp"
    },
    {
     "alias": "404",
     "bucketAggs": [
      { "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "http_status : 404 AND Logger:keystone",
     "timeField": "@timestamp"
    },
    {
     "alias": "409",
     "bucketAggs": [
      { "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(http_status : 401 OR http_status : 409)  AND Logger:keystone",
     "timeField": "@timestamp"
    },
    {
     "alias": "504",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "http_status : 504 AND Logger:keystone",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Hosts",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 13, "y": 32 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Hostname.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger:openstack.keystone AND log_level:warn|error",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Programname",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "programname.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger:openstack.keystone",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Log Levels",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "alias": "ERROR",
     "bucketAggs": [
      { "field": "@timestamp", "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "log_level:warn|error|WARN|ERROR AND Logger:openstack.keystone",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Keystone Logs",
   "type": "logs",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "repeat": "Filters",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "Logger:openstack.keystone AND log_level:warn|error",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Cinder", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Faults",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger:openstack.cinder AND log_level:warn|error|WARN|ERROR",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Log Levels",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "WARN",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(log_level : warn OR log_level : WARN) AND Logger:openstack.cinder",
     "timeField": "@timestamp"
    },
    {
     "alias": "ERROR",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "log_level : error  AND Logger:openstack.cinder",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "API Resp",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 45 },
   "targets": [
    {
     "alias": "400",
     "bucketAggs": [
      { "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "http_status : 400 AND Logger:cinder",
     "timeField": "@timestamp"
    },
    {
     "alias": "404",
     "bucketAggs": [
      { "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "http_status : 404 AND Logger:cinder",
     "timeField": "@timestamp"
    },
    {
     "alias": "409",
     "bucketAggs": [
      { "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(http_status : 401 OR http_status : 409)  AND Logger:cinder",
     "timeField": "@timestamp"
    },
    {
     "alias": "504",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "http_status : 504 AND Logger:cinder",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Hosts",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 13, "y": 45 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Hostname.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger:openstack.cinder AND log_level:warn|error",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Programname",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "programname.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger:openstack.cinder",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Log Levels",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "alias": "ERROR",
     "bucketAggs": [
      { "field": "@timestamp", "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "log_level:warn|error|WARN|ERROR AND Logger:openstack.cinder",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Cinder Logs",
   "type": "logs",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "repeat": "Filters",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "Logger:openstack.cinder AND log_level:warn|error",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Octavia", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Faults",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger:openstack.octavia AND log_level:warn|error|WARN|ERROR",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Log Levels",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "WARN",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(log_level : warn|WARN) AND Logger:openstack.octavia",
     "timeField": "@timestamp"
    },
    {
     "alias": "ERROR",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "log_level : error|ERROR  AND Logger:openstack.octavia",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "API Resp",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 58 },
   "targets": [
    {
     "alias": "400",
     "bucketAggs": [
      { "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "http_status : 400 AND Logger:octavia",
     "timeField": "@timestamp"
    },
    {
     "alias": "404",
     "bucketAggs": [
      { "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "http_status : 404 AND Logger:octavia",
     "timeField": "@timestamp"
    },
    {
     "alias": "409",
     "bucketAggs": [
      { "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(http_status : 401 OR http_status : 409)  AND Logger:octavia",
     "timeField": "@timestamp"
    },
    {
     "alias": "504",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "http_status : 504 AND Logger:octavia",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Hosts",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 13, "y": 58 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Hostname.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger:openstack.octavia AND log_level:warn|error|WARN|ERROR",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Programname",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "programname.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger:openstack.octavia AND log_level:warn|error|WARN|ERROR",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Log Levels",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {
     "alias": "ERROR",
     "bucketAggs": [
      { "field": "@timestamp", "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "log_level:warn|error|WARN|ERROR AND Logger:openstack.octavia",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Glance Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 69 },
   "repeat": "Filters",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "Logger:openstack.glance AND log_level:warn|error",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}