{
 "title": "Openstack VM Overview",
 "description": "A dashboard to expose libvirt Metrics and Project Overview",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(openstack_identity_up,os_region)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,2m,5m,15m,30m,1h,2h,1d" },
   {
    "name": "project",
    "label": "project",
    "query": {
     "query": "label_values({job=\"libvirt_exporter\", os_region=\"$cluster\", __name__=~\"libvirt_domain_openstack_info|libvirt_domain_info_meta\"},project_name)"
    }
   },
   {
    "name": "compute",
    "label": "Compute",
    "query": {
     "query": "label_values(libvirt_up{os_region=\"$cluster\"},compute)"
    }
   },
   {
    "name": "instance_name",
    "label": "Instance",
    "query": {
     "query": "label_values(openstack_nova_server_status{os_region=\"$cluster\", tenant_id=~\"$tenant_id\"},name)"
    }
   },
   {
    "name": "domain",
    "label": "Domain",
    "query": {
     "query": "label_values(openstack_nova_server_status{os_region=\"$cluster\", name=~\"$instance_name\"},id)"
    }
   },
   {
    "name": "tenant_id",
    "label": "Tenant",
    "query": {
     "query": "label_values(openstack_cinder_limits_volume_max_gb{os_region=\"$cluster\", tenant=~\"$project\"},tenant_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Instance Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory on VMs",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, libvirt_domain_info_maximum_memory_bytes{domain=~\"$domain\", job=~\"libvirt_exporter\",os_region=~\"$cluster\",compute=~\"$compute\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "topk(5, libvirt_domain_memory_stats_unused_bytes{domain=~\"$domain\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\",compute=~\"$compute\"})",
     "legendFormat": "Available"
    },
    {
     "expr": "topk(5, libvirt_domain_info_maximum_memory_bytes{domain=~\"$domain\", compute=~\"$compute\", job=~\"libvirt_exporter\",os_region=~\"$cluster\"} - libvirt_domain_memory_stats_unused_bytes{domain=~\"$domain\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "VM State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "libvirt_domain_info_vstate{domain=~\"$domain\",compute=~\"$compute\", job=~\"libvirt_exporter\"} or libvirt_domain_info_state{domain=~\"$domain\",compute=~\"$compute\", job=~\"libvirt_exporter\"}",
     "legendFormat": "Running"
    }
   ]
  },
  {
   "title": "RX/TX Throughput on VM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(libvirt_domain_interface_stats_receive_bytes_total{domain=~\"$domain\",job=~\"libvirt_exporter\",compute=~\"$compute\"}[$__rate_interval]))*8 or on() vector(0)",
     "legendFormat": "RX Bytes"
    },
    {
     "expr": "sum(rate(libvirt_domain_interface_stats_transmit_bytes_total{domain=~\"$domain\",job=~\"libvirt_exporter\",compute=~\"$compute\"}[$__rate_interval]))*8",
     "legendFormat": "TX Bytes"
    }
   ]
  },
  {
   "title": "RX/TX Packets Per Sec on VMs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(libvirt_domain_interface_stats_receive_packets_total{domain=~\"$domain\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"}[$__rate_interval])) or on() vector(0)",
     "legendFormat": "RX Packets"
    },
    {
     "expr": "sum(rate(libvirt_domain_interface_stats_transmit_packets_total{domain=~\"$domain\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"}[$__rate_interval])) or on() vector(0)",
     "legendFormat": "TX Packets"
    }
   ]
  },
  {
   "title": "IOPS R/W on VMs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(rate(libvirt_domain_block_stats_read_requests_total{domain=~\"$domain\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(rate(libvirt_domain_block_stats_write_requests_total{domain=~\"$domain\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "IOPS R/W on VM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(libvirt_domain_block_stats_read_requests_total{domain=~\"$domain\",compute=~\"$compute\",job=~\"libvirt_exporter\"}[$__rate_interval])) or on() vector(0)",
     "legendFormat": "Read IOPS"
    },
    {
     "expr": "sum(rate(libvirt_domain_block_stats_write_requests_total{domain=~\"$domain\",compute=~\"$compute\",job=~\"libvirt_exporter\"}[$__rate_interval])) or on() vector(0)",
     "legendFormat": "Write IOPS"
    }
   ]
  },
  {
   "title": "Throughput R/W on VM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(libvirt_domain_block_stats_read_bytes_total{domain=~\"$domain\", compute=~\"$compute\", job=~\"libvirt_exporter\"}[$__rate_interval])) or on() vector(0)",
     "legendFormat": "Read Bytes"
    },
    {
     "expr": "sum(rate(libvirt_domain_block_stats_write_bytes_total{domain=~\"$domain\", compute=~\"$compute\", job=~\"libvirt_exporter\"}[$__rate_interval]))",
     "legendFormat": "Write Bytes"
    }
   ]
  },
  {
   "title": "RX/TX Packets Drop on VMs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(libvirt_domain_interface_stats_receive_drops_total{domain=~\"$domain\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "RX Packets"
    },
    {
     "expr": "sum(rate(libvirt_domain_interface_stats_transmit_drops_total{domain=~\"$domain\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "TX Packets"
    }
   ]
  },
  {
   "title": "RX/TX Packets Error on VMs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(libvirt_domain_interface_stats_receive_errors_total{domain=~\"$domain\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "RX Packets"
    },
    {
     "expr": "sum(rate(libvirt_domain_interface_stats_transmit_errors_total{domain=~\"$domain\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "TX Packets"
    }
   ]
  },
  {
   "title": "VMs Stats",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "libvirt_domain_info_virtual_cpus{domain=~\"$domain\",compute=~\"$compute\", job=~\"libvirt_exporter\"}  * on(domain) group_left(flavor,instance_name,project_name,user_name) libvirt_domain_info_meta{domain=~\"$domain\",job=~\"libvirt_exporter\",compute=~\"$compute\"}",
     "legendFormat": "vCPU Total"
    },
    {
     "expr": "(avg by (domain) (irate(libvirt_domain_info_cpu_time_seconds_total{domain=~\"$domain\",compute=~\"$compute\",job=~\"libvirt_exporter\"}[$__rate_interval])) * 100)",
     "legendFormat": "vCPU Used"
    },
    {
     "expr": "libvirt_domain_info_maximum_memory_bytes{domain=~\"$domain\",compute=~\"$compute\", job=~\"libvirt_exporter\"}",
     "legendFormat": "Memory Total"
    },
    {
     "expr": "(libvirt_domain_info_maximum_memory_bytes{domain=~\"$domain\",compute=~\"$compute\", job=~\"libvirt_exporter\"} - libvirt_domain_memory_stats_unused_bytes{domain=~\"$domain\",compute=~\"$compute\",job=~\"libvirt_exporter\"})",
     "legendFormat": "Memory Used"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "vCPU Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(20, libvirt_domain_info_virtual_cpus{domain=~\"$domain\",job=~\"libvirt_exporter\",compute=~\"$compute\"} * on(domain) group_left(flavor,instance_name,project_name,user_name) (libvirt_domain_info_meta{domain=~\"$domain\",job=~\"libvirt_exporter\",compute=~\"$compute\"} or libvirt_domain_openstack_info{domain=~\"$domain\",job=~\"libvirt_exporter\",compute=~\"$compute\"}))",
     "legendFormat": "{{instance_name}}"
    }
   ]
  },
  {
   "title": "vCPU Usage on VM",
   "type": "timeseries",
   "description": "100% = 1 Thread",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(20, avg by (domain,instance_name) (irate(libvirt_domain_info_cpu_time_seconds_total{domain=~\"$domain\",job=~\"libvirt_exporter\",compute=~\"$compute\"}[$__rate_interval]) * on(domain) group_left(flavor,instance_name,project_name,user_name) (libvirt_domain_info_meta{domain=~\"$domain\",job=~\"libvirt_exporter\",compute=~\"$compute\"} or libvirt_domain_openstack_info{domain=~\"$domain\",job=~\"libvirt_exporter\",compute=~\"$compute\"})) * 100)",
     "legendFormat": "{{instance_name}}"
    }
   ]
  },
  {
   "title": "vCPU Steal Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(20, avg by (domain,instance_name) (irate(libvirt_domain_vcpu_delay_seconds_total{domain=~\"$domain\",job=~\"libvirt_exporter\",compute=~\"$compute\"}[$__rate_interval]) * on(domain) group_left(flavor,instance_name,project_name,user_name) (libvirt_domain_info_meta{domain=~\"$domain\",job=~\"libvirt_exporter\",compute=~\"$compute\"} or libvirt_domain_openstack_info{domain=~\"$domain\",job=~\"libvirt_exporter\",compute=~\"$compute\"})) * 100)",
     "legendFormat": "{{instance_name}}"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "IOPS Read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "topk(10, rate(libvirt_domain_block_stats_read_requests_total{domain=~\"$domain\",job=~\"libvirt_exporter\",compute=~\"$compute\"}[$__rate_interval] * on(domain) group_left(flavor,instance_name,project_name,user_name) (libvirt_domain_info_meta{domain=~\"$domain\",job=~\"libvirt_exporter\",compute=~\"$compute\"} or libvirt_domain_openstack_info{domain=~\"$domain\",job=~\"libvirt_exporter\",compute=~\"$compute\"})))",
     "legendFormat": "{{instance_name}} - {{target_device}}"
    }
   ]
  },
  {
   "title": "IOPS Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "topk(10, rate(libvirt_domain_block_stats_write_requests_total{domain=~\"$domain\",job=~\"libvirt_exporter\",compute=~\"$compute\"}[$__rate_interval]) * on(domain) group_left(flavor,instance_name,project_name,user_name) (libvirt_domain_info_meta{domain=~\"$domain\",job=~\"libvirt_exporter\",compute=~\"$compute\"} or libvirt_domain_openstack_info{domain=~\"$domain\",job=~\"libvirt_exporter\",compute=~\"$compute\"}))",
     "legendFormat": "{{instance_name}} - {{target_device}}"
    }
   ]
  },
  {
   "title": "Throughput Read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(10, rate(libvirt_domain_block_stats_read_bytes_total{domain=~\"$domain\",job=~\"libvirt_exporter\",compute=~\"$compute\"}[$__rate_interval]) * on(domain) group_left(flavor,instance_name,project_name,user_name) (libvirt_domain_info_meta{domain=~\"$domain\",job=~\"libvirt_exporter\",compute=~\"$compute\"} or libvirt_domain_openstack_info{domain=~\"$domain\",job=~\"libvirt_exporter\",compute=~\"$compute\"})) or on() vector(0)",
     "legendFormat": "{{instance_name}} - {{target_device}}"
    }
   ]
  },
  {
   "title": "Throughput Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(10, rate(libvirt_domain_block_stats_write_bytes_total{domain=~\"$domain\",job=~\"libvirt_exporter\",compute=~\"$compute\"}[$__rate_interval]) * on(domain) group_left(flavor,instance_name,project_name,user_name) (libvirt_domain_info_meta{domain=~\"$domain\",job=~\"libvirt_exporter\",compute=~\"$compute\"} or libvirt_domain_openstack_info{domain=~\"$domain\",job=~\"libvirt_exporter\",compute=~\"$compute\"})) or on() vector(0)",
     "legendFormat": "{{instance_name}} - {{target_device}}"
    }
   ]
  },
  {
   "title": "Write time",
   "type": "timeseries",
   "description": "Total time (ns) spent on writes on a block device, in ns, that is, 1/1,000,000,000 of a second, or 10−9 seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(libvirt_domain_block_stats_write_time_seconds_total{domain=~\"$domain\", job=~\"libvirt_exporter\"}[$__rate_interval]* on(domain) group_left(flavor,instance_name,project_name,user_name) (libvirt_domain_info_meta{domain=~\"$domain\",job=~\"libvirt_exporter\"} or libvirt_domain_openstack_info{domain=~\"$domain\",job=~\"libvirt_exporter\"}))",
     "legendFormat": "{{instance_name}} - write"
    }
   ]
  },
  {
   "title": "Read  time",
   "type": "timeseries",
   "description": "Total time (ns) spent on read  on a block device, in ns, that is, 1/1,000,000,000 of a second, or 10−9 seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(20, irate(libvirt_domain_block_stats_read_time_seconds_total{domain=~\"$domain\", job=~\"libvirt_exporter\", compute=~\"$compute\"}[$__rate_interval] * on(domain) group_left(flavor,instance_name,project_name,user_name) libvirt_domain_info_meta{domain=~\"$domain\",job=~\"libvirt_exporter\",compute=~\"$compute\"}))",
     "legendFormat": "{{instance_name}} - write"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(10, libvirt_domain_info_maximum_memory_bytes{domain=~\"$domain\", job=~\"libvirt_exporter\",compute=~\"$compute\"} * on(domain) group_left(flavor,instance_name,project_name,user_name) (libvirt_domain_info_meta{domain=~\"$domain\",job=~\"libvirt_exporter\",compute=~\"$compute\"} or libvirt_domain_openstack_info{domain=~\"$domain\",job=~\"libvirt_exporter\",compute=~\"$compute\"}))",
     "legendFormat": "{{instance_name}}"
    }
   ]
  },
  {
   "title": "Available",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(20, libvirt_domain_memory_stats_unused_bytes{domain=~\"$domain\", job=~\"libvirt_exporter\",compute=~\"$compute\"} * on(domain) group_left(flavor,instance_name,project_name,user_name) (libvirt_domain_info_meta{domain=~\"$domain\",job=~\"libvirt_exporter\",compute=~\"$compute\"} or libvirt_domain_openstack_info{domain=~\"$domain\",job=~\"libvirt_exporter\",compute=~\"$compute\"}))",
     "legendFormat": "{{instance_name}}"
    }
   ]
  },
  {
   "title": "Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(20, libvirt_domain_info_maximum_memory_bytes{domain=~\"$domain\",job=~\"libvirt_exporter\",compute=~\"$compute\"} - libvirt_domain_memory_stats_unused_bytes{domain=~\"$domain\",job=~\"libvirt_exporter\",compute=~\"$compute\"}) * on(domain) group_left(flavor,instance_name,project_name,user_name) (libvirt_domain_info_meta{domain=~\"$domain\",job=~\"libvirt_exporter\",compute=~\"$compute\"} or libvirt_domain_openstack_info{domain=~\"$domain\",job=~\"libvirt_exporter\",compute=~\"$compute\"})",
     "legendFormat": "{{instance_name}}"
    }
   ]
  },
  {
   "title": "Resident Set Size",
   "type": "timeseries",
   "description": "Resident Set Size of the process running the domain, in bytes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(20, libvirt_domain_memory_stats_rss_bytes{domain=~\"$domain\",compute=~\"$compute\", job=~\"libvirt_exporter\"} * on(domain) group_left(flavor,instance_name,project_name,user_name) (libvirt_domain_info_meta{domain=~\"$domain\",job=~\"libvirt_exporter\",compute=~\"$compute\"} or libvirt_domain_openstack_info{domain=~\"$domain\",job=~\"libvirt_exporter\",compute=~\"$compute\"}))",
     "legendFormat": "{{instance_name}}"
    }
   ]
  },
  {
   "title": "Swap Read",
   "type": "timeseries",
   "description": "The total amount of data read from swap space",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "libvirt_domain_stat_memory_swap_in_bytes{compute=~\"$compute\", job=~\"libvirt_exporter\"}",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "Swap Written",
   "type": "timeseries",
   "description": "The total amount of memory written out to swap space",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "libvirt_domain_stat_memory_swap_out_bytes{compute=~\"$compute\", job=~\"libvirt_exporter\"}",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "RX Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "topk(10, rate(libvirt_domain_interface_stats_receive_bytes_total{domain=~\"$domain\",job=~\"libvirt_exporter\",compute=~\"$compute\"}[$__rate_interval] * on(domain) group_left(flavor,instance_name,project_name,user_name) (libvirt_domain_info_meta{domain=~\"$domain\",job=~\"libvirt_exporter\",compute=~\"$compute\"} or libvirt_domain_openstack_info{domain=~\"$domain\",job=~\"libvirt_exporter\",compute=~\"$compute\"}))*8)",
     "legendFormat": "{{instance_name}} - {{target_device}}"
    }
   ]
  },
  {
   "title": "TX Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "topk(10, rate(libvirt_domain_interface_stats_transmit_bytes_total{domain=~\"$domain\",job=~\"libvirt_exporter\",compute=~\"$compute\"}[$__rate_interval] * on(domain) group_left(flavor,instance_name,project_name,user_name) (libvirt_domain_info_meta{domain=~\"$domain\",job=~\"libvirt_exporter\",compute=~\"$compute\"} or libvirt_domain_openstack_info{domain=~\"$domain\",job=~\"libvirt_exporter\",compute=~\"$compute\"}))*8)",
     "legendFormat": "{{instance_name}} - {{target_device}}"
    }
   ]
  },
  {
   "title": "RX Packets",
   "type": "timeseries",
   "description": "Number of packets received on a network interface.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "topk(10, rate(libvirt_domain_interface_stats_receive_packets_total{domain=~\"$domain\",job=~\"libvirt_exporter\",compute=~\"$compute\"}[$__rate_interval]) * on(domain) group_left(flavor,instance_name,project_name,user_name) (libvirt_domain_info_meta{domain=~\"$domain\",job=~\"libvirt_exporter\",compute=~\"$compute\"} or libvirt_domain_openstack_info{domain=~\"$domain\",job=~\"libvirt_exporter\",compute=~\"$compute\"}))",
     "legendFormat": "{{instance_name}} - {{target_device}}"
    }
   ]
  },
  {
   "title": "TX Packets",
   "type": "timeseries",
   "description": "Number of packets transmitted on a network interface.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "topk(10, rate(libvirt_domain_interface_stats_transmit_packets_total{domain=~\"$domain\",job=~\"libvirt_exporter\",compute=~\"$compute\"}[$__rate_interval]) * on(domain) group_left(flavor,instance_name,project_name,user_name) (libvirt_domain_info_meta{domain=~\"$domain\",job=~\"libvirt_exporter\",compute=~\"$compute\"} or libvirt_domain_openstack_info{domain=~\"$domain\",job=~\"libvirt_exporter\",compute=~\"$compute\"}))",
     "legendFormat": "{{instance_name}} - {{target_device}}"
    }
   ]
  },
  {
   "title": "RX Packets Error",
   "type": "timeseries",
   "description": "Number of packet receive errors on a network interface.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "topk(10, rate(libvirt_domain_interface_stats_receive_errors_total{domain=~\"$domain\",job=~\"libvirt_exporter\",compute=~\"$compute\"}[$__rate_interval] * on(domain) group_left(flavor,instance_name,project_name,user_name) (libvirt_domain_info_meta{domain=~\"$domain\",job=~\"libvirt_exporter\",compute=~\"$compute\"} or libvirt_domain_openstack_info{domain=~\"$domain\",job=~\"libvirt_exporter\",compute=~\"$compute\"})))",
     "legendFormat": "{{instance_name}} - {{target_device}}"
    }
   ]
  },
  {
   "title": "TX Packets Error",
   "type": "timeseries",
   "description": "Number of packet transmit errors on a network interface",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(libvirt_domain_interface_stats_transmit_errors_total{domain=~\"$domain\",compute=~\"$compute\", job=~\"libvirt_exporter\"}[$__rate_interval] * on(domain) group_left(flavor,instance_name,project_name,user_name) (libvirt_domain_info_meta{domain=~\"$domain\",job=~\"libvirt_exporter\",compute=~\"$compute\"} or libvirt_domain_openstack_info{domain=~\"$domain\",job=~\"libvirt_exporter\",compute=~\"$compute\"}))",
     "legendFormat": "{{instance_name}} - {{target_device}}"
    }
   ]
  },
  {
   "title": "RX Packets Drop",
   "type": "timeseries",
   "description": "Number of packet receive drops on a network interface.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(libvirt_domain_interface_stats_receive_drops_total{domain=~\"$domain\",compute=~\"$compute\", job=~\"libvirt_exporter\"}[$__rate_interval] * on(domain) group_left(flavor,instance_name,project_name,user_name) (libvirt_domain_info_meta{domain=~\"$domain\",job=~\"libvirt_exporter\",compute=~\"$compute\"} or libvirt_domain_openstack_info{domain=~\"$domain\",job=~\"libvirt_exporter\",compute=~\"$compute\"}))",
     "legendFormat": "{{instance_name}} - {{target_device}}"
    }
   ]
  },
  {
   "title": "TX Packets Drop",
   "type": "timeseries",
   "description": "Number of packet transmit drops on a network interface.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(libvirt_domain_interface_stats_transmit_drops_total{domain=~\"$domain\",compute=~\"$compute\", job=~\"libvirt_exporter\"}[$__rate_interval] * on(domain) group_left(flavor,instance_name,project_name,user_name) (libvirt_domain_info_meta{domain=~\"$domain\",job=~\"libvirt_exporter\",compute=~\"$compute\"} or libvirt_domain_openstack_info{domain=~\"$domain\",job=~\"libvirt_exporter\",compute=~\"$compute\"}))",
     "legendFormat": "{{instance_name}} - {{target_device}}"
    }
   ]
  }
 ]
}