{
 "title": "OpenStack Dashboardv2",
 "description": "Openstack dashboard using the Openstack Exporter",
 "tags": [
  "openstack",
  "openstack-exporter",
  "folder-openstack"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(os_region)" } },
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Volume by Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(openstack_cinder_volume_status_counter{os_region=~\"$cluster\"}) by (status) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Available volumes/PVC by tenant",
   "type": "table",
   "gridPos": { "h": 14, "w": 8, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(openstack_cinder_volume_gb{os_region=~\"$cluster\",status=\"available\"}) by (tenant_id) > 5",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Instance by status",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(openstack_nova_server_status{os_region=~\"$cluster\"}) by (status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Space allocated to available volumes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_cinder_volume_gb{status=\"available\",os_region=~\"$cluster\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Volume Types",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(openstack_cinder_volume_gb{os_region=~\"$cluster\",bootable=\"true\"})",
     "legendFormat": "Bootable"
    },
    {
     "expr": "count(openstack_cinder_volume_gb{os_region=~\"$cluster\",bootable=\"false\"})",
     "legendFormat": "Not bootable"
    },
    {
     "expr": "count(openstack_cinder_volume_gb{os_region=~\"$cluster\",name=~\"pvc-(.*)\"})",
     "legendFormat": "PVC"
    },
    {
     "expr": "count(openstack_cinder_volume_gb{os_region=~\"$cluster\",name=~\"pvc-(.*)\",status=\"available\"})",
     "legendFormat": "PVC Available"
    }
   ]
  },
  {
   "title": "Network Stats",
   "type": "stat",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_neutron_floating_ips{os_region=~\"$cluster\"}) ",
     "legendFormat": "floating ips"
    },
    {
     "expr": "sum(openstack_neutron_networks{os_region=~\"$cluster\"})",
     "legendFormat": "networks"
    },
    {
     "expr": "sum(openstack_neutron_security_groups{os_region=~\"$cluster\"})",
     "legendFormat": "security groups"
    },
    {
     "expr": "sum(openstack_neutron_subnets{os_region=~\"$cluster\"})",
     "legendFormat": "subnets"
    },
    {
     "expr": "count(openstack_neutron_port{os_region=~\"$cluster\"})",
     "legendFormat": "ports"
    }
   ]
  },
  {
   "title": "VMs per AZ",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 9, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count by (availability_zone)(openstack_nova_server_status{os_region=~\"$cluster\"}) > 1",
     "legendFormat": "{{availability_zone}}"
    }
   ]
  },
  {
   "title": "Volume Qos",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 9, "x": 15, "y": 14 },
   "targets": [
    {
     "expr": "count(openstack_cinder_volume_gb{}) by (volume_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Nova agents down",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(openstack_nova_agent_state{adminState=\"enabled\",os_region=~\"$cluster\"})-sum(openstack_nova_agent_state{adminState=\"enabled\",os_region=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Nova agent status",
     "type": "table",
     "gridPos": { "h": 8, "w": 19, "x": 3, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "openstack_nova_agent_state{adminState=\"enabled\",os_region=~\"$cluster\"}"
      }
     ]
    },
    {
     "title": "Nova agents up",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(openstack_nova_agent_state{adminState=\"enabled\",os_region=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Cinder agents down",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "(count(openstack_cinder_agent_state{adminState=\"enabled\",os_region=~\"$cluster\"})-sum(openstack_cinder_agent_state{adminState=\"enabled\",os_region=~\"$cluster\"}))"
      }
     ]
    },
    {
     "title": "Cinder agent status",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 19, "x": 3, "y": 36 },
     "targets": [
      {
       "expr": "openstack_cinder_agent_state{os_region=~\"$cluster\"}"
      }
     ]
    },
    {
     "title": "Cinder agent up",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(openstack_cinder_agent_state{adminState=\"enabled\",os_region=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Neutron agents down",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "count(openstack_neutron_agent_state{adminState=\"up\",os_region=~\"$cluster\"})-sum(openstack_neutron_agent_state{adminState=\"up\",os_region=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Neutron agent status",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 19, "x": 3, "y": 44 },
     "targets": [
      {
       "expr": "openstack_neutron_agent_state{os_region=~\"$cluster\"}"
      }
     ]
    },
    {
     "title": "Neutron agents up",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(openstack_neutron_agent_state{adminState=\"up\",os_region=~\"$cluster\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Overall memory usage (TiB)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(openstack_placement_resource_total{resourcetype=\"MEMORY_MB\",os_region=~\"$cluster\"})",
     "legendFormat": "memory total"
    },
    {
     "expr": "sum(openstack_placement_resource_total{resourcetype=\"MEMORY_MB\",os_region=~\"$cluster\"}) - sum(openstack_placement_resource_usage{resourcetype=\"MEMORY_MB\",os_region=~\"$cluster\"})",
     "legendFormat": "memory available"
    },
    {
     "expr": "sum(openstack_placement_resource_usage{resourcetype=\"MEMORY_MB\",os_region=~\"$cluster\"})",
     "legendFormat": "memory used"
    }
   ]
  },
  {
   "title": "Overall CPU cores usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(openstack_placement_resource_usage{resourcetype=\"VCPU\",os_region=~\"$cluster\"})",
     "legendFormat": "used vcpu cores"
    },
    {
     "expr": "sum(openstack_placement_resource_total{resourcetype=\"VCPU\",os_region=~\"$cluster\"})",
     "legendFormat": "total vcpu cores"
    }
   ]
  },
  {
   "title": "Local Storage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "sum(openstack_placement_resource_usage{resourcetype=\"DISK_GB\",os_region=~\"$cluster\"})",
     "legendFormat": "local storage used"
    },
    {
     "expr": "sum(openstack_placement_resource_total{resourcetype=\"DISK_GB\",os_region=~\"$cluster\"})",
     "legendFormat": "local storage available"
    }
   ]
  },
  {
   "title": "Neutron Stats",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(openstack_neutron_floating_ips) ",
     "legendFormat": "floating ips"
    },
    {
     "expr": "avg(openstack_neutron_networks{os_region=~\"$cluster\"})",
     "legendFormat": "networks"
    },
    {
     "expr": "avg(openstack_neutron_security_groups{os_region=~\"$cluster\"})",
     "legendFormat": "security groups"
    },
    {
     "expr": "avg(openstack_neutron_subnets{os_region=~\"$cluster\"})",
     "legendFormat": "subnets"
    },
    {
     "expr": "count(openstack_neutron_port{os_region=~\"$cluster\"})",
     "legendFormat": "ports"
    }
   ]
  },
  {
   "title": "Keystone stats",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(openstack_identity_projects{os_region=~\"$cluster\"})",
     "legendFormat": "projects"
    },
    {
     "expr": "avg(openstack_identity_users{os_region=~\"$cluster\"})",
     "legendFormat": "users"
    },
    {
     "expr": "avg(openstack_identity_groups{os_region=~\"$cluster\"})",
     "legendFormat": "groups"
    }
   ]
  },
  {
   "title": "Virtual Machines",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(openstack_nova_running_vms{os_region=~\"$cluster\"})",
     "legendFormat": "running vms"
    },
    {
     "expr": "sum(openstack_nova_total_vms{os_region=~\"$cluster\"})",
     "legendFormat": "total vms"
    }
   ]
  },
  {
   "title": "Cinder volumes/snapshots",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(openstack_cinder_volumes{os_region=~\"$cluster\"})",
     "legendFormat": "volumes"
    },
    {
     "expr": "avg(openstack_cinder_snapshots{os_region=~\"$cluster\"})",
     "legendFormat": "snapshots"
    }
   ]
  },
  {
   "title": "Glance Images",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(openstack_glance_images{os_region=~\"$cluster\"})",
     "legendFormat": "images"
    }
   ]
  },
  { "title": "PVC Data Exporter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Data exporter for PVC Volumes",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "openstack_cinder_volume_gb{name=~\"pvc-(.*)\",os_region=~\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}