{
 "title": "Openstack Capacity Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1d",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(libvirt_versions_info,os_region)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,2m,5m,15m,30m,1h,2h,1d" },
   {
    "name": "project",
    "label": "project",
    "query": {
     "query": "label_values(libvirt_domain_info_meta{job=\"libvirt_exporter\", os_region=\"$cluster\"},project_name)"
    }
   },
   {
    "name": "compute",
    "label": "Compute",
    "query": {
     "query": "label_values(libvirt_up{os_region=\"$cluster\"},compute)"
    }
   },
   {
    "name": "instance_name",
    "label": "Instance",
    "query": {
     "query": "label_values(libvirt_domain_info_meta{job=\"libvirt_exporter\", project_name=\"${project}\", os_region=\"$cluster\"},instance_name)"
    }
   },
   {
    "name": "virtual_machine",
    "label": "VM",
    "query": {
     "query": "label_values(libvirt_domain_info_meta{job=\"libvirt_exporter\", project_name=\"${project}\", os_region=\"$cluster\", instance_name=~\"$instance_name\"},domain)"
    }
   },
   {
    "name": "tenant_id",
    "label": "Tenant",
    "query": {
     "query": "label_values(openstack_cinder_limits_volume_max_gb{os_region=\"$cluster\", tenant=~\"$project\"},tenant_id)"
    }
   },
   {
    "name": "availability_zone_all",
    "label": "AZ",
    "query": {
     "query": "label_values(openstack_nova_agent_state{os_region=\"$cluster\"},zone)"
    }
   },
   {
    "name": "availability_zone_1",
    "label": "AZ",
    "query": {
     "query": "label_values(openstack_nova_agent_state{os_region=\"$cluster\"},zone)"
    }
   },
   {
    "name": "availability_zone_2",
    "label": "AZ",
    "query": {
     "query": "label_values(openstack_nova_agent_state{os_region=\"$cluster\"},zone)"
    }
   },
   {
    "name": "availability_zone_3",
    "label": "AZ",
    "query": {
     "query": "label_values(openstack_nova_agent_state{os_region=\"$cluster\"},zone)"
    }
   },
   {
    "name": "az1_hosts",
    "label": "AZ1 Hosts",
    "query": {
     "query": "label_values(openstack_nova_agent_state{zone=\"$availability_zone_1\"},hostname)"
    }
   },
   {
    "name": "az2_hosts",
    "label": "AZ2 Hosts",
    "query": {
     "query": "label_values(openstack_nova_agent_state{zone=\"$availability_zone_2\"},hostname)"
    }
   },
   {
    "name": "az3_hosts",
    "label": "AZ3 Hosts",
    "query": {
     "query": "label_values(openstack_nova_agent_state{zone=\"$availability_zone_3\"},hostname)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Computes $cluster",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_nova_agent_state{adminState=\"enabled\",os_region=~\"$cluster\"}) or vector(0)",
     "legendFormat": "Enabled"
    },
    {
     "expr": "sum(openstack_nova_agent_state{adminState=\"disabled\",os_region=~\"$cluster\"}) or vector(0)",
     "legendFormat": "Disabled"
    },
    { "expression": "$A + $B", "type": "math" }
   ]
  },
  {
   "title": "VCPU usage $cluster",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_placement_resource_usage{resourcetype=\"VCPU\",os_region=~\"$cluster\"})",
     "legendFormat": "vCPU Used"
    },
    {
     "expr": "sum(openstack_placement_resource_total{resourcetype=\"VCPU\",os_region=~\"$cluster\"})",
     "legendFormat": "vCPU Total"
    }
   ]
  },
  {
   "title": "VCPU Usage Over Time - $cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(openstack_placement_resource_usage{resourcetype=\"VCPU\",os_region=~\"$cluster\"})",
     "legendFormat": "vCPU core used"
    },
    {
     "expr": "sum(openstack_placement_resource_total{resourcetype=\"VCPU\",os_region=~\"$cluster\"})",
     "legendFormat": "vCPU core total"
    }
   ]
  },
  {
   "title": "Memory Usage $cluster",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_placement_resource_total{resourcetype=\"MEMORY_MB\",os_region=~\"$cluster\"}) - sum(openstack_placement_resource_usage{resourcetype=\"MEMORY_MB\",os_region=~\"$cluster\"})",
     "legendFormat": "Memory Available"
    },
    {
     "expr": "sum(openstack_placement_resource_usage{resourcetype=\"MEMORY_MB\",os_region=~\"$cluster\"})",
     "legendFormat": "Memory Used"
    }
   ]
  },
  {
   "title": "Memory Usage Over Time $cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(openstack_placement_resource_total{resourcetype=\"MEMORY_MB\",os_region=~\"$cluster\"})",
     "legendFormat": "Memory Total"
    },
    {
     "expr": "sum(openstack_placement_resource_usage{resourcetype=\"MEMORY_MB\",os_region=~\"$cluster\"})",
     "legendFormat": "Memory Used"
    }
   ]
  },
  { "title": "AZ overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "AZ1 Computes $cluster",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_nova_agent_state{adminState=\"enabled\",os_region=~\"$cluster\",zone=\"$availability_zone_1\"}) or vector(0)",
     "legendFormat": "Enabled"
    },
    {
     "expr": "sum(openstack_nova_agent_state{adminState=\"disabled\",os_region=~\"$cluster\",zone=\"$availability_zone_1\"}) or vector(0)",
     "legendFormat": "Disabled"
    },
    { "expression": "$A + $B", "type": "math" }
   ]
  },
  {
   "title": "AZ2 Computes $cluster",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_nova_agent_state{adminState=\"enabled\",os_region=~\"$cluster\",zone=\"$availability_zone_2\"}) or vector(0)",
     "legendFormat": "Enabled"
    },
    {
     "expr": "sum(openstack_nova_agent_state{adminState=\"disabled\",os_region=~\"$cluster\",zone=\"$availability_zone_2\"}) or vector(0)",
     "legendFormat": "Disabled"
    },
    { "expression": "$A + $B", "type": "math" }
   ]
  },
  {
   "title": "AZ3 Computes $cluster",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_nova_agent_state{adminState=\"enabled\",os_region=~\"$cluster\",zone=\"$availability_zone_3\"}) or vector(0)",
     "legendFormat": "Enabled"
    },
    {
     "expr": "sum(openstack_nova_agent_state{adminState=\"disabled\",os_region=~\"$cluster\",zone=\"$availability_zone_3\"}) or vector(0)",
     "legendFormat": "Disabled"
    },
    { "expression": "$A + $B", "type": "math" }
   ]
  },
  {
   "title": "AZ1 Memory Usage $cluster",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_placement_resource_total{resourcetype=\"MEMORY_MB\",os_region=~\"$cluster\",hostname=~\"$az1_hosts\"})",
     "legendFormat": "Memory Total"
    },
    {
     "expr": "sum(openstack_placement_resource_total{resourcetype=\"MEMORY_MB\",os_region=~\"$cluster\",hostname=~\"$az1_hosts\"}) - sum(openstack_placement_resource_usage{resourcetype=\"MEMORY_MB\",os_region=~\"$cluster\",hostname=~\"$az1_hosts\"})",
     "legendFormat": "Memory Available"
    },
    {
     "expr": "sum(openstack_placement_resource_usage{resourcetype=\"MEMORY_MB\",os_region=~\"$cluster\",hostname=~\"$az1_hosts\"})",
     "legendFormat": "Memory Used"
    }
   ]
  },
  {
   "title": "AZ2 Memory Usage $cluster",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_placement_resource_total{resourcetype=\"MEMORY_MB\",os_region=~\"$cluster\",hostname=~\"$az2_hosts\"})",
     "legendFormat": "Memory Total"
    },
    {
     "expr": "sum(openstack_placement_resource_total{resourcetype=\"MEMORY_MB\",os_region=~\"$cluster\",hostname=~\"$az2_hosts\"}) - sum(openstack_placement_resource_usage{resourcetype=\"MEMORY_MB\",os_region=~\"$cluster\",hostname=~\"$az2_hosts\"})",
     "legendFormat": "Memory Available"
    },
    {
     "expr": "sum(openstack_placement_resource_usage{resourcetype=\"MEMORY_MB\",os_region=~\"$cluster\",hostname=~\"$az2_hosts\"})",
     "legendFormat": "Memory Used"
    }
   ]
  },
  {
   "title": "AZ3 Memory Usage $cluster",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_placement_resource_total{resourcetype=\"MEMORY_MB\",os_region=~\"$cluster\",hostname=~\"$az3_hosts\"})",
     "legendFormat": "Memory Total"
    },
    {
     "expr": "sum(openstack_placement_resource_total{resourcetype=\"MEMORY_MB\",os_region=~\"$cluster\",hostname=~\"$az3_hosts\"}) - sum(openstack_placement_resource_usage{resourcetype=\"MEMORY_MB\",os_region=~\"$cluster\",hostname=~\"$az3_hosts\"})",
     "legendFormat": "Memory Available"
    },
    {
     "expr": "sum(openstack_placement_resource_usage{resourcetype=\"MEMORY_MB\",os_region=~\"$cluster\",hostname=~\"$az3_hosts\"})",
     "legendFormat": "Memory Used"
    }
   ]
  },
  {
   "title": "AZ1 VCPU usage $cluster",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_placement_resource_usage{resourcetype=\"VCPU\",os_region=~\"$cluster\",hostname=~\"$az1_hosts\"})",
     "legendFormat": "vCPU Used"
    },
    {
     "expr": "sum(openstack_placement_resource_total{resourcetype=\"VCPU\",os_region=~\"$cluster\",hostname=~\"$az1_hosts\"})",
     "legendFormat": "vCPU Total"
    }
   ]
  },
  {
   "title": "AZ2 VCPU usage $cluster",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_placement_resource_usage{resourcetype=\"VCPU\",os_region=~\"$cluster\",hostname=~\"$az2_hosts\"})",
     "legendFormat": "vCPU Used"
    },
    {
     "expr": "sum(openstack_placement_resource_total{resourcetype=\"VCPU\",os_region=~\"$cluster\",hostname=~\"$az2_hosts\"})",
     "legendFormat": "vCPU Total"
    }
   ]
  },
  {
   "title": "AZ3 VCPU usage $cluster",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_placement_resource_usage{resourcetype=\"VCPU\",os_region=~\"$cluster\",hostname=~\"$az3_hosts\"})",
     "legendFormat": "vCPU Used"
    },
    {
     "expr": "sum(openstack_placement_resource_total{resourcetype=\"VCPU\",os_region=~\"$cluster\",hostname=~\"$az3_hosts\"})",
     "legendFormat": "vCPU Total"
    }
   ]
  },
  {
   "title": "Disabled Hosts $cluster",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "openstack_nova_agent_state{os_region=~\"$cluster\",service=\"nova-compute\",adminState=\"disabled\"}"
    }
   ]
  }
 ]
}