{
 "title": "Openstack VM Exporter  GB4",
 "description": "VM exporter VMs",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(libvirt_versions_info{os_region=~\"gb-lon|gb4-retail\"},os_region)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,2m,5m,15m,30m,1h,2h,1d" },
   {
    "name": "project",
    "label": "project",
    "query": {
     "query": "label_values(libvirt_domain_info_meta{job=\"libvirt_exporter\", os_region=\"$cluster\", project_name=~\"st-retail-dev-test|li-retail-gb4\"},project_name)"
    }
   },
   {
    "name": "compute",
    "label": "Compute",
    "query": {
     "query": "label_values(libvirt_up{os_region=\"$cluster\"},compute)"
    }
   },
   {
    "name": "instance_name",
    "label": "Instance",
    "query": {
     "query": "label_values(libvirt_domain_info_meta{job=\"libvirt_exporter\", project_name=\"${project}\", os_region=\"$cluster\"},instance_name)"
    }
   },
   {
    "name": "virtual_machine",
    "label": "VM",
    "query": {
     "query": "label_values(libvirt_domain_info_meta{job=\"libvirt_exporter\", project_name=\"${project}\", os_region=\"$cluster\", instance_name=~\"$instance_name\"},domain)"
    }
   },
   {
    "name": "tenant_id",
    "label": "Tenant",
    "query": {
     "query": "label_values(openstack_cinder_limits_volume_max_gb{os_region=\"$cluster\", tenant=~\"$project\"},tenant_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Data Exporter VMs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "VM Quota",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openstack_nova_limits_instances_max{tenant_id=~\"$tenant_id\",os_region=~\"$cluster\"}",
     "legendFormat": "Quota"
    },
    {
     "expr": "openstack_nova_limits_instances_used{tenant_id=~\"$tenant_id\",os_region=~\"$cluster\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "CPU Quota",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openstack_nova_limits_vcpus_max{tenant_id=~\"$tenant_id\",os_region=~\"$cluster\"}",
     "legendFormat": "Quota"
    },
    {
     "expr": "openstack_nova_limits_vcpus_used{tenant_id=~\"$tenant_id\",os_region=~\"$cluster\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "RAM Quota",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openstack_nova_limits_memory_max{tenant_id=~\"$tenant_id\",os_region=~\"$cluster\"}",
     "legendFormat": "Quota"
    },
    {
     "expr": "openstack_nova_limits_memory_used{tenant_id=~\"$tenant_id\",os_region=~\"$cluster\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Volume Quota",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openstack_cinder_limits_volume_max_gb{tenant_id=~\"$tenant_id\",os_region=~\"$cluster\"}",
     "legendFormat": "Quota"
    },
    {
     "expr": "openstack_cinder_limits_volume_used_gb{tenant_id=~\"$tenant_id\",os_region=~\"$cluster\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "VMs Stats",
   "type": "table",
   "gridPos": { "h": 29, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(libvirt_domain_info_virtual_cpus{job=\"libvirt_exporter\",os_region=\"$cluster\"}) by (domain) * on(domain) group_left(flavor,instance_name,project_name,) libvirt_domain_info_meta{job=\"libvirt_exporter\",project_name=\"$project\",os_region=\"$cluster\"} * on(domain) group_left(ip_address,cinder_backend_host,service,team) openstack_db_metadata{os_region=\"$cluster\"} ",
     "legendFormat": "__auto"
    },
    {
     "expr": "(avg by (domain) (irate(libvirt_domain_info_cpu_time_seconds_total{domain=~\"$virtual_machine\",compute=~\"$compute\",job=~\"libvirt_exporter\"}[$__rate_interval])) * 100)",
     "legendFormat": "vCPU Used"
    },
    {
     "expr": "libvirt_domain_info_maximum_memory_bytes{domain=~\"$virtual_machine\",compute=~\"$compute\", job=~\"libvirt_exporter\"}",
     "legendFormat": "Memory Total"
    },
    {
     "expr": "(libvirt_domain_info_maximum_memory_bytes{compute=~\"$compute\", job=~\"libvirt_exporter\",os_region=\"$cluster\"} - libvirt_domain_memory_stats_unused_bytes{compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=\"$cluster\"})",
     "legendFormat": "Memory Used"
    }
   ]
  }
 ]
}