{
 "title": "Ceph Dashboard",
 "tags": [ "folder-opensearch" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" },
   { "name": "cluster", "label": "Cluster", "query": "grafana-opensearch-datasource" }
  ]
 },
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Logs",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger: CEPH*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "API",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "log_level.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger: CEPH*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Ceph Logs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 7, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger: CEPH*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Ceph service perfs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 13, "y": 1 },
   "targets": [
    {
     "alias": "OSD",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger: CEPH.OSD",
     "timeField": "@timestamp"
    },
    {
     "alias": "VOL",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger: CEPH.VOL",
     "timeField": "@timestamp"
    },
    {
     "alias": "CEPHGW",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger: CEPH.GW",
     "timeField": "@timestamp"
    },
    {
     "alias": "MGR",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger: CEPH.MGR",
     "timeField": "@timestamp"
    },
    {
     "alias": "MON",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger: CEPH.MON",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "API Resp",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 1 },
   "targets": [
    {
     "alias": "INFO",
     "bucketAggs": [
      { "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(log_level : INFO OR log_level : info) and Logger: CEPH.*",
     "timeField": "@timestamp"
    },
    {
     "alias": "ERROR",
     "bucketAggs": [
      { "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "log_level : error and Logger: CEPH.*",
     "timeField": "@timestamp"
    },
    {
     "alias": "DEBUG",
     "bucketAggs": [
      { "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(log_level : DEBUG OR log_level : debug ) and Logger: CEPH.*",
     "timeField": "@timestamp"
    },
    {
     "alias": "WARN",
     "bucketAggs": [
      { "id": "1", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(log_level : WARN OR log_level : warn) and Logger: CEPH.*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Hosts",
   "type": "table",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 6 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Hostname.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Hostname: *ceph*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Programname",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 7, "x": 3, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Programname.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger: CEPH*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Ceph Services",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 6 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Logger.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Service",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Logger.keyword",
       "id": "1",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger: CEPH.*",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Ceph OSD", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "OSD Logs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 13 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger: CEPH.OSD",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Log Levels",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 6, "y": 13 },
   "targets": [
    {
     "alias": "DEBUG",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "log_level : DBG AND Logger: CEPH.OSD",
     "timeField": "@timestamp"
    },
    {
     "alias": "INFO",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(log_level : info OR log_level : INFO) AND Logger: CEPH.OSD",
     "timeField": "@timestamp"
    },
    {
     "alias": "WARN",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(log_level : warn OR log_level : WARN) AND Logger: CEPH.OSD",
     "timeField": "@timestamp"
    },
    {
     "alias": "ERROR",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "log_level : error AND Logger: CEPH.OSD",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Hosts",
   "type": "table",
   "gridPos": { "h": 5, "w": 3, "x": 17, "y": 13 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Hostname.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger: CEPH.OSD",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Programname",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Programname.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger: CEPH.OSD",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Ceph Monitors ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Monitor Logs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 19 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger: CEPH.MON",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Log Levels",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 6, "y": 19 },
   "targets": [
    {
     "alias": "DEBUG",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "log_level : DBG AND Logger: CEPH.MON",
     "timeField": "@timestamp"
    },
    {
     "alias": "INFO",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(log_level : info OR log_level : INFO) AND Logger: CEPH.MON",
     "timeField": "@timestamp"
    },
    {
     "alias": "WARN",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(log_level : warn OR log_level : WARN) AND Logger: CEPH.MON",
     "timeField": "@timestamp"
    },
    {
     "alias": "ERROR",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "log_level : error  AND Logger: CEPH.MON",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Hosts",
   "type": "table",
   "gridPos": { "h": 5, "w": 3, "x": 17, "y": 19 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Hostname.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger: CEPH.MON",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Programname",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Programname.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger: CEPH.MON",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Ceph Manager ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "MGR Logs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 25 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger: CEPH.MGR",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Log Levels",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 6, "y": 25 },
   "targets": [
    {
     "alias": "DEBUG",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "log_level : DBG AND Logger: CEPH.MGR",
     "timeField": "@timestamp"
    },
    {
     "alias": "INFO",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(log_level : info OR log_level : INFO) AND Logger: CEPH.MGR",
     "timeField": "@timestamp"
    },
    {
     "alias": "WARN",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(log_level : warn OR log_level : WARN) AND Logger: CEPH.MGR",
     "timeField": "@timestamp"
    },
    {
     "alias": "ERROR",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "log_level : error  AND Logger: CEPH.MGR",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Hosts",
   "type": "table",
   "gridPos": { "h": 5, "w": 3, "x": 17, "y": 25 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Hostname.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger: CEPH.MGR",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Programname",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Programname.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger: CEPH.mgr",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Ceph RGW ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "RGW Logs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 31 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger: CEPH.GW",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Log Levels",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 6, "y": 31 },
   "targets": [
    {
     "alias": "DEBUG",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "log_level : DBG AND Logger: CEPH.GW",
     "timeField": "@timestamp"
    },
    {
     "alias": "INFO",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(log_level : info OR log_level : INFO) AND Logger: CEPH.GW",
     "timeField": "@timestamp"
    },
    {
     "alias": "WARN",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(log_level : warn OR log_level : WARN) AND Logger: CEPH.GW",
     "timeField": "@timestamp"
    },
    {
     "alias": "ERROR",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "log_level : error  AND Logger: CEPH.GW",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Hosts",
   "type": "table",
   "gridPos": { "h": 5, "w": 3, "x": 17, "y": 31 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Hostname.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger: CEPH.GW",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Programname",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Programname.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Logger: CEPH.GW",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}