{
 "title": "Openstack Hypervisor",
 "tags": [
  "openstack",
  "openstack-nova",
  "folder-openstack"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1h",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(openstack_identity_regions,os_region)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,2m,5m,15m,30m,1h,2h,1d" },
   {
    "name": "compute",
    "label": "Compute",
    "query": {
     "query": "label_values(libvirt_up{os_region=\"$cluster\"},compute)"
    }
   },
   {
    "name": "AZ",
    "label": "AZ",
    "query": {
     "query": "label_values(openstack_nova_agent_state{os_region=\"$cluster\"},zone)"
    }
   },
   {
    "name": "availability_zone_1",
    "label": "AZ",
    "query": {
     "query": "label_values(openstack_nova_agent_state{os_region=\"$cluster\"},zone)"
    }
   },
   {
    "name": "availability_zone_2",
    "label": "AZ",
    "query": {
     "query": "label_values(openstack_nova_agent_state{os_region=\"$cluster\"},zone)"
    }
   },
   {
    "name": "availability_zone_3",
    "label": "AZ",
    "query": {
     "query": "label_values(openstack_nova_agent_state{os_region=\"$cluster\"},zone)"
    }
   },
   {
    "name": "az1_hosts",
    "label": "AZ1 Hosts",
    "query": {
     "query": "label_values(openstack_nova_agent_state{zone=\"$availability_zone_1\"},hostname)"
    }
   },
   {
    "name": "az2_hosts",
    "label": "AZ2 Hosts",
    "query": {
     "query": "label_values(openstack_nova_agent_state{zone=\"$availability_zone_2\"},hostname)"
    }
   },
   {
    "name": "az3_hosts",
    "label": "AZ3 Hosts",
    "query": {
     "query": "label_values(openstack_nova_agent_state{zone=\"$availability_zone_3\"},hostname)"
    }
   },
   {
    "name": "st_hosts",
    "label": "AZ3 Hosts",
    "query": {
     "query": "label_values(openstack_nova_agent_state{zone=\"$availability_zone_3\"},hostname)"
    }
   },
   {
    "name": "hostnames",
    "label": "hostnames",
    "query": {
     "query": "label_values(libvirt_up{os_region=\"$cluster\"},compute)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Hypervisor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Computes ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(openstack_nova_agent_state{adminState=\"enabled\",os_region=\"$cluster\",service=\"nova-compute\"}) or vector(0)",
     "legendFormat": "Enabled"
    },
    {
     "expr": "count(openstack_nova_agent_state{adminState=\"disabled\",os_region=\"$cluster\",service=\"nova-compute\"}) or vector(0)",
     "legendFormat": "Disabled"
    },
    { "expression": "$A + $B", "type": "math" }
   ]
  },
  {
   "title": "Compute Stats",
   "type": "table",
   "gridPos": { "h": 30, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "openstack_nova_memory_available_bytes{os_region=\"$cluster\",availability_zone=~\"$AZ|\"}",
     "legendFormat": "Memory available"
    },
    {
     "expr": "openstack_nova_running_vms{os_region=\"$cluster\",availability_zone=~\"$AZ|\"}",
     "legendFormat": "Instance"
    },
    {
     "expr": "openstack_placement_resource_total{os_region=\"$cluster\", resourcetype=\"VCPU\"} +\non (hostname) group_left(availability_zone) 0 * \n(openstack_nova_running_vms{os_region=\"$cluster\"} )\n",
     "legendFormat": "VCPU"
    },
    {
     "expr": "openstack_placement_resource_total{os_region=\"$cluster\",resourcetype=\"VCPU\"}*openstack_placement_resource_allocation_ratio{os_region=\"$cluster\",resourcetype=\"VCPU\"}",
     "legendFormat": "VCPU total"
    },
    {
     "expr": "openstack_placement_resource_usage{os_region=\"$cluster\",resourcetype=\"VCPU\"} +\non (hostname) group_left(availability_zone) 0 * \n(openstack_nova_running_vms{os_region=\"$cluster\"} )",
     "legendFormat": "VCPU Used"
    },
    {
     "expr": "openstack_placement_resource_total{os_region=\"$cluster\",resourcetype=\"DISK_GB\"} +\non (hostname) group_left(availability_zone) 0 * \n(openstack_nova_running_vms{os_region=\"$cluster\"} )",
     "legendFormat": "DISK_GB"
    },
    {
     "expr": "openstack_placement_resource_usage{os_region=\"$cluster\",resourcetype=\"DISK_GB\"}",
     "legendFormat": "DISK_GB Used"
    },
    {
     "expr": "openstack_placement_resource_total{os_region=\"$cluster\",resourcetype=\"MEMORY_MB\"}*1024*1024 +\non (hostname) group_left(availability_zone) 0 * \n(openstack_nova_running_vms{os_region=\"$cluster\"} )",
     "legendFormat": "RAM"
    },
    {
     "expr": "openstack_placement_resource_total{os_region=\"$cluster\",resourcetype=\"MEMORY_MB\"}*openstack_placement_resource_allocation_ratio{os_region=\"$cluster\",resourcetype=\"MEMORY_MB\"}*1024*1024",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "(openstack_placement_resource_usage{os_region=\"$cluster\",resourcetype=\"MEMORY_MB\"}+openstack_placement_resource_reserved{os_region=\"$cluster\",resourcetype=\"MEMORY_MB\"}) * 1024 * 1024",
     "legendFormat": "RAM_ALLOCATED"
    },
    {
     "expr": "(label_replace(node_memory_MemTotal_bytes{instance=~\".*nova.*|.*compute.*\",os_region=\"$cluster\"},\"hostname\",\"$1\",\"instance\",\"(.+)\") - label_replace(node_memory_MemFree_bytes{instance=~\".*nova.*|.*compute.*\",os_region=\"$cluster\"},\"hostname\",\"$1\",\"instance\",\"(.+)\") - label_replace(node_memory_Cached_bytes{instance=~\".*nova.*|.*compute.*\",os_region=\"$cluster\"},\"hostname\",\"$1\",\"instance\",\"(.+)\") + label_replace(node_memory_Buffers_bytes{instance=~\".*nova.*|.*compute.*\",os_region=\"$cluster\"},\"hostname\",\"$1\",\"instance\",\"(.+)\") + on (hostname) group_left(availability_zone) 0 * (openstack_nova_running_vms{os_region=\"$cluster\"} )) * 1.03",
     "legendFormat": "RAM Usage"
    },
    {
     "expr": "round((label_replace(node_time_seconds{instance=~\".*nova.*|.*compute.*\",os_region=\"$cluster\"},\"hostname\",\"$1\",\"instance\",\"(.+)\") - label_replace(node_boot_time_seconds{instance=~\".*nova.*|.*compute.*\",os_region=\"$cluster\"},\"hostname\",\"$1\",\"instance\",\"(.+)\"))/86400) + on (hostname) group_left(availability_zone) 0 * (openstack_nova_running_vms{os_region=\"$cluster\"} )",
     "legendFormat": "Uptime"
    },
    {
     "expr": "(sum by (hostname) (label_replace(irate(node_cpu_seconds_total{mode!=\"idle\",instance=~\".*nova.*|.*compute.*\",os_region=\"$cluster\"}[3m]), \"hostname\", \"$1\", \"instance\", \"(.*)\")))\n / on(hostname) group_left sum by (hostname)(((sum by (hostname) (label_replace(irate(node_cpu_seconds_total{instance=~\".*nova.*|.*compute.*\",os_region=\"$cluster\"}[3m]), \"hostname\", \"$1\", \"instance\", \"(.*)\"))))) * 100 + on (hostname) group_left(availability_zone) 0 * (openstack_nova_running_vms{os_region=\"$cluster\"} )",
     "legendFormat": "CPU consumption"
    },
    {
     "expr": "openstack_nova_agent_state{os_region=\"$cluster\",service=\"nova-compute\"}",
     "legendFormat": "adminState"
    },
    {
     "expr": "label_replace(up{job=\"node\",os_region=\"$cluster\",instance=~\".*nova.*|.*compute.*\"},\"hostname\",\"$1\",\"instance\",\"(.+)\")",
     "legendFormat": "hostState"
    }
   ]
  },
  {
   "title": "Cluster Stas",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "VCPU Usage Over Time ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 19, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(openstack_placement_resource_usage{resourcetype=\"VCPU\",os_region=\"$cluster\"})",
       "legendFormat": "vCPU used"
      },
      {
       "expr": "sum(openstack_placement_resource_total{resourcetype=\"VCPU\",os_region=\"$cluster\"})",
       "legendFormat": "vCPU total"
      }
     ]
    },
    {
     "title": "VCPU usage",
     "type": "stat",
     "gridPos": { "h": 8, "w": 5, "x": 19, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(openstack_placement_resource_usage{resourcetype=\"VCPU\",os_region=\"$cluster\"})",
       "legendFormat": " Used"
      },
      {
       "expr": "sum(openstack_placement_resource_total{resourcetype=\"VCPU\",os_region=\"$cluster\"})",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "RAM Usage Over Time ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 19, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "sum(openstack_placement_resource_total{resourcetype=\"MEMORY_MB\",os_region=~\"$cluster\"}) - sum(openstack_placement_resource_reserved{os_region=~\"$cluster\",resourcetype=\"MEMORY_MB\"}) - max(openstack_placement_resource_total{os_region=~\"$cluster\",resourcetype=\"MEMORY_MB\"})",
       "legendFormat": "Total"
      },
      {
       "expr": " sum(openstack_placement_resource_usage{resourcetype=\"MEMORY_MB\",os_region=~\"$cluster\"})+sum(openstack_placement_resource_reserved{os_region=~\"$cluster\",resourcetype=\"MEMORY_MB\"})",
       "legendFormat": "Required"
      },
      {
       "expr": "sum(openstack_placement_resource_usage{resourcetype=\"MEMORY_MB\",os_region=\"$cluster\"})",
       "legendFormat": "Allocated"
      },
      {
       "expr": "(sum(node_memory_MemTotal_bytes{os_region=\"$cluster\"}) - sum(node_memory_MemFree_bytes{os_region=\"$cluster\"}) - (sum(node_memory_Cached_bytes{os_region=\"$cluster\"}) + sum(node_memory_Buffers_bytes{os_region=\"$cluster\"})))/1024/1024",
       "legendFormat": "Usage"
      }
     ]
    },
    {
     "title": "RAM usage",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 5, "x": 19, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(openstack_placement_resource_usage{resourcetype=\"MEMORY_MB\",os_region=\"$cluster\"})",
       "legendFormat": " Used"
      },
      {
       "expr": "sum(openstack_placement_resource_total{resourcetype=\"MEMORY_MB\",os_region=\"$cluster\"})-(sum(openstack_placement_resource_usage{resourcetype=\"MEMORY_MB\",os_region=\"$cluster\"})+sum(openstack_placement_resource_reserved{resourcetype=\"MEMORY_MB\",os_region=\"$cluster\"}))",
       "legendFormat": "Free"
      },
      {
       "expr": "sum(openstack_placement_resource_reserved{resourcetype=\"MEMORY_MB\",os_region=\"$cluster\"})",
       "legendFormat": "Reserved"
      }
     ]
    },
    {
     "title": "DISK Usage Over Time ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 19, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "targets": [
      {
       "expr": "sum(openstack_placement_resource_usage{resourcetype=\"DISK_GB\",os_region=\"$cluster\"})",
       "legendFormat": "Disk used"
      },
      {
       "expr": "sum(openstack_placement_resource_reserved{resourcetype=\"DISK_GB\",os_region=\"$cluster\"})",
       "legendFormat": "Disk reserved"
      },
      {
       "expr": "sum(openstack_placement_resource_total{resourcetype=\"DISK_GB\",os_region=\"$cluster\"})",
       "legendFormat": "Disk Total"
      }
     ]
    },
    {
     "title": "DISK usage",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 5, "x": 19, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(openstack_placement_resource_usage{resourcetype=\"DISK_GB\",os_region=\"$cluster\"})",
       "legendFormat": " Used"
      },
      {
       "expr": "sum(openstack_placement_resource_reserved{resourcetype=\"DISK_GB\",os_region=\"$cluster\"})",
       "legendFormat": "Reserved"
      },
      {
       "expr": "sum(openstack_placement_resource_total{resourcetype=\"DISK_GB\",os_region=\"$cluster\"})-(sum(openstack_placement_resource_usage{resourcetype=\"DISK_GB\",os_region=\"$cluster\"})+sum(openstack_placement_resource_reserved{resourcetype=\"DISK_GB\",os_region=\"$cluster\"}))",
       "legendFormat": "Free"
      }
     ]
    }
   ]
  }
 ]
}