{
 "title": "Openstack Project Overview",
 "tags": [
  "folder-openstack",
  "folder-tenant"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(openstack_identity_up,os_region)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,2m,5m,15m,30m,1h,2h,1d" },
   {
    "name": "project",
    "label": "project",
    "query": {
     "query": "label_values({job=\"libvirt_exporter\", os_region=\"$cluster\", __name__=~\"libvirt_domain_openstack_info|libvirt_domain_info_meta\"},project_name)"
    }
   },
   {
    "name": "compute",
    "label": "Compute",
    "query": {
     "query": "label_values(libvirt_up{os_region=\"$cluster\"},compute)"
    }
   },
   {
    "name": "instance_name",
    "label": "Instance",
    "query": {
     "query": "label_values(openstack_nova_server_status{os_region=\"$cluster\", tenant_id=~\"$tenant_id\"},name)"
    }
   },
   {
    "name": "virtual_machine",
    "label": "VM",
    "query": {
     "query": "label_values({job=\"libvirt_exporter\", project_name=\"${project}\", os_region=\"$cluster\", instance_name=~\"$instance_name\"},domain)"
    }
   },
   {
    "name": "tenant_id",
    "label": "Tenant",
    "query": {
     "query": "label_values(openstack_cinder_limits_volume_max_gb{os_region=\"$cluster\", tenant=~\"$project\"},tenant_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Project Quota", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "VM Quota",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openstack_nova_limits_instances_max{tenant_id=\"$tenant_id\",os_region=\"$cluster\"}",
     "legendFormat": "Quota"
    },
    {
     "expr": "openstack_nova_limits_instances_used{tenant_id=\"$tenant_id\",os_region=\"$cluster\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Volume Types",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(openstack_cinder_volume_gb{os_region=~\"$cluster\",bootable=\"true\",tenant_id=~\"$tenant_id\"})",
     "legendFormat": "Bootable"
    },
    {
     "expr": "count(openstack_cinder_volume_gb{os_region=~\"$cluster\",bootable=\"false\",tenant_id=~\"$tenant_id\"})",
     "legendFormat": "Not bootable"
    },
    {
     "expr": "count(openstack_cinder_volume_gb{os_region=~\"$cluster\",name=~\"pvc-(.*)\",tenant_id=~\"$tenant_id\"})",
     "legendFormat": "PVC"
    },
    {
     "expr": "count(openstack_cinder_volume_gb{os_region=~\"$cluster\",name=~\"pvc-(.*)\",status=\"available\",tenant_id=~\"$tenant_id\"})",
     "legendFormat": "PVC Available"
    }
   ]
  },
  {
   "title": "Volumes by Qos Type",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(openstack_cinder_volume_gb{tenant_id=~\"$tenant_id\"}) by (volume_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total vCPU Allocated",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(libvirt_domain_info_virtual_cpus{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\"} and on(compute,domain) libvirt_domain_openstack_info{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\",project_name=\"$project\",domain=~\"$virtual_machine\",instance_name=~\"$instance_name\"}) or on() vector(0)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Volume Quota",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openstack_cinder_limits_volume_max_gb{tenant_id=\"$tenant_id\",os_region=\"$cluster\"}",
     "legendFormat": "Quota"
    },
    {
     "expr": "openstack_cinder_limits_volume_used_gb{tenant_id=\"$tenant_id\",os_region=\"$cluster\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "CPU Quota",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openstack_nova_limits_vcpus_max{tenant_id=\"$tenant_id\",os_region=\"$cluster\"}",
     "legendFormat": "Quota"
    },
    {
     "expr": "openstack_nova_limits_vcpus_used{tenant_id=\"$tenant_id\",os_region=\"$cluster\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "RAM Quota",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openstack_nova_limits_memory_max{tenant_id=\"$tenant_id\",os_region=\"$cluster\"}",
     "legendFormat": "Quota"
    },
    {
     "expr": "openstack_nova_limits_memory_used{tenant_id=\"$tenant_id\",os_region=\"$cluster\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "VM Overview",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openstack_nova_limits_instances_max{tenant_id=\"$tenant_id\",os_region=\"$cluster\"}",
     "legendFormat": "Quota"
    },
    {
     "expr": "openstack_nova_limits_instances_used{tenant_id=\"$tenant_id\",os_region=\"$cluster\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "count(libvirt_domain_info_state{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\"} == 1 and on(compute,domain) libvirt_domain_openstack_info{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\",project_name=\"$project\",domain=~\"$virtual_machine\",instance_name=~\"$instance_name\"}) or on() vector(0)",
     "legendFormat": "Running"
    },
    {
     "expr": "count(libvirt_domain_info_state{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\"} == 5 and on(compute,domain) libvirt_domain_openstack_info{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\",project_name=\"$project\",domain=~\"$virtual_machine\",instance_name=~\"$instance_name\"}) or on() vector(0)",
     "legendFormat": "Shut Off"
    },
    {
     "expr": "count(libvirt_domain_info_state{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\"} == 0 and on(compute,domain) libvirt_domain_openstack_info{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\",project_name=\"$project\",domain=~\"$virtual_machine\",instance_name=~\"$instance_name\"}) or on() vector(0)",
     "legendFormat": "No State"
    },
    {
     "expr": "count(libvirt_domain_info_state{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\"} == 3 and on(compute,domain) libvirt_domain_openstack_info{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\",project_name=\"$project\",domain=~\"$virtual_machine\",instance_name=~\"$instance_name\"}) or on() vector(0)",
     "legendFormat": "Suspended"
    },
    {
     "expr": "count(libvirt_domain_info_state{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\"} == 6 and on(compute,domain) libvirt_domain_openstack_info{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\",project_name=\"$project\",domain=~\"$virtual_machine\",instance_name=~\"$instance_name\"}) or on() vector(0)",
     "legendFormat": "Crashed"
    }
   ]
  },
  {
   "title": "VMs per AZ Split",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (availability_zone)(openstack_nova_server_status{os_region=~\"$cluster\",tenant_id=~\"$tenant_id\"}) > 1",
     "legendFormat": "{{availability_zone}}"
    }
   ]
  },
  { "title": "Libvirt/Openstack Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Total VMs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(libvirt_domain_info_state{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\"} and on(compute,domain) libvirt_domain_openstack_info{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\",project_name=\"$project\",domain=~\"$virtual_machine\",instance_name=~\"$instance_name\"}) or on() vector(0)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Running VMs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(libvirt_domain_info_state{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\"} == 1 and on(compute,domain) libvirt_domain_openstack_info{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\",project_name=\"$project\",domain=~\"$virtual_machine\",instance_name=~\"$instance_name\"}) or on() vector(0)",
     "legendFormat": "Running"
    }
   ]
  },
  {
   "title": "Shut Off VMs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(libvirt_domain_info_state{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\"} == 5 and on(compute,domain) libvirt_domain_openstack_info{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\",project_name=\"$project\",domain=~\"$virtual_machine\",instance_name=~\"$instance_name\"}) or on() vector(0)",
     "legendFormat": "Shut Off"
    }
   ]
  },
  {
   "title": "No State VMs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(libvirt_domain_info_state{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\"} == 0 and on(compute,domain) libvirt_domain_openstack_info{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\",project_name=\"$project\",domain=~\"$virtual_machine\",instance_name=~\"$instance_name\"}) or on() vector(0)",
     "legendFormat": "Suspend"
    }
   ]
  },
  {
   "title": "Suspend VMs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(libvirt_domain_info_state{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\"} == 3 and on(compute,domain) libvirt_domain_openstack_info{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\",project_name=\"$project\",domain=~\"$virtual_machine\",instance_name=~\"$instance_name\"}) or on() vector(0)",
     "legendFormat": "Suspend"
    }
   ]
  },
  {
   "title": "Crashed VMs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(libvirt_domain_info_state{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\"} == 6 and on(compute,domain) libvirt_domain_openstack_info{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\",project_name=\"$project\",domain=~\"$virtual_machine\",instance_name=~\"$instance_name\"}) or on() vector(0)",
     "legendFormat": "Shut Off"
    }
   ]
  },
  {
   "title": "VMs Stats",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "libvirt_domain_info_virtual_cpus{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\"} * on(compute,domain) group_left(flavor_name,instance_name,project_name,user_name) libvirt_domain_openstack_info{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\",project_name=\"$project\",domain=~\"$virtual_machine\",instance_name=~\"$instance_name\"}",
     "legendFormat": "vCPU Total"
    },
    {
     "expr": "(avg by (compute,domain) (irate(libvirt_domain_info_cpu_time_seconds_total{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\"}[2m])) * 100) * on(compute,domain) group_left(flavor_name,instance_name,project_name,user_name) libvirt_domain_openstack_info{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\",project_name=\"$project\",domain=~\"$virtual_machine\",instance_name=~\"$instance_name\"}",
     "legendFormat": "vCPU Used"
    },
    {
     "expr": "libvirt_domain_info_maximum_memory_bytes{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\"} * on(compute,domain) group_left(flavor_name,instance_name,project_name,user_name) libvirt_domain_openstack_info{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\",project_name=\"$project\",domain=~\"$virtual_machine\",instance_name=~\"$instance_name\"} + on(domain) group_left(status) (0 * label_replace(openstack_nova_server_status{os_region=\"$cluster\"}, \"domain\", \"$1\", \"uuid\", \"(.+)\"))",
     "legendFormat": "Memory Total"
    },
    {
     "expr": "(libvirt_domain_info_maximum_memory_bytes{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\"} - libvirt_domain_memory_stats_unused_bytes{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\"}) * on(compute,domain) group_left(flavor_name,instance_name,project_name,user_name) libvirt_domain_openstack_info{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\",project_name=\"$project\",domain=~\"$virtual_machine\",instance_name=~\"$instance_name\"}",
     "legendFormat": "Memory Used"
    },
    {
     "expr": "sum by (domain) (label_replace(openstack_cinder_volume_gb{os_region=\"$cluster\"}, \"domain\", \"$1\", \"server_id\", \"(.*)\") * on(domain) group_left(flavor_name,instance_name,project_name) libvirt_domain_openstack_info{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\",project_name=\"$project\",domain=~\"$virtual_machine\",instance_name=~\"$instance_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "vCPU Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "topk(20, libvirt_domain_info_virtual_cpus{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\"} * on(compute,domain) group_left(flavor_name,instance_name,project_name,user_name) libvirt_domain_openstack_info{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\",project_name=\"$project\",domain=~\"$virtual_machine\",instance_name=~\"$instance_name\"})",
       "legendFormat": "{{instance_name}}"
      },
      {
       "expr": "sum(libvirt_domain_info_virtual_cpus{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\"} and on(compute,domain) libvirt_domain_openstack_info{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\",project_name=\"$project\",domain=~\"$virtual_machine\",instance_name=~\"$instance_name\"})",
       "legendFormat": "Total vCPU"
      }
     ]
    },
    {
     "title": "vCPU Usage on VM",
     "type": "timeseries",
     "description": "100% = 1 Thread",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "topk(20, avg by (domain,instance_name) (irate(libvirt_domain_info_cpu_time_seconds_total{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\"}[$__rate_interval]) * on(compute,domain) group_left(flavor_name,instance_name,project_name,user_name) libvirt_domain_openstack_info{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\",project_name=\"$project\",domain=~\"$virtual_machine\",instance_name=~\"$instance_name\"}) * 100)",
       "legendFormat": "{{instance_name}}"
      }
     ]
    },
    {
     "title": "vCPU Steal Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "topk(20, avg by (domain,instance_name) (irate(libvirt_domain_vcpu_delay_seconds_total{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\"}[$__rate_interval]) * on(compute,domain) group_left(flavor_name,instance_name,project_name,user_name) libvirt_domain_openstack_info{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\",project_name=\"$project\",domain=~\"$virtual_machine\",instance_name=~\"$instance_name\"}) * 100)",
       "legendFormat": "{{instance_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(10, libvirt_domain_info_maximum_memory_bytes{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\"} * on(compute,domain) group_left(flavor_name,instance_name,project_name,user_name) libvirt_domain_openstack_info{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\",project_name=\"$project\",domain=~\"$virtual_machine\",instance_name=~\"$instance_name\"})",
       "legendFormat": "{{instance_name}}"
      }
     ]
    },
    {
     "title": "Available",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(20, libvirt_domain_memory_stats_unused_bytes{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\"} * on(compute,domain) group_left(flavor_name,instance_name,project_name,user_name) libvirt_domain_openstack_info{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\",project_name=\"$project\",domain=~\"$virtual_machine\",instance_name=~\"$instance_name\"})",
       "legendFormat": "{{instance_name}}"
      }
     ]
    },
    {
     "title": "Used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(20, (libvirt_domain_info_maximum_memory_bytes{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\"} - libvirt_domain_memory_stats_unused_bytes{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\"}) * on(compute,domain) group_left(flavor_name,instance_name,project_name,user_name) libvirt_domain_openstack_info{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\",project_name=\"$project\",domain=~\"$virtual_machine\",instance_name=~\"$instance_name\"})",
       "legendFormat": "{{instance_name}}"
      }
     ]
    },
    {
     "title": "Resident Set Size",
     "type": "timeseries",
     "description": "Resident Set Size of the process running the domain, in bytes.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(20, libvirt_domain_memory_stats_rss_bytes{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\"} * on(compute,domain) group_left(flavor_name,instance_name,project_name,user_name) libvirt_domain_openstack_info{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\",project_name=\"$project\",domain=~\"$virtual_machine\",instance_name=~\"$instance_name\"})",
       "legendFormat": "{{instance_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "RX Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "decbits" } },
     "targets": [
      {
       "expr": "topk(10, (rate(libvirt_domain_interface_stats_receive_bytes_total{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\"}[$__rate_interval]) * on(compute,domain) group_left(flavor_name,instance_name,project_name,user_name) libvirt_domain_openstack_info{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\",project_name=\"$project\",domain=~\"$virtual_machine\",instance_name=~\"$instance_name\"}) * 8)",
       "legendFormat": "{{instance_name}} - {{target_device}}"
      }
     ]
    },
    {
     "title": "TX Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "decbits" } },
     "targets": [
      {
       "expr": "topk(10, (rate(libvirt_domain_interface_stats_transmit_bytes_total{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\"}[$__rate_interval]) * on(compute,domain) group_left(flavor_name,instance_name,project_name,user_name) libvirt_domain_openstack_info{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\",project_name=\"$project\",domain=~\"$virtual_machine\",instance_name=~\"$instance_name\"}) * 8)",
       "legendFormat": "{{instance_name}} - {{target_device}}"
      }
     ]
    },
    {
     "title": "RX Packets",
     "type": "timeseries",
     "description": "Number of packets received on a network interface.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "topk(10, rate(libvirt_domain_interface_stats_receive_packets_total{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\"}[$__rate_interval]) * on(compute,domain) group_left(flavor_name,instance_name,project_name,user_name) libvirt_domain_openstack_info{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\",project_name=\"$project\",domain=~\"$virtual_machine\",instance_name=~\"$instance_name\"})",
       "legendFormat": "{{instance_name}} - {{target_device}}"
      }
     ]
    },
    {
     "title": "TX Packets",
     "type": "timeseries",
     "description": "Number of packets transmitted on a network interface.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "topk(10, rate(libvirt_domain_interface_stats_transmit_packets_total{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\"}[$__rate_interval]) * on(compute,domain) group_left(flavor_name,instance_name,project_name,user_name) libvirt_domain_openstack_info{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\",project_name=\"$project\",domain=~\"$virtual_machine\",instance_name=~\"$instance_name\"})",
       "legendFormat": "{{instance_name}} - {{target_device}}"
      }
     ]
    },
    {
     "title": "RX Packets Error",
     "type": "timeseries",
     "description": "Number of packet receive errors on a network interface.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "topk(10, rate(libvirt_domain_interface_stats_receive_errors_total{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\"}[$__rate_interval]) * on(compute,domain) group_left(flavor_name,instance_name,project_name,user_name) libvirt_domain_openstack_info{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\",project_name=\"$project\",domain=~\"$virtual_machine\",instance_name=~\"$instance_name\"})",
       "legendFormat": "{{instance_name}} - {{target_device}}"
      }
     ]
    },
    {
     "title": "TX Packets Error",
     "type": "timeseries",
     "description": "Number of packet transmit errors on a network interface",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(libvirt_domain_interface_stats_transmit_errors_total{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\"}[$__rate_interval]) * on(compute,domain) group_left(flavor_name,instance_name,project_name,user_name) libvirt_domain_openstack_info{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\",project_name=\"$project\",domain=~\"$virtual_machine\",instance_name=~\"$instance_name\"}",
       "legendFormat": "{{instance_name}} - {{target_device}}"
      }
     ]
    },
    {
     "title": "RX Packets Drop",
     "type": "timeseries",
     "description": "Number of packet receive drops on a network interface.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(libvirt_domain_interface_stats_receive_drops_total{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\"}[$__rate_interval]) * on(compute,domain) group_left(flavor_name,instance_name,project_name,user_name) libvirt_domain_openstack_info{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\",project_name=\"$project\",domain=~\"$virtual_machine\",instance_name=~\"$instance_name\"}",
       "legendFormat": "{{instance_name}} - {{target_device}}"
      }
     ]
    },
    {
     "title": "TX Packets Drop",
     "type": "timeseries",
     "description": "Number of packet transmit drops on a network interface.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(libvirt_domain_interface_stats_transmit_drops_total{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\"}[$__rate_interval]) * on(compute,domain) group_left(flavor_name,instance_name,project_name,user_name) libvirt_domain_openstack_info{job=\"libvirt_exporter\",os_region=\"$cluster\",compute=~\"$compute\",project_name=\"$project\",domain=~\"$virtual_machine\",instance_name=~\"$instance_name\"}",
       "legendFormat": "{{instance_name}} - {{target_device}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "PVC Volumes",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "targets": [
      {
       "expr": "openstack_cinder_volume_gb{name=~\"pvc-(.*)\",os_region=~\"$cluster\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Subnet",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Subnets info",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
     "targets": [
      {
       "expr": "avg by(cidr,subnet_name,network_id,network_name) (openstack_neutron_network_ip_availabilities_total{project_id=~\"$tenant_id\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by(cidr,subnet_name,network_id,network_name) (openstack_neutron_network_ip_availabilities_used{project_id=~\"$tenant_id\"}) * on(network_id) group_left(dns_nameservers,enable_dhcp,gateway_ip,id) openstack_neutron_subnet{}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}