{
 "title": "Openstack Capacity Dashboard GB4",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1d",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(libvirt_versions_info{os_region=~\"gb4-retail\"},os_region)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,2m,5m,15m,30m,1h,2h,1d" },
   {
    "name": "project",
    "label": "project",
    "query": {
     "query": "label_values(libvirt_domain_info_meta{job=\"libvirt_exporter\", os_region=\"$cluster\"},project_name)"
    }
   },
   {
    "name": "compute",
    "label": "Compute",
    "query": {
     "query": "label_values(libvirt_up{os_region=\"$cluster\"},compute)"
    }
   },
   {
    "name": "compute_st_gb_lon",
    "label": "Compute_st",
    "query": {
     "query": "label_values(libvirt_up{os_region=\"gb-lon\"},compute)"
    }
   },
   {
    "name": "instance_name",
    "label": "Instance",
    "query": {
     "query": "label_values(libvirt_domain_info_meta{job=\"libvirt_exporter\", project_name=\"${project}\", os_region=\"$cluster\"},instance_name)"
    }
   },
   {
    "name": "virtual_machine",
    "label": "VM",
    "query": {
     "query": "label_values(libvirt_domain_info_meta{job=\"libvirt_exporter\", project_name=\"${project}\", os_region=\"$cluster\", instance_name=~\"$instance_name\"},domain)"
    }
   },
   {
    "name": "tenant_id",
    "label": "Tenant",
    "query": {
     "query": "label_values(openstack_cinder_limits_volume_max_gb{os_region=\"$cluster\", tenant=~\"$project\"},tenant_id)"
    }
   },
   {
    "name": "availability_zone_all",
    "label": "AZ",
    "query": {
     "query": "label_values(openstack_nova_agent_state{os_region=\"$cluster\"},zone)"
    }
   },
   {
    "name": "availability_zone_1",
    "label": "AZ",
    "query": {
     "query": "label_values(openstack_nova_agent_state{os_region=\"$cluster\"},zone)"
    }
   },
   {
    "name": "availability_zone_2",
    "label": "AZ",
    "query": {
     "query": "label_values(openstack_nova_agent_state{os_region=\"$cluster\"},zone)"
    }
   },
   {
    "name": "availability_zone_3",
    "label": "AZ",
    "query": {
     "query": "label_values(openstack_nova_agent_state{os_region=\"$cluster\"},zone)"
    }
   },
   {
    "name": "availability_zone_st_gb_lon",
    "label": "AZ",
    "query": {
     "query": "label_values(openstack_nova_agent_state{os_region=\"gb-lon\"},zone)"
    }
   },
   {
    "name": "az1_hosts",
    "label": "AZ1 Hosts",
    "query": {
     "query": "label_values(openstack_nova_agent_state{zone=\"$availability_zone_1\"},hostname)"
    }
   },
   {
    "name": "az2_hosts",
    "label": "AZ2 Hosts",
    "query": {
     "query": "label_values(openstack_nova_agent_state{zone=\"$availability_zone_2\"},hostname)"
    }
   },
   {
    "name": "az3_hosts",
    "label": "AZ3 Hosts",
    "query": {
     "query": "label_values(openstack_nova_agent_state{zone=\"$availability_zone_3\"},hostname)"
    }
   },
   {
    "name": "st_hosts",
    "label": "AZ3 Hosts",
    "query": {
     "query": "label_values(openstack_nova_agent_state{zone=\"$availabilty_zone_3\"},hostname)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Computes $cluster",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_nova_agent_state{adminState=\"enabled\",os_region=~\"$cluster\",service=\"nova-compute\"}) - (sum(openstack_nova_agent_state{adminState=\"enabled\",hostname=~\"$st_hosts\"}) or vector(0)) or vector(0)",
     "legendFormat": "Enabled"
    },
    {
     "expr": "sum(openstack_nova_agent_state{adminState=\"disabled\",os_region=~\"$cluster\",service=\"nova-compute\"}) - (sum(openstack_nova_agent_state{adminState=\"disabled\",hostname=~\"$st_hosts\"}) or vector(0)) or vector(0)",
     "legendFormat": "Disabled"
    },
    { "expression": "$A + $B", "type": "math" }
   ]
  },
  {
   "title": "VCPU usage $cluster",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_placement_resource_usage{resourcetype=\"VCPU\",os_region=~\"$cluster\"})",
     "legendFormat": "vCPU Used"
    },
    {
     "expr": "sum(openstack_placement_resource_total{resourcetype=\"VCPU\",os_region=~\"$cluster\"}) - sum(openstack_placement_resource_reserved{resourcetype=\"VCPU\",os_region=~\"$cluster\"})",
     "legendFormat": "vCPU Total"
    }
   ]
  },
  {
   "title": "VCPU Usage Over Time - $cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(openstack_placement_resource_usage{resourcetype=\"VCPU\",os_region=~\"$cluster\"}) ",
     "legendFormat": "vCPU core used"
    },
    {
     "expr": "sum(openstack_placement_resource_total{resourcetype=\"VCPU\",os_region=~\"$cluster\"}) - sum(openstack_placement_resource_reserved{resourcetype=\"VCPU\",os_region=~\"$cluster\"}) ",
     "legendFormat": "vCPU core total"
    }
   ]
  },
  {
   "title": "Memory Usage $cluster",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_placement_resource_total{resourcetype=\"MEMORY_MB\",os_region=~\"$cluster\"}) - sum(openstack_placement_resource_usage{resourcetype=\"MEMORY_MB\",os_region=~\"$cluster\"}) -  max(openstack_placement_resource_total{os_region=~\"$cluster\",resourcetype=\"MEMORY_MB\"})",
     "legendFormat": "RAM  Available"
    },
    {
     "expr": "sum(openstack_placement_resource_usage{resourcetype=\"MEMORY_MB\",os_region=~\"$cluster\"})",
     "legendFormat": "RAM Used"
    }
   ]
  },
  {
   "title": "Memory Usage Over Time $cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(openstack_placement_resource_total{resourcetype=\"MEMORY_MB\",os_region=~\"$cluster\"}) - sum(openstack_placement_resource_reserved{os_region=~\"$cluster\",resourcetype=\"MEMORY_MB\"}) ",
     "legendFormat": "Memory Total"
    },
    {
     "expr": "sum(openstack_placement_resource_total{resourcetype=\"MEMORY_MB\",os_region=~\"$cluster\"})- sum(openstack_placement_resource_reserved{os_region=~\"$cluster\",resourcetype=\"MEMORY_MB\"}) - sum(openstack_placement_resource_usage{resourcetype=\"MEMORY_MB\",os_region=~\"$cluster\"})",
     "legendFormat": "Memory Available"
    },
    {
     "expr": "sum(openstack_placement_resource_usage{resourcetype=\"MEMORY_MB\",os_region=~\"$cluster\"})",
     "legendFormat": "Memory Used"
    }
   ]
  },
  { "title": "AZ overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Computes $cluster",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_nova_agent_state{adminState=\"enabled\",os_region=~\"$cluster\",service=\"nova-compute\"}) or vector(0)",
     "legendFormat": "Enabled"
    },
    {
     "expr": "sum(openstack_nova_agent_state{adminState=\"disabled\",os_region=~\"$cluster\"}) or vector(0)",
     "legendFormat": "Disabled"
    },
    { "expression": "$A + $B", "type": "math" }
   ]
  },
  {
   "title": "Memory Usage $cluster",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_placement_resource_total{resourcetype=\"MEMORY_MB\",os_region=~\"$cluster\"})",
     "legendFormat": "Memory Total"
    },
    {
     "expr": "sum(openstack_placement_resource_total{resourcetype=\"MEMORY_MB\",os_region=~\"$cluster\"}) - sum(openstack_placement_resource_usage{resourcetype=\"MEMORY_MB\",os_region=~\"$cluster\"})",
     "legendFormat": "Memory Available"
    },
    {
     "expr": "sum(openstack_placement_resource_usage{resourcetype=\"MEMORY_MB\",os_region=~\"$cluster\"})",
     "legendFormat": "Memory Used"
    }
   ]
  },
  {
   "title": "VCPU usage $cluster",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_placement_resource_usage{resourcetype=\"VCPU\",os_region=~\"$cluster\"})",
     "legendFormat": "vCPU Used"
    },
    {
     "expr": "sum(openstack_placement_resource_total{resourcetype=\"VCPU\",os_region=~\"$cluster\"})",
     "legendFormat": "vCPU Total"
    }
   ]
  },
  {
   "title": "Disabled Hosts $cluster",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "openstack_nova_agent_state{os_region=~\"$cluster\",service=\"nova-compute\",adminState=\"disabled\"}"
    }
   ]
  },
  { "title": "Computes Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Compute Stats $cluster",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "openstack_nova_memory_available_bytes{os_region=\"$cluster\"}",
     "legendFormat": "Memory available"
    },
    {
     "expr": "openstack_nova_running_vms{os_region=\"$cluster\"}",
     "legendFormat": "Instance"
    },
    {
     "expr": "openstack_placement_resource_total{os_region=\"$cluster\", resourcetype=\"VCPU\"} +\non (hostname) group_left(availability_zone) 0 * \n(openstack_nova_running_vms{os_region=\"$cluster\"} )\n",
     "legendFormat": "VCPU"
    },
    {
     "expr": "openstack_placement_resource_total{os_region=\"$cluster\",resourcetype=\"VCPU\"}*openstack_placement_resource_allocation_ratio{os_region=\"$cluster\",resourcetype=\"VCPU\"}",
     "legendFormat": "VCPU total"
    },
    {
     "expr": "openstack_placement_resource_usage{os_region=\"$cluster\",resourcetype=\"VCPU\"} +\non (hostname) group_left(availability_zone) 0 * \n(openstack_nova_running_vms{os_region=\"$cluster\"} )",
     "legendFormat": "VCPU Used"
    },
    {
     "expr": "openstack_placement_resource_total{os_region=\"$cluster\",resourcetype=\"DISK_GB\"} +\non (hostname) group_left(availability_zone) 0 * \n(openstack_nova_running_vms{os_region=\"$cluster\"} )",
     "legendFormat": "DISK_GB"
    },
    {
     "expr": "openstack_placement_resource_usage{os_region=\"$cluster\",resourcetype=\"DISK_GB\"}",
     "legendFormat": "DISK_GB Used"
    },
    {
     "expr": "openstack_placement_resource_total{os_region=\"$cluster\",resourcetype=\"MEMORY_MB\"}*1024*1024 +\non (hostname) group_left(availability_zone) 0 * \n(openstack_nova_running_vms{os_region=\"$cluster\"} )",
     "legendFormat": "RAM"
    },
    {
     "expr": "openstack_placement_resource_total{os_region=\"$cluster\",resourcetype=\"MEMORY_MB\"}*openstack_placement_resource_allocation_ratio{os_region=\"$cluster\",resourcetype=\"MEMORY_MB\"}*1024*1024",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "(openstack_placement_resource_usage{os_region=\"$cluster\",resourcetype=\"MEMORY_MB\"}+openstack_placement_resource_reserved{os_region=\"$cluster\",resourcetype=\"MEMORY_MB\"}) * 1024 * 1024",
     "legendFormat": "RAM_ALLOCATED"
    },
    {
     "expr": "(label_replace(node_memory_MemTotal_bytes{instance=~\".*nova.*|.*compute.*\",os_region=\"$cluster\"},\"hostname\",\"$1\",\"instance\",\"(.+)\") - label_replace(node_memory_MemFree_bytes{instance=~\".*nova.*|.*compute.*\",os_region=\"$cluster\"},\"hostname\",\"$1\",\"instance\",\"(.+)\") - label_replace(node_memory_Cached_bytes{instance=~\".*nova.*|.*compute.*\",os_region=\"$cluster\"},\"hostname\",\"$1\",\"instance\",\"(.+)\") + label_replace(node_memory_Buffers_bytes{instance=~\".*nova.*|.*compute.*\",os_region=\"$cluster\"},\"hostname\",\"$1\",\"instance\",\"(.+)\") + on (hostname) group_left(availability_zone) 0 * (openstack_nova_running_vms{os_region=\"$cluster\"} )) * 1.03",
     "legendFormat": "RAM Usage"
    },
    {
     "expr": "round((label_replace(node_time_seconds{instance=~\".*nova.*|.*compute.*\",os_region=\"$cluster\"},\"hostname\",\"$1\",\"instance\",\"(.+)\") - label_replace(node_boot_time_seconds{instance=~\".*nova.*|.*compute.*\",os_region=\"$cluster\"},\"hostname\",\"$1\",\"instance\",\"(.+)\"))/86400) + on (hostname) group_left(availability_zone) 0 * (openstack_nova_running_vms{os_region=\"$cluster\"} )",
     "legendFormat": "Uptime"
    },
    {
     "expr": "(sum by (hostname) (label_replace(irate(node_cpu_seconds_total{mode!=\"idle\",instance=~\".*nova.*|.*compute.*\",os_region=\"$cluster\"}[3m]), \"hostname\", \"$1\", \"instance\", \"(.*)\")))\n / on(hostname) group_left sum by (hostname)(((sum by (hostname) (label_replace(irate(node_cpu_seconds_total{instance=~\".*nova.*|.*compute.*\",os_region=\"$cluster\"}[3m]), \"hostname\", \"$1\", \"instance\", \"(.*)\"))))) * 100 + on (hostname) group_left(availability_zone) 0 * (openstack_nova_running_vms{os_region=\"$cluster\"} )",
     "legendFormat": "CPU consumption"
    },
    {
     "expr": "openstack_nova_agent_state{os_region=\"$cluster\",service=\"nova-compute\"}",
     "legendFormat": "adminState"
    },
    {
     "expr": "label_replace(up{job=\"node\",os_region=\"$cluster\",instance=~\".*nova.*|.*compute.*\"},\"hostname\",\"$1\",\"instance\",\"(.+)\")",
     "legendFormat": "hostState"
    }
   ]
  }
 ]
}