{
 "title": "Openstack VMs Overview Admin",
 "tags": [
  "openstack",
  "openstack-nova"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(os_region)" } },
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "interval", "label": "Interval", "query": "1m,2m,5m,15m,30m,1h,2h,1d" },
   {
    "name": "compute",
    "label": "Compute",
    "query": {
     "query": "label_values(libvirt_up{os_region=~\"$cluster\"},compute)"
    }
   },
   {
    "name": "virtual_machine",
    "label": "VM",
    "query": {
     "query": "label_values(libvirt_domain_info_meta{job=\"libvirt_exporter\", os_region=~\"$cluster\", compute=~\"$compute\"},domain)"
    }
   },
   { "name": "TopItems", "label": "Top Items", "query": "5,8,10,15,20,25" },
   {
    "name": "AZ",
    "label": "AZ",
    "query": {
     "query": "label_values(openstack_nova_agent_state{os_region=\"$cluster\"},zone)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total VMs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(libvirt_domain_info_vstate{domain=~\"$virtual_machine\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Running VMs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(libvirt_domain_info_vstate{domain=~\"$virtual_machine\",compute=~\"$compute\", job=~\"libvirt_exporter\",os_region=~\"$cluster\"}==1)",
     "legendFormat": "Running"
    }
   ]
  },
  {
   "title": "Shut Off VMs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(libvirt_domain_info_vstate{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",compute=~\"$compute\",os_region=~\"$cluster\"}==5)",
     "legendFormat": "Shut Off"
    }
   ]
  },
  {
   "title": "IOPS R/W on VMs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(rate(libvirt_domain_block_stats_read_requests_total{domain=~\"$virtual_machine\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Read IOPS"
    },
    {
     "expr": "sum(rate(libvirt_domain_block_stats_write_requests_total{domain=~\"$virtual_machine\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Write IOPS"
    }
   ]
  },
  {
   "title": "Throughput R/W on VMs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(libvirt_domain_block_stats_read_bytes_total{domain=~\"$virtual_machine\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Read Bytes"
    },
    {
     "expr": "sum(rate(libvirt_domain_block_stats_write_bytes_total{domain=~\"$virtual_machine\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Write Bytes"
    }
   ]
  },
  {
   "title": "No State VMs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(libvirt_domain_state_code{domain=~\"$virtual_machine\",compute=~\"$compute\", job=~\"libvirt_exporter\",os_region=~\"$cluster\"} ==0)",
     "legendFormat": "Suspend"
    }
   ]
  },
  {
   "title": "Suspend VMs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(libvirt_domain_state_code{domain=~\"$virtual_machine\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"}==3)",
     "legendFormat": "Suspend"
    }
   ]
  },
  {
   "title": "Crashed VMs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(libvirt_domain_state_code{domain=~\"$virtual_machine\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"}==6)",
     "legendFormat": "Shut Off"
    }
   ]
  },
  {
   "title": "RX/TX Packets Per Sec on VMs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 11, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(libvirt_domain_interface_stats_receive_packets_total{domain=~\"$virtual_machine\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "RX Packets"
    },
    {
     "expr": "sum(rate(libvirt_domain_interface_stats_transmit_packets_total{domain=~\"$virtual_machine\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "TX Packets"
    }
   ]
  },
  {
   "title": "RX/TX Throughput on VMs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(libvirt_domain_interface_stats_receive_bytes_total{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"}[$__rate_interval]))*8",
     "legendFormat": "RX Bytes"
    },
    {
     "expr": "sum(rate(libvirt_domain_interface_stats_transmit_bytes_total{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"}[$__rate_interval]))*8",
     "legendFormat": "TX Bytes"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "0+(sum(libvirt_domain_memory_stats_unused_bytes{domain=~\"$virtual_machine\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"}) == 0) or (sum(libvirt_domain_info_maximum_memory_bytes{domain=~\"$virtual_machine\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"}) - sum(libvirt_domain_memory_stats_unused_bytes{domain=~\"$virtual_machine\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"}))",
     "legendFormat": "Memory Unsed"
    },
    {
     "expr": "sum(libvirt_domain_info_maximum_memory_bytes{domain=~\"$virtual_machine\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"})",
     "legendFormat": "Memory Allocated"
    }
   ]
  },
  {
   "title": "Total vCPU Allocated",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 7, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(libvirt_domain_info_virtual_cpus{domain=~\"$virtual_machine\",compute=~\"$compute\", job=~\"libvirt_exporter\",os_region=~\"$cluster\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "RX/TX Packets Drop on VMs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 11, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(libvirt_domain_interface_stats_receive_drops_total{domain=~\"$virtual_machine\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "RX Packets"
    },
    {
     "expr": "sum(rate(libvirt_domain_interface_stats_transmit_drops_total{domain=~\"$virtual_machine\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "TX Packets"
    }
   ]
  },
  {
   "title": "RX/TX Packets Error on VMs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(libvirt_domain_interface_stats_receive_errors_total{domain=~\"$virtual_machine\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "RX Packets"
    },
    {
     "expr": "sum(rate(libvirt_domain_interface_stats_transmit_errors_total{domain=~\"$virtual_machine\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "TX Packets"
    }
   ]
  },
  {
   "title": "IOPS R/W on VMs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(rate(libvirt_domain_block_stats_read_requests_total{domain=~\"$virtual_machine\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(rate(libvirt_domain_block_stats_write_requests_total{domain=~\"$virtual_machine\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(rate(libvirt_domain_block_stats_read_bytes_total{domain=~\"$virtual_machine\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "read_bytes"
    },
    {
     "expr": "sum(rate(libvirt_domain_block_stats_write_bytes_total{domain=~\"$virtual_machine\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "write_bytes"
    },
    {
     "expr": "sum(rate(libvirt_domain_block_stats_read_time_total{domain=~\"$virtual_machine\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "read_time"
    },
    {
     "expr": "sum(rate(libvirt_domain_block_stats_write_time_total{domain=~\"$virtual_machine\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "write_time"
    }
   ]
  },
  {
   "title": "IOPS on Network",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(rate(libvirt_domain_interface_stats_receive_bytes_total{domain=~\"$virtual_machine\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "receive"
    },
    {
     "expr": "sum(rate(libvirt_domain_interface_stats_transmit_bytes_total{domain=~\"$virtual_machine\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "transmit"
    },
    {
     "expr": "sum(rate(libvirt_domain_interface_stats_receive_packets_total{domain=~\"$virtual_machine\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "receive_packets"
    },
    {
     "expr": "sum(rate(libvirt_domain_interface_stats_transmit_packets_total{domain=~\"$virtual_machine\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "transmit_packets"
    },
    {
     "expr": "sum(rate(libvirt_domain_interface_stats_receive_errors_total{domain=~\"$virtual_machine\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "transmit_errors"
    },
    {
     "expr": "sum(rate(libvirt_domain_interface_stats_transmit_errors_total{domain=~\"$virtual_machine\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "transmit_errors"
    }
   ]
  },
  {
   "title": "Hypervisors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Computes ",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(openstack_nova_agent_state{adminState=\"enabled\",os_region=~\"$cluster\",service=\"nova-compute\"}) or vector(0)",
       "legendFormat": "Enabled"
      },
      {
       "expr": "count(openstack_nova_agent_state{adminState=\"disabled\",os_region=~\"$cluster\",service=\"nova-compute\"}) or vector(0)",
       "legendFormat": "Disabled"
      },
      { "expression": "$A + $B", "type": "math" }
     ]
    },
    {
     "title": "Compute Stats",
     "type": "table",
     "gridPos": { "h": 30, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "openstack_nova_memory_available_bytes{os_region=\"$cluster\",availability_zone=~\"$AZ\"}",
       "legendFormat": "Memory available"
      },
      {
       "expr": "openstack_nova_running_vms{os_region=\"$cluster\",availability_zone=~\"$AZ\"}",
       "legendFormat": "Instance"
      },
      {
       "expr": "openstack_placement_resource_total{os_region=\"$cluster\", resourcetype=\"VCPU\"} +\non (hostname) group_left(availability_zone) 0 * \n(openstack_nova_running_vms{os_region=\"$cluster\"} )\n",
       "legendFormat": "VCPU"
      },
      {
       "expr": "openstack_placement_resource_total{os_region=\"$cluster\",resourcetype=\"VCPU\"}*openstack_placement_resource_allocation_ratio{os_region=\"$cluster\",resourcetype=\"VCPU\"}",
       "legendFormat": "VCPU total"
      },
      {
       "expr": "openstack_placement_resource_usage{os_region=\"$cluster\",resourcetype=\"VCPU\"} +\non (hostname) group_left(availability_zone) 0 * \n(openstack_nova_running_vms{os_region=\"$cluster\"} )",
       "legendFormat": "VCPU Used"
      },
      {
       "expr": "openstack_placement_resource_total{os_region=\"$cluster\",resourcetype=\"DISK_GB\"} +\non (hostname) group_left(availability_zone) 0 * \n(openstack_nova_running_vms{os_region=\"$cluster\"} )",
       "legendFormat": "DISK_GB"
      },
      {
       "expr": "openstack_placement_resource_usage{os_region=\"$cluster\",resourcetype=\"DISK_GB\"}",
       "legendFormat": "DISK_GB Used"
      },
      {
       "expr": "openstack_placement_resource_total{os_region=\"$cluster\",resourcetype=\"MEMORY_MB\"}*1024*1024 +\non (hostname) group_left(availability_zone) 0 * \n(openstack_nova_running_vms{os_region=\"$cluster\"} )",
       "legendFormat": "RAM"
      },
      {
       "expr": "openstack_placement_resource_total{os_region=\"$cluster\",resourcetype=\"MEMORY_MB\"}*openstack_placement_resource_allocation_ratio{os_region=\"$cluster\",resourcetype=\"MEMORY_MB\"}*1024*1024",
       "legendFormat": "RAM Total"
      },
      {
       "expr": "(openstack_placement_resource_usage{os_region=\"$cluster\",resourcetype=\"MEMORY_MB\"}+openstack_placement_resource_reserved{os_region=\"$cluster\",resourcetype=\"MEMORY_MB\"}) * 1024 * 1024",
       "legendFormat": "RAM_ALLOCATED"
      },
      {
       "expr": "(label_replace(node_memory_MemTotal_bytes{instance=~\".*nova.*|.*compute.*\",os_region=\"$cluster\"},\"hostname\",\"$1\",\"instance\",\"(.+)\") - label_replace(node_memory_MemFree_bytes{instance=~\".*nova.*|.*compute.*\",os_region=\"$cluster\"},\"hostname\",\"$1\",\"instance\",\"(.+)\") - label_replace(node_memory_Cached_bytes{instance=~\".*nova.*|.*compute.*\",os_region=\"$cluster\"},\"hostname\",\"$1\",\"instance\",\"(.+)\") + label_replace(node_memory_Buffers_bytes{instance=~\".*nova.*|.*compute.*\",os_region=\"$cluster\"},\"hostname\",\"$1\",\"instance\",\"(.+)\") + on (hostname) group_left(availability_zone) 0 * (openstack_nova_running_vms{os_region=\"$cluster\"} )) * 1.03",
       "legendFormat": "RAM Usage"
      },
      {
       "expr": "round((label_replace(node_time_seconds{instance=~\".*nova.*|.*compute.*\",os_region=\"$cluster\"},\"hostname\",\"$1\",\"instance\",\"(.+)\") - label_replace(node_boot_time_seconds{instance=~\".*nova.*|.*compute.*\",os_region=\"$cluster\"},\"hostname\",\"$1\",\"instance\",\"(.+)\"))/86400) + on (hostname) group_left(availability_zone) 0 * (openstack_nova_running_vms{os_region=\"$cluster\"} )",
       "legendFormat": "Uptime"
      },
      {
       "expr": "(sum by (hostname) (label_replace(irate(node_cpu_seconds_total{mode!=\"idle\",instance=~\".*nova.*|.*compute.*\",os_region=\"$cluster\"}[3m]), \"hostname\", \"$1\", \"instance\", \"(.*)\")))\n / on(hostname) group_left sum by (hostname)(((sum by (hostname) (label_replace(irate(node_cpu_seconds_total{instance=~\".*nova.*|.*compute.*\",os_region=\"$cluster\"}[3m]), \"hostname\", \"$1\", \"instance\", \"(.*)\"))))) * 100 + on (hostname) group_left(availability_zone) 0 * (openstack_nova_running_vms{os_region=\"$cluster\"} )",
       "legendFormat": "CPU consumption"
      },
      {
       "expr": "openstack_nova_agent_state{os_region=\"$cluster\",service=\"nova-compute\"}",
       "legendFormat": "adminState"
      },
      {
       "expr": "label_replace(up{job=\"node\",os_region=\"$cluster\",instance=~\".*nova.*|.*compute.*\"},\"hostname\",\"$1\",\"instance\",\"(.+)\")",
       "legendFormat": "hostState"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Top $TopItems vCPU Steal Time",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(rate(libvirt_domain_block_stats_write_time_seconds_total{job=~\"libvirt_exporter\",compute=~\"$compute\",os_region=~\"$cluster\"}[$__rate_interval]) * on(domain,compute) group_left(flavor,instance_name,project_name) libvirt_domain_info_meta{job=~\"libvirt_exporter\",compute=~\"$compute\"}) by (domain,compute,instance_name) + \ntopk($TopItems,avg_over_time(sum(rate(libvirt_domain_block_stats_write_time_seconds_total{job=~\"libvirt_exporter\",compute=~\"$compute\",os_region=~\"$cluster\"}[$__rate_interval] * on(domain,compute) group_left(domain,compute,instance_name,project_name) libvirt_domain_info_meta{job=~\"libvirt_exporter\",compute=~\"$compute\"})) by (domain,compute,instance_name) @ end()))*0\n",
       "legendFormat": "{{instance_name}} - {{domain}} - {{compute}}"
      }
     ]
    },
    {
     "title": "Top $TopItems vCPU Usage",
     "type": "timeseries",
     "description": "100% = 1 Thread",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(rate(libvirt_domain_info_cpu_time_seconds_total{job=~\"libvirt_exporter\",os_region=~\"$cluster\"}[$__rate_interval])) by (domain,compute)\n+ \ntopk($TopItems,avg_over_time(sum(rate(libvirt_domain_info_cpu_time_seconds_total{job=~\"libvirt_exporter\",os_region=~\"$cluster\"}[$__rate_interval])) by (domain, compute)@ end()))",
       "legendFormat": "{{domain}} - {{compute}}"
      }
     ]
    },
    {
     "title": "Top $TopItems vCPU Total",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk($TopItems, libvirt_domain_info_virtual_cpus{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",compute=~\"$compute\",os_region=~\"$cluster\"})",
       "legendFormat": "{{domain}} - {{compute}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Top $TopItems IOPS Read",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sum(rate(libvirt_domain_block_stats_read_requests_total{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",compute=~\"$compute\",os_region=~\"$cluster\"}[$__rate_interval])) by (domain, target_device,compute)\n+ \ntopk($TopItems,avg_over_time(sum(rate(libvirt_domain_block_stats_read_requests_total{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",compute=~\"$compute\",os_region=~\"$cluster\"}[$__rate_interval])) by (domain,target_device,compute)@ end()))*0",
       "legendFormat": "{{domain}} - {{target_device}} - {{ compute }}"
      }
     ]
    },
    {
     "title": "Top $TopItems IOPS Write",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sum(rate(libvirt_domain_block_stats_write_requests_total{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",compute=~\"$compute\",os_region=~\"$cluster\"}[$__rate_interval])) by (domain, target_device,compute)\n+ \ntopk($TopItems,avg_over_time(sum(rate(libvirt_domain_block_stats_write_requests_total{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",compute=~\"$compute\",os_region=~\"$cluster\"}[$__rate_interval])) by (domain, target_device,compute)@ end()))*0\n\n",
       "legendFormat": "{{domain}} - {{target_device}} - {{ compute }}"
      }
     ]
    },
    {
     "title": "Top $TopItems Throughput Read",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(libvirt_domain_block_stats_read_bytes_total{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",compute=~\"$compute\",os_region=~\"$cluster\"}[$__rate_interval])) by (domain, target_device,compute)\n+ \ntopk(10,avg_over_time(sum(rate(libvirt_domain_block_stats_read_bytes_total{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",compute=~\"$compute\",os_region=~\"$cluster\"}[$__rate_interval])) by (domain, target_device,compute)@ end()))*0",
       "legendFormat": "{{domain}} - {{target_device}} - {{compute}}"
      }
     ]
    },
    {
     "title": "Top $TopItems Throughput Write",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(libvirt_domain_block_stats_write_bytes_total\n{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",compute=~\"$compute\",os_region=~\"$cluster\"}[$__rate_interval])) by (domain,target_device,compute)\n+ \ntopk($TopItems,avg_over_time(sum(rate(libvirt_domain_block_stats_write_bytes_total\n{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",compute=~\"$compute\",os_region=~\"$cluster\"}[$__rate_interval])) by (domain,target_device,compute)@ end()))*0\n",
       "legendFormat": "{{domain}} - {{target_device}} - {{ compute }}"
      }
     ]
    },
    {
     "title": "Top $TopItems Read time",
     "type": "timeseries",
     "description": "Total time (ns) spent on reads on a block device, in ns, that is, 1/1,000,000,000 of a second, or 10−9 seconds.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(rate(libvirt_domain_block_stats_read_time_seconds_total{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",compute=~\"$compute\",os_region=~\"$cluster\"}[$__rate_interval])) by (domain, target_device,compute)\n+ \ntopk($TopItems,avg_over_time(sum(rate(libvirt_domain_block_stats_read_time_seconds_total{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",compute=~\"$compute\",os_region=~\"$cluster\"}[$__rate_interval])) by (domain, target_device,compute)@ end()))*0\n\n",
       "legendFormat": "{{domain}} - {{target_device}} - {{compute}}"
      }
     ]
    },
    {
     "title": "Write time",
     "type": "timeseries",
     "description": "Total time (ns) spent on writes on a block device, in ns, that is, 1/1,000,000,000 of a second, or 10−9 seconds.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(rate(libvirt_domain_block_stats_write_time_seconds_total\n{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",compute=~\"$compute\",os_region=~\"$cluster\"}[$__rate_interval])) by (domain, target_device,compute)\n+ \ntopk($TopItems,avg_over_time(sum(rate(libvirt_domain_block_stats_write_time_seconds_total\n{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",compute=~\"$compute\",os_region=~\"$cluster\"}[$__rate_interval])) by (domain, target_device,compute)@ end()))*0\n",
       "legendFormat": "{{domain}} - {{target_device}} - {{compute}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Memory on VMs",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(5, libvirt_domain_info_maximum_memory_bytes{domain=~\"$virtual_machine\", job=~\"libvirt_exporter\",os_region=~\"$cluster\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "topk(5, libvirt_domain_memory_stats_unused_bytes{domain=~\"$virtual_machine\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"})",
       "legendFormat": "Available"
      },
      {
       "expr": "topk(5, libvirt_domain_info_maximum_memory_bytes{domain=~\"$virtual_machine\", compute=~\"$compute\", job=~\"libvirt_exporter\",os_region=~\"$cluster\"} - libvirt_domain_memory_stats_unused_bytes{domain=~\"$virtual_machine\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"})",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk($TopItems,libvirt_domain_info_maximum_memory_bytes{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",os_region=~\"$cluster\", compute=~\"$compute\"})",
       "legendFormat": "{{domain}}"
      }
     ]
    },
    {
     "title": "Top $TopItems Resident Set Size",
     "type": "timeseries",
     "description": "Resident Set Size of the process running the domain, in bytes.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk($TopItems, libvirt_domain_memory_stats_rss_bytes{domain=~\"$virtual_machine\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"})",
       "legendFormat": "{{domain}}"
      }
     ]
    },
    {
     "title": "Used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(20, libvirt_domain_info_maximum_memory_bytes{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",compute=~\"$compute\",os_region=~\"$cluster\"} - libvirt_domain_memory_stats_unused_bytes{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",compute=~\"$compute\",os_region=~\"$cluster\"})",
       "legendFormat": "{{domain}}"
      }
     ]
    },
    {
     "title": "Top $TopItems Available",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk($TopItems, libvirt_domain_memory_stats_unused_bytes{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"})",
       "legendFormat": "{{domain}}"
      }
     ]
    },
    {
     "title": "Swap Read",
     "type": "timeseries",
     "description": "The total amount of data read from swap space",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "ibvirt_domain_stat_memory_swap_in_bytes{compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"}",
       "legendFormat": "{{domain}}"
      }
     ]
    },
    {
     "title": "Swap Written",
     "type": "timeseries",
     "description": "The total amount of memory written out to swap space",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "libvirt_domain_stat_memory_swap_out_bytes{compute=~\"$compute\", job=~\"libvirt_exporter\",os_region=~\"$cluster\"}",
       "legendFormat": "{{domain}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Top $TopItems RX Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "decbits" } },
     "targets": [
      {
       "expr": "sum(rate(libvirt_domain_interface_stats_receive_bytes_total{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",compute=~\"$compute\",os_region=~\"$cluster\"}[$__rate_interval])*8) by (domain,target_device,compute)\n+ \ntopk($TopItems,avg_over_time(sum(rate(libvirt_domain_interface_stats_receive_bytes_total{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",compute=~\"$compute\",os_region=~\"$cluster\"}[$__rate_interval])*8) by (domain,target_device,compute) @ end()))*0",
       "legendFormat": "{{domain}} - {{target_device}} - {{ compute }}"
      }
     ]
    },
    {
     "title": "Top $TopItems TX Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "decbits" } },
     "targets": [
      {
       "expr": "sum(rate(libvirt_domain_interface_stats_transmit_bytes_total\n{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",compute=~\"$compute\",os_region=~\"$cluster\"}[$__rate_interval])*8) by (domain,target_device,compute)\n+ \ntopk($TopItems,avg_over_time(sum(rate(libvirt_domain_interface_stats_transmit_bytes_total\n{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",compute=~\"$compute\",os_region=~\"$cluster\"}[$__rate_interval])*8) by (domain,target_device,compute) @ end()))*0",
       "legendFormat": "{{domain}} - {{target_device}}"
      }
     ]
    },
    {
     "title": "Top $TopItems RX Packets",
     "type": "timeseries",
     "description": "Number of packets received on a network interface.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(libvirt_domain_interface_stats_receive_packets_total\n{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",compute=~\"$compute\",os_region=~\"$cluster\"}[$__rate_interval])) by (domain,target_device,compute)\n+ \ntopk($TopItems,avg_over_time(sum(rate(libvirt_domain_interface_stats_receive_packets_total\n{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",compute=~\"$compute\",os_region=~\"$cluster\"}[$__rate_interval])) by (domain, target_device,compute)@ end()))*0\n",
       "legendFormat": "{{domain}} - {{target_device}}"
      }
     ]
    },
    {
     "title": "TX Packets",
     "type": "timeseries",
     "description": "Number of packets transmitted on a network interface.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(libvirt_domain_interface_stats_transmit_packets_total{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",compute=~\"$compute\",os_region=~\"$cluster\"}[$__rate_interval])) by (domain,target_device,compute)\n+ \ntopk($TopItems,avg_over_time(sum(rate(libvirt_domain_interface_stats_transmit_packets_total\n{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",compute=~\"$compute\",os_region=~\"$cluster\"}[$__rate_interval])) by (domain, target_device,compute)@ end()))*0",
       "legendFormat": "{{domain}}-{{target_device}}-{{compute}}"
      }
     ]
    },
    {
     "title": "Top $TopItems RX/TX Packets Drop",
     "type": "timeseries",
     "description": "Number of packet receive/transmit drops on a network interface.",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(libvirt_domain_interface_stats_receive_drops_total\n{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",compute=~\"$compute\",os_region=~\"$cluster\"}[$__rate_interval])) by (domain,target_device,compute)\n+ \ntopk($TopItems,avg_over_time(sum(rate(libvirt_domain_interface_stats_receive_drops_total\n{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",compute=~\"$compute\",os_region=~\"$cluster\"}[$__rate_interval])) by (domain, target_device,compute) @end()))*0\n",
       "legendFormat": "{{domain}} - {{target_device}} - rx - {{compute}}"
      },
      {
       "expr": "sum(rate(libvirt_domain_interface_stats_transmit_drops_total\n\n{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",compute=~\"$compute\",os_region=~\"$cluster\"}[$__rate_interval])) by (domain,target_device,compute)\n+ \ntopk(10,avg_over_time(sum(rate(libvirt_domain_interface_stats_transmit_drops_total\n{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",compute=~\"$compute\",os_region=~\"$cluster\"}[$__rate_interval])) by (domain, target_device,compute)@ end()))*0\n",
       "legendFormat": "{{domain}} - {{target_device}} - tx - {{compute}}"
      }
     ]
    },
    {
     "title": "RX/TX Packets Error",
     "type": "timeseries",
     "description": "Number of packet receive/trasmit errors on a network interface.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "topk(10, rate(libvirt_domain_interface_stats_receive_errors_total{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",compute=~\"$compute\",os_region=~\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "{{domain}} - {{target_device}} - rx"
      },
      {
       "expr": "topk($TopItems,rate(libvirt_domain_interface_stats_transmit_errors_total{domain=~\"$virtual_machine\",compute=~\"$compute\",job=~\"libvirt_exporter\",os_region=~\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "{{domain}} - {{target_device}} - tx"
      }
     ]
    }
   ]
  },
  {
   "title": "Data Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "VMs Stats",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "libvirt_domain_info_virtual_cpus{domain=~\"$virtual_machine\",compute=~\"$compute\", job=~\"libvirt_exporter\"} * on(domain,compute) group_left(flavor,instance_name,project_name,user_name) libvirt_domain_info_meta{domain=~\"$virtual_machine\",job=~\"libvirt_exporter\",compute=~\"$compute\"}",
     "legendFormat": "vCPU Total"
    },
    {
     "expr": "(avg by (domain) (irate(libvirt_domain_info_cpu_time_seconds_total{domain=~\"$virtual_machine\",compute=~\"$compute\",job=~\"libvirt_exporter\"}[$__rate_interval])) * 100)",
     "legendFormat": "vCPU Used"
    },
    {
     "expr": "libvirt_domain_info_maximum_memory_bytes{domain=~\"$virtual_machine\",compute=~\"$compute\", job=~\"libvirt_exporter\"}",
     "legendFormat": "Memory Total"
    },
    {
     "expr": "(libvirt_domain_info_maximum_memory_bytes{domain=~\"$virtual_machine\",compute=~\"$compute\", job=~\"libvirt_exporter\"} - libvirt_domain_memory_stats_unused_bytes{domain=~\"$virtual_machine\",compute=~\"$compute\",job=~\"libvirt_exporter\"})",
     "legendFormat": "Memory Used"
    }
   ]
  }
 ]
}